### ISSUE TITLE
Voicecracks/Pitchcracks After Converting Acapellas In Mangio-Crepe Models

### ISSUE THREAD

**Issue by owenborillo82** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1012]
Hello, I'm having problems of voicecracks to my acapellas I'm using on some songs, that doesn't have separated vocal/acapella stems. I'm using UVR5 for splitting vocals and my songs are high quality at 128kbps, but my problem is still there. I even used some of the recommended models for vocal splitting and I use RMVPE for pitch extraction, but I'm still here. Frustrated for my converted acapellas having voicecracks. I used some of Mangio-Crepe Trained Models I downloaded, the results are good in other songs, but the others having voicecracks after converting, even it's clean and free from background noises and reverbs. Can you all fix this? I'm so frustrated to perfecting them clean to make more AI Covers.

Also while we waiting, can you all give me some alternative solutions that can fix it temporary? Thanks!

**Comment by ogbanugot** [comment]
Hey @owenborillo82 did you find any fix for the voice cracks?
