### ISSUE TITLE
可以提供一个示例用于跑infer_cli.py脚本吗？

### ISSUE THREAD

**Issue by hawgjmrd72** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1013]
环境安装应该没问题，但不知道如何构造i[nfer_cli.py](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/infer_cli.py)输入参数，求提供一个可用示例，包括输入文件，谢谢。

**Comment by ty78329785** [comment]
请问能出一个阿里云的安装代码脚本吗
