### ISSUE TITLE
COLAB ERROR regarding no RMVPE model found

### ISSUE THREAD

**Issue by audioses** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1015]
Hello there. ıs it possible to fix the colab? Wen trying to use the RMVPE model during training, it cannot find the RMVPE model file. 
Thank you very much

**Comment by RVC-Boss** [comment]
You should download it from https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/rmvpe.pt following readme
