### ISSUE TITLE
Audio does not load properly

### ISSUE THREAD

**Issue by NeMqki** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#102]
When I started step2a with the version, there should be 1801 files in that file, but when I check the command prompt, the actual file, only 23 files are loaded.
It seems to work fine in other speakers' files.
However, only certain speakers do not seem to be working properly.
Is it just taking a long time?

**Comment by RVC-Boss** [comment]
It has been fixed in the latest version.
