### ISSUE TITLE
Unable to enter custom training folder path

### ISSUE THREAD

**Issue by hermetika** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1022]
this happens when i try to enter the path of the training folder and click on process data, the folder is inside of the RVC folder next to the other RVC files 

runtime\python.exe trainset_preprocess_pipeline_print.py D:\SD AI\RVC-beta0717\testin 40000 11 D:\SD AI\RVC-beta0717/logs/mi-test False Traceback (most recent call last): File "D:\SD AI\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 8, in <module> sr = int(sys.argv[2]) ValueError: invalid literal for int() with base 10: 'AI\RVC-beta0717\testin'

folder is named testin, there is a single wav file inside

**Comment by RVC-Boss** [comment]
you should download the latest version (0813)

the issue is caused by the space in your exp path (SD AI)

and 0813 fixed it

or you can rename "SD AI" to another name not containing space

**Comment by hermetika** [comment]
Thanks a lot , worked like a charm , now i just need to find the 3 little dots in the lower right hand corner , i dont know what they are not appearing will try to disable addons in my browser
