### ISSUE TITLE
无法打开。

### ISSUE THREAD

**Issue by animality92624** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1025]
C:\Retrieval-based-Voice-Conversion-WebUI-updated0814v2>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
The system cannot find the path specified.

C:\Retrieval-based-Voice-Conversion-WebUI-updated0814v2>pause
Press any key to continue . . .

**Comment by BetaxxxCross** [comment]
I also have the same problem. I Reinstalled and add Python to PATH but the problem still persists

**Comment by LogMeIn-Hamachi** [comment]
Please remove "runtime\" and ".exe" in the bat file everywhere.

windows needs to just have "python" for it to work.
