### ISSUE TITLE
报错你好，我在训练rvc的时候报了以下错误，不知道如何解决呢？Traceback (most recent call last):   File "/root/cvdata/ppy/Retrieval-based-Voice-Conversion-WebUI/trainset_preprocess_pipeline_print.py", line 79, in pipeline     audio = load_audio(path, self.sr)   File "/root/cvdata/ppy/Retrieval-based-Voice-Conversion-WebUI/lib/audio.py", line 19, in load_audio     raise RuntimeError(f"Failed to load audio: {e}") RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by ppy2017** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1035]
你好，我在训练rvc的时候报了以下错误，不知道如何解决呢？Traceback (most recent call last):
  File "/root/cvdata/ppy/Retrieval-based-Voice-Conversion-WebUI/trainset_preprocess_pipeline_print.py", line 79, in pipeline
    audio = load_audio(path, self.sr)
  File "/root/cvdata/ppy/Retrieval-based-Voice-Conversion-WebUI/lib/audio.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'

**Comment by yaodada1** [comment]
除了要在conda环境装python-ffmpeg，还需要在Linux上安装ffmpeg。
