### ISSUE TITLE
4090 is barely 1.5x faster for training than a 3060 with optimized batch size

### ISSUE THREAD

**Issue by JarodMica** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1037]
Hey guys,

I was running some tests with RVC between a 3060 12 GB and a 4090 and, on average, the 4090 is 1.5x faster than the 3060.  This seems to be out of line with other other software I've tested such as Tortoise TTS and Stable Diffusion where I was seeing closer to around 4-5x faster for inference and training.  The tests were done by swapping GPUs, so the PC shouldn't be a factor.

This was with the rmpve update on 7/17, but even on the latest commit and older commits, this trend is still the same.

I saw there is an "issue" where if batch size exceeds vram capacity, it loads it into shared memory.  This in fact was an issue as a batch size of 40 was taking longer than 36, however, even as I optimized the batch to saturate my VRAM as much as possible, no significant speed improvements occurred.  

Tests were done on the same sample sets with the following:

Batch size 3060: 16
Batch size 4090: 32-26

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/76232114/1016a44d-2286-4675-9012-c93fbe871eff)

I have been looking through the code, but due to my limited knowledge, it is me just crawling through functions so any insights on what is occurring would be appreciated. All of these results are with base RVC without any custom modifications.

If you need any more information, let me know and I can work to provide that.

**Comment by aibymind** [comment]
> Batch size 3060: 16 Batch size 4090: 32-26

Hi Jarod. Have you resolved this issue?
Based on my personal experience, the GPU batch size for RTX3060 12Gb vram card is around 7-8. For the RTX3060ti 8 Gb vram optimal batch size is 9.

I think (and I see it in my experiments) the "Number of CPU processes" also matters and affects to the training time.


In my case, the value of 18 out of 20 processes in the RVC settings gives better results than 20 out of 20. All other settings being equal.

My setup: 

GPU: RTX3060ti (8Gb vram)
CPU: intel core i9-10900K (20 cores)
SSD: m.2 ADATA XPG GAMMIX S11 Pro 1Gb (write: 3000 mbps / read: 3500 mbps)
RAM: 64 Gb 3200 MHz (Kingston HyperX FURY Black 4x16 Gb)


Dataset: 14 minutes 48 kHz 32 bit wav stereo
Algorithm: RMVPE_GPU
CPU: 18 (out of 20 available)
GPU: 9

Result: time for train 1 epoch is around 22 seconds

If I increase the dataset to 30 minutes, the time per epoch will up to ~45 seconds
