### ISSUE TITLE
Error when the RVC-GUI starts up

### ISSUE THREAD

**Issue by InfinityPotato** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1040]
Running with the runtime Python, Please wait.
Traceback (most recent call last):
  File "C:\RVC-GUI-pkg\rvcgui.py", line 39, in <module>
    config = Config()
  File "C:\RVC-GUI-pkg\config.py", line 28, in __init__
    self.x_pad, self.x_query, self.x_center, self.x_max = self.device_config()
  File "C:\RVC-GUI-pkg\config.py", line 96, in device_config
    elif torch.backends.mps.is_available():
AttributeError: module 'torch.backends' has no attribute 'mps'
![obraz_2023-08-17_170643547](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/87308033/4b25c19d-185d-4996-8069-7f39c595643d)

**Comment by RVC-Boss** [comment]
you need update pytorch version
