### ISSUE TITLE
what

### ISSUE THREAD

**Issue by FloriLMFAO** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1041]
I don't understand a singe thing
how do you download it
how does it work
what are the features
how to do the training 
I'm completely clueless

**Comment by knoopx** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/README.en.md

**Comment by nikocraft** [comment]
https://www.youtube.com/watch?v=-JcvdDErkAU
