### ISSUE TITLE
无法打开，只有黑框。已更换过旧版本,旧显卡,以及从nvidia studio驱动更换为GRD驱动依然打不开，朋友的电脑可以。

### ISSUE THREAD

**Issue by DRCX** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1046]
![f67860e62876999f4a1da52190cdd516](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/b4744aec-9668-4f14-abcd-3725b08b7b41)
使用2060S 无法打开 只有黑框。

![ddc7590e075dd8a27b510f908da294cd](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/5e8a0dd3-6917-4cfb-a2c6-f7e0fb7125df)
![92e3845eb9f3c50492b3d60cf9501a4f](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/02daeca3-7879-4af6-ad18-f16041b069ef)
炼丹程序go-web.bat能打开，也有网页

![5dccc1619ffb121a99528d61f0ff878d](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/5fb937cf-f66a-4c0c-b0dd-f809959ecb22)
朋友的1070能打开没问题（他正在跑AI绘图）

![{48EE16B7-124A-40f3-BA98-25A081F3ACB1}](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/66acf89a-f424-47d6-96e9-d1d6a5047769)
以及从nvidia studio驱动更换为GRD驱动依然打不开。

![fe8b8422539d140a91cc50ba90103b2f](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/6fe4d52e-6847-4029-bf51-643252db8177)
换了张老卡1050，同样的问题。

![def50c049586c7f172fc2cbb7aba7c06](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/8b94c343-61c2-4fcd-bb97-6c01477ce0ed)
GIThub上的问题都看了遍，python确实装过（3.1.4），但我卸了还是打不开

![a9b22cd57ce5e6d97c12de6d045d3c8f](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/cb11cefc-6d83-4844-ba50-317ffc0a8ddf)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/1957d483-6cce-4023-826e-139919e29236)

系统版本WIN11  CPU是AMD 3700X

**Comment by DRCX** [comment]
![bdf2220c610127181c466a9ea39b359d](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/c23ffd10-a275-4087-8e79-0a57b8948a01)
补个图，之前用锁驱的1080打开是这样的…因为没有CUDA，所以找不到…
![b203e7931903f8c04d95e00f1b9fe1b6](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/9f98cd55-2d12-4a05-9e04-830cbd2fc988)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/d0de1305-f9ef-40d1-bc27-68c943fc9668)
![54083c550557662a2301e0f4a5a324ef](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/091888ad-1a46-4ecd-aa3e-daadfcf15207)
![b5188fce427aea7c45559802822584b6](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/1745e12b-782e-41f9-9623-faaec1536561)
![13e0351b36f3b72386482f4cd6a4be90](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17066543/07db0142-d9c8-4184-aa4c-a9fd7389795a)

从1070朋友哪里拷过来自己跑的AI绘图，证明我的电脑是能跑AI的。

**Comment by hulululu7654321** [comment]
遇到了同样的问题，你解决了么
