### ISSUE TITLE
命令训练推理（813版本）

### ISSUE THREAD

**Issue by hengshizhi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1048]
我在常见问题解答中找到了
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94#q7%E4%B8%8D%E7%94%A8webui%E5%A6%82%E4%BD%95%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%AE%AD%E7%BB%83%E6%8E%A8%E7%90%86
我运行了脚本会出现
ModuleNotFoundError: No module named 'infer_pack'
的报错，
经过对webui源码的研究
代码 infer_pack.modules 改为 lib.infer_pack.models
my_utils 改为 lib.audio
即可

**Comment by RVC-Boss** [comment]
Thanks for your reminding!

**Comment by RVC-Boss** [comment]
fixed.
