### ISSUE TITLE
Is 'Converged (Lack of improvement in inertia)' an Error?

### ISSUE THREAD

**Issue by toriwale** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1050]
I've been getting this when I did train feature index, what does it mean?;

![Screenshot (1047)](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/142621876/4b2f69c3-811b-4e8a-803c-a43afe4d2be0)

And my following question would be, does it affect model quality?

This is probably a dumb question but the thing is, for me it would say; 'Converged (Lack of improvement in inertia) at step 300 (or so) / 4960'

But when I look in the Logs Folder there would be the 'Trained' and 'Added' index. So I was confused, was it successful or not? because it did not say 'done' like the previous 2 steps.

But with the index in place, I did a test train with 5 epoch to see if I would get the model .pth. because I didn't want to go through the process of a 200+ epoch train just to end up with nothing. So I did the 5 epoch test and it worked and I got a model. And that reassured me to restart and go ahead with 250 epoch train even when I got the same 'Converged (Lack of improvement in inertia)' again. But when that training process finished the voice model I trained with 250 epoch for 11hrs had almost the same quality as the model I trained with 5 epoch for 15 minutes. There should be a drastic difference, right? but there really wasn't.

So now I'm wondering if it could be because of the 'Converged (Lack of improvement in inertia)' I just want to know if this is an issue.  Is it essential that it finishes to get a high-quality model? How do I fix this so it can finish 4960/4960?

I should also note that I ran 'train feature index' BEFORE 'train model', as I was informed the order apparently wasn't important.

And also note my data set has around 62 minutes of audio all split into 10 ish second segments.

**Comment by RVC-Boss** [comment]
If you can find the added_xxxxxxx.index in logs/xxx folder, the all index training pipeline is done successfully.

**Comment by toriwale** [comment]
> If you can find the added_xxxxxxx.index in logs/xxx folder, the all index training pipeline is done successfully.

So the train 'feature index' step does NOT need to complete at 4960/4960. And has no impact on the quality of the model at all?

**Comment by RVC-Boss** [comment]
> > If you can find the added_xxxxxxx.index in logs/xxx folder, the all index training pipeline is done successfully.
> 
> So the train 'feature index' step does NOT need to complete at 4960/4960. And has no impact on the quality of the model at all?

Yes.

**Comment by mella2023** [comment]
> > > If you can find the added_xxxxxxx.index in logs/xxx folder, the all index training pipeline is done successfully.
> > 
> > 
> > So the train 'feature index' step does NOT need to complete at 4960/4960. And has no impact on the quality of the model at all?
> 
> Yes.

I met the same error and the training stop at Train Epoch: 1 [0%]
RuntimeError: The expanded size of the tensor (12800) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [1, 12800].  Tensor sizes: [0]
what does this mean?

**Comment by yuki556677** [comment]
are you solve the problem?

**Comment by ILG2021** [comment]
经常卡死在这里，不生成索引。

**Comment by Jay-9-c** [comment]
> If you can find the added_xxxxxxx.index in logs/xxx folder, the all index training pipeline is done successfully.

I got the same problem, and I can not find the added_xxxxxxx.index in logs/xxx folder. How can I solve the problems? Thanks for your reply.

**Comment by a2659802** [comment]
> If you can find the added_xxxxxxx.index in logs/xxx folder, the all index training pipeline is done successfully.

<img width="1522" height="1101" alt="Image" src="https://github.com/user-attachments/assets/55d0c1ab-08a8-44a7-8036-d0a131697178" />

<img width="787" height="810" alt="Image" src="https://github.com/user-attachments/assets/894479a7-e346-4bda-b9f1-6bdcd5e0a1a5" />

<img width="1135" height="198" alt="Image" src="https://github.com/user-attachments/assets/c386f7c0-fe2c-4d3b-ae9e-7099727e0dcd" />

 I have same problem. when i click "训练特征索引", it stuck in "Converged  xxxx" and no `index` file generated

一样的问题，在云平台租的3090，训练时选了200轮，在101轮的时候ctrl+c终止训练，打算试一下100轮的效果，结果没法生成index文件
