### ISSUE TITLE
How to load pretrained_v2 models?

### ISSUE THREAD

**Issue by artificialnouveau** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1057]
I am having issues with loading the rvc v2 model weights. Is it because the hubert_base.pt is no longer the pretrained model, rather I should use load one of the .\pretrained_v2 models? If so, how do I load them?

**Comment by anty94** [comment]
+1

**Comment by RVC-Boss** [comment]
Hubert_base.pt and the pretrained_v2 models(G/D) are need to be loaded.
