### ISSUE TITLE
gui版本支持无音高模型的推理

### ISSUE THREAD

**Issue by alex89123** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#106]
![image](https://user-images.githubusercontent.com/131310798/233223752-00681a3b-fb41-4aad-8871-b697ebb7a3f6.png)
![image](https://user-images.githubusercontent.com/131310798/233223903-08df53c2-ce89-4113-8976-7b071c12ef95.png)
using the latest version，用的是最新版本
![image](https://user-images.githubusercontent.com/131310798/233224503-990b8843-784c-4f5f-8be6-016596babf0c.png)
这是我的电脑配置：
![image](https://user-images.githubusercontent.com/131310798/233224613-2500af1c-4d51-4656-8036-3897cb184d40.png)
![image](https://user-images.githubusercontent.com/131310798/233224705-530880b1-b1a7-46e4-89c5-94b6e9d4770e.png)

**Comment by liujing04** [comment]
收到反馈，我们复现一下。
你是下载的老版本的hf上的大包，然后直接下的最新的updated包，里面所有文件进行覆盖，是吗

**Comment by alex89123** [comment]
> 收到反馈，我们现在恢复一下。 你是下载的旧版的hf上的大包，然后直接接下最新的updated包，里面所有文件进入外壳，是吗

是的呢

**Comment by mikisayakamitakihara** [comment]
箭头所指示的位置可能是一个错误，当我们在那里添加检查并进行培训时。选择这个选项并重新训练模型后，这个问题的错误似乎已经解决了。　　模型是否带音高指导(唱歌一定要, 语音可以不要)
![BUsqlaeE](https://user-images.githubusercontent.com/121276038/233546284-b7cb4db0-c47e-4cc4-b2e6-9e3acc5cfbb9.png)

**Comment by mikisayakamitakihara** [comment]
也许，或者说　　　箭头所指示的位置可能是一个错误，当我们在那里添加检查并进行培训时。选择这个选项并重新训练模型后，这个问题的错误似乎已经解决了。　　（（模型是否带音高指导(唱歌一定要，语音可以不要)））
![1](https://user-images.githubusercontent.com/121276038/233548231-ff04993a-b0fa-436b-b9f7-2346e8497677.png)

**Comment by alex89123** [comment]
> 也许，或者说　点击箭头指示的位置进行训练的模型可能会出现这个问题。在我的情况下，点击“是”并进行训练的模型似乎没有发生这个问题。　　(模型是否带音高指导(唱歌一定要，语音可以不要)) ![1](https://user-images.githubusercontent.com/121276038/233548231-ff04993a-b0fa-436b-b9f7-2346e8497677.png)

谢谢您，这样设置可以正常实时转换了， 不过可能拉长了实时转换的处理时间。等待作者更新软件，哈哈

**Comment by RVC-Boss** [comment]
嗯，在群友的帮助下已经知道问题在于gui版本还没写无音高模型的推理支持了，后面更新版本我们修复掉这个

**Comment by RVC-Boss** [comment]
Done.
