### ISSUE TITLE
Where is RVC-beta.7z?

### ISSUE THREAD

**Issue by smartgalilei** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1060]
I can't find this file neither her nor huggingface.

**Comment by zzadryzz** [comment]
just download the source archive right here.

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases/tag/updated0814v2
You can download it from huggingface.
