### ISSUE TITLE
G*.pth checkpoints do not match the RVC v2 models

### ISSUE THREAD

**Issue by artificialnouveau** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1068]
Hi there, 

I'm trying to load a G*.pth checkpoint to load my net_g model using: 

'''
utils.load_checkpoint(
            utils.latest_checkpoint_path(hps.model_dir, "G_*.pth"), net_g, optim_g
        )
''' 

I get the following error:

INFO:root:enc_p.emb_pitch.weight is not in the checkpoint
INFO:root:dec.m_source.l_linear.weight is not in the checkpoint
INFO:root:dec.m_source.l_linear.bias is not in the checkpoint
INFO:root:dec.noise_convs.0.weight is not in the checkpoint
INFO:root:dec.noise_convs.0.bias is not in the checkpoint
INFO:root:dec.noise_convs.1.weight is not in the checkpoint
INFO:root:dec.noise_convs.1.bias is not in the checkpoint
INFO:root:dec.noise_convs.2.weight is not in the checkpoint
INFO:root:dec.noise_convs.2.bias is not in the checkpoint
INFO:root:dec.noise_convs.3.weight is not in the checkpoint
INFO:root:dec.noise_convs.3.bias is not in the checkpoint
INFO:root:dec.noise_convs.4.weight is not in the checkpoint
INFO:root:dec.noise_convs.4.bias is not in the checkpoint
INFO:root:dec.ups.4.bias is not in the checkpoint
INFO:root:dec.ups.4.weight_g is not in the checkpoint
INFO:root:dec.ups.4.weight_v is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.0.bias is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.0.weight_g is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.0.weight_v is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.1.bias is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.1.weight_g is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.1.weight_v is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.2.bias is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.2.weight_g is not in the checkpoint
INFO:root:dec.resblocks.12.convs1.2.weight_v is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.0.bias is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.0.weight_g is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.0.weight_v is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.1.bias is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.1.weight_g is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.1.weight_v is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.2.bias is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.2.weight_g is not in the checkpoint
INFO:root:dec.resblocks.12.convs2.2.weight_v is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.0.bias is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.0.weight_g is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.0.weight_v is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.1.bias is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.1.weight_g is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.1.weight_v is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.2.bias is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.2.weight_g is not in the checkpoint
INFO:root:dec.resblocks.13.convs1.2.weight_v is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.0.bias is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.0.weight_g is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.0.weight_v is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.1.bias is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.1.weight_g is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.1.weight_v is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.2.bias is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.2.weight_g is not in the checkpoint
INFO:root:dec.resblocks.13.convs2.2.weight_v is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.0.bias is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.0.weight_g is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.0.weight_v is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.1.bias is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.1.weight_g is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.1.weight_v is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.2.bias is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.2.weight_g is not in the checkpoint
INFO:root:dec.resblocks.14.convs1.2.weight_v is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.0.bias is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.0.weight_g is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.0.weight_v is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.1.bias is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.1.weight_g is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.1.weight_v is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.2.bias is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.2.weight_g is not in the checkpoint
INFO:root:dec.resblocks.14.convs2.2.weight_v is not in the checkpoint
shape-dec.conv_post.weight-mismatch|need-torch.Size([1, 16, 7])|get-torch.Size([1, 32, 7])
INFO:root:dec.conv_post.weight is not in the checkpoint
INFO:root:Loaded model weights

Do you know what the cause of the issue is?

**Comment by RVC-Boss** [comment]
You shouldn't modify the sample rate during training. It's caused by sample rate modifying when continuing training.
