### ISSUE TITLE
RVC API GET/POST REQUEST

### ISSUE THREAD

**Issue by skshadan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1074]
i want to use RVC as an api? how can i use?

something like this.....

upload the audio - load the model - get generated audio - without using gradio!

?????????????????????

**Comment by skshadan** [comment]
https://gitlab.com/alexchadwick/bark-rvc-api

see this - this is using bark but how can i run normal RVC models?

**Comment by skshadan** [comment]
i just want simple api code, which can just take my audio and then do the voice conversion.

**Comment by professrr** [comment]
+1 I just want to use API or CLI tool

**Comment by skshadan** [comment]
https://github.com/skshadan/TTS-RVC-API

check this out @professrr

**Comment by professrr** [comment]
@skshadan Yo that's great! But is there any solutions just only to convert `input.wav` with my `model.pth` and `mymodel.index` to some `output.wav` ?

**Comment by RavneetDTU** [comment]
@professrr did you able to find any solution for you issue? 
Where you just only to convert input.wav with my mymodel.pth and mymodel.index to some output.wav

Please share looking for the same.

**Comment by MRINFINITE0** [comment]
Greetings! @skshadan @professrr @RavneetDTU I am trying to figure out api part and implemented  collab notebook on azure notebook and interface is up running we can use azure for better scalability and can develop API there for project if you guys are interested then we can partner up and boost things up

**Comment by skshadan** [comment]
sure, share ur mail.

**Comment by MRINFINITE0** [comment]
@skshadan  email- infinitygaming2580@gmail.com

**Comment by professrr** [comment]
@MRINFINITE0 @skshadan @RavneetDTU I am developing fastAPI project to convert `input.wav` to `output.wav`  
Everything is ok, you may also take a conversion part from RVC to build your own project

**Comment by skshadan** [comment]
Check out this, maybe this will help
https://github.com/skshadan/TTS-RVC-API

**Comment by MRINFINITE0** [comment]
@professrr @skshadan Can we work together?

**Comment by RavneetDTU** [comment]
@professrr and @MRINFINITE0 I am also interested in developing this API. Here is my mail ID: ravneet.dtu@gmail.com. Let me know and how to connect with you guys.

**Comment by ProjCRys** [comment]
Any progress?

**Comment by snowfluke** [comment]
Im joining, invite me awala@duck.com

**Comment by Tps-F** [comment]
We will provide an API for inference by the end of this month.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion

**Comment by peili** [comment]
> We will provide an API for inference by the end of this month. https://github.com/RVC-Project/Retrieval-based-Voice-Conversion

Any updates you can share on the first draft you wanted to release?

**Comment by yukiarimo** [comment]
Anything new?
