### ISSUE TITLE
Audio comes out with accent? Is it the index file or am I doing something wrong?

### ISSUE THREAD

**Issue by MastermindR** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1082]
I finally managed to train a model around 2,000k epoch's, and I tried rendering the audio after generating an index file. I've tried it with and without an index file and even made a separate data set so I could see if I did anything wrong; Mangio-Crepe first and then RMVPE, but it sounds the same every time. I assume that the index file stops training when it says "Success" and generates the added and trained files, so if I have to wait longer to finish training the index, I will. I waited for around 2 hours with no result. This is the audio output:

https://vocaroo.com/1hOjhz5KyGev

(It is who you think it is rip)

**Comment by pursuitcurves** [comment]
Can you double check on the logs if it is actually doing something? The logs should look like it divided the training audio into 400-500 smaller segments depending on the training audio length.
