### ISSUE TITLE
ModuleNotFoundError: No module named 'noisereduce'

### ISSUE THREAD

**Issue by Nox1911** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1090]
F:\RVC0813Nvidia>python gui_v1.py
Traceback (most recent call last):
  File "F:\RVC0813Nvidia\gui_v1.py", line 43, in <module>
    import noisereduce as nr
ModuleNotFoundError: No module named 'noisereduce'

**Comment by RVC-Boss** [comment]
runtime\python.exe -m pip install noisereduce
