### ISSUE TITLE
v2感觉比v1电音重

### ISSUE THREAD

**Issue by hpx502766238** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1092]
如题，直接使用示例模型测试的
[RVC814测试.zip](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/12446012/RVC814.zip)
测试歌曲红豆，用yongzhanv2示例模型测试的，电音效果很明显，kikiv1就好很多，还有tianfuzhenv2是自己训练了300个epoch的，但感觉还是有些电音，不知道是不是心理作用。

**Comment by RVC-Boss** [comment]
数据集原因。
