### ISSUE TITLE
Document request: Training from scratch

### ISSUE THREAD

**Issue by tarepan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#110]
## Summary
There seems to be no document of ***training from scratch*** (base model training).  
Can you share the method?  
Once I successfully reproduce the result with shared info, I am grad to write document (make PR).  

## Current Status
Current RVC repository contain enough information for fine-tuning.  
But, there is only little info about training from scratch (base model training).  

README suggests that we can train base model with VCTK.  
`/train_nsf_sim_cache_sid_load_pretrain.py` is training code, but it seems to be for fine-tuning.  
`/train/` contain some command txt, but it specify missing file (`train_nsf_sim_cache_sid.py`).  

As a result, I cannnot reproduce base model.  

## Request
Can you share method to train base model?  

## Proposal
If you kindly share the method, I am grad to write documentation for future developers.

**Comment by fire** [comment]
I found https://booth.pm/en/items/4701666 but i don't know how to use.
