### ISSUE TITLE
probable bug in gui.py

### ISSUE THREAD

**Issue by captinbaptin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#111]
I'm not at all familiar with python so its possible this isnt a bug but rather is an issue on my end.
I'm running this in a conda environment on linux mint 20. When I launch gui.py it gives an index error on line 220. I looked at the code in gui.py and found that when it runs `default_value=input_devices[sd.default.device[0]]` sd.default.device[0] is outside the range of input_devices. I replaced that line and the similar default output device line with `default_value=input_devices[0]` and `default_value=output_devices[0]` respectively and then it launched successfully.

**Comment by EntropyRiser** [comment]
It seems that sounddevice fail to get the default device of your Mint.
That's the first case I have met so you may fix the code yourself. If this issue occurs more times I would remove the function of searching for default devices.

**Comment by deadp** [comment]
I'm getting this error as well on Arch. I think its a pytorch issue but I'm not super familiar with this all.
