### ISSUE TITLE
关于loss_kl值

### ISSUE THREAD

**Issue by lcwuxianr** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1112]
感觉，如果在训练中保存模型时，把模型保存点的loss_kl值也对应的保存到日志里，是不是就能快速找到效果相对较好的模型了？有大佬帮实现一下吗？

**Comment by RVC-Boss** [comment]
现在就会定期保存（打印+输出日志到train.log）的，通过json文件配置设置定期打印频率
configs/采样率_版本.json里面的log_interval越低打印频率越高
找较好的模型：定期保存小模型，全部跑完后推理测试二分法选择最优epoch

**Comment by lcwuxianr** [comment]
推理测试二分法怎么弄？请问哪里有相关的资料
