### ISSUE TITLE
Issue on Run Web

### ISSUE THREAD

**Issue by BRLTS** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1118]
I have an error message when try to run the gradio:

Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 16, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

what should i do?

**Comment by Tps-F** [comment]
@BRLTS Please run `pip install python-dotenv`

**Comment by BRLTS** [comment]
@Tps-F 
where should i run this? is it before the Run Web?

**Comment by Tps-F** [comment]
@BRLTS 
Yes!

**Comment by lennondong** [comment]
192:Retrieval-based-Voice-Conversion-WebUI-main Leo$ pip install python-dotenv
Requirement already satisfied: python-dotenv in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.0.0)


**I have installed the dotenv. But the error still appeared.**

Traceback (most recent call last):
  File "/Volumes/ZhiTai/AI/Retrieval-based-Voice-Conversion-WebUI-main/infer-web.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by oloboy** [comment]
from command line go to 
cd C:\pinokio\api\rvc.pinokio.git\app\env\Scripts
run  
activate.bat
and
pip install python-dotenv
