### ISSUE TITLE
灵活选择gpu

### ISSUE THREAD

**Issue by ZhangZhaofeng** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#112]
在infer阶段，如果有两个以上的gpu，程序会默认选择所有gpu进行推理。
这时如果有gpu已经被占用，就会发生内存不足的错误。
希望在infer阶段加入选择gpu的选项。

**Comment by RVC-Boss** [comment]
大佬分析得有道理，但是选择训练GPU是可以手工选的嗷~有个写卡号的选项，并且卡号对应什么能用的N卡有一个文本栏做了展示
推理的话用什么卡，需要在启动的时候在config里面改好device

**Comment by ZhangZhaofeng** [comment]
训练时可以选卡，推理的话好像不会自动选。如果能改config的话也行。我现在是在docker里面跑的，每次开始要把被占用的卡禁掉。

**Comment by RVC-Boss** [comment]
这个实现有难度，怎么判断哪个GPU是最优的GPU呢，也有可能一个显存已经被占用的GPU性能更强，也能继续用。
我还是建议config里面人为判断。
