### ISSUE TITLE
RVC colab disconnect

### ISSUE THREAD

**Issue by Focus506** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1123]
am I the only one that get disconnected when I try to run the colab version of RVC ? I try on different pc and same problem :/
It's disconnect me from the google colab during the step2b on harvest mode or during step 3 after <10 min.

**Comment by pniewolski** [comment]
same here, I started using RVC on Colab 3 days ago and I could do nice session with 200 epochs. now 20 epochs and cut off. And only 20 voica samples. So colab is not usable anymore :(

**Comment by vovan0802ee** [comment]
help PLZ !!!

**Comment by mocci24** [comment]
There's problem between github and colab i think, 🤔
for solution i don't recommended using github to colab,
for now i use hugingface, 
check this
https://colab.research.google.com/drive/1sC3PcoVQCt-LEtptH3v5SX7xXer2YdEO?authuser=1#scrollTo=Cj_6ldpEZ8w2

**Comment by Valr1e** [comment]
Same.. when disconnect all runtime reset all file gone. And you must re-install all. Please fix it

**Comment by little-brother** [comment]
I think that it's a not RVC notebook but Google Colab issue.
I tried to use a simplified notebook with the same result (disconnect after about 10min).

**Comment by mocci24** [comment]
it's google colab issue, i don't know the details, but i think they are trying to ban rvc 🤔

**Comment by AbdurrehmanSubhani** [comment]
Facing the same issue, i think it has something to do with their updated policy on not allowing the following anymore:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/53292031/517c98f3-bcf2-4c1a-8d6d-4fbf5ff0b54f)

**Comment by JRabun517** [comment]
Glad I am not the only one with this issue. It seems like there aren't many people complaining about it yet which makes me wonder if I am just too poor to buy a Google collab package.

**Comment by little-brother** [comment]
I tried to run training without GUI e.g. 
```
!mkdir /content/Retrieval-based-Voice-Conversion-WebUI/logs/myvoice
python3 /content/Retrieval-based-Voice-Conversion-WebUI/trainset_preprocess_pipeline_print.py /content/drive/MyDrive/dataset/myvoice 40000 2 /content/Retrieval-based-Voice-Conversion-WebUI/logs/myvoice False
```
The result is the same - disconnect after 5-10min. So it's a not the policy restriction. It looks like a repository ban.

**Comment by mocci24** [comment]
exactly, i found this since day one, 
i tried to upload all repo to my drive including hubert, pre-trained files etc, and extract it to colab (before i do training), and surprisingly it run without any issue, you can try it,

**Comment by instant-high** [comment]
Same problem. 
Tried different accounts and different colab notebooks.
Disconnected between 10 and 20 epochs

**Comment by little-brother** [comment]
I copied the repisotory on Google disk, then downloaded assets.
The first attempt was to run from Google disk and it failed with an error like #441.
So I run T4-session and copied RVC folder with assets to `/content/RVC` and finally the train was completed successfully.

My Colab has only 4 steps
```
# 1. Attach Google Drive
from google.colab import drive
drive.mount("/content/drive")

# 2. Copy RVC on the session machine
!cp -r /content/drive/MyDrive/RVC /content/```

# 3. Install dependencies
!nvidia-smi

!apt-get -y install build-essential python3-dev ffmpeg
!pip3 install --upgrade setuptools wheel
!pip3 install --upgrade pip
!pip3 install faiss-cpu==1.7.2 fairseq gradio==3.14.0 ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.2
%cd /content/RVC
!pip3 install -r requirements.txt

# 4. Run UI
%cd /content/RVC
!python3 infer-web.py --colab --pycmd python3
```

**Comment by D-Flime** [comment]
Worked fine but last 3 weeks it started to disconnect after 10 minutes of work.

**Comment by instant-high** [comment]
At the bottom of the above image: creating deep fakes.

**Comment by SalavatNabi** [comment]
> I think that it's a not RVC notebook but Google Colab issue. I tried to use a simplified notebook with the same result (disconnect after about 10min).

Can it be solved by buying the pro version?

**Comment by SalavatNabi** [comment]
> Facing the same issue, i think it has something to do with their updated policy on not allowing the following anymore: ![image](https://user-images.githubusercontent.com/53292031/264368863-517c98f3-bcf2-4c1a-8d6d-4fbf5ff0b54f.png)

What is the point of colab if it is not going to run a program?

**Comment by instant-high** [comment]
![Screenshot](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/77229558/1856b9f3-fe1a-4443-bf62-f7def034895b)

**Comment by RiniRaw** [comment]
> ![Screenshot](https://user-images.githubusercontent.com/77229558/270156765-1856b9f3-fe1a-4443-bf62-f7def034895b.jpg)

I bought a pro subscription, and yet.... I ggt an error. I lost a great deal of tokens to get 0 results.

**Comment by Daviddv0601** [comment]
Will nobody help?! I have the exact same problem! Been a week now and nothing's changed. I don't have enough data to install the local version. PLEASE HELP!!!

**Comment by hahunavth** [comment]
I found [this notebook](https://www.kaggle.com/code/varaslaw/aisingers-rvc-rmvpe-https-t-me-aisingers-ru) on Kaggle, and it doesn't use WebUI, so it doesn't face disconnection issues on Google Colab or Kaggle.

**Comment by Hedwig7s** [comment]
> I tried to run training without GUI e.g.
> 
> ```
> !mkdir /content/Retrieval-based-Voice-Conversion-WebUI/logs/myvoice
> python3 /content/Retrieval-based-Voice-Conversion-WebUI/trainset_preprocess_pipeline_print.py /content/drive/MyDrive/dataset/myvoice 40000 2 /content/Retrieval-based-Voice-Conversion-WebUI/logs/myvoice False
> ```
> 
> The result is the same - disconnect after 5-10min. So it's a not the policy restriction. It looks like a repository ban.

Because the webui code is still present it has to be fully stripped

**Comment by mwamon** [comment]
> I found [this notebook](https://www.kaggle.com/code/varaslaw/aisingers-rvc-rmvpe-https-t-me-aisingers-ru) on Kaggle, and it doesn't use WebUI, so it doesn't face disconnection issues on Google Colab or Kaggle.

Is there an English version? Chrome doesnt translate the full page for some reason

**Comment by cahayamahardika16** [comment]
Look that error much this AttributeError: 'FigureCanvasAgg' object has no attribute 'tostring_rgb'
But how can fix RVC v2 Disconnected in/content/Mangio-RVC-Fork/train/utils
![Capture 253](https://github.com/user-attachments/assets/f3d89114-2952-4e3f-a3a1-0e3619d09cd4)
