### ISSUE TITLE
Adding automatic pitch like in SVC?

### ISSUE THREAD

**Issue by sickdyingdead** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1130]
I would like to know if there is some way to add auto f0 in some future updates because sometimes you have to generate 2 or more times and cut audio in peaces just to get the best pitch result. 

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/108198294/53323ea0-2ea3-432c-a75c-22dbf75630ec)

**Comment by RVC-Boss** [comment]
This is feasible, but it is necessary to know the pitch range of the target speaker, which needs to be calculated based on the f0 folder of the training set

**Comment by rogermiranda1000** [comment]
May be useful to check how [rvc-tts implemented this](https://github.com/litagin02/rvc-tts-webui/blob/main/lib/infer_pack/modules/F0Predictor/PMF0Predictor.py)
