### ISSUE TITLE
新版本无法使用。

### ISSUE THREAD

**Issue by GGbond2007** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1138]
在安装了最新0814版本后。我无法使用推理以及训练和伴奏提取功能。具体的情况是当点击转换按钮时，会处理一阵。过了一段时间就会显示error。在推理过程中老版本CPU会比较猛烈，但是新版本中不会再转动CPU。导致后来也会造成error。训练数据的时候，第2步提取声音特征，只要点击就会error。请问这是什么问题呢？可以解决吗？谢谢！

**Comment by RVC-Boss** [comment]
需要提供控制台报错截图和logs文件夹里面的.log日志文件
