### ISSUE TITLE
Gradio API is not working properly

### ISSUE THREAD

**Issue by super1515** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1151]
I want to change the voice model, which in the web interface is presented as a drop-down list at the top of the page. However, none of the API methods infer_clean, infer_refresh, infer_convert accepts the file name of the voice model .pth.

Another problem I encountered in the Gradio API was using the uvr_convert method. It's strange, but in order to separate the vocals from the accompaniment, I needed to call this method 3-5 times in a row.

**Comment by fuomag9** [comment]
Same issue here, my voice models don't appear in the UI

**Comment by PatrickAi01** [comment]
I got the api for the infer/convert/batch to work but not the infer/refresh or infer/clean this is my api request for convert/batch

![Screenshot 2023-09-02 at 3 08 43 PM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/136882606/373c1405-8a8d-496d-823b-5dbe56f21de2)

**Comment by jswildone** [comment]
@PatrickAi01 
Hey mate!
I saw you've seemed to have already solved the problem but I would be happy to offer a reward of $100USD if you could lend me a hand building out this same API call (batch infer convert). I cannot for the life of me figure out how to implement this functionality (RVC1006 & GTX1080) such that I can have it properly run locally. I just want to be able to specify a speaker (PTH/index), an input file (or directory) and an output directory. If you would be interested please feel free to get in touch :)
discord: jsw4142

**Comment by PatrickAi01** [comment]
hello my friend @jswildone I could help you out, I sent you a request on discord

**Comment by ZBEP** [comment]
RVC1006

```
import requests
import json
url = "http://127.0.0.1:7897/run/infer_convert_batch"
payload={
    "data": [
        0,
        r"C:\Users\ZBEP\Desktop\audios",
        r"C:\Users\ZBEP\Desktop\opt",
        None,
        0.0,
        "rmvpe",
        "HW",
        r"logs\LetovClean\added_IVF2140_Flat_nprobe_1_LetovClean_v2.index",
        0.9,
        3,
        0,
        1,
        0.33,
        "wav",
    ]
}
response = requests.post(url, json=payload).json()
```
