### ISSUE TITLE
RVC-UI working with M1 MacOS, ffmpeg issue

### ISSUE THREAD

**Issue by sakanventures** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1161]
So I got everything setup with the RVC-UI on my Mac and it launches successfully
but when I try to use a .pth file and convert audio, I get an error with the ffmpeg.

Any assistance??
![Screenshot_2023-09-01_at_4 46 53_PM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/119982316/e4952795-9576-4490-aee3-af3b006a85f2)

**Comment by vivekjvsdot** [comment]
I got the same error while working with RVC-WebUI.
Upon investigation,I found that there are hidden files in the audio(training dataset) directory.I named it as 'work'
In my case,there were ".DS_Store" files.
The ".DS_Store" file is a system file created by macOS Finder to store custom attributes of a folder. It's not an audio file, so attempting to load it as audio is causing the error.

to delete the files(macos)
`find . -name ".DS_Store" -print -delete `

<img width="855" alt="image" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/74709571/3b3b27e4-e92b-4703-96dc-c533b7f388c0">

 The error is resolved.Hope it helps you.
