### ISSUE TITLE
Gradio API for /run/infer_refresh

### ISSUE THREAD

**Issue by PatrickAi01** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1172]
I am not particularly sure why this is not working, I have gotten the API for conversion to work but not this one. anyone has ideas?

![Screenshot 2023-09-02 at 8 15 49 PM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/136882606/a47b216e-27b1-44e3-9885-561194cdec80)

![Screenshot 2023-09-02 at 8 16 06 PM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/136882606/5be60608-d36e-482f-b0d3-26fe5c4e4b39)

**Comment by super1515** [comment]
Hello. I also ran into this problem. Before calling the infer_convert API method, you need to select the _.pth_ model file. In WebUI, this can be done using a drop-down list, but there is no corresponding method for this in the Gradio API.
Therefore, I propose the following solution.
In the [infer-web.py](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/b5050fbf0d6b82305c589c59393b94ab72e606cb/infer-web.py#L1027C12-L1027C12) need to add one line that will add a new endpoint to the Gradio API, it should turn out like this:
```python
sid0.change(
        fn=vc.get_vc,
        inputs=[sid0, protect0, protect1],
        outputs=[spk_item, protect0, protect1, file_index2, file_index4],
        api_name="infer_set",
)
```
Now in the documentation API you can see the new endpoint `/run/infer_set`. It should be called before the _/run/infer_convert_ method. For example as follows:
```JSON
{
    "data": [
        "myModel.pth",
        0.33,
        0.33
    ]
}
```
I hope this helps you.

**Comment by PatrickAi01** [comment]
So essentially you will be creating a new gradio api endpoint?

**Comment by super1515** [comment]
> So essentially you will be creating a new gradio api endpoint?

Yes, in fact, adding only one line to the file [infer-web.py](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/b5050fbf0d6b82305c589c59393b94ab72e606cb/infer-web.py#L1027C12-L1027C12):
`api_name="infer_set",`
You will have a new endpoint that will allow you to select .pth model files.

**Comment by PatrickAi01** [comment]
okay i will try it out thank you

**Comment by PatrickAi01** [comment]
it work incredibly! thank you my friend @super1515

**Comment by PatrickAi01** [comment]
by any chance have you tried out the uvr api? @super1515

**Comment by super1515** [comment]
> by any chance have you tried out the uvr api? @super1515

I had a problem with the `uvr_convert` API method. In order to divide the audio into vocals and instrumental, for some reason I needed to call the method 3-5 times. I think the problem is in the function https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/b5050fbf0d6b82305c589c59393b94ab72e606cb/infer/modules/uvr5/modules.py#L17
Every time yield is called in the code, for example [here](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/b5050fbf0d6b82305c589c59393b94ab72e606cb/infer/modules/uvr5/modules.py#L77C17-L77C39):
`yield "\n".join(infos)`
The server sends a new response each time. 
I think I need to delete all the lines with yield in the code. And then add at the very end something like:
`return "\n".join(infos)`
This way, you don't have to call this method multiple times.

**Comment by PatrickAi01** [comment]
@super1515 i have the same problem with the conver_batch, i need to call it 3x to get it working,

**Comment by super1515** [comment]
> conver_batch

I think that to fix this, you need to remove all yield in the [function](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/94277fd71e3e671257f1473bcf807dbd7996ade8/infer/modules/vc/modules.py#L228) by analogy and then add to the end of this function `return "\n".join(infos)`.

**Comment by PatrickAi01** [comment]
btw the reason as to why i am using the infer/convert/batch instead of the infer convert is because there seems to be no output directory for the infer/convert API 
is that really the case and I should stick with the infer convert/batch?

**Comment by super1515** [comment]
> btw the reason as to why i am using the infer/convert/batch instead of the infer convert is because there seems to be no output directory for the infer/convert API
> is that really the case and I should stick with the infer convert/batch?

Yes, I think it's right

**Comment by PatrickAi01** [comment]
So basically I will replace all these 4 yields with the `return "\n" .join(infos)` ???

![Screenshot 2023-09-04 at 12 10 35 PM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/136882606/7a55a4df-b2a0-4cee-acb8-b73fc048bfb6)

**Comment by PatrickAi01** [comment]
As well as here in the vc/modules.py file for the [](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/94277fd71e3e671257f1473bcf807dbd7996ade8/infer/modules/vc/modules.py#L228)
![Screenshot 2023-09-04 at 12 13 32 PM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/136882606/5fe47bb3-c248-4a26-9b1f-e339e77f5792)

**Comment by super1515** [comment]
No, not really. You need to delete all the yield lines and then write only one return line at the end of the function.
