### ISSUE TITLE
Multi-speaker training 

### ISSUE THREAD

**Issue by bochch** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1176]
Hi! I'm wondering if there is a guide for multi-speaker training in the terminal. I'm aware that it's possible but not with a GUI yet. Could someone share their knowledge on how to correctly prepare the dataset? I'm struggling with creating a filelist.txt, and it's easy to do with two or three speakers, but when dealing with a large dataset containing many speakers, it becomes challenging to create a filelist.txt without a specific script. Could anyone help with this?

**Comment by BoltzmannEntropy** [comment]
I used so-vits-svc-fork, but it does not seem to be compatible with this repo
