### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by InkyKnight** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1180]
So I'm completely new to any of this and have no idea what I'm doing. There's no spaces in any of the folders or .wav files. I made sure everything was in the same drive, if that's in any way important, and it just keeps sending back an error.

Here's the entirety of what I got back in the command window:

F:\Documents\RVC AI VOICE\RVC-beta\RVC-beta0717>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Found GPU NVIDIA GeForce GTX 1660 Ti , force to fp32
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
runtime\python.exe trainset_preprocess_pipeline_print.py F:\Documents\AIVoiceSamples\ApexLegends\RevenantSamples 40000 6 F:\Documents\RVC AI VOICE\RVC-beta\RVC-beta0717/logs/Apex-Revenant01 False
Traceback (most recent call last):
  File "F:\Documents\RVC AI VOICE\RVC-beta\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 20, in <module>
    f = open("%s/preprocess.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Documents\\RVC/preprocess.log'

**Comment by flowzen1337** [comment]
> So I'm completely new to any of this and have no idea what I'm doing. There's no spaces in any of the folders or .wav files. I made sure everything was in the same drive, if that's in any way important, and it just keeps sending back an error.
> 
> Here's the entirety of what I got back in the command window:
> 
> F:\Documents\RVC AI VOICE\RVC-beta\RVC-beta0717>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897 Found GPU NVIDIA GeForce GTX 1660 Ti , force to fp32 Use Language: en_US Running on local URL: http://0.0.0.0:7897 runtime\python.exe trainset_preprocess_pipeline_print.py F:\Documents\AIVoiceSamples\ApexLegends\RevenantSamples 40000 6 F:\Documents\RVC AI VOICE\RVC-beta\RVC-beta0717/logs/Apex-Revenant01 False Traceback (most recent call last): File "F:\Documents\RVC AI VOICE\RVC-beta\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 20, in f = open("%s/preprocess.log" % exp_dir, "a+") FileNotFoundError: [Errno 2] No such file or directory: 'F:\Documents\RVC/preprocess.log'

I guess it’s the path: “F:\Documents\RVC AI VOICE\….” where the spaces making trouble, try to rename the folder to “…\RVC_AI_VOICE\…” maybe that’s already the solution

**Comment by InkyKnight** [comment]
Oh. Somehow I completely forgot that folder existed. That was exactly the issue. Thank you so much!
