### ISSUE TITLE
Keeps Disconnecting

### ISSUE THREAD

**Issue by MinecrafterGirl40** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1184]
I keep having issues with my model disconnecting and it keeps giving me the error
"Cannot connect to GPU".
What's going on?

**Comment by mashhoor-ahdal** [comment]
Same here, keeps disconnecting after some time  any solution

**Comment by spgoutham** [comment]
If you wannna train and convert your model. Use my google colab notebook in my repo. It wont disconnect while you train and even made simpler

**Comment by aarvndhNG** [comment]
> If you wannna train and convert your model. Use my google colab notebook in my repo. It wont disconnect while you train and even made simpler

Which one?

**Comment by Parsam70** [comment]
> اگر می خواهید مدل خود را آموزش دهید و تبدیل کنید. از نوت بوک google colab من در مخزن خود استفاده کنید. در حین تمرین قطع نمی شود و حتی ساده تر می شود

rvc in g colab for me dissconected!

**Comment by MRINFINITE0** [comment]
Greetings! @spgoutham I am working around api for rvc and setting up rvc in azure notebook , if you are interested then we can partner up and boost things up
