### ISSUE TITLE
Robotic / metallic noise on S letters

### ISSUE THREAD

**Issue by Mixomo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#119]
Hi, this is really a wonderful project, so far it is the one that has the best quality compared to its alternatives, incredible how well it works with small datasets (in my case 9 minutes of clean singing), and how well it recreates the voice timbre.
I only have one question, is it normal that in the S letters or breaths there is a metallic noise? is it produced by the vocoder? I have trained my model for a longer time thinking that the noise would go away, but it sounds exactly the same, either with 20 minutes of training or more than 1 hour. Do I need to do a longer training? How many epochs do you recommend?
Thanks and congratulations for the project!

**Comment by fumiama** [comment]
Well, on the contrary, you may want to try a shorter training instead😂. A small dataset cannot cover all tones thus the longer you train, the more details in the base model you lost.

**Comment by Tybost** [comment]
If you have more data (20m+) and train for longer you can potentially smooth out the roboticness slightly. Don't forget to equip the .NPY and .INDEX trained (sometimes .NPY greatly helps reduce the robotic noises) but in some rare cases .INDEX can introduce a lisp (Zundamodel)

I find DIO trained voice models to have a softer robotic sound than default HARVEST and the sound quality is about the same.

Changelog indicates future plans for a possible improvement in reducing it further. _"Collect breath wav and add it to the training set to correct the problem of breath changing sound and electronic sound "_

**Comment by Tybost** [comment]
> > If you have more data (20m+) and train for longer you can potentially smooth out the roboticness slightly. Don't forget to equip the .NPY and .INDEX trained (sometimes .NPY greatly helps reduce the robotic noises) but in some rare cases .INDEX can introduce a lisp (Zundamodel)
> > I find DIO trained voice models to have a softer robotic sound than default HARVEST and the sound quality is about the same.
> > Changelog indicates future plans for a possible improvement in reducing it further. _"Collect breath wav and add it to the training set to correct the problem of breath changing sound and electronic sound "_
> 
> Thanks for your answer! I use the file total_fea.npy and one called Added.index, (since that is how it is pointed in the gradio interface) and that's how the model sounds. There is an .Index called trained, but if I select it the model just "sings" similar to a pure tone with background noise. Therefore, I concluded that the added.index was the right one. Is this correct?

I'm honestly not entirely sure of the 'correct' one to use (trained or added) since I'm only a week into RVC- but haven't really noticed a difference between the two. Use the one that works better than the other for your voice. 🤣 

Sometimes index helps my models and changes the breathing quite a bit and other voice models don't have much of an effect (I also swap between 32k / 16k) which also changes the robotic sounds / breathing slightly on some models.

**You really have to find the sweet spot for your own voice and data / always seems to behave differently.** DIO actually only benefits one of my models more than the others/improvement is minuscule. Hopefully the future planned update fixes this for good so we just have to be patient and pray. 😊

**Comment by APISeeker** [comment]
Hello to all @Mixomo  @fumiama  @Tybost  @ath  @hiwanz 
Could you tell me how do you guys make sure the VOICE created with the .pth files become LESS robotic and MORE human? What other tools do you use? Where do you use your models.pth files? What other techs and ideas? 
Please tell me!
Please
Thanks.

**Comment by Metalhead33** [comment]
I found that running a de-esser on the end result does wonders.

Alternatively, you just open it up in Audacity, duplicate the channel, run one through a low-pass filter (6000 Hz, 48db), one through a high-pass filter (again, 6000 Hz, 48 db), run the latter channel through heavy compression, make it quiet, then merge them back together.
