### ISSUE TITLE
10分钟的音频预处理完只剩下27s

### ISSUE THREAD

**Issue by MagicGJ** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#120]
预处理前：
![image](https://user-images.githubusercontent.com/38968311/233756885-7bee3e51-8af3-4ed1-8508-ea4eec4eb152.png)
![image](https://user-images.githubusercontent.com/38968311/233756971-de0eb165-0744-4bd2-99e0-96e7eb2e44f6.png)

预处理后：
![image](https://user-images.githubusercontent.com/38968311/233756876-20e8ee8e-52c0-4892-a7c8-12dc9a3c6ea0.png)

求教下，是我姿势不对吗？

附音频文件
链接: https://pan.baidu.com/s/1LkfqZbHu5FaazXm7jufh7Q
提取码: 819v

**Comment by MagicGJ** [comment]
尝试手动试用auto-slicer，保持一样的参数是可以分割出200+个切片的

**Comment by RVC-Boss** [comment]
确实有点不太符合预期，我复现下看看

现在的静音阈值写得很保守，切到只剩27s应该是哪里不对

**Comment by RVC-Boss** [comment]
已查明原因并修复
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/trainset_preprocess_pipeline_print.py#L90
加上这行
