### ISSUE TITLE
Request:Is there a way to convert English audio (input) to Hindi audio (output) or vice versa

### ISSUE THREAD

**Issue by Thrqureshi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1201]
Is there a way to convert English song (input) to Hindi song (output) or vice versa

**Comment by 670246038** [comment]
Attempt to use Microsoft's speech recognition and then translate and convert speech output to software

**Comment by Rolun** [comment]
YourTTS has a "language" input if you check their paper, which can help you change the accent in voice conversion/generation.
As for the actual words that are sung, you may need to do as @670246038 suggests. There's plenty of good ASR models out there.
