### ISSUE TITLE
doesnt detect amd gpu

### ISSUE THREAD

**Issue by famo69** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1202]
hello im using the code to train some models but it says no gpu detected and it takes a while to finish help
my gpu is biostar amd rx 6800 16gb
ive also downloaded the version for amd gpus
**NO GPU DETECTED: falling back to CPU - this may take a while**

**Comment by Leynoxxx** [comment]
Same with a 6750 xt

**Comment by little-brother** [comment]
At first you should run `torch.cuda.is_available()` to be sure that `pytorch` supports your GPU.
Then run `torch.cuda.get_device_name()` to get your GPU name.
```
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name()))
```

The next step is to edit `infer-web.py`: add the name on line 74.

It should be enough.

**Comment by famo69** [comment]
where should i run this on cmd or python or???

**Comment by little-brother** [comment]
It's a python code.

**Comment by mixern6** [comment]
AMD is not supported at the moment
