### ISSUE TITLE
笑声失真问题

### ISSUE THREAD

**Issue by dcxs** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1203]
作者，你好。这个工具真的很棒，简单易用，又稳定可靠。国内有这样优质的项目，让人非常自豪。

这边在使用过程中，发现2个问题，看有没有办法解决。非常感谢

1，有情绪的话，比如笑声，变声后失真严重，听起来不真实没有原声音的感情【主要问题】

2，变声后，不管有没有笑声，声音听起来都有些空洞，不真实

**Comment by 670246038** [comment]
绝大多数为自己的训练集有对应问题，可以再次使用该RVC的实时语音转换：w-okada/voice-changer，如果还是有对应的问题请尝试更换训练集或者优化训练集。
