### ISSUE TITLE
error while one-click training

### ISSUE THREAD

**Issue by forsengosling** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1206]
im very new to all this, i have no programming skills, but i keep getting this error, any solutions? 

[WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\OneDrive\\Documents\\GitHub\\elis speaking\\RVC-beta\\RVC-beta0717/logs/elis/0_gt_wavs'

**Comment by Fratermalou** [comment]
It's weird, i use the one click training for 90% of my trains and i never saw this error maybe you should not train directly on a onedrive directory, did you try to train on your harddrive and copy on the onedrive after that ?

**Comment by Fratermalou** [comment]
i am noob too i precise

**Comment by forsengosling** [comment]
> It's weird, i use the one click training for 90% of my trains and i never saw this error maybe you should not train directly on a onedrive directory, did you try to train on your harddrive and copy on the onedrive after that ?

the issue was having a space in between "elis speaking", so i changed it to "elisspeaking" and it works

**Comment by LatusPL** [comment]
FIXED IT! Your path needs to never have any spaces inbetween lines. [ That means renaming everything that way there is no space ]
