### ISSUE TITLE
 rvc fork google colab dissconect problem

### ISSUE THREAD

**Issue by Parsam70** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1209]
I use the free version of Google Club with GPU settings for RVC, but when uploading a file or other times, Google Club disconnects after a few minutes and everything is reset.

I will try to connect again. It connects but disconnects again after a few minutes.

Is there a solution to this problem? for exmp: change code?

**Comment by little-brother** [comment]
Duplicated #1123

**Comment by Parsam70** [comment]
> Duplicated #1123

bro i use difrents rvc >>👉https://colab.research.google.com/drive/1r4IRL0UA7JEoZ0ZK8PKfMyTIBHKpyhcw

Can you make a short tutorial video and send it?

I am a beginner.

**Comment by little-brother** [comment]
It doesn't matter what a notebook you use. The RVC-repository is banned. So you need to avoid its url in your notebook.

> Can you make a tutorial video for discconected g colab problem and send it?

Nope. I think that Google will ban any workaround and I don't like to do useless work.

**Comment by MRINFINITE0** [comment]
Greetings! @little-brother  can we try to copy collab notebook to azure notebook? I tried so and it worked interface is running but stuck in process data part of train model it shows ffmpeg error , is there a way out or just code mistake ?

**Comment by diskreet90** [comment]
> It doesn't matter what a notebook you are using. The RVC-repository is banned. So you need to avoid its url in your notebook.
> 
> > Can you make a tutorial video for discconected g colab problem and send it?
> 
> Nope. I think that Google will ban any workaround and I don't like to do useless work.

seems you're not the slowpoke after all, are you? lol preciate you
