### ISSUE TITLE
RVC converting voice

### ISSUE THREAD

**Issue by Derptheesplayer** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1212]
I'm currently stuck trying to find a way to convert a sing voice on someone. I don't know why it's not working or how to fix the problem. I'm on Windows 10
![Screenshot (238)](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/144381327/620ceb3d-3ca1-4b3e-a815-c5da57b3d147)
![Screenshot (237)](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/144381327/0db5e93f-ae80-4855-81cc-eadef1c87008)

**Comment by IMHFX** [comment]
一样的问题，求帮助
