### ISSUE TITLE
Where is the Converted audio file's folder

### ISSUE THREAD

**Issue by Tarinankertoja** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1214]
Stupid Q prehaps, but can’t find info via google nor youtube..

Where is the converted audiofile? I mean when using modelinterface WebUI.  There is no 3 dots on audiolayer (firefox) to download the result ie. converted audiofile. But It has to be somewhere? Tutorials about G-colab shows TEMP folder, but my local installation that’s empty.

I have worked around this by using batchconverter, where you can specify the output folder, but single conversion audio must be somewhere?

where?

**Comment by CYBERAlcholikos125** [comment]
I am assuming you are using Firefox and,like me, you cant find the download button, in witch case you can just right-click on the bar  (The one that lest you p[lay the file in the web-UI) and click on "save audio as" (it should be under hide controls). Alternatively you can  use google chrome (or chromium if you don't want spyware) temporarily to donload it simply by clicking the 3 dots and clicking "download"


If you still want to see the original folder for some reason and if you are using windows, the file should be located in your AppData\Temp folder and you can access it easily by pressing win+r and typing %Temp% in the field that comes up and then look for it (i recommend the search feature and copying the file name from q)

Hope this helps
