### ISSUE TITLE
GPU recommendations for local training

### ISSUE THREAD

**Issue by instant-high** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1221]
Training on coloab seems to be down, disconnecting after a few minutes....

For local training, does the download package support the rtx 3060, or can any one say which gforce gpu's are supported without changes?

I could run a test training using 30 sec. audio on a GTX 1060/3Gb vram but its very slow of course.

On colab (T4) training using 6-7 min. audio and 200 epochs is done in ~ 60 min.
How long does this take run locally on a RTX 3060 for example?

Or any other recommendations or comparisons which card and how much vram is minimum.?
I'm asking because I think about buying new hardware

**Comment by abubakrHasssn** [comment]
**> I could run a test training using 30 sec. audio on a GTX 1060/3Gb vram but its very slow of course.**


How It run on 1060 3gb ? it didn't work for me , it gave me out of memory error 
can you help plz.

**Comment by instant-high** [comment]
I think it's the nvidia graphic driver version.
On my laptop (gtx 1050 2gb) I can run one of my projects (wav2lip - tpsmm - faceparsing and gpen 256 in one inference)
Drivers are 2021
Updating to latest drivers I can run all that in one inference but also gpen 512 or codeformer.
Looking at the taskmanager I see latest driver uses shared memory instead of giving oom error.
But everything is ~ 25% slower

**Comment by Vagenda** [comment]
I might be wrong - but I believe the version of CUDA on your card matters.
This article gives a LOT of detail : https://en.wikipedia.org/wiki/CUDA
The 1060 has CUDA 6.1
I just had to replace my 1070 with a 4080 (which hurt a lot $) but got me to CUDA 8.9
I read some places that 16gb VRAM and CUDA 7+ was required, but I'm no expert.
