### ISSUE TITLE
Unfortunately there is no compatible GPU available to support your training.

### ISSUE THREAD

**Issue by Yabadiboom** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1230]
I see "No supported Nvidia GPU found, use CPU instead" and then "Unfortunately there is no compatible GPU available to support your training". I tried to install Torch but nothing helps (maybe I installed wrong version, idk).
Has anyone had a similar problem, but on Ubuntu and Nvidia?
I've read similar topics and someone write about Torch (or Pytorch), and CUDA but nothing helps.

**Comment by YunaOneeChan** [comment]
pip uninstall torch torchvision torchaudio
then
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
atleast for 30 series cards.

**Comment by Yabadiboom** [comment]
> pip uninstall torch torchvision torchaudio then pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 atleast for 30 series cards.

OK, I'll try this.

**Comment by Yabadiboom** [comment]
Something's wrong again.
I did: pip uninstall torch torchvision torchaudio and then:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
After opening a terminal in the RVC folder and typing:
$ python3.8 infer-web.py --pycmd python3.8 there's:
Traceback (most recent call last):
File "infer-web.py", line 12, in <module>
Import torch
ModuleNotFoundError: No module named 'torch'
Then I wrote: python3 and torch.cuda.is_available() but in response there's:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'torch' is not defined.

🤔 🤔 🤔

**Comment by JoeWHoward** [comment]
> pip uninstall torch torchvision torchaudio then pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 atleast for 30 series cards.

This worked for me on Windows 11 with an RTX 3080

**Comment by themightyatom** [comment]
This fix worked for me :)
A thousand Thanks @Yabadiboom
