### ISSUE TITLE
Issue of "moaning" output audios which were processed by RVC on macOS Sonoma (14), MacBook Air M1

### ISSUE THREAD

**Issue by kokrasov** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1236]
Hello, guys.
Came across with the problem, when all the processed audios are just "moans" instead of cloned voice. First I noticed this problem after I updated my MacBook Air M1 to newest beta on macOS Sonoma (14). Now it's already pre-release build of it - still dealing with this issue.
However it worked just perfect on previous macOS version - Ventura.

Is it possible to fix it or something?

This is the example of the output audio on macOS Sonoma:
[example output macos sonoma.wav.zip](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/12591522/example.output.macos.sonoma.wav.zip)

**Comment by nikita-sedletskiy** [comment]
Have you found any solution?

**Comment by kokrasov** [comment]
> Have you found any solution?

No, unfortunately I haven’t. But I did some research (googled it) and seems this is a common issue for lots of voice cloning AIs running on macOS Sonoma.
e.g. there is the same issue for ‘w-okada/voice-changer’ (idk what is this for and about): https://github.com/w-okada/voice-changer/issues/591. There are much more comments, maybe you’ll be able to find any solution.

**Comment by dv1x3r** [comment]
This issue is fixed in the torch nightly build.

pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
