### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by r4m71n** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1237]
File "C:\Users\Fadak\Desktop\voice\Retrieval-based-Voice-Conversion-WebUI-main\infer-web.py", line 138, in <module>
    for root, dirs, files in os.walk(index_root, topdown=False):
  File "C:\Program Files\Python39\lib\os.py", line 342, in walk
    return _walk(fspath(top), topdown, onerror, followlinks)
TypeError: expected str, bytes or os.PathLike object, not NoneType

app could not recognized my gpu so as I saw in issues, i reinstalled pytorch and now it can recognize my gpu, but the app cant run succesfuly.

**Comment by cowcheng** [comment]
It seems that the program cannot find the index_root directory, which is assigned by `index_root = os.getenv("index_root")`, and the index_root in the .env file refer to the `./logs` directory. Please check your `./logs` directory exists under the project root directory.

**Comment by r4m71n** [comment]
Thank you for your help. I reinstalled the project and it works well
