### ISSUE TITLE
请问 trainset_preprocess_pipeline_print.py 文件是什么功能？

### ISSUE THREAD

**Issue by TinaChen95** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#124]
up主好！信号处理小白想请教一下，这个文件完成了什么功能呢？
似乎是把音频分割成好多小段、去除了长静音。

另外请教下您的模型框架是怎么样的呢，是否有相关资料可以学习下？
感谢回答！

**Comment by RVC-Boss** [comment]
还有响度归一化

**Comment by RVC-Boss** [comment]
目前有的资料https://www.bilibili.com/video/BV1pm4y1z7Gm

**Comment by TinaChen95** [comment]
谢谢！请问是否可以这样理解：

1. 按照rms阈值对音频进行VAD，分割成多个小片段
2. 以3.7s为窗长、overlap为0.3s，截取音频片段
3. 每个音频片段内，按照幅值做归一化，rescale到0.8，并保存原始采样率和16K采样率两个版本

请问这个VAD和webrtcvad的性能差别如何呢？

**Comment by RVC-Boss** [comment]
你的123理解是正确的

没有对比过，不太重要。主要是去静音，这样来精简训练集，加快训练速度。

**Comment by RVC-Boss** [comment]
漏点没查出来的，或者多切一刀，影响都不会很大。

**Comment by TinaChen95** [comment]
明白了，感谢解答！
