### ISSUE TITLE
How to fix the error?

### ISSUE THREAD

**Issue by Drkogot** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1241]
![Screenshot_10](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17192740/4193c4fd-5b62-4690-ac70-81c240877b83)

No matter what version of RVC I install, there is always this line with an error at the end, and the model training stops.
Video card Nvidia 1060 3GB

**Comment by cowcheng** [comment]
It seems not to be an error, just a warning. How long do you wait for the program, and then you think it is stuck?

**Comment by Drkogot** [comment]
> It seems not to be an error, just a warning. How long do you wait for the program, and then you think it is stuck?

About an hour

**Comment by cowcheng** [comment]
Did the GPU resource keep being used? You can check via `nvidia-smi`.

**Comment by Drkogot** [comment]
> Did the GPU resource keep being used? You can check via `nvidia-smi`.

![Screenshot_12](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17192740/939c3e10-caaf-457f-813c-0b3cd7eca95c)

**Comment by Drkogot** [comment]
Could it be that my settings are 40K and the dataset is 48K?

**Comment by cowcheng** [comment]
Unmatching dataset settings is not the cause because the program will do the resampling procedures. I got the same output message as yours, but mine runs smoothly. The problem is either your driver/CUDA version or your GPU doesn't have enough power to train your model.
