### ISSUE TITLE
WebUI Display Problems

### ISSUE THREAD

**Issue by 4Z0N4S** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1244]
![Screenshot_20230914_145433_Chrome](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/15088456/47470cac-8900-44ac-97ea-7a30e27213ac)

The WebUI appears broken as shown in the picture. How can I solve this?

**Comment by cowcheng** [comment]
What browser do you use? I use Chrome, and everything is well.

**Comment by 4Z0N4S** [comment]
> What browser do you use? I use Chrome, and everything is well.

I'm also using Chrome.

**Comment by cowcheng** [comment]
Any error message from the terminal?

**Comment by 4Z0N4S** [comment]
> Any error message from the terminal?

I didn't see any errors from the terminal. There is no problem with the overall function, but there is just a problem with the homepage being displayed.

**Comment by cowcheng** [comment]
Have you tried another browser? You may try to use the incognito windows to open the web UI to see if the issue is still there.

**Comment by 4Z0N4S** [comment]
> Have you tried another browser? You may try to use the incognito windows to open the web UI to see if the issue is still there.

I changed from Windows to Docker and re-built my environment, and I solved the problem. Thank you.
