### ISSUE TITLE
AMD GPU, AMD Dependancies downloaded | no gpu detected: falling back to cpu

### ISSUE THREAD

**Issue by TheRaggedLlama** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1249]
I am running an Rx6650M on an Omen 16 Laptop. I have downloaded the dml version of RVC and have all of the dependencies. Nonetheless. I cannot seem to get RVC or DirectML to recognize the GPU. Whenever I try to train a model, it immediately falls back to CPU. Any help would be appreciated.

`C:\Users\evanj\Downloads\RVC0813AMD_Intel>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897 --dml
No supported Nvidia GPU found
use DirectML instead
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
write filelist done
use gpus: 0-1-2
runtime\python.exe train_nsf_sim_cache_sid_load_pretrain.py -e "4th Member 05" -sr 40k -f0 1 -bs 6 -g 0-1-2 -te 100 -se 12 -pg pretrained_v2/f0G40k.pth -pd pretrained_v2/f0D40k.pth -l 1 -c 0 -sw 1 -v v2
NO GPU DETECTED: falling back to CPU - this may take a while`

**Comment by KawaiiSelbst** [comment]
This is most likely due to the fact that training on direct-ml has not yet been implemented, and it is not known whether it will be implemented at all

**Comment by TheRaggedLlama** [comment]
If training on direct-ml is non-functioning, then why does it say in README.en.md "AMD/Intel graphics cards acceleration supported" and why would it give specific instructions for installing the direct-ml version for AMD graphics cards on Windows? ("for AMD/Intel graphics cards on Windows (DirectML):  pip install -r requirements-dml.txt") Its all a little confusing, please pardon me this is my first time delving into this kind of thing.

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/en/README.en.md

**Comment by aliosmanzengin** [comment]
Were you able to work with Amd GPU now?

**Comment by Andyholm** [comment]
Couldn't get it to work on my 7900xtx, so probably not
