### ISSUE TITLE
Slow training

### ISSUE THREAD

**Issue by ahmedessa2002** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1250]
I have RTX 3050 Laptop "plugged in"
but 1 epoch takes 3 minutes and my dataset's audio less than 10 minutes

**Comment by ahmedessa2002** [comment]
![Screenshot_53](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/145069890/ab35ce55-5239-4aa4-9ccd-b5e256115d73)

**Comment by Eipckz** [comment]
Speed heavily depends on both GPU vRAM and speed, and also the amount of data you're training it on. Can you provide the command prompt picture?
