### ISSUE TITLE
Disconnect colab after 5-10 minutes

### ISSUE THREAD

**Issue by SalavatNabi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1251]
Why does colab stop after 5-10 minutes?
Is this problem solvable?
Will this problem be solved by buying the pro version?
Or does it not matter what version it is, it is against the rules and policies of colab?

**Comment by Parsam70** [comment]
> Why does colab stop after 5-10 minutes? Is this problem solvable? Will this problem be solved by buying the pro version? Or does it not matter what version it is, it is against the rules and policies of colab?

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1123
