### ISSUE TITLE
bug：web-ui中训练-step3-保存频率设为0报错

### ISSUE THREAD

**Issue by SupppRabit** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1262]
if epoch % hps.save_every_epoch == 0 and rank == 0:
ZeroDivisionError: integer division or modulo by zero

酒吧点炒饭（）

**Comment by yaodada1** [comment]
> if epoch % hps.save_every_epoch == 0 and rank == 0: ZeroDivisionError: integer division or modulo by zero
> 
> 酒吧点炒饭（）

hps.save_every_epoch>=1

**Comment by RVC-Boss** [comment]
webui里我记得加了最小限制的
