### ISSUE TITLE
Bug: 伴奏人声分离选项中的问题

### ISSUE THREAD

**Issue by TLMEMO** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1266]
使用MDX-Net模型时，vocal和ins的输出是反的。

在导出为mp3和m4a格式时，会额外保存一份Wav格式的。

**Comment by RVC-Boss** [comment]
mdxnet没反，他的输出命名是main（无混响）和others（有混响）

额外保存的问题已解决

**Comment by TLMEMO** [comment]
> mdxnet没反，他的输出命名是main（无混响）和others（有混响）
> 
> 额外保存的问题已解决

说的不是输出的名字反了，是输出的文件夹反了。具体来说是mdxnet里prediction函数传参反了，UVR里传的是
```
pre_fun._path_audio_(
                        inp_path, save_root_ins, save_root_vocal, format0
                    )
```
mdxnet里传的是
```
    def _path_audio_(self, input, vocal_root, others_root, format, is_hp3=False):
        self.pred.prediction(input, vocal_root, others_root, format)
```
所以说导致了指定人声和非人声输出的文件夹后，others会输出在人声文件夹下，main输出在非人声文件夹下
