### ISSUE TITLE
Python code to run inference for RVC

### ISSUE THREAD

**Issue by MaxTran96** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1277]
Hi is it possible to run training and inference without going through the WebUI? Can i do that via some python codes that are available in the repo? If anyone knows, could you point me to it? Thanks!

**Comment by admalekar** [comment]
This is from FAQ section:
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/en/faq_en.md#q7how-to-train-and-infer-without-the-webui

See if this works.

**Comment by MaxTran96** [comment]
Thanks! Do you know what this means in the FAQ section?

This requires that the training set has a very distinctive timbre (e.g. a high-frequency airy anime girl sound) and the quality of the audio is high; Data of less than 1min duration has not been successfully attempted so far. This is not recommended.


Does it mean that the training dataset need to be in high pitch voice?

**Comment by ZZZ-zero** [comment]
> 谢谢！您知道常见问题解答部分的含义吗？
> 
> 这就要求训练集具有非常独特的音色（例如高频空灵动漫女孩的声音），并且音频质量很高;到目前为止，尚未成功尝试持续时间小于 1 分钟的数据。不建议这样做。
> 
> 这是否意味着训练数据集需要采用高音调？

他的意思是，请使用较长(不低于一分钟)，无噪音，重复率低的声源进行训练
