### ISSUE TITLE
Suddenly-long Epoch Training generation (not from the get-go) (0 NVIDIA GeForce GTX 1050 Ti)

### ISSUE THREAD

**Issue by Genet-Lair** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1278]
**DISCLAIMER: There are three videos in this post. But they couldn't be uploaded so I had to turn them to links to the discord downloads instead. The only way they can be watched apparently.**

-----------------------------

Okay so lately after making a good amount of pth. models with **Gradio (RVC)**. 

But then for some reason, lately I’ve after some diagnosing the issue with a friend on Discord (who suggested I ask here since our ideas ran out), I’ve been going through this issue where during model training, the **intervals** where the **targeted epochs** were generating was **slowing down majorly**.

Like even when the **computer is on for a whole day** the epochs would still be at like the **7 or 8th mark** while the target epochs for a model was about **10, 20 or 50 epochs.**

As shown in this picture here. It would take like **hours** just to progress to another epoch.

![Picture 1](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/377c9716-1e4f-44b5-b8aa-913adde84783)

Here are my **pth. model training settings**

![My Model settings](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/a552b307-c244-4f3a-a1be-eded66ce0af5)

I’ve already **updated my GPU via GeForce Experience via Game Ready Driver** ( though I haven’t tried Studio Driver yet ) 
These are my **current specs and GPU**

![Specs and GPU 1](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/8c79c11e-1120-4997-b40f-6635da46812e)
![Specs and GPU 2](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/dbd09fc5-a0f6-4fe7-8f38-2eb9cfd39a9f)

I’ve already **moved the root folder** and the **training folder** for RVC/Gladio to an **SSD drive**. And by my friend’s suggestion I even tried training with the **“Save a small final model to the weights folder at each save point” option enabled to “Yes”**

But…I think that only managed to slow things down even more……
So I decided, that maybe instead I could do a fresh start and just **delete the root and train folder** (while saving the downloaded and my successful models of course) and then **reinsert the root folder via the downloaded zip file** from the get go. 

It seemed to have improved the generating to **10 min ( previously it was like 18 min )**
Note: My **target epoch is 50**…and remained that way from this point to now)

VIDEO
[(First Vid Cropped)](https://cdn.discordapp.com/attachments/950024784635375636/1153598475519414332/First_Vid_CROPPED.mp4)
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/988ee061-50e8-4221-94a7-2705056a4aa1

![After first vid also to be CROPPED](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/6a904383-4a42-4b92-942a-63c0a9da5d9e)

So I decided to maybe make it even faster by **increasing the “Batch size per GPU” to four (the default was 2)**, since I was told a larger batch size would  make processing faster, albeit at the cost of GPU.

Sadly no improvements

VIDEO
[(First Batch per GPU to be Cropped)](https://cdn.discordapp.com/attachments/950024784635375636/1153598510575394847/First_Batch_per_GPU_to_be_Cropped.mp4)
![Batch per GPU Screenshot TO BE CROPPED](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/6e652fa3-5b73-4572-bfe2-80b19f127373)

So after that, me and my friend decided to **drop the batch per GPU to 1**. But that only get worse
8:04 pm

VIDEO
[(8 04 PM TO CROP)](https://cdn.discordapp.com/attachments/950024784635375636/1153598454275252244/8_04_PM_TO_CROP.mp4)

9:28 pm

![9 28 pm Image TO CROP](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/b11af5fb-37e2-41d6-b027-f6c477f1f7ef)

10:18 pm
****
![10 18 pm Image TO CROP](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106809875/8082e617-3a06-4fe0-b601-3cc2eecb079d)

It was after this point that we ran out of ideas and I decided to ask here…since we figured you guys might know stuff that we haven’t yet.

NOTE:  What really doesn’t add up is that,..**this wasn’t the issue from the beginning!** Before the issue occurred, I was able to train my previous models just fine. The cmd went at a pace **no more than an hour, like anyone else!** 

This issue started after my **5th model.**

———————————————

_**If everything I told wasn’t clear, feel free to ask for more info on my issue, I will be willing to offer more information and screenshots or videos to aid in getting my issue fixed.**_

**Comment by ZZZ-zero** [comment]
我认为可能还是GPU显存不足，建议更换GPU或者租用云端GPU服务

**Comment by Genet-Lair** [comment]
> 我认为可能还是GPU显存不足，建议更换GPU或者租用云端GPU服务

I'm sorry, I don't speak Chinese...so the google translation will be more of less loose. Forgive me if I misinterpret your instructions...
"I think the GPU may still have insufficient video memory. It is recommended to replace the GPU or rent a cloud GPU service." 

Now for my response...

**Replace the GPU** - I would have to ask my dad since he's the only one that knows how to do so and it would involve opening a drive case (which is attached to a LOT of cables to keep track off), screwing and pressing stuff. 
A lot of labor and potential confusion and mistakes. So definitely a **last resort**.

And I haven't even heard of the concept of **renting a cloud GPU service** until now.... (sheltered life and all..)

So before I do the last resort of replacing the GPU...

Are there any other alternatives?

**Comment by AutomaticSound** [comment]
HI! I have the same graphic card, but somehow I've got that the message that my graphic card isn't supported.
How did you manage to make it work? @Genet-Lair

**Comment by Genet-Lair** [comment]
> HI! I have the same graphic card, but somehow I've got that the message that my graphic card isn't supported. How did you manage to make it work? @Genet-Lair

I'm sorry but I can't answer that cuz I wasn't the one who added the card to my PC so other than having it , I don;t know much about how it works.

And also,...this is a thread where I'm asking for help on my issue, so if you want help you're gonna have to make your own thread instead of commenting on someone else's so please.

Delete your comment.
