### ISSUE TITLE
训练男声的问题

### ISSUE THREAD

**Issue by gotothehill** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1279]
我训练男声后，用来转换女声音频，转换出来的声音特别怪，像是捏着嗓子说话。是需要其他什么设置吗？

**Comment by gotothehill** [comment]
看到方案了

**Comment by stevin-dong** [comment]
> 看到方案了

我也遇到了同样的问题，大佬，请问如何解决，我试过了index_rate调整为1,但是还是无法将tts输出的女声变为模型训练的男生

**Comment by stevin-dong** [comment]
> > > 看到方案了
> > 
> > 
> > 我也遇到了同样的问题，大佬，请问如何解决，我试过了index_rate调整为1,但是还是无法将tts输出的女声变为模型训练的男生
> 
变调：一般男转女12，女转男-12

感谢！
