### ISSUE TITLE
Error at the beginning of the training phase :/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 20 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d '

### ISSUE THREAD

**Issue by adelkk** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1281]
Hello I am having the following error after the pretrained models are loaded at the beginning of the training phase : 

`/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 20 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d '`

Not a single epoch is started when the error pops up, the pretrained models are loaded, and a few minutes later, this happens, I have an NVIDIA Geforce GTX 1660 SUPER.

Does anyone know how to fix this ?

**Comment by hosein-moayedi** [comment]
@adelkk 

```
source .venv\bin\activate
pip install faiss-cpu==1.7.0
```
