### ISSUE TITLE
ModuleNotFoundError: No module named 'infer.lib.jit.torchgate'

### ISSUE THREAD

**Issue by gotothehill** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1286]
拉取最新代码后，运行 python gui_v1.py，报错：
Traceback (most recent call last):
  File ".\gui_v1.py", line 54, in <module>
    from infer.lib.jit.torchgate import TorchGate
ModuleNotFoundError: No module named 'infer.lib.jit.torchgate'

**Comment by venometric** [comment]
try this
pip uninstall infer.lib.jit.torchgate
pip install infer.lib.jit.torchgate

**Comment by venometric** [comment]
try this.
pip uninstall infer.lib.jit.torchgate
pip install infer.lib.jit.torchgate

**Comment by cccRaim** [comment]
> try this. pip uninstall infer.lib.jit.torchgate pip install infer.lib.jit.torchgate

ERROR: No matching distribution found for infer.lib.jit.torchgate

**Comment by venometric** [comment]
> > try this. pip uninstall infer.lib.jit.torchgate pip install infer.lib.jit.torchgate
> 
> ERROR: No matching distribution found for infer.lib.jit.torchgate

Can't figure out the problem... but you could try to reinstall the correct torch again

**Comment by Tps-F** [comment]
Please use the latest

**Comment by gotothehill** [comment]
> Please use the latest

I pulled the latest code. Still the same error.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/133727960/765f1bad-be99-4fca-b46e-ddb9e3165548)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/133727960/7ba5f603-3723-4086-962e-fd913cfa3d55)

**Comment by RVC-Boss** [comment]
from tools.torchgate import TorchGate

We're updating the codes in dev branch 2weeks ago. Now main branch and dev branch are updated.

**Comment by RVC-Boss** [comment]
@gotothehill
