### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by SharkBee80** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1310]
![微信截图_20230922190409](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/115618339/2de7845f-1f44-4842-8afa-10027f680e59)

**Comment by RVC-Boss** [comment]
Did you use the same type of input and output device? Such as MME vs MME

**Comment by SharkBee80** [comment]
![屏幕截图 2023-10-08 233749](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/115618339/81ed7a06-42b1-4dca-b85f-1eab0e8d504b)
Done
