### ISSUE TITLE
distorted voice (auto-tune like) (directml)

### ISSUE THREAD

**Issue by peterjul55** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1321]
Everything works well in general, but when I convert the voice with any model, it sounds strange, as if it had auto-tune. I was testing, with short audios it works without problems, but when I play a slightly longer audio, that happens.

I don't know what it means, or if my PC's resources have anything to do with it. I leave them just in case.
Laptop with 20GB RAM, 2GB (integrated) AMD VRAM, AMD Ryzen 5500U @2.10GHz (that's why I use directml lol)

**Comment by JohnAMacDonald** [comment]
This is also happening to me, and to my knowledge, it didn't happen on earlier versions of RVC (Ex. 0618), but I would have to confirm that 100%.

It also happens of different models both trained by me and other people, namely the AI Hub Discord Models. As well as it's happening on different OS's for me (Ex. Windows & Ubuntu 22.04).

Specs:

CPU: i5 13500
GPU: AMD Radeon RX 6750 XT
RAM: 32 GBs of DDR4 @ 3000MHz

Would love to have this fixed! :)

**Comment by peterjul55** [comment]
> This is also happening to me, and to my knowledge, it didn't happen on earlier versions of RVC (Ex. 0618), but I would have to confirm that 100%.
> 
> It also happens of different models both trained by me and other people, namely the AI Hub Discord Models. As well as it's happening on different OS's for me (Ex. Windows & Ubuntu 22.04).
> 
> Specs:
> 
> CPU: i5 13500 GPU: AMD Radeon RX 6750 XT RAM: 32 GBs of DDR4 @ 3000MHz
> 
> Would love to have this fixed! :)

I had forgotten that I had written that error here. I already solved it, all I did was remove the last command "--dml" by modifying the file "ge-web-dml.bat" with that it worked perfectly for me
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/43360888/36e8f8f1-345d-4fc6-aa02-e61edafd9b29)

**Comment by peterjul55** [comment]
ill close the issue right now
