### ISSUE TITLE
Questions: AI accelerator card

### ISSUE THREAD

**Issue by AlexNikMak** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1331]
Hello everyone, I’m quite new to this topic, so forgive me in advance if the question is posted in the wrong way or is off topic.

I'm wondering if it's possible to use M.2 Accelerator with Dual Edge TPU(https://coral.ai/products/m2-accelerator-dual-edgetpu/) instead of or together with a regular video card. Also, will this bring a performance increase or will it significantly reduce the use of the video card? Or will replace it altogether. This question interests me greatly since these devices are relatively inexpensive compared to video cards.

Thank you very much for your answer.

**Comment by Vagenda** [comment]
If the RVC is ever programmed to use a TPU, then it may be a good thing.  However, currently it is primarily aimed specifically at nVidia GPU's, so having a TPU will not make any impact since RVC isn't programmed to use one.
