### ISSUE TITLE
Please edit Google colaboratory

### ISSUE THREAD

**Issue by BlindMovies** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1337]
I want to launch Web Ui with Google Collaboratory, but I can't specify the zip file directory.

**Comment by pursuitcurves** [comment]
You cannot run the RVC UI on colab, they seem to have started to block instances.

You can sign up to Google cloud for a trial account ($300 in free credits) and connect it to a custom runtime. I use a V100, works like a charm (:

https://research.google.com/colaboratory/marketplace.html
