### ISSUE TITLE
fail to load pretrained model when training

### ISSUE THREAD

**Issue by liulfy** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1340]
I try to run in python script:

from infer_web import train1key

def run():
    return train1key(exp_dir1 = 'test',
                sr2 = '40k',
                if_f0_3 = False,
                trainset_dir4="/test_data",
                spk_id5=0,
                np7=1,
                f0method8='rmvpe_gpu',
                save_epoch10=5,
                total_epoch11=100,
                batch_size12=8,
                if_save_latest13='Yes',
                pretrained_G14="pretrained_v2/f0G40k.pth",
                pretrained_D15="pretrained_v2/f0D40k.pth",
                gpus16='0',
                if_cache_gpu17='No',
                if_save_every_weights18='Yes',
                version19='v2',
                gpus_rmvpe='0-0')

res = run()
print('start to run')
for i in res:
    print(i)

I copy the pretrained_v2/f0G40k.pth, pretrained_v2/f0D40k.pth to logs/test, but when training, it always runs into this error, neither v1 or v2:

'/usr/bin/python train_nsf_sim_cache_sid_load_pretrain.py -e "test2" -sr 40k -f0 0 -bs 8 -g 0 -te 100 -se 5 -pg pretrained/f0G40k.pth -pd pretrained/f0D40k.pth -l 1 -c 0 -sw 1 -v v1
INFO:test2:{'train': {'log_interval': 200, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 8, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 40000, 'filter_length': 2048, 'hop_length': 400, 'win_length': 2048, 'n_mel_channels': 125, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': './logs/test2/filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 10, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'model_dir': './logs/test2', 'experiment_dir': './logs/test2', 'save_every_epoch': 5, 'name': 'test2', 'total_epoch': 100, 'pretrainG': 'pretrained/f0G40k.pth', 'pretrainD': 'pretrained/f0D40k.pth', 'version': 'v1', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 0, 'if_latest': 1, 'save_every_weights': '1', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
gin_channels: 256 self.spk_embed_dim: 109
./logs/test2/D_40.pth
INFO:test2:Loaded model weights
INFO:test2:loaded pretrained pretrained/f0G40k.pth
Process Process-1:
Traceback (most recent call last):
  File "/opt/app/tts/VoiceConversionWebUI/extract/RVC0813Nvidia/train_nsf_sim_cache_sid_load_pretrain.py", line 183, in run
    _, _, _, epoch_str = utils.load_checkpoint(
  File "/opt/app/tts/VoiceConversionWebUI/extract/RVC0813Nvidia/lib/train/utils.py", line 131, in load_checkpoint
    optimizer.load_state_dict(checkpoint_dict["optimizer"])
KeyError: 'optimizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app/tts/VoiceConversionWebUI/extract/RVC0813Nvidia/train_nsf_sim_cache_sid_load_pretrain.py", line 203, in run
    net_g.module.load_state_dict(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid_nono:
        Unexpected key(s) in state_dict: "enc_p.emb_pitch.weight", "dec.m_source.l_linear.weight", "dec.m_source.l_linear.bias", "dec.noise_convs.0.weight", "dec.noise_convs.0.bias", "dec.noise_convs.1.weight", "dec.noise_convs.1.bias", "dec.noise_convs.2.weight", "dec.noise_convs.2.bias", "dec.noise_convs.3.weight", "dec.noise_convs.3.bias". '
That means the pretrained model does not have 'optimizer'. 
How to solve this problem? Which is the right pretrained model?

**Comment by cowcheng** [comment]
Have you tried to run your function in infer-web.py? There are some initializations before the training/inference procedures. You may have missed them.

**Comment by liulfy** [comment]
> Have you tried to run your function in infer-web.py? There are some initializations before the training/inference procedures. You may have missed them.

I run the function in infer-web.py. I consider that I tried the wrong pretrained model. I download the pretrained model here: https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main, and then rename f0G48k.pth to G_48.pth. 
Besides, when I run this function, I also need to copy the pretrained model to the logs/exp-dir. I think what I do is strange and it may not be correct....
I didn't find some detailed document, so could you please share me with the correct model, the correct script, to help me run the pipeline? Thank you very much!

**Comment by cowcheng** [comment]
You can download the latest release .7z file instead of cloning the repository directly. The zipped file contains all the model files and the configs file.

Release version: updated1006v2
Date: 3 days ago

**Comment by liulfy** [comment]
cd ru

> You can download the latest release .7z file instead of cloning the repository directly. The zipped file contains all the model files and the configs file. I am also using that one, and I think everything should be fine if you use that, too. :)
> 
> Release version: updated1006v2 Date: 3 days ago

I still meet the problem... I just put the following script in the infer-web.py:
`def run():
    return train1key(exp_dir1 = 'test_v2',
                sr2 = '40k',
                if_f0_3 = False,
                trainset_dir4="/opt/app/tts/dataset/yujiaodata",
                spk_id5=0,
                np7=1,
                f0method8='rmvpe_gpu',
                save_epoch10=5,
                total_epoch11=100,
                batch_size12=8,
                if_save_latest13='Yes',
                pretrained_G14="pretrained_v2/f0G40k.pth",
                pretrained_D15="pretrained_v2/f0D40k.pth",
                gpus16='0',
                if_cache_gpu17='No',
                if_save_every_weights18='Yes',
                version19='v2',
                gpus_rmvpe='0-0')


res = run()
print('start to run')
for i in res:
    print(i)`

The error info is:
`INFO:test0001:loaded pretrained pretrained_v2/f0G40k.pth
Process Process-1:
Traceback (most recent call last):
  File "/opt/app/tts/RVC1006Nvidia/infer/modules/train/train.py", line 210, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "/opt/app/tts/RVC1006Nvidia/infer/lib/train/utils.py", line 213, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app/tts/RVC1006Nvidia/infer/modules/train/train.py", line 231, in run
    torch.load(hps.pretrainG, map_location="cpu")["model"]
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_v2/f0G40k.pth'`

**Comment by liulfy** [comment]
> You can download the latest release .7z file instead of cloning the repository directly. The zipped file contains all the model files and the configs file. I am also using that one, and I think everything should be fine if you use that, too. :)
> 
> Release version: updated1006v2 Date: 3 days ago

Besides I meet this problem in issue https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1382. I rewrite 'super(self, SynthesizerTrnMs768NSFsid_nono).init()' to 'super().init()' to solve this problem.
