### ISSUE TITLE
RVC Documentation

### ISSUE THREAD

**Issue by notnotniche** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1357]
I was wondering if there was any documentation available somewhere ? I wish to add this project to one of mine but i dont want the GUI , i just want to be able to load a model and a voice and transform it from a python file since i want to export it to AWS

**Comment by Afredi123** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.wiki.git

**Comment by MRINFINITE0** [comment]
hey @notnotniche I am working on same thing but on azure can we partner up to boost things up?

**Comment by notnotniche** [comment]
Yeah for sure, add me on discord Notnotniche !

**Comment by notnotniche** [comment]
> https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.wiki.git

This doesnt seem to work ?

**Comment by MRINFINITE0** [comment]
sure here is discord link- https://discord.gg/PmPwuqXA

**Comment by phineas-pta** [comment]
https://docs.aihub.wtf/

(not official but for a fork)
