### ISSUE TITLE
More support AMD models pls

### ISSUE THREAD

**Issue by DiabloodOfficial** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1365]
Pls. Add old models AMD. (RX560-RX590)

**Comment by TheZuspect** [comment]
Yes pls add it

**Comment by sukualam** [comment]
just install hackintosh (macos 13.4 ventura or up) if you cpu is intel and gpu is amd, mine is working perfectly with macos

**Comment by sukualam** [comment]
mine is rx 560 too, it can leverage MPS accelerator in macos, so it can utilising gpu in macos.

**Comment by nikolicpetar17** [comment]
I have RX5600xt and training is very slow, took me couple of hours for just one epoch
