### ISSUE TITLE
rvc3 when?

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1367]

**Comment by RVC-Boss** [comment]
testing

**Comment by deviandice** [comment]
What about an Alpha/beta release in the discord for gathering feedback? Maybe even a bulletin board for community distributed testing to speed that up might give people some way to keep busy.

**Comment by Abedalhkeem-z** [comment]
It has been three weeks
