### ISSUE TITLE
download result in mp3 format

### ISSUE THREAD

**Issue by loboere** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#137]
It would be nice to have a button to download in mp3 format or another light format, I can download from the player but it downloads in wav format that generates a very large file and fills up my disk

and it would be great if the file had a recognizable name like so-vits-svc has in the form name_song-keypitch-namevoice.mp3

**Comment by RVC-Boss** [comment]
Good idea!
Next version.

**Comment by RVC-Boss** [comment]
It has been achived. Now you can choose output wavform format using batch inference processing.
