### ISSUE TITLE
有能复现成功效果比较好的数据集吗？自己训练出来的效果好差

### ISSUE THREAD

**Issue by timegoby** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#138]

**Comment by edmund-zhao** [comment]
你训练出来loss值是多少呢？
`loss_disc=1.876, loss_gen=4.434, loss_fm=11.077,loss_mel=21.187, loss_kl=0.851`

**Comment by holylong** [comment]
这loss是不是太高了

INFO:feier:[3000, 9.977523890319963e-05]
INFO:feier:loss_disc=3.107, loss_gen=4.287, loss_fm=13.863,loss_mel=26.175, loss_kl=1.997
INFO:feier:====> Epoch: 19 [2024-02-29 14:55:36] | (0:00:51.579960)
INFO:feier:Train Epoch: 20 [39%]
INFO:feier:[3200, 9.976276699833672e-05]
INFO:feier:loss_disc=3.519, loss_gen=3.646, loss_fm=11.745,loss_mel=26.872, loss_kl=1.892
INFO:root:Saving model and optimizer state at epoch 20 to ./logs/feier/G_3300.pth
INFO:root:Saving model and optimizer state at epoch 20 to ./logs/feier/D_3300.pth
INFO:feier:====> Epoch: 20 [2024-02-29 14:56:29] | (0:00:52.857867)
