### ISSUE TITLE
The error in real-time conversion in the October 06 version of RVC is as follows:

### ISSUE THREAD

**Issue by mikisayakamitakihara** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1382]
cuda_is_available: True
Traceback (most recent call last):
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\tools\rvc_for_realtime.py", line 169, in __init__
    set_synthesizer()
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\tools\rvc_for_realtime.py", line 166, in set_synthesizer
    set_default_model()
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\tools\rvc_for_realtime.py", line 113, in set_default_model
    self.net_g, cpt = get_synthesizer(self.pth_path, self.device)
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\infer\lib\jit\get_synthesizer.py", line 26, in get_synthesizer
    net_g = SynthesizerTrnMs768NSFsid_nono(*cpt["config"])
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\infer\lib\infer_pack\models.py", line 1128, in __init__
    super(self, SynthesizerTrnMs768NSFsid_nono).__init__()
TypeError: super() argument 1 must be type, not SynthesizerTrnMs768NSFsid_nono

Traceback (most recent call last):
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\gui_v1.py", line 871, in <module>
    gui = GUI()
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\gui_v1.py", line 109, in __init__
    self.launcher()
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\gui_v1.py", line 395, in launcher
    self.event_handler()
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\gui_v1.py", line 426, in event_handler
    self.start_vc()
  File "C:\Users\compu1\Downloads\RVC1006Nvidia\gui_v1.py", line 553, in start_vc
    self.gui_config.samplerate = self.rvc.tgt_sr
AttributeError: 'RVC' object has no attribute 'tgt_sr'

・RTX 2070
・My RVC model has been working smoothly in versions from August, June, and others.
model detail . 40k v2 　　　I can't get it to work with PM, Harvest, or RMVPE.

**Comment by mikisayakamitakihara** [comment]
model detail . 40k v2 　　　I can't get it to work with PM, Harvest, or RMVPE.

**Comment by subatomicjamie** [comment]
I am also having the same error, did you find a solution?

**Comment by yxlllc** [comment]
Did you overwrite the files from the older version instead of installing the new version entirely separately?

**Comment by BarbeRace** [comment]
I've got also this kind of error when trying to train a model : 
``2023-10-07 11:10:33 | INFO | __main__ | "/usr/bin/python3" infer/modules/train/train.py -e "jocemort" -sr 40k -f0 0 -bs 4 -g 0 -te 20 -se 5 -pg /app/assets/weights/pretrained_v2/G40k.pth -pd /app/assets/weights/pretrained_v2/D40k.pth -l 0 -c 0 -sw 0 -v v2
INFO:jocemort:{'data': {'filter_length': 2048, 'hop_length': 400, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 125, 'sampling_rate': 40000, 'win_length': 2048, 'training_files': './logs/jocemort/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 
'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 
4, 4], 'upsample_rates': [10, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 4, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': True, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 12800, 'warmup_epochs': 0}, 'model_dir': './logs/jocemort', 'experiment_dir': './logs/jocemort', 'save_every_epoch': 5, 'name': 'jocemort', 'total_epoch': 20, 'pretrainG': '/app/assets/weights/pretrained_v2/G40k.pth', 'pretrainD': '/app/assets/weights/pretrained_v2/D40k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 0, 'if_latest': 0, 'save_every_weights': '0', 'if_cache_data_in_gpu': 0}
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/infer/modules/train/train.py", line 176, in run
    net_g = RVC_Model_nof0(
  File "/app/infer/lib/infer_pack/models.py", line 1128, in __init__
    super(self, SynthesizerTrnMs768NSFsid_nono).__init__()
TypeError: super() argument 1 must be type, not SynthesizerTrnMs768NSFsid_nono``

**Comment by a3131919** [comment]
Same here:
INFO:Obama-test:{'data': {'filter_length': 2048, 'hop_length': 400, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 125, 'sampling_rate': 40000, 'win_length': 2048, 'training_files': './logs\\Obama-tes
t/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1,
3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'upsample_rates': [10, 10, 2, 2], 'use_spectral_norm': False}, 'train
': {'batch_size': 40, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': False, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_s
ize': 12800, 'warmup_epochs': 0}, 'model_dir': './logs\\Obama-test', 'experiment_dir': './logs\\Obama-test', 'save_every_epoch': 20, 'name': 'Obama-test', 'total_epoch': 150, 'pretrainG': 'assets/pretrained_v2/f0G40k.pth', 'pretrain
D': 'assets/pretrained_v2/f0D40k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 0, 'if_latest': 0, 'save_every_weights': '0', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Process Process-1:
Traceback (most recent call last):
  File "D:\python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\RVC\RVC1006Nvidia\infer\modules\train\train.py", line 174, in run
    net_g = RVC_Model_nof0(
  File "D:\RVC\RVC1006Nvidia\infer\lib\infer_pack\models.py", line 1128, in __init__
    super(self, SynthesizerTrnMs768NSFsid_nono).__init__()
TypeError: super() argument 1 must be type, not SynthesizerTrnMs768NSFsid_nono

**Comment by RVC-Boss** [comment]
Fixed now. You can update infer-web.py and infer/lib/infer_pack/models.py to fix the issue.
Thanks!

**Comment by AIhasArrived** [comment]
> Fixed now. You can update infer-web.py and infer/lib/infer_pack/models.py to fix the issue. Thanks!

Hello @RVC-Boss  how to upload them?

**Comment by AIhasArrived** [comment]
I meant how to "update" them? @RVC-Boss and @liulfy
