### ISSUE TITLE
Valueerror

### ISSUE THREAD

**Issue by PianoChanXD04** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1388]
Hey, I don't know how to fix the value error. It says "ValueError: 40000 SR doesn't match target 48000 SR" Do I need to use new vocals or is there any way to fix this issue. I already tried to switch this to 48k because I thought it would fix the error. I appreciate any help!

**Comment by RVC-Boss** [comment]
You should use the same sample rate config when dataset preprocessing and model training.

**Comment by PianoChanXD04** [comment]
Okay, thanks! :)

> You should use the same sample rate config when dataset preprocessing and model training.
