### ISSUE TITLE
webui推理报错,实时推理没事

### ISSUE THREAD

**Issue by HiColinn** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1389]
报错如下:
![10月07日004](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/65964332/aeec7055-798e-4416-bb28-b7a04086368d)
webui会报错,实时推理的正常
![10月07日005](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/65964332/3e9d562e-45c1-46ab-a84d-0f8196cacf95)

**Comment by RVC-Boss** [comment]
这个是因为你v1和v2版本，模型和索引混了。要v1配v1，v2配v2

**Comment by HiColinn** [comment]
> 这个是因为你v1和v2版本，模型和索引混了。要v1配v1，v2配v2

好的已经解决了,谢谢,把index关了就好了
