### ISSUE TITLE
output speed changes without any reason

### ISSUE THREAD

**Issue by PYL29** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1390]
the output voice's speed so the pitch changes without a reason. It is a checkpoint pth so it doesn't have an index file. As seen in the video; it works the first time, but not the second time. What could be the reason of this?

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/90216013/32dd1029-e992-48da-8637-156b8fdf14e2

**Comment by RVC-Boss** [comment]
What's the version of RVC you used?

**Comment by RVC-Boss** [comment]
It's a history bug. If you modify the output sample rate, the second output audio would be strange, and this is fixed on the latest version.
