### ISSUE TITLE
Don't see .index fild in dricetory log 

### ISSUE THREAD

**Issue by jygytfugi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1403]
When i train new voice model i don't see In the model directory ./logs/Ownmodel i don't see .index file

**Comment by cracklebox** [comment]
Also having the same problem, training locally using RVC-beta0717

**Comment by xixino** [comment]
same

**Comment by Gerarudo42** [comment]
Same here.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/91257475/0b7b3df5-0e07-4adc-bf54-626edc29be35)
