### ISSUE TITLE
Training on Windows using new AMD ROCm 

### ISSUE THREAD

**Issue by UberStorm** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1415]
Hi!
Can you PLEASE finally add an AMD GPU support for training, due to the release of AMD ROCm for Windows?
https://rocm.docs.amd.com/en/latest/release/windows_support.html

Thanks <3

**Comment by JohnAMacDonald** [comment]
Would love to see this as well!

**Comment by JohnAMacDonald** [comment]
> Same, i don't know why they didn't add this feature already, i've seen so much people on internet trying to get it working on AMD GPUs

The main reason it hasn't been working for Training on Windows, but works to a degree on Linux is PyTorch and other pip packages hasn't been ported over to work with ROCm and Windows yet as they were waiting for dependencies to be updated not too long ago. As well as AMD just made ROCm available for Windows not too long ago.

That being said, I'm unsure if any progress has been made with PyTorch and the other pip packages, and would love to see Windows support :)
