### ISSUE TITLE
推理没问题,训练报错,热心的你帮忙看一下可以吗

### ISSUE THREAD

**Issue by HiColinn** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1422]
如下图所示,显卡驱动,CUDA都没问题,GUI推理和WEB推理都正常,就是训练的时候会报错.
训练原素材文件夹内是3个wav音频文件,不含中文.
训练界面第1步骤,和第2a2b步都不报错,就最后训练的时候会报错,报错日志也看不懂...
![error](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/65964332/72ce5927-39b9-4535-ba07-b2827c6cf8f4)
![1-2](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/65964332/50eeeeb2-118f-4bf8-918c-73979bd4b0fa)

**Comment by RVC-Boss** [comment]
github上更新下infer\lib\infer_pack\models.py这个文件，dev或者main分支都行。
最新的1006 7z包已经修复了，你应该是下得比较早的
