### ISSUE TITLE
Extremely low speed in Train (RVC1006Nvidia)

### ISSUE THREAD

**Issue by AHYvfx** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1435]
Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz   2.90 GHz
32.0 GB
Windows 10
Nvidia GeForce GTX 1650 Super
1T ssd m2
<--------------->
Save frequency (save_every_epoch): 50
Total training epochs (total_epoch): 200
Batch size per GPU: 1

Train Time = 18 hours
<------------------------------------>
When I set the Batch size for each GPU to more than 1, it gives a GPU error
My graphics card is 4 GB and I think it should work properly on 3 GB
I don't know if there is a CPU version that I can test

I really don't know what to do with this slow speed

<-------------->
CMD : 

P:\RVC1006Nvidia\RVC1006Nvidia>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
2023-10-15 14:44:05 | INFO | configs.config | Found GPU NVIDIA GeForce GTX 1650 SUPER, force to fp32
overwrite preprocess and configs.json
is_half:False, device:cuda:0
2023-10-15 14:44:10 | INFO | __main__ | Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
Traceback (most recent call last):
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 48, in uvr
    info = ffmpeg.probe(inp_path, cmd="ffprobe")
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\ffmpeg\_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)
ffmpeg version n4.3.2-160-gfbb9368226 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --disable-avisynth --enable-libdav1d --disable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --disable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libtwolame --disable-libvidstab --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
P:\Temp\takdown\z\mic: Permission denied
100%|██████████████████████████████████████████████████████████████████████████████████| 67/67 [00:18<00:00,  3.64it/s]
2023-10-15 14:45:09 | INFO | infer.modules.uvr5.preprocess | Surprise.mp3 instruments done
Traceback (most recent call last):
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 54, in uvr
    pre_fun._path_audio_(
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\uvr5\preprocess.py", line 124, in _path_audio_
    sf.write(
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 340, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'P:\\Temp\\takdown\\z\\mic\\instrument_Surprise.mp3_10.wav': System error.
ffmpeg version n4.3.2-160-gfbb9368226 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --disable-avisynth --enable-libdav1d --disable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --disable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libtwolame --disable-libvidstab --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
P:\Temp\takdown\z\Surprise.mp3: No such file or directory
Traceback (most recent call last):
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 48, in uvr
    info = ffmpeg.probe(inp_path, cmd="ffprobe")
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\ffmpeg\_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)
ffmpeg version n4.3.2-160-gfbb9368226 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --disable-avisynth --enable-libdav1d --disable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --disable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libtwolame --disable-libvidstab --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
P:\Temp\takdown\z\Vocal: Permission denied
2023-10-15 14:45:09 | INFO | infer.modules.uvr5.modules | Executed torch.cuda.empty_cache()
Traceback (most recent call last):
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\uvr5\modules.py", line 48, in uvr
    info = ffmpeg.probe(inp_path, cmd="ffprobe")
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\ffmpeg\_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)
ffmpeg version n4.3.2-160-gfbb9368226 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --disable-avisynth --enable-libdav1d --disable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --disable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libtwolame --disable-libvidstab --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
P:\Temp\z\mic: Permission denied
100%|██████████████████████████████████████████████████████████████████████████████████| 67/67 [00:13<00:00,  5.10it/s]
2023-10-15 16:10:17 | INFO | __main__ | Use gpus: 0
2023-10-15 16:10:17 | INFO | __main__ | "runtime\python.exe" infer/modules/train/train.py -e "Dariush" -sr 40k -f0 1 -bs 2 -g 0 -te 150 -se 50 -pg assets/pretrained_v2/f0G40k.pth -pd assets/pretrained_v2/f0D40k.pth -l 0 -c 0 -sw 0 -v v2
INFO:Dariush:{'data': {'filter_length': 2048, 'hop_length': 400, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 125, 'sampling_rate': 40000, 'win_length': 2048, 'training_files': './logs\\Dariush/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'upsample_rates': [10, 10, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 2, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': False, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 12800, 'warmup_epochs': 0}, 'model_dir': './logs\\Dariush', 'experiment_dir': './logs\\Dariush', 'save_every_epoch': 50, 'name': 'Dariush', 'total_epoch': 150, 'pretrainG': 'assets/pretrained_v2/f0G40k.pth', 'pretrainD': 'assets/pretrained_v2/f0D40k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 0, 'save_every_weights': '0', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
DEBUG:infer.lib.infer_pack.models:gin_channels: 256, self.spk_embed_dim: 109
DEBUG:root:./logs\Dariush\D_111800.pth
INFO:root:discriminators.7.convs.0.bias is not in the checkpoint
INFO:root:discriminators.7.convs.0.weight_g is not in the checkpoint
INFO:root:discriminators.7.convs.0.weight_v is not in the checkpoint
INFO:root:discriminators.7.convs.1.bias is not in the checkpoint
INFO:root:discriminators.7.convs.1.weight_g is not in the checkpoint
INFO:root:discriminators.7.convs.1.weight_v is not in the checkpoint
INFO:root:discriminators.7.convs.2.bias is not in the checkpoint
INFO:root:discriminators.7.convs.2.weight_g is not in the checkpoint
INFO:root:discriminators.7.convs.2.weight_v is not in the checkpoint
INFO:root:discriminators.7.convs.3.bias is not in the checkpoint
INFO:root:discriminators.7.convs.3.weight_g is not in the checkpoint
INFO:root:discriminators.7.convs.3.weight_v is not in the checkpoint
INFO:root:discriminators.7.convs.4.bias is not in the checkpoint
INFO:root:discriminators.7.convs.4.weight_g is not in the checkpoint
INFO:root:discriminators.7.convs.4.weight_v is not in the checkpoint
INFO:root:discriminators.7.conv_post.bias is not in the checkpoint
INFO:root:discriminators.7.conv_post.weight_g is not in the checkpoint
INFO:root:discriminators.7.conv_post.weight_v is not in the checkpoint
INFO:root:discriminators.8.convs.0.bias is not in the checkpoint
INFO:root:discriminators.8.convs.0.weight_g is not in the checkpoint
INFO:root:discriminators.8.convs.0.weight_v is not in the checkpoint
INFO:root:discriminators.8.convs.1.bias is not in the checkpoint
INFO:root:discriminators.8.convs.1.weight_g is not in the checkpoint
INFO:root:discriminators.8.convs.1.weight_v is not in the checkpoint
INFO:root:discriminators.8.convs.2.bias is not in the checkpoint
INFO:root:discriminators.8.convs.2.weight_g is not in the checkpoint
INFO:root:discriminators.8.convs.2.weight_v is not in the checkpoint
INFO:root:discriminators.8.convs.3.bias is not in the checkpoint
INFO:root:discriminators.8.convs.3.weight_g is not in the checkpoint
INFO:root:discriminators.8.convs.3.weight_v is not in the checkpoint
INFO:root:discriminators.8.convs.4.bias is not in the checkpoint
INFO:root:discriminators.8.convs.4.weight_g is not in the checkpoint
INFO:root:discriminators.8.convs.4.weight_v is not in the checkpoint
INFO:root:discriminators.8.conv_post.bias is not in the checkpoint
INFO:root:discriminators.8.conv_post.weight_g is not in the checkpoint
INFO:root:discriminators.8.conv_post.weight_v is not in the checkpoint
INFO:root:Loaded model weights
INFO:Dariush:loaded pretrained assets/pretrained_v2/f0G40k.pth
INFO:Dariush:<All keys matched successfully>
INFO:Dariush:loaded pretrained assets/pretrained_v2/f0D40k.pth
INFO:Dariush:<All keys matched successfully>
P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\autograd\__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:337.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:Dariush:Train Epoch: 1 [0%]
INFO:Dariush:[0, 0.0001]
INFO:Dariush:loss_disc=3.781, loss_gen=5.438, loss_fm=18.749,loss_mel=28.959, loss_kl=9.000
DEBUG:matplotlib:matplotlib data path: P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\AHY\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\train\train.py", line 268, in run
    train_and_evaluate(
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\modules\train\train.py", line 437, in train_and_evaluate
    ) = net_g(phone, phone_lengths, pitch, pitchf, spec, spec_lengths, sid)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\lib\infer_pack\models.py", line 933, in forward
    o = self.dec(z_slice, pitchf, g=g)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\lib\infer_pack\models.py", line 592, in forward
    xs += resblock(x)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\infer\lib\infer_pack\modules.py", line 334, in forward
    xt = F.leaky_relu(xt, self.lrelu_slope)
  File "P:\RVC1006Nvidia\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\functional.py", line 1632, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.37 GiB already allocated; 0 bytes free; 3.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by THE-SINDOL** [comment]
missing file: - ffprobe.exe just copy ffprobe.exe on same folder as ffmpeg.exe
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/ffprobe.exe
and you can put more GPU size, try 4, and test in small epoch, like 20epoch or 30epoch.. 
Reference : for 12Go is 20 Batch size per GPU.
GPU : RTX 3060 - 12Go 
dataset : 5min 
training : 13min for 100epoch

**Comment by AHYvfx** [comment]
> missing file: - ffprobe.exe just copy ffprobe.exe on same folder as ffmpeg.exe https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/ffprobe.exe and i thing 4Go of ram is too short, ppl use 8go RAM, 12Go RAM, etc... Reference : for 12Go is 20 Batch size per GPU. GPU : RTX 3060 - 12Go dataset : 5min training : 13min for 100epoch
> 
> You can try on paid colab...

Thank you for your guidance .
Oh, I want to buy GAINWARD Geforce RTX 3060 Ghost 12GB graphic card, is it ok?
Are there any other changes needed?

**Comment by kcoul** [comment]
I'm getting good results training with RTX 3060 12GB so I would say yes

**Comment by THE-SINDOL** [comment]
AHYvfx is that's all you need, good gpu card with a lot of vram.
