### ISSUE TITLE
能否在web训练页面加入训练完自动关机指令?

### ISSUE THREAD

**Issue by HiColinn** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1436]
比如使用AutoDL训练的时候,官方是支持下面的格式训练完自动关机的,但是因为是web调用的训练指令,无法自己拼接关机指令

python train.py; /usr/bin/shutdown      
python train.py && /usr/bin/shutdown

**Comment by MrXnneHang** [comment]
你写个bat文件就好了

**Comment by MrXnneHang** [comment]
好吧如果无法写在bat那边。就找train字眼，然后在最后一个save下面写个关机就好了。
