### ISSUE TITLE
特征索引index文件训练不出来

### ISSUE THREAD

**Issue by GUGUGU-01** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1440]
![AYW(7I`C4J(ISWK{J3O(9L8](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/69163794/7d4a3067-584b-49af-8e7d-cd2cf257799d)
训练二三十来分钟的素材可以出index文件 超过一个半小时以上的的就出不来了 不知道有没有办法解决这个问题 我还有两个十多个小时素材的训练集 模型能训练出来 但是训练索引的时候就会报错

**Comment by GUGUGU-01** [comment]
训练环境win11
使用最新的RVC1006包
cpu:3970x
内存:128g
显卡:3090
硬盘:空闲大概1tb

**Comment by Cheneng** [comment]
同问

**Comment by GUGUGU-01** [comment]
![QL6E}VEGL051OF7O_L_1Z2P](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/69163794/e2921593-3dde-41a5-ae3f-414847e049ac)
是因为程序不支持32核以上的CPU吗...
