### ISSUE TITLE
用于训练 v2 模型的数据集

### ISSUE THREAD

**Issue by ai202305** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1443]
@RVC-Boss 
VCTK 是用于训练 v2 模型的唯一数据集吗？
是否需要任何额外的东西，是否有 v2 基础模型的训练脚本可用？
我尝试过使用 VCTK 数据集从头开始训练，但结果不佳。

**Comment by Yaodada12** [comment]
> @RVC-Boss VCTK 是用于训练 v2 模型的唯一数据集吗？ 是否需要任何额外的东西，是否有 v2 基础模型的训练脚本可用？ 我尝试过使用 VCTK 数据集从头开始训练，但结果不佳。

哥们，在VCTK上训练的怎样了？要训练多久，效果如何？
