### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by srbadni** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1449]
hi, during the `one-click training` process i get this error:

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/77675736/e2e56e1c-e55d-4b26-a366-9438f80f901e)

also i download `ffprobe.exe` file and put it in the same folder, but still get this error.
i also reduce batch size gpu to 1, but not work again

i have GPU NVIDIA Geforce GTX 1650 4.00 GB
16GB Ram Memory

**Comment by panzer-chan** [comment]
Unfortunately your GPU ran out of VRAM. See what other programs you have that takes VRAM and try to disable them. Good tip is to disable hardware acceleration on your browsers so they don't use GPU resources. Try to only run this program and nothing else.

Please reference this if you need more information: https://pytorch.org/docs/stable/notes/faq.html
