### ISSUE TITLE
训练的时候提示矩阵尺寸不匹配

### ISSUE THREAD

**Issue by lanyuer** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1456]
File "E:\Downloads\RVC1006Nvidia\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid_nono:
        size mismatch for dec.ups.0.weight_v: copying a param with shape torch.Size([512, 256, 16]) from checkpoint, the shape in current model is torch.Size([512, 256, 24]).
        size mismatch for dec.ups.1.weight_v: copying a param with shape torch.Size([256, 128, 16]) from checkpoint, the shape in current model is torch.Size([256, 128, 20]).

**Comment by hixuanyu** [comment]
你可以试着把log目录之前练的清理下再清理下weigh页面的非默认模型，重启，试下，我是这么解决的
