### ISSUE TITLE
Add the new FCPE F0 method

### ISSUE THREAD

**Issue by GabryB03** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1457]
I can see from the official so-vits-svc repository that they are implementing a new F0 detection method that is designed for real-time voice conversion. Here are the official links to this method:

- Official repository: https://github.com/CNChTu/FCPE
- Pretrained model: https://huggingface.co/datasets/ylzz1997/rmvpe_pretrain_model/blob/main/fcpe.pt

It could be a nice addition to the actual RVC project, maybe it could support or replace the current RMVPE which is already good.

**Comment by yxlllc** [comment]
This is in the plan. At present, it is found that the anti-noise ability of fcpe is still not ideal. We are adding data to train some better weights for testing.

**Comment by GabryB03** [comment]
Alright, that's good news. Keep up the hard work!

**Comment by Kamikadashi** [comment]
Are there any updates?

**Comment by Tps-F** [comment]
#1618
It's already implemented.

**Comment by Kamikadashi** [comment]
As I understand it, it has been implemented only for the real-time GUI. Is there a way to use it for regular audio file processing?

**Comment by ykk648** [comment]
In 2024, rmvpe and fcpe which is best f0 predictor for real-time infering?

**Comment by cheezebone** [comment]
> As I understand it, it has been implemented only for the real-time GUI. Is there a way to use it for regular audio file processing?

I would like to know too.

**Comment by rsxdalv** [comment]
> As I understand it, it has been implemented only for the real-time GUI. Is there a way to use it for regular audio file processing?

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/1934
