### ISSUE TITLE
Very slow epoch training 

### ISSUE THREAD

**Issue by nikolicpetar17** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1460]
I have AMD GPU (RX 5600xt) and it works but really slow.
For example I started training model last night and when I went to sleep it was stuck on this: "INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration."
and  when I woke up this morning it just finished training one epoch. 
GPU was at 45-50% utilization whole night but than it dropped to 5% this morning and then my CPU utilization went to 70%.
Does it have something to do with my GPU being AMD or I need to change something in software? 
Also my training data is quite large at more than an hour long but I still think that it should take much much less time to train one epoch.

**Comment by Subraiz** [comment]
this has everything to do with your GPU being AMD, pytorch relies on CUDA devices which are Nvidia GPUs
