### ISSUE TITLE
start preprocess ['trainset_preprocess_pipeline_print.py', 'C:\\Users\\Public\\Oscar\\1.wav', '48000', '8', 'C:\\Users\\Public\\RVC-beta0717/logs/mi-test', 'False'] Fail. Traceback (most recent call last):   File "C:\Users\Public\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 111, in pipeline_mp_inp_dir     for idx, name in enumerate(sorted(list(os.listdir(inp_root)))) NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\Public\\Oscar\\1.wav'

### ISSUE THREAD

**Issue by hackman1973** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1462]
start preprocess
['trainset_preprocess_pipeline_print.py', 'C:\\Users\\Public\\Oscar\\1.wav', '48000', '8', 'C:\\Users\\Public\\RVC-beta0717/logs/mi-test', 'False']
Fail. Traceback (most recent call last):
  File "C:\Users\Public\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 111, in pipeline_mp_inp_dir
    for idx, name in enumerate(sorted(list(os.listdir(inp_root))))
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\Public\\Oscar\\1.wav'

**Comment by THE-SINDOL** [comment]
Please use new release, just hit go-web.bat for launch.
for nvidia gpu : https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z
for amd/intel gpu : https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z
