### ISSUE TITLE
DirectML (v1006) causes issues. Auto-tune / f0 / pitch-snap issues

### ISSUE THREAD

**Issue by codename0og** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1466]
I've seen few other people report the same thing but apparently the thing isn't checked or discussed.
DirectML Support is all nice, as well as the boost but, it doesn't work all that great. The pitch seems manipulation is distorted / broken. Specifically, it sounds as if it was auto-tuned or the f0 detection went wrong. Have to fallback to cpu to resolve it so yeah, def dml issue.
Not sure it's needed but, using rx 570

**Comment by yxlllc** [comment]
Are you sure that the problem is caused by directml? That is, after switching to cuda, the pitch will be completely normal.

**Comment by codename0og** [comment]
> Are you sure that the problem is caused by directml? That is, after switching to cuda, the pitch will be completely normal.

yeah I honestly think it is, why? because cpu-fallback totally eliminates the issue
