### ISSUE TITLE
The system cannot find the path specified. - no space in absolute path

### ISSUE THREAD

**Issue by panzer-chan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1467]
While attempting to train model using WAV files, clicking on process data after entering the path of the WAV files folder results in "The system cannot find the path specified." error in console.

Path of aforementioned folder: `C:\RTCWebui\audio`
Has no spaces, dashes, underscores, or non-English characters.
Replacing string like this: `C:\\RTCWebui\\audio` does not solve the issue either.
Forward slashes rather than backslashes in file path likewise does not work.

Attempting to train model results in the same error and crashes the program.

Seems like a bug of python occurring while trying to interpret windows absolute paths because in tutorials on YouTube and provided in documentation the file path worked while having dashes or underscores.
Using python 3.10.0 with all dependencies installed for windows.
Windows version: latest windows 10.

**Comment by panzer-chan** [comment]
Checked .log files, and all of them are empty.

**Comment by codename0og** [comment]
try to use  " / " forward slash instead of backward one, if that didn't help then try to get python 3.9.X, alternatively, check 3.10.6 specifically ( works for me ), if that doesn't resolve the issue the idk man, more issues arise lately ig.

**Comment by panzer-chan** [comment]
> try to use " / " forward slash instead of backward one, if that didn't help then try to get python 3.9.X, alternatively, check 3.10.6 specifically ( works for me ), if that doesn't resolve the issue the idk man, more issues arise lately ig.

Tried that... but the problem likely lies in how the developers of this program is handling the user input. Suggest improvements to add file explorer to manually select the path.
Considering I'm not a python developer, I have no idea how this works so this should be a suggestion for now.

**Comment by panzer-chan** [comment]
Update #2:
Apparently loading in models from asset folder works. .pth files can be loaded from asset folder in the WAV conversion tab.

Why doesn't the file path in train tab work then?

**Comment by codename0og** [comment]
I personally maintain my saturn port of rvc so, it's non local and can't help much but, In this case I'd blame your ffmpeg ( or lack of it? ) iirc there are python ffmpeg and standard ffmpeg, not sure which one's used, simply forgot, but you can search for it in issues ye. Alternatively, add me on discord and maybe we could figure it out somehow. dsc;  .codename0.

**Comment by panzer-chan** [comment]
Somehow running infer-web.py directly with python works rather than me running the go-web.bat file.
Why though?

**Comment by codename0og** [comment]
> Somehow running infer-web.py directly with python works rather than me running the go-web.bat file. Why though?

I've no idea tbh, tho, glad you somewhat sorted it out

**Comment by AIhasArrived** [comment]
> Somehow running infer-web.py directly with python works rather than me running the go-web.bat file. Why though?

because the bat file lacks lines of code to call the VENV you have probably installed your libraries inside a venv.

**Comment by AIhasArrived** [comment]
> Update 2: Apparently loading in models from asset folder works. .pth files can be loaded from asset folder in the WAV conversion tab.
> 
> Why doesn't the file path in train tab work then?

Hello what do you mean by this sentence? what wav conversation tab are youtalking about? I dont see it, I am newly using this.

**Comment by panzer-chan** [comment]
> > Somehow running infer-web.py directly with python works rather than me running the go-web.bat file. Why though?
> 
> because the bat file lacks lines of code to call the VENV you have probably installed your libraries inside a venv.

It's a problem with the .bat script
After replacing all occurences of "runtime\python.exe" with python.exe it works.

**Comment by AIhasArrived** [comment]
I finally ended using a release file they made, instead of trying to install it myself , and it worked. What other tools for voice clonign and voice gen are you using since?
