### ISSUE TITLE
RMVPE missing in Co-Lab

### ISSUE THREAD

**Issue by maxbatt22** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1468]
Hello All,

Thanks so much for this amazing tool. I noticed that when launching in GOOGLE CO LAB, that RMVPE isn't an option for pitch extraction, only Harvest and one other option.

I've heard RMVPE is the best, so I wanted to ask for any pointers.

Thank you!!

**Comment by maxbatt22** [comment]
To clarify, I am also happy using Harvest if I have to, I just heard great things about RMVPE.

**Comment by yxlllc** [comment]
Maybe they didn't update the colab notebook
