### ISSUE TITLE
Possible issue with model output resampling

### ISSUE THREAD

**Issue by ThePhosphorus** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1469]
Hello,

let me start by saying great job on the work you did here.
I've been working on making your model compatible with torchscript, but I am confused about specific lines of code.

mainly in `infer/modules/vc/pipeline.py:445`, `modules.py:211` and `infer/modules/vc/modules.py:211`
```python
if tgt_sr != resample_sr >= 16000:
    # Exemple Code
    audio_opt = librosa.resample(
                audio_opt, orig_sr=tgt_sr, target_sr=resample_sr
            )
```

It does not seem to do what it is intended to do (it compares  `tgt_sr != resample_sr` then compares the boolean to `16000`.

**Comment by houyafei** [comment]
tgt_sr != resample_sr >= 16000 应该是等价于
tgt_sr != resample_sr and resample_sr >= 16000

**Comment by houyafei** [comment]
你是怎么把模型转换为torchScript，就是这个项目中使用到的模型，还有自己训练出来的模型。
可以加一下联系方式吗 yafeihou@sina.com是我的邮件

**Comment by ThePhosphorus** [comment]
Hi. In order to convert the model to Torchscript. I wre-wrote all components that did not work with Torchscript. then, I imported the weights from the given models and transferred them to the new nn modules.

While I was successful in converting some parts of the model in Torchscript. I dropped the project when I had to convert the f0 extraction to Torchscript.
