### ISSUE TITLE
Inference Time Discrepancies in Gradio API

### ISSUE THREAD

**Issue by Kamikadashi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1472]
I’m currently using the Gradio API with RMVPE. Regardless of the length of the input audio file, the minimum inference time is always 2 seconds, even for files that are shorter. When I process everything through the browser, I get the following times: npy 0.14s, f0 1.01s, and infer 0.24s for the first call. For subsequent calls, the times are reduced to npy: 0.04s, f0: 0.28s, and infer: 0.11s, which totals less than a second and would be acceptable. However, these reduced times are not achieved when making API calls. What can be done to address this issue? 

P.S. I call /run/infer_change_voice once at the start of the script and then make consecutive /run/infer_convert calls.

**Comment by jswildone** [comment]
Could you please share the file/relevant sections of code where you call the Gradio API.
Will take a look

**Comment by Kamikadashi** [comment]
> Could you please share the file/relevant sections of code where you call the Gradio API. Will take a look

```
def call_gradio_api():
    response = requests.post("http://localhost:7897/run/infer_change_voice", json={
      "data": [
        "Emilia.pth",
        0.33,
        0.33,
    ]}).json()

    data = response["data"]
```

```
def call_gradio_convert_api(output_file_name, base64_audio_data):
    output_path_name = os.path.join(os.path.dirname(os.path.realpath(__file__)), output_file_name)
    response = requests.post("http://localhost:7897/run/infer_convert", json={
      "data": [
        0,
        output_path_name,
        0,
        {"name": "gg.wav", "data": f"data:@file/octet-stream;base64,{base64_audio_data}"},
        "rmvpe",
        "",
        "",
        1,
        3,
        0,
        0.5,
        0.33,
    ]}).json()

    data = response["data"]
```

**Comment by jswildone** [comment]
I've been using a CLI based implementation that does essentially what yours is seeking to do but without the additional overhead (when compared to the browser). I've seen other users report quite similar, they claim it is mostly due to API calls requiring a much larger amount of total overhead for the same process.

I tried to get your implementation working but I haven't been able to get it working yet, if you could share the remainder of the code I will benchmark the browser vs my CLI vs your API method. I'll have a poke around within RVC and try to figure out the root cause/solution if there seems to be a discrepancy big enough.

**Comment by jswildone** [comment]
@Kamikadashi I've been using a CLI based implementation that does essentially what yours is seeking to do but without the additional overhead (when compared to the browser). I've seen other users report quite similar, they claim it is mostly due to API calls requiring a much larger amount of total overhead for the same process.

I tried to get your implementation working but I haven't been able to get it working yet, if you could share the remainder of the code I will benchmark the browser vs my CLI vs your API method. I'll have a poke around within RVC and try to figure out the root cause/solution if there seems to be a discrepancy big enough.I tried to get your implementation working but I haven't been able to get it working yet, if you could share the remainder of the code I will benchmark the browser vs my CLI vs your API method. I'll have a poke around within RVC and try to figure out the root cause/solution if there seems to be a discrepancy big enough.

**Comment by Kamikadashi** [comment]
@jswildone I’ve noticed that in all the CLI implementations I’ve seen, they reload all the models every time they make an inference, which introduces its own additional overhead. Is that the same for your implementation?

**Comment by jswildone** [comment]
@Kamikadashi 
It is for now but I have been working on removing the forced reloading, it isn't yet in a working state but I believe it may be do-able but rather VRAM dependent and not for weaker GPUs.

If you would like to share the rest of the code you can email me or paste here and I will benchmark sometime today.

**Comment by jswildone** [comment]
@Kamikadashi 
Also, which RVC are you running? I'm on RVC1006Nvidia

**Comment by Kamikadashi** [comment]
@jswildone I'm also on RVC1006Nvidia. If you somehow manage to remove the forced reload, I hope you'll share the solution. I have enough VRAM, but unfortunately have not been able to find a workaround. 

````
import os
import time
import requests
import tkinter as tk
from tkinter import filedialog

def call_gradio_api():
    start_time = time.perf_counter()
    response = requests.post("http://localhost:7897/run/infer_change_voice", json={
      "data": [
        "HertaJP.pth",
        0.33,
        0.33,
    ]}).json()

    end_time = time.perf_counter()
    print(f"Execution time of call_gradio_api: {end_time - start_time} seconds")

def call_gradio_convert_api(output_file_name):
    start_time = time.perf_counter()
    output_path_name = os.path.join(os.path.dirname(os.path.realpath(__file__)), output_file_name)
    response = requests.post("http://localhost:7897/run/infer_convert", json={
      "data": [
        0,
        output_path_name,
        0,
        {"name": "gg.wav", "data": f"data:@file/octet-stream;base64,c2hvcnQ="},
        "rmvpe",
        "",
        "",
        0.5,
        3,
        0,
        0.5,
        0.33,
    ]}).json()

    end_time = time.perf_counter()
    print(f"Execution time of call_gradio_convert_api: {end_time - start_time} seconds")

def select_file():
    root = tk.Tk()
    root.withdraw()
    file_path = filedialog.askopenfilename()
    return file_path

if __name__ == "__main__":
    call_gradio_api()
    output_file_name = select_file()
    # Call the function as soon as the file has been chosen
    call_gradio_convert_api(output_file_name) #Look for the result in C:\Users\UserName\AppData\Local\Temp

**Comment by Kamikadashi** [comment]
@jswildone What are the results of your benchmark?

**Comment by jswildone** [comment]
@Kamikadashi I haven't had much time over the last couple days to go much further in but I cannot get your Gradio API code to work, no matter what I try. I have no clue if its just me or if this is a known issue but the documentation on the RVC API is functionally non-existent and the instances I've seen of other users implementing working API calls don't provide complete documentation as to how to go about it. I'm admittedly somewhat unfamiliar with API usage but feel this an issue with RVC.  Irrespective of the file paths and way I format my call requests, I still receive this error:

```
2023-11-09 19:25:27 | INFO | infer.modules.vc.modules | Get sid: HUBERTEST.pth
2023-11-09 19:25:28 | INFO | infer.modules.vc.modules | Loading: assets/weights/HUBERTEST.pth
2023-11-09 19:25:29 | INFO | infer.modules.vc.modules | Select index: logs\HUBERTEST\added_IVF669_Flat_nprobe_1_HUBERTEST_v2.index
2023-11-09 19:25:32 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "C:\Programming\RVC\infer\modules\vc\modules.py", line 163, in vc_single
    try:
  File "C:\Programming\RVC\infer\lib\audio.py", line 57, in load_audio
    if os.path.exists(file) == False:
RuntimeError: You input a wrong audio path that does not exists, please fix it!

Traceback (most recent call last):
  File "D:\Programming\Anaconda\envs\vallex+rvc\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Programming\Anaconda\envs\vallex+rvc\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Programming\Anaconda\envs\vallex+rvc\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\Programming\Anaconda\envs\vallex+rvc\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "D:\Programming\Anaconda\envs\vallex+rvc\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
```


It doesn't seem to matter where they are located or what format my audio files are, RVC is refusing to recognise their existence when called via API. I even wrote a quick audio file checker to verify their existence/validity (which is indicating they are all perfectly ok/file paths are correct/contain audio etc) before I attempt to run inference on them. I'll paste my entire program below if you want to take a look at it, mostly copied from yours above, but am near giving up on implementing the calling functionality like this. RVC runs without fault in the web UI yet will not cooperate with me in this manner. I will continue to work on lazy loading the model in CLI but this is pretty frustrating as the root of the problem completely escapes me. Feel free to look 

```
import os
import time
import requests
import base64
from pathlib import Path

def call_gradio_api():
    start_time = time.perf_counter()
    response = requests.post("http://localhost:7897/run/infer_change_voice", json={
      "data": [
        "HUBERTEST.pth",
        0.33,
        0.33,
    ]}).json()

    print("Voice change response: " + str(response))
    end_time = time.perf_counter()
    print(f"Execution time of call_gradio_api: {end_time - start_time} seconds")


def is_valid_audio_file(filepath):
    # Check if file exists
    if not Path(filepath).is_file():
        print(f"File does not exist: {filepath}")
        return False

    # Check if file is not empty
    if os.path.getsize(filepath) == 0:
        print(f"File is empty: {filepath}")
        return False

    # Check if file has a valid audio extension
    valid_extensions = ['.wav', '.mp3', '.flac', '.aac', '.ogg', '.m4a']
    file_extension = os.path.splitext(filepath)[1].lower()
    if file_extension not in valid_extensions:
        print(f"Invalid file extension for audio: {filepath}")
        return False

    # File passes all checks
    print(f"File is a valid audio file: {filepath}")
    return True



def call_gradio_convert_api(output_file_name, audio_file_paths):
    start_time = time.perf_counter()

    for audio_file_path in audio_file_paths:
        print(f"Processing {audio_file_path}...")

        # Validation of audio file
        if not is_valid_audio_file(audio_file_path):
            continue

        try:
            # Read the audio file and encode it to base64
            with open(audio_file_path, "rb") as audio_file:
                base64_audio = base64.b64encode(audio_file.read()).decode('utf-8')

            # The output file name will be based on the input file
            output_path_name = os.path.join(os.path.dirname(audio_file_path), f"{output_file_name}_{os.path.basename(audio_file_path)}")

            # Create the payload with the physical file path and base64 data
            payload = {
                "data": [
                    audio_file_path,  # Physical path to the file
                    output_path_name,
                    0,
                    {"name": 'input_audio.wav', "data": f"data:audio/wav;base64,{base64_audio}"},
                    "rmvpe",
                    "",
                    "",
                    0.5,
                    3,
                    0,
                    0.5,
                    0.33,
                ]
            }
            
            # Send the request
            response = requests.post("http://localhost:7897/run/infer_convert", json=payload).json()
            print(f"Conversion response for {audio_file_path}: {response}")

        except Exception as e:
            print(f"An error occurred while processing {audio_file_path}: {e}")

    end_time = time.perf_counter()
    print(f"Execution time of call_gradio_convert_api: {end_time - start_time} seconds")

if __name__ == "__main__":
    call_gradio_api()
    
    #Using several audio files to test.
    audio_file_paths = [ 
        r'C:\Programming\RVC\Training\Huberman\Huberman_1.wav',
        r'C:\Programming\RVC\Training\Huberman\Huberman_2.wav',
        r'C:\Programming\RVC\Training\Huberman\test.wav',
        r'C:\Programming\RVC\TESTING\input_audio.wav'
    ]
    output_file_name = 'test_output.wav'  # This will be prefixed to the input file's basename
    call_gradio_convert_api(output_file_name, audio_file_paths)
```

**Comment by Kamikadashi** [comment]
@jswildone Why did you replace ‘Speaker ID’ with ‘audio_file_path’?

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/90068423/661052cd-d4aa-4ed7-8c8b-3804e0727f01)

From what I’ve tried, you can’t change the folder where the result is saved; it’s always generated in C:\Users\UserName\AppData\Local\Temp. The {base64_audio} is also optional and unneeded, but some data should be present for a payload to be accepted, so you can replace it with any short but correct byte64 string. Try the following modification of your script and check C:\Users\UserName\AppData\Local\Temp



```
import os
import time
import requests
from pathlib import Path

def call_gradio_api():
    start_time = time.perf_counter()
    response = requests.post("http://localhost:7897/run/infer_change_voice", json={
      "data": [
        "HertaJP.pth",
        0.33,
        0.33,
    ]}).json()

    print("Voice change response: " + str(response))
    end_time = time.perf_counter()
    print(f"Execution time of call_gradio_api: {end_time - start_time} seconds")


def is_valid_audio_file(filepath):
    # Check if file exists
    if not Path(filepath).is_file():
        print(f"File does not exist: {filepath}")
        return False

    # Check if file is not empty
    if os.path.getsize(filepath) == 0:
        print(f"File is empty: {filepath}")
        return False

    # Check if file has a valid audio extension
    valid_extensions = ['.wav', '.mp3', '.flac', '.aac', '.ogg', '.m4a']
    file_extension = os.path.splitext(filepath)[1].lower()
    if file_extension not in valid_extensions:
        print(f"Invalid file extension for audio: {filepath}")
        return False

    # File passes all checks
    print(f"File is a valid audio file: {filepath}")
    return True

def call_gradio_convert_api(audio_file_paths):
    start_time = time.perf_counter()

    for audio_file_path in audio_file_paths:
        print(f"Processing {audio_file_path}...")

        # Validation of audio file
        if not is_valid_audio_file(audio_file_path):
            continue

        try:

            # Create the payload with the physical file path and base64 data
            payload = {
                "data": [
                    0,  # NOT the Physical path to the file
                    audio_file_path,
                    0,
                    {"name": 'input_audio.wav', "data": f"data:audio/wav;base64,c2hvcnQ="},
                    "rmvpe",
                    "",
                    "",
                    0.5,
                    3,
                    0,
                    0.5,
                    0.33,
                ]
            }
            
            # Send the request
            response = requests.post("http://localhost:7897/run/infer_convert", json=payload).json()
            print(f"Conversion response for {audio_file_path}: {response}")

        except Exception as e:
            print(f"An error occurred while processing {audio_file_path}: {e}")

    end_time = time.perf_counter()
    print(f"Execution time of call_gradio_convert_api: {end_time - start_time} seconds")

if __name__ == "__main__":
    call_gradio_api()
    
    #Using several audio files to test.
    audio_file_paths = [ 
        r'C:\Programming\RVC\Training\Huberman\Huberman_1.wav',
        r'C:\Programming\RVC\Training\Huberman\Huberman_2.wav',
        r'C:\Programming\RVC\Training\Huberman\test.wav',
        r'C:\Programming\RVC\TESTING\input_audio.wav'
    ]
    call_gradio_convert_api(audio_file_paths)
```

**Comment by jswildone** [comment]
With a little bit of tweaking that actually ended up doing the trick. I didn't really gain much much of a speedup one way or the other regarding CLI vs API. API seems to be a little more functionality friendly so I wrote a jank-y workaround where I'm just reading the audio from the files written to the temp folder and saving it where I want to instead but believe there has to be a better way to do this. I also think there is still definitely room for improvement on optimising model loading mechanisms but will be putting it on the backburner for a little while as uni exams are coming up.

Cheers for playing tech support, I know how frustrating it is doing that for people on random open source repo's as it usually goes in circles. Will let you know if I ever make progress in this regard! @Kamikadashi

**Comment by Kamikadashi** [comment]
This fixes the problem: https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/1614
