### ISSUE TITLE
sounddevice.PortAudioError: Error opening Stream: Invalid sample rate

### ISSUE THREAD

**Issue by LMProduction67** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1474]
Hello,
I tried to set up gui_v1 but i become a message after clicking on Start audio conversion 👍 sounddevice.PortAudioError: Error opening Stream: Invalid sample rate [PaErrorCode -9997]
I had a previous version and all was ok.
I have python 3.10.11 on Windows 10.
Thanks

**Comment by Artholos** [comment]
Hey dude, I had the same error message today too. It happened when I tried using the WASAPI. It fixed for me by switching to MME and unplugging/replugging my audio out device (for me is my audio mixer for speakers). Then it started working for me. So maybe you can try the old unplug and plug back in trick.
