### ISSUE TITLE
Tts asking for path that does not exist. FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ai\\Mangio-RVC-v23.7.0/logs/mute/0_gt_wavs/mute40k.wav'

### ISSUE THREAD

**Issue by RenNgu** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1485]
So I have tried to run it on my Ryzen 7, RTX 3050 4Gs, 16Gs RAM and I have tried to run V2 on it but faced some errors such as Cuda out of memory so I lowered the batch size and tried to run it on 1 but I was still getting the same error so I tried to run V1 and I kept the batch size at 1 but now I have a different error.
Please check out the screenshot for more details.

![Screenshot (7)](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/49364461/5770a18e-fc86-4a8b-980f-b7664520c691)

**Comment by LordMilutin** [comment]
I have the same error... 
No spaces in my filepath as well...

**Comment by JD-2006** [comment]
@RenNgu you have mixed forward and backward slashes in your file path.
