### ISSUE TITLE
AMD Linux Step2b "rvmpe_gpu" doesn't generate 2a_f0 and 2b_f0nsf folders

### ISSUE THREAD

**Issue by vlkigdm** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1489]
Is that normal behaviour?

Regular "rvmpe" (on CPU) and model training (on GPU) works alright thought.

**Comment by orcusbeat** [comment]
Same issue on Apple Silicon M3 Max Macbook Pro

    & set([name.split(".")[0] for name in os.listdir(f0_dir)])
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Desktop/RVC/RVC-2/logs/test-model/2a_f0'
