### ISSUE TITLE
The entry 'RVC1006Nvidia\run.sh cannot be extracted

### ISSUE THREAD

**Issue by Berserker4896** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1495]
When I extract the .7z file, the folder is deleted after the prompt message.
Error: The entry 'RVC1006Nvidia\run.sh cannot be extracted from the archive because it is an unsupported filt type.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/81061387/eb3d0d8d-0308-4a07-ae12-5d98da0a7fa6)

**Comment by SNERTTT** [comment]
I'm also having this exact issue.

**Comment by farruhpro** [comment]
> When I extract the .7z file, the folder is deleted after the prompt message. Error: The entry 'RVC1006Nvidia\run.sh cannot be extracted from the archive because it is an unsupported filt type.
> 
> ![image](https://private-user-images.githubusercontent.com/81061387/279433502-eb3d0d8d-0308-4a07-ae12-5d98da0a7fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjQ4NTIsIm5iZiI6MTcwNjg2NDU1MiwicGF0aCI6Ii84MTA2MTM4Ny8yNzk0MzM1MDItZWIzZDBkOGQtMDMwOC00YTA3LWFlMTItNWQ5OGRhMGE3ZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA5MDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiM2M4NWU4MzE5YjRiNGM5OWY5YjYyOWJkOWMxMjRhMTZiMGE5OGEyMzNkZWUyOWQ4MTkzMWM5NzJlMmZmNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ey0z4R8f_ODJf-LKpA1RULt1KOp7OtU7WL7cTY4_8Ns)

I tried to download the latest version of "7-zip" and I was able to unzip it successfully. I opened the archive using the "7zFM.exe" shortcut and clicked "Extract". It unpacked perfectly.
