### ISSUE TITLE
torchvision failed

### ISSUE THREAD

**Issue by BRLTS** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1497]
Hello, i have a problem when try to installing the torchvision

D:\RVC_AI\Retrieval-based-Voice-Conversion-WebUI>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

Looking in indexes: https://download.pytorch.org/whl/cu117
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

How to fix this?

**Comment by levlevin** [comment]
Can reproduce: Windows 11 22H2, python 3.12.0

**Comment by BRLTS** [comment]
I'm using Windows 11 and Python 3.12.0

Should i turnback the installed python version into the old one?

**Comment by levlevin** [comment]
Running in 3.10 seems to have fixed the issue for me

**Comment by BRLTS** [comment]
Alright, i'm using python 3.11 rn and it solved. Thanks
