### ISSUE TITLE
Will the project support AMD GPUs on windows soon?

### ISSUE THREAD

**Issue by SmSmKun** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1498]
I have a 5700XT card and I'm forced to use my weak 1060TI card. The progress is good, but very slow.
I also have 5900X CPU. 
Is there a version that can utilize my CPU better? 
Thanks.

**Comment by hamidmashhouri** [comment]
I have RX 6700 XT and I hope that RVC project will support amd cards in the windows os.
