### ISSUE TITLE
How to CREATE an F0 Curve?

### ISSUE THREAD

**Issue by abanoy** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1499]
This is somewhat an extension of this [post](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/477l) in which I don't believe this has been really been explicitly answered to those who want to know the usage of the f0 curve.

I myself am interested in knowing how to use this also. The best that I've attempted was using PRAAT on my audio files, but to no avail. I've been trying to use _collect_formant_data_from_files.praat_ and _draw_f0_curves_from_files.praat_ scripts for it. 

For me, I am trying to solve an issue on why the model doesn't want to empathize on certain intonations, whereas websites like ElevenLabs seems to not have this issue (But getting the exact intonation is random).

Honestly, I have no idea if the F0 Curve would solve the desired intonation from a given audio file to convert. Please correct me if you know anything better.

**Comment by JD-2006** [comment]
I would also like to know for using the api.
There's a line for "api_name="/infer_convert"" that states "'F0 curve file (optional). One pitch per line. Replaces the default F0 and pitch modulation:' File component"

**Comment by kexul** [comment]
> I would also like to know for using the api. There's a line for "api_name="/infer_convert"" that states "'F0 curve file (optional). One pitch per line. Replaces the default F0 and pitch modulation:' File component"

I think that's not needed, it's hided in the page and it's none by default in the following function. I think it's just a placeholder there. I just deleted that component in the page and removed the correspond parameter in the function and passed a None.
