### ISSUE TITLE
Audio block passed. Index search FAILED or disabled

### ISSUE THREAD

**Issue by AinOfficial** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1501]
go-realtime-gui.bat doesn't work properly, keeps popping up Audio block passed. index search FAILED or disabled

**Comment by Samat3000** [comment]
+

**Comment by Rockergmail** [comment]
same here

**Comment by st26** [comment]
same here Index search FAILED or disabled

**Comment by lclty** [comment]
same.
I use huaerbuku's RVC1006Nvidia one click package. Its WebUI is used by myself to training my V2 RVC model,and the Voice is coming from Genshin Impact's character Furina. I choose her best 160 voices messages to train the V2 RVC model. While I use this model at the RVC GUI, it always displays the following errors:
`Audio block passed.`
`Audio block passed.`
`Index search FAILED or disabled`
`Audio block passed.`
`Spent time: fea = 0.04s, index = 0.00s, f0 = 0.00s, model = 0.72s`
`sola_offset = 0`
`Infer time: 2.40`
`Audio block passed.`
`Audio block passed.`
`Index search FAILED or disabled`
`Spent time: fea = 0.01s, index = 0.00s, f0 = 0.00s, model = 0.04s`
`sola_offset = 0`
`Infer time: 0.06`
I searched for this error, some information says the V2 model causes those errors, the RVC GUI is only supported V1 model. but I don't have enough time to training V1 model to correct or check those errors, emmm......
