### ISSUE TITLE
伴奏人声分离那个模块怎么改写成代码啊

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1504]
我引用了/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/modules.py，这段代码，依然无法使用，函数进不去。

**Comment by yaodada1** [comment]
直接去原始urv5里剥离人声分离的代码，rvc里的人声分离代码我跑之后音频有瞬噪。
