### ISSUE TITLE
Problem when launch the web

### ISSUE THREAD

**Issue by BRLTS** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1509]
Hello, i have a problem when try to launch the gradio

D:\RVC2\Retrieval-based-Voice-Conversion-WebUI>python infer-web.py
Traceback (most recent call last):
  File "D:\RVC2\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 7, in <module>
    from infer.modules.vc.modules import VC
  File "D:\RVC2\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\modules.py", line 11, in <module>
    from infer.lib.audio import load_audio, wav2
ModuleNotFoundError: No module named 'infer.lib'

what should i do?

**Comment by hopto-dot** [comment]
You should launch `go-web.bat` instead. That runs `infer-web.py` using RVC's local python environment for you.

**Comment by wcyy** [comment]
why con't run with meself python environment    i'm try doit  . but it only can run with  RVC's local python environment

**Comment by wcyy** [comment]
> why con't run with meself python environment i'm try doit . but it only can run with RVC's local python environment

why con't run with meself python environment i'm try doit . but it only can run with RVC's local python environment

**Comment by ZeaMays14142** [comment]
> You should launch `go-web.bat` instead. That runs `infer-web.py` using RVC's local python environment for you.

excuse me, where is the RVC local python environment located?
im having similar ModuleNotFoundError: No module named 'infer.lib'
problems, in another script, and the correct local python env would be very useful
how do i access it?
im using ubuntu from WSL2

**Comment by ZeaMays14142** [comment]
> You should launch `go-web.bat` instead. That runs `infer-web.py` using RVC's local python environment for you.

im trying to run extract_f0_rmvpe.py by itself, to better debug the issues with faiss-cpu, but it keeps giving me that infer.lib missing (even after successfully installing infer with pip)
i checked all the different requirements.txt files i found in the repo, and not a single one seems to have any version of infer listed
how do i even run it then?

**Comment by hamidmashhouri** [comment]
> You should launch `go-web.bat` instead. That runs `infer-web.py` using RVC's local python environment for you.

What should I do to run it on Ubuntu? I mean, running it on Windows is done by double-clicking on `go-web.bat`. What about on Ubuntu? I have installed all the RVC requirements on Ubuntu but I have no solution to run it Because I am not an Ubuntu user.
