### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by AlphaOmegaPepega** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1512]
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:My-Voice:Train Epoch: 1 [0%]
INFO:My-Voice:[0, 0.0001]
INFO:My-Voice:loss_disc=nan, loss_gen=nan, loss_fm=nan,loss_mel=nan, loss_kl=9.000
DEBUG:matplotlib:matplotlib data path: E:\Mangio-RVC-v23.7.0\runtime\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\павел\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "E:\Mangio-RVC-v23.7.0\train_nsf_sim_cache_sid_load_pretrain.py", line 225, in run
    train_and_evaluate(
  File "E:\Mangio-RVC-v23.7.0\train_nsf_sim_cache_sid_load_pretrain.py", line 579, in train_and_evaluate
    cursor.execute("SELECT stop FROM stop_train LIMIT 1")
sqlite3.OperationalError: no such table: stop_train

Thats what i get in console and it just stops training after first Epoch. Any fix to this?

**Comment by hopto-dot** [comment]
1. Which version of RVC are you using? Use the latest `RVC1006Nvidia` version (assuming you have a nvidia gpu)
2. Did you click 'one_click_training', or manually run the first two steps then click `Train model`?

Other than that, it's hard to help without much information.

**Comment by BoltzmannEntropy** [comment]
I trained using svc-so-vits-fork, are the models compatible?
