### ISSUE TITLE
能否不使用webui进行推理？(不是训练，就是单纯的改变音色)我想用python代码来自动跑

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1516]
如题

**Comment by RavneetDTU** [comment]
Same queston, why infer_cli.py is removed from latest version of code?

**Comment by Nowebyone** [comment]
请观看Web UI 中的唱见问题解答： 

Q7:不用WebUI如何通过命令训练推理
训练脚本：
可先跑通WebUI，消息窗内会显示数据集处理和训练用命令行；

推理脚本：
https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer.py

例子：

runtime\python.exe myinfer.py 0 "E:\codes\py39\RVC-beta\todo-songs\1111.wav" "E:\codes\py39\logs\mi-test\added_IVF677_Flat_nprobe_7.index" harvest "test.wav" "weights/mi-test.pth" 0.6 cuda:0 True

f0up_key=sys.argv[1]
input_path=sys.argv[2]
index_path=sys.argv[3]
f0method=sys.argv[4]#harvest or pm
opt_path=sys.argv[5]
model_path=sys.argv[6]
index_rate=float(sys.argv[7])
device=sys.argv[8]
is_half=bool(sys.argv[9])

**Comment by BarryAllen-Arrow** [comment]
> 请观看Web UI 中的唱见问题解答：
> 
> Q7:不用WebUI如何通过命令训练推理 训练脚本： 可先跑通WebUI，消息窗内会显示数据集处理和训练用命令行；
> 
> 推理脚本： https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer.py
> 
> 例子：
> 
> runtime\python.exe myinfer.py 0 "E:\codes\py39\RVC-beta\todo-songs\1111.wav" "E:\codes\py39\logs\mi-test\added_IVF677_Flat_nprobe_7.index" harvest "test.wav" "weights/mi-test.pth" 0.6 cuda:0 True
> 
> f0up_key=sys.argv[1] input_path=sys.argv[2] index_path=sys.argv[3] f0method=sys.argv[4]#harvest or pm opt_path=sys.argv[5] model_path=sys.argv[6] index_rate=float(sys.argv[7]) device=sys.argv[8] is_half=bool(sys.argv[9])

太感谢了！！我以为这个是只能用来训练的！看来用来推理也可以~它是支持v1还是v2的版本呀？
