### ISSUE TITLE
How to pause a training then Restart again?

### ISSUE THREAD

**Issue by AIhasArrived** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1520]
Sorry I did not see it nowhere how to do it.
I know you can check the checkbox: "save states"
I think this means you can use a state that was saved for example during half the time of 200 epochs, = 100 epochs,
then come back and restart the training from 101 to 200, am I wrrong?

Anyway how to use thoses stats please?

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this feature has been implemented.
