### ISSUE TITLE
Has anyone tried training with multiple GPU?

### ISSUE THREAD

**Issue by treya-lin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1522]
I tested training with 3 GPU using a small dataset. 
```
python infer/modules/train/train.py -e "testvoice_1" -sr 48k -f0 0 -bs 8 -g "1-2-3" -te 10 -se 5 -pg assets/pretrained/G48k.pth -pd assets/pretrained/D48k.pth -l 0 -c 0 -sw 1 -v v1
```
If I train this dataset using one GPU, it would take up about 6G virtual memory, and everything went well. But when I train with more than one gpu, say 3 gpus, the required virtual memory on each card went up and exceeded 10G, resulting in CUDA OOM error. 

I wonder if this is normal that if you use more than one GPU, the memory required for each GPU will be much greater than in the case when using only one GPU?

**Comment by blakejrobinson** [comment]
Just a comment to say I experienced this too - more memory usage with multi-gpu training (and it is much slower to train)
