### ISSUE TITLE
native English speaker --> same, but Russian speaker without the English accent ???

### ISSUE THREAD

**Issue by ssu-art** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1523]
I have an original dataset of a native English speaker. I want to train the model for use in Russian. now I can't generate TTS using trained model in Russian because I hear that English accent and it doesn't sound good. Can I correct the accent and advise what exactly I should do to get the desired result? Thanks.

**Comment by v6p** [comment]
use index file from another model where the native speaker is Russian

**Comment by ssu-art** [comment]
> use index file from another model where the native speaker is Russian

Thank you so much! I will try to do like you said. Maybe I can ask you two more questions - What optimal amount of 10s segments for dataset for RVCv2 rmvpe_gpu and what optimal amount of epochs? (on my rtx3060 1 epoch training took ~12 min) Bless you, my friend.

**Comment by Grausamkeeit** [comment]
> > use index file from another model where the native speaker is Russian
> 
> Thank you so much! I will try to do like you said. Maybe I can ask you two more questions - What optimal amount of 10s segments for dataset for RVCv2 rmvpe_gpu and what optimal amount of epochs? (on my rtx3060 1 epoch training took ~12 min) Bless you, my friend.

The more diverse the segments, the more accurate the model. Usually people take 10-20 minutes of data for a test and 50-100 epochs to listen to the approximate result.
If they are satisfied, they leave the same amount of data or add more (Personally, I add more) and continue training. From 200 epochs to infinity.
But at one point the model reaches its peak and it is pointless to continue training. To keep track of when that moment comes, you'd better learn to use TensorBoard. Here is the good video about it https://www.youtube.com/watch?v=P0M7PAsG1fk . Actually this guy makes good videos on the subject of neural networks and AI, so check out his other videos as well

Also dude, 12 minutes is too long. On your GPU the epoch shouldn't take more than a minute, look at your settings, something is obviously wrong
