### ISSUE TITLE
colab training webui ipynb rmvpe not work

### ISSUE THREAD

**Issue by mikisayakamitakihara** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1525]
Why doesn't the rmvpe f0 detection check button appear in the training webui started with colab ipynb?  For the zip type downloaded with loacal, the rmvpe training check button appears on the webui

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/Retrieval_based_Voice_Conversion_WebUI_v2.ipynb

![スクリーンショット (7023)](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/121276038/eb940303-f3ac-41cd-88a5-6b557f9c0288)

**Comment by Tps-F** [comment]
Which COLAB do you use?

**Comment by mikisayakamitakihara** [comment]
Google Colab
