### ISSUE TITLE
Preprocess Data not working- preprocess.py", line 11 IndexError: list index out of range

### ISSUE THREAD

**Issue by mostlyhuman** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1529]
File "I:\RVC\RVC1006Nvidia\infer\modules\train\preprocess.py", line 11, in <module>
    sr = int(sys.argv[2])
IndexError: list index out of range

Training path is:  "I:\stems2"  None of the files have spaces or special characters and are in .flac format, previously the files were successfully processed through MDX-Net and DeEcho-Aggressive 

On Windows using the Complete package For Nvidia GPU users

Thank you for any help!

**Comment by mostlyhuman** [comment]
Fixed, it was the numeral 2 at the end of the directory name, renamed to  stemstwo and it worked.

**Comment by maxadc** [comment]
临时改为这样，等作者修复。那么久了还没放出来
`now_dir = os.getcwd()
sys.path.append(now_dir)
print(sys.argv)
# 拆分字符串为列表
argv=sys.argv[1].split(" ")
inp_root = argv[0].replace("\"", "")
sr = int(argv[1])
n_p = int(argv[2])
exp_dir = argv[3]
noparallel = argv[4] == "True"
per = float(argv[5])`

**Comment by maxadc** [comment]
> 临时改为这样，等作者修复。那么久了还没放出来
 `now_dir = os.getcwd()
sys.path.append(now_dir)
print(sys.argv)
argv=sys.argv[1].split(" ")
inp_root = argv[0].replace("\"", "")
sr = int(argv[1])
n_p = int(argv[2])
exp_dir = argv[3]
noparallel = argv[4] == "True"
per = float(argv[5])`

**Comment by maxadc** [comment]
临时改为这样，等作者修复。
那么久了还没放出来
`now_dir = os.getcwd()
sys.path.append(now_dir)
print(sys.argv)
argv=sys.argv[1].split(" ")
inp_root = argv[0].replace("\"", "")
sr = int(argv[1])
n_p = int(argv[2])
exp_dir = argv[3]
noparallel = argv[4] == "True"
per = float(argv[5])`
