### ISSUE TITLE
error when installing parselmouth

### ISSUE THREAD

**Issue by Lyuoko** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1535]
I am running python infer-web.py and it give me 

Traceback (most recent call last):
  File "C:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 8, in <module>
    from infer.modules.vc.modules import VC
  File "C:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\modules.py", line 18, in <module>
    from infer.modules.vc.pipeline import Pipeline
  File "C:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\pipeline.py", line 14, in <module>
    import parselmouth
ModuleNotFoundError: No module named 'parselmouth'

so, i run 'pip install parselmouth'
but, it gave me this error

Collecting parselmouth
  Using cached parselmouth-1.1.1.tar.gz (33 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting googleads==3.8.0 (from parselmouth)
  Using cached googleads-3.8.0.tar.gz (23 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in googleads setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

any solution?

**Comment by Lyuoko** [comment]
wait nvm, i solved it

**Comment by mtnguy3n** [comment]
Hi,

How did you solve this? I have the same issue.

Thanks

**Comment by equmaq** [comment]
@mtnguy3n do 'pip install praat-parselmouth' instead
