### ISSUE TITLE
一个功能建议

### ISSUE THREAD

**Issue by err140** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1541]
在之后的实时变声里是否有机会加入声纹识别呢？这样应该就可以将环境噪音背景音等不通过变声直通输出，仅将当前说话人的声音变声输出，可以让通话更加真实。因为一般通话都会附带一些背景噪音，喝水手机提示音甚至父母的声音等。

**Comment by yxlllc** [comment]
那可能延迟会高非常多
