### ISSUE TITLE
运行go-realtime-gui.bat后卡住无响应

### ISSUE THREAD

**Issue by maomaoaigou** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1546]
![20231115052250](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/23420806/5c46c449-3720-4eae-af09-87266460d68c)
运行go-web.bat正常使用。但是go-realtime-gui就一直卡在图里的这个状态。

**Comment by butata-hg** [comment]
你解决了吗，我现在也是这个问题

**Comment by robinma** [comment]
我的也是这样，继续不了

**Comment by butata-hg** [comment]
> 我的也是这样，继续不了

如果是win11系统的话，试试把unicode utf-8打开，我通过这个办法解决了

**Comment by robinma** [comment]
> > 我的也是这样，继续不了
> 
> 如果是win11系统的话，试试把unicode utf-8打开，我通过这个办法解决了

谢谢，打开utf-8后，可以打开了。操作方法是 搜索 区域-管理-更新系统区域设置
