### ISSUE TITLE
No have Win 1 click installer - suggested comit (win installer script)

### ISSUE THREAD

**Issue by JohnTesla** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1550]
No have Win 1 click installer 
**Supposed comit (win installer script)**
[run.zip](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/13373845/run.zip)

**Comment by Tps-F** [comment]
If you can create a PR, we can review it.

**Comment by blakejrobinson** [comment]
> No have Win 1 click installer **Supposed comit (win installer script)** [run.zip](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/13373845/run.zip)

It would need a much more robust installer than this, I believe. It's a good start but it doesn't take into consideration cuda-accelerated distros of torch, poetry isn't needed, etc.

Something like oobabooga's installer for text-generation-webui would be great.

**Comment by JohnTesla** [comment]
last ver. but I cannot run it on Win, but in Ubuntu  - RVC starts and works fine

rem install python3.8.10 (3.8.x) from installer
rem disable the 3rd line rem for 1st time...
rem python -m venv venv

call venv\Scripts\activate.bat

pip install torch torchvision torchaudio
curl -sSL https://install.python-poetry.org | python -
rem poetry install

rem for Nvidia graphics cards
pip install -r requirements.txt
 rem for AMD/Intel graphics cards on Windows (DirectML):
 rem pip install -r requirements-dml.txt
 rem for Intel ARC graphics cards on Linux / WSL using Python 3.10: 
 rem pip install -r requirements-ipex.txt
 rem for AMD graphics cards on Linux (ROCm):
 rem pip install -r requirements-amd.txt
 
echo installed OK)))
call go-web.bat
pause
