### ISSUE TITLE
Training model gives "RuntimeError: GlooDeviceFactory::makeUVDevice(): interface or hostname can't be empty"

### ISSUE THREAD

**Issue by MarcoReckless** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1551]
```
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to []:39507 (system error: 10049).

[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to []:39507 (system error: 10049).

Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\RVC\RVC-beta0717\train_nsf_sim_cache_sid_load_pretrain.py", line 100, in run
    dist.init_process_group(
  File "C:\RVC\RVC-beta0717\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\RVC\RVC-beta0717\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 994, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
	
RuntimeError: GlooDeviceFactory::makeUVDevice(): interface or hostname can't be empty

```
Hello, I'm getting this error when trying to create a new model, I already created a few models a while back so my guess is that this has to do with some update of some dependency, or something that changed in my system.

**Comment by THE-SINDOL** [comment]
please don't use beta release, there are new one here :
For Nvidia GPU users:
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z

For AMD/Intel GPU users:
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z

for start UI : go-web.bat

**Comment by MarcoReckless** [comment]
> please don't use beta release, there are new one here :
> For Nvidia GPU users:
> https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z
> 
> For AMD/Intel GPU users:
> https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z
> 
> for start UI : go-web.bat

I'm getting it on even on the stable release, but I figured I'd try the latest one to see if it had any sort of fix (even if it's probably just an issue on my end).

**Comment by MarcoReckless** [comment]
For whatever reason my PC's hostname was blank, I thought it was set and that this was just a random error, now I can train properly.
