### ISSUE TITLE
Error when running inference: AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by Innocence667** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1553]
I see many issues about this, and I have looked through but none of them worked for me.

Here's my traceback after running the inference process:

> 
2023-11-16 21:29:00 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "D:\RVC1006AMD_Intel\infer\modules\vc\modules.py", line 185, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "D:\RVC1006AMD_Intel\infer\modules\vc\pipeline.py", line 367, in pipeline
    pitch = torch.tensor(pitch, device=self.device).unsqueeze(0).long()
RuntimeError

Traceback (most recent call last):
  File "D:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "D:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "D:\RVC1006AMD_Intel\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

Before inference process, the training process was successful. I don't have a discrete graphics, and my graphics is "Intel(R) Iris(R) Xe Graphics" so there's no error from CUDA. I found a lack of file named "hubert_base.pt" so I downloaded it. I have confirmed that both my trained model and index are v2. There's no space in the route of filename. And I have ffmpeg.exe and ffprobe.exe. I have tried running the inference over and over again but this error 100% occurs. In short, I have tried nearly all methods mentioned in other issues, but the error stucks. I need to know what other aspects may interfere the inference process and cause this error.

**Comment by Innocence667** [comment]
btw bothpm and rmvpe will cause this error. Sometimes, using rmvpe will lead to another form of error like #1546

**Comment by JD-2006** [comment]
Post a screenshot of your training tab.

**Comment by Innocence667** [comment]
<img width="1280" alt="image" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/73272230/def7665e-ea4e-4e70-9dcf-f29fa04a938d">


<img width="1265" alt="image" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/73272230/a8386582-0427-4f05-bfe3-f80b4376f99a">

I use the model I trained this time and the error occurs again. I have trained the model. Unfortunately, all the models fail when doing inference work.

**Comment by JD-2006** [comment]
Did you use this for Intel?
for AMD/Intel graphics cards on Windows (DirectML)：
  pip install -r requirements-dml.txt

**Comment by JD-2006** [comment]
I see you are using a wav file that I assume you split from another audio file. Try doing an inference on another wav file.

**Comment by Innocence667** [comment]
I tried many other wav file (and even some mp3 audio file), but sadly this error occurs on all my attempts.
So is the creation of tensor using PyTorch causing the error? Is there any other possible problem with wav files or other things?

**Comment by JD-2006** [comment]
Ok. I'm run out of ideas, I thought I was close. Guess not.
I even asked Chatgpt haha. That was my best possibility.

**Comment by Innocence667** [comment]
Thank you though, and now I'd like to try chatgpt😂

**Comment by JD-2006** [comment]
Here is another option if you have python installed and are comfortable with it. Trying the cli.
[https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1516](url)

**Comment by Innocence667** [comment]
Oh, thanks so much, I'll try it

**Comment by rgwan1314** [comment]
I have the same problem as you. Have you solved it？

**Comment by Innocence667** [comment]
Unfortunately not yet. In fact I have deleted rvc on my computer for my disk has little space :(
