### ISSUE TITLE
我不能运行

### ISSUE THREAD

**Issue by tomh500** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1556]
我之前在我的电脑上成功使用了0813版本，我换成了RTX4060 Laptop的机型，环境是python3.10，10月版本 在安装依赖的时候提示pip install torch torchvision torchaudio
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

我尝试下载对应版本 pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
Looking in indexes: https://download.pytorch.org/whl/cu117
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

其他的也有问题
pip install -r requirements.txt
Ignoring onnxruntime: markers 'sys_platform == "darwin"' don't match your environment
Collecting joblib>=1.1.0 (from -r requirements.txt (line 1))
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting numba==0.56.4 (from -r requirements.txt (line 2))
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      C:\Users\tomh5\AppData\Local\Temp\pip-install-gs9s43_0\numba_81775fe4e6a74b3e8e9a562339faf885\versioneer.py:335: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tomh5\AppData\Local\Temp\pip-install-gs9s43_0\numba_81775fe4e6a74b3e8e9a562339faf885\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\tomh5\AppData\Local\Temp\pip-install-gs9s43_0\numba_81775fe4e6a74b3e8e9a562339faf885\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

我在原来的RTX2060 笔记本没有遇到这个问题

**Comment by mdkberry** [comment]
would be nice if this was put into the README section as it currently says anything over 3.8 works and it clearly does not. I installed 3.11 and got this error.
