### ISSUE TITLE
[BUG]安装fairseq失败导致无法启动。Failed to install fairseq.

### ISSUE THREAD

**Issue by LieDeath** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#156]
安装依赖最后一步卡在fairseq，报错提示似乎和我电脑上的VS studio冲突。百思不得其解了，希望大佬能帮助我这个小白找到原因。
When installing the dependences, it stuck in the fairseq, which seems related to conflicts with VS studio. I have no idea what is going on, and help you the masters can help me the primer find the answer.
会不会是dist-info发行版与egg（toml-based）发行版编译方式不同导致的问题。
Will it cause by difference between dist-info and egg (toml-based)? Might them complied in different ways.
另外一个让我感到疑惑不解的点是依赖中的faiss-gpu似乎并不存在，使用了pip和poetry均没有找到该依赖，是faiss-cpu的错误拼写吗？
Another issue is that the faiss-gpu in the requirements.txt seems does not exist, both pip and poetry failed to find that dependence. Does it is an mistake from faiss-cpu?
这是安装过程中的报错截图。Here is the screenshots.
![fairseq](https://user-images.githubusercontent.com/115352572/234073303-ffc485fe-6d5d-436a-92a9-d2dfb6f0bdcb.png)
![missing_faiss-gpu2](https://user-images.githubusercontent.com/115352572/234073367-8383918f-d20c-4afe-8b35-4cb721ba100a.png)
<img width="734" alt="missing_faiss-gpu1" src="https://user-images.githubusercontent.com/115352572/234073388-142d3371-cc1f-4c6f-a69a-35f301b4b7bb.png">
![faiss-cpu](https://user-images.githubusercontent.com/115352572/234073431-3608ec9c-87a9-4330-abce-0bcd761860aa.png)

**Comment by RVC-Boss** [comment]
后续将撤销fairseq库改为transformers库。
faiss-cpu的应该已经修复了
