### ISSUE TITLE
¿Training from scratch / fine-tuning with a large dataset?

### ISSUE THREAD

**Issue by Mixomo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1562]
Hello @RVC-Boss, I plan to improve the pronunciation of the voice conversion in Spanish language.
I have a studio quality dataset of almost 40 hours of speech in Spanish, of both genders, and varied accents.

1- Do you recommend training from scratch or fine-tuning from the pre-trained RVC models?

2- How long is the VCKT dataset that was originally used for RVC?

3- I plan to train my dataset with a 40 GB Nvidia A100, what batch size and epochs do you recommend?

4- Is there a way to switch from FP16 to FP32? Is it worth it?

Thanks!

**Comment by JackVinati** [comment]
1 - PRE-TRAINED
2 - I don't know
3 - size 90
4 - stay on FP16

**Comment by KushATrivedi** [comment]
> Hello [@RVC-Boss](https://github.com/RVC-Boss), I plan to improve the pronunciation of the voice conversion in Spanish language. I have a studio quality dataset of almost 40 hours of speech in Spanish, of both genders, and varied accents.
> 
> 1- Do you recommend training from scratch or fine-tuning from the pre-trained RVC models?
> 
> 2- How long is the VCKT dataset that was originally used for RVC?
> 
> 3- I plan to train my dataset with a 40 GB Nvidia A100, what batch size and epochs do you recommend?
> 
> 4- Is there a way to switch from FP16 to FP32? Is it worth it?
> 
> Thanks!

Hi @Mixomo ! 
Could you refer a documentation for training RVC model from scratch or finetuning from baseline RVC model on our own dataset (instead of VCKT dataset)?
