### ISSUE TITLE
Why are sampling rates to 40k and 48k instead of 44.1k and 48k?

### ISSUE THREAD

**Issue by epietrocola** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1565]
Just a curiosity. In audio I would expect 44100 and 48000hz, this is the first time I saw 40k, why is that?

**Comment by Oleksandr2505** [comment]
it is probably just a naming for cheakpoint which has 40 thousands samples or audious, which it was trained on

**Comment by nikich340** [comment]
> it is probably just a naming for cheakpoint which has 40 thousands samples or audious, which it was trained on

No, you can open config file and check "sampling_rate" param, it is actually 32000, 40000 and 48000 for different configs.
