### ISSUE TITLE
Display meter from 0 to 100 percent

### ISSUE THREAD

**Issue by The-cpu-max** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1569]
There is no way to know how much the model has left to train
I would love to have some listed
And in addition canceling the workout in the middle while saving the last step

**Comment by HSultankhan** [comment]
In the process of initializing training, it is imperative to designate the number of epochs beforehand. Subsequently, within the command prompt interface, one can readily ascertain the progress of the training regimen by observing the cumulative number of epochs executed. This can be accomplished by subtracting the epochs that have already transpired from the initially specified total.

Furthermore, a prudent practice is to enable the generation of small checkpoints during the training process. This feature facilitates the evaluation of the model's performance at intermediate stages, allowing for testing and validation before the entirety of the epochs is completed. This strategic utilization of checkpoints contributes to an enhanced and iterative model development approach.

**Comment by The-cpu-max** [comment]
> In the process of initializing training, it is imperative to designate the number of epochs beforehand. Subsequently, within the command prompt interface, one can readily ascertain the progress of the training regimen by observing the cumulative number of epochs executed. This can be accomplished by subtracting the epochs that have already transpired from the initially specified total.
> 
> Furthermore, a prudent practice is to enable the generation of small checkpoints during the training process. This feature facilitates the evaluation of the model's performance at intermediate stages, allowing for testing and validation before the entirety of the epochs is completed. This strategic utilization of checkpoints contributes to an enhanced and iterative model development approach.

and how i can check all that steps
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/102416233/96bf675e-8d08-4fcc-be70-ca1dbd9859bf)
