### ISSUE TITLE
No Compatible Cuda GPU Found Use CPU Instead

### ISSUE THREAD

**Issue by tomas122727** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1572]
ok its been working all this time i have been doing numerous training but after updating graphics driver and cuda toolkit it has stopped working and it isnt just affecting RVC its affecting all my other ai programs i have no idea whats going on i have a cuda compatible GPU
 i have a nvidea RTX 3060 12 gb AORUS i tried installing pytorch in my conda base and such i tried everything from reinstalling everything i dont know what to do now i cant survive on just cpu i want to do actual gpu training again how do i fix this its so weird how it maraciuslly stopped working

**Comment by tomas122727** [comment]
even changing my enviroment variables

**Comment by tomas122727** [comment]
and nothing has worked i have no clue whats going on if someone wants to help me out here to disclose whats going on with this please do

**Comment by tomas122727** [comment]
my gpu is a 30 series rtx card ampere
SM83

**Comment by THE-SINDOL** [comment]
unzip this one https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z and hit go-web.bat

**Comment by SmoothPlay** [comment]
Got the same problem my friends

**Comment by THE-SINDOL** [comment]
can you post screenshot of cmd when you launch go-web.bat please.
