### ISSUE TITLE
RVC - Error after a few seconds

### ISSUE THREAD

**Issue by delete-exe** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1573]
When I use RMVPE and a compatible trained voice for dubbing an audio, I get an error after a few seconds on several computers. I can find no reason, why this happens. have not found any logs. Maybe there are some repositories missing, but I can not figure out which.
Can someone help, with what I can do to track this problem?

**Comment by delete-exe** [comment]
I've been working a bit on this problem.
First of all, there was the **rmvpe.pt** file missing in "\app\assets\rmvpe\" folder. I've found it somewhere on GitHub and placed it in this folder. Now I takes some more time & the error message is different:
`RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

Maybe someone know, what to do here.

**Comment by danablend** [comment]
@delete-exe Did you find a solution to this?

**Comment by resolvds** [comment]
did you guys ever find a solution?

**Comment by danablend** [comment]
I fix

> did you guys ever find a solution?

I fixed it by running it on a different machine. AWS EC2 instance with A10G card.

Didn't work on my laptop's Quadro T1000 card.
