### ISSUE TITLE
RVC - No audio in dubbed audio

### ISSUE THREAD

**Issue by delete-exe** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1574]
I've a notebook with a built-in nVidia T1200 graphics card. CPU i7, 16 GB DDR5 RAM.

Whenever I try to dubb audio with a trained voice (RVC2 verified), I get an output with no audio - eighter in the GUI of RVC, nor the downloaded audio has any info when loaded in an audio editor. Simply empty. I don't get it.
I can hear any other browser-based audio, like YT or else. But here, no audio is produced at all.

Any ideas?

**Comment by THE-SINDOL** [comment]
salut, mets screenshot de ta config de rvc

**Comment by delete-exe** [comment]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/38488241/89848d45-a223-4b0f-90ae-caeca97a7c25)

This is it, what I used on all my three computers, but on this laptop, it doesn't generate any audio at all. The resulting file is empty, although there are no errors.

**Comment by THE-SINDOL** [comment]
is last rvc ( https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases/tag/updated1006v2 ) ???
