### ISSUE TITLE
[BUG]三个错误的依赖导致安装失败

### ISSUE THREAD

**Issue by LieDeath** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#158]
①依赖中的faiss-gpu在poetry软件源并不存在，提示找不到软件安装包。
![missing_faiss-gpu2](https://user-images.githubusercontent.com/115352572/234073367-8383918f-d20c-4afe-8b35-4cb721ba100a.png)
在pip软件源中显示faiss-gpu的Metadata错误，识别为faiss-cpu的安装包。
<img width="734" alt="missing_faiss-gpu1" src="https://user-images.githubusercontent.com/115352572/234073388-142d3371-cc1f-4c6f-a69a-35f301b4b7bb.png">
需要手动安装faiss-cpu。

②依赖中的fairseq使用的发行版本错误，应当更换为dist-info版，而不是基于pyproject.toml的版本。
![fairseq](https://user-images.githubusercontent.com/115352572/234073303-ffc485fe-6d5d-436a-92a9-d2dfb6f0bdcb.png)
<img width="850" alt="fairseq" src="https://user-images.githubusercontent.com/115352572/234081129-341f29cb-64ad-4772-83b3-ebd7deb454ba.png">

③依赖中的hydra需要手动安装，原因同②。
<img width="850" alt="hydra" src="https://user-images.githubusercontent.com/115352572/234082493-304e62ff-7adc-42c5-aedb-6843c3d214e3.png">
此总结不一定准确，可能只适用于我的电脑环境，解决了 #156 中的问题。

**Comment by fumiama** [comment]
很奇怪的问题😂我在Linux下并未遇到，也许需要其他用Windows的朋友尝试复现一下。

**Comment by LieDeath** [comment]
问题发生在 52661df ，等待通过更新解决。不清楚为何fairseq会编译失败，会不会是老版本VS studio缺失某些特性而导致的。

**Comment by PetYin** [comment]
②问题fairseq类似失败出现，但错误信息不一样。电脑早已安装C++14.2，通过安装Visual Studio生成工具2022和其内部的使用C++的桌面开发后解决。使用conda虚拟环境。
<img width="1023" alt="Snip1" src="https://user-images.githubusercontent.com/50064856/234173809-53493876-4674-4df8-bed9-b3d8c89efef7.png">

**Comment by RVC-Boss** [comment]
faiss-cpu的问题我已经修改了依赖文件

fairseq的问题，我去试下transformers替代库，如果效果保持一致，直接把fairseq下掉
