### ISSUE TITLE
HugginFace RVC go-web.bat

### ISSUE THREAD

**Issue by KovacsGergely01** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1582]
I get this error when I try run it 
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/107806677/c5a5e7ec-199c-4918-b9c9-49f4f73ae07d)

**Comment by sunspiritz** [comment]
You just need to download a complete package.
Check here :
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases

The complete package links in details.

**Comment by KovacsGergely01** [comment]
> You just need to download a complete package. Check here : https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases
> 
> The complete package links in details.

Thanks dude it's working!
