### ISSUE TITLE
RVC Architecture

### ISSUE THREAD

**Issue by shaniyacamita** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1583]
Hi! been trying to understand about RVC technical wise, does anyone have like a flowchart/map/link/docs that describe the full architecture of rvc? Thankyou!

**Comment by artificalaudio** [comment]
@shaniyacamita あなたを混乱させる必須の日本語文字。そしておそらくこれを読んでいる他の人もいるでしょう。このffsにキャッシュコンバージョンを追加すると。 RVC万歳！:

<img width="1403" alt="Screenshot 2023-11-29 at 18 35 20" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135162720/ce0cafd4-cb58-413b-86d6-cc0f1b481fd7">

[]((https://i.stack.imgur.com/M0OcW.jpg))

**Comment by shaniyacamita** [comment]
HAHAHA, Thank you so much!!!

**Comment by JohnTesla** [comment]
Is it possible to Integrate Base EVC to TTS-gen for TRAIN RVC support?
How about gradio ver

**Comment by dhruv1710** [comment]
I see that RVC uses text in training but where does that text come from? and in the architecture there's a text encoder also, does it do speech to text?

**Comment by molo32** [comment]
Is there a better graph than this one? This one seems to lack information, for example, 
what is posterior encoder? 
Where is the error to be reduced? 
What is target voice in the training process?

**Comment by AlirezaKamyab** [comment]
> I see that RVC uses text in training but where does that text come from? and in the architecture there's a text encoder also, does it do speech to text?

I don't suppose it is the text but it is the audio's features from Hubert model

**Comment by AlirezaKamyab** [comment]
> @shaniyacamita あなたを混乱させる必須の日本語文字。そしておそらくこれを読んでいる他の人もいるでしょう。このffsにキャッシュコンバージョンを追加すると。 RVC万歳！:
> 
> <img alt="Screenshot 2023-11-29 at 18 35 20" width="1403" src="https://private-user-images.githubusercontent.com/135162720/286707140-ce0cafd4-cb58-413b-86d6-cc0f1b481fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MjkwMTAsIm5iZiI6MTczNjkyODcxMCwicGF0aCI6Ii8xMzUxNjI3MjAvMjg2NzA3MTQwLWNlMGNhZmQ0LWNiNTgtNDEzYi04NmQ2LWNjMGYxYjQ4MWZkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQwODExNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTRkOTNkNjk1OTIzOTNjN2M3M2QzZjBiZTk2YzcyZGUxMWFkMDFjMGRiYzVkZjY2YmJmY2VlMThmMTAwOTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AUfO0I09wZDflZhHDx6Ge6aNKY2j5nWsnayPVpl8sAE">

I don't seem to find anything about Contrastive Learning in the code! Can you tell me where contrastive learning is implemented?
