### ISSUE TITLE
RuntimeError: Could not allocate tensor with 295289856 bytes. There is not enough GPU video memory available! 

### ISSUE THREAD

**Issue by ARX77** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1590]
when i want to convert using a model i made before it gives me this error

**Comment by codename0og** [comment]
that means you've not enough of gpu memory ( video ram ) to complete an inference.
it needs more memory, about ~282 mb. Are you doing it on a 4gb gpu? ( especially, amd, so - directml ? ) 

in case it's 4gb and amd - that's the constraints I suppose, does the same on my rx 570 4gb
in case it's 4gb nvidia - are you using crepe? try rmvpe or harvest instead
