### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x00'.

### ISSUE THREAD

**Issue by Abedalhkeem-z** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1591]
Is there any packaged being updated that cause the following error?
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by ajayarora1235** [comment]
running into the same issue

**Comment by Abedalhkeem-z** [comment]
So this problem happened to me bc the .pth and .index files where zipped using mac, when I use the zipped file on windows, I got this problem.
