### ISSUE TITLE
Insanely slow training (40 epochs in 8 hours)

### ISSUE THREAD

**Issue by takearushfan82** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1593]
I'm not sure what happened but it used to be 3 minutes per epoch on my GPU (GTX 1660 6Gb) now it takes about 40 epochs in 8 hours.  What happened?  Changing "fp16" to true doesn't help, nor does raising or lowering my CPU processes or the batch size.  I've tried all kinds of variations.  What might help?  Thanks.

**Comment by codename0og** [comment]
are you now using the same size / length for dataset as previously?
you see, bigger the dataset, longer it takes.
As an example of the time on tesla t4:  15 min set, sub 20-30 secs for an epoch, sub 40-45 mins of set, 1-1.5 min for an epoch
