### ISSUE TITLE
How to split audio in consol

### ISSUE THREAD

**Issue by vshlykov** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1594]
Hello!

I want to split audio to vocal and instruments using HP5 model. Is it possibe to use consol for it?

**Comment by THE-SINDOL** [comment]
Is not possible, but you can write a small python code for make it.

**Comment by THE-SINDOL** [comment]
i think no, i heard in next release on new repo ( https://github.com/RVC-Project/Retrieval-based-Voice-Conversion ) it will be integrate.
