### ISSUE TITLE
problem after move model to cuda (Solved)

### ISSUE THREAD

**Issue by icinemagr** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1595]
I have install it on Linux Mint 21
i have GPU nvidia gtx1060  6g ram
i try to train a voice with 3 minute audio wav
here is my last Lines of terminal
f0ing,now-25,all-29,-/home/mel/rvc/logs/Kazantzidis/1_16k_wavs/0_55.wav
['infer/modules/train/extract_feature_print.py', 'cuda:0', '1', '0', '0', '/home/mel/rvc/logs/Kazantzidis', 'v2']
/home/mel/rvc/logs/Kazantzidis
load model(s) from assets/hubert/hubert_base.pt
move model to cuda
all-feature-59
all-feature-done

it never Ends
how can i debug messages like verbose or something similar?

**Comment by codename0og** [comment]
I mean, that's what it is supposed to say, all-feature-done, then you can move onto the next step

**Comment by icinemagr** [comment]
> I mean, that's what it is supposed to say, all-feature-done, then you can move onto the next step

when i use pm i get notifications that epoch 1 finishe epoch 2 finish etc. and takes about 5-10 minutes for a sample 2 minutes to train just for check.  using only CPU.
when i installed on a pc with gpu 1060 gtx 6 g it doesnt display on webUI that all operations completed
what i describe is on terminal the webui just saystartin pitch extraction and never finish.

thanks for reply to my problem any way.

**Comment by icinemagr** [comment]
some facts

1st) doesnt work on windows 7 or windows server 2008 r2
2nd) Doesnt work on windows 2019  
3rd) doesnt work  on windows 10
4th ) doesnt work in Ubuntu 
5th) Doesnt work on Min 21
it does work in Centos 9  (  at last ) with CPU only

so the question is 
is any OS that can work out of the box with nvidia gtx 1060?

**Comment by codename0og** [comment]
it should work just fine on win 10.
Make sure you have python 3.10.6 and try this rec list:
[requirements_3.10.6.txt](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/13626269/requirements_3.10.6.txt)

and if that still failed, try to confirm if it's release's fault or something on your pc's end:
Try release 0618 or try mangio crepe's rvc fork

**Comment by icinemagr** [comment]
> it should work just fine on win 10. Make sure you have python 3.10.6 and try this rec list: [requirements_3.10.6.txt](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/13626269/requirements_3.10.6.txt)
> 
> and if that still failed, try to confirm if it's release's fault or something on your pc's end: Try release 0618 or try mangio crepe's rvc fork
> 
> and if you need further support, maybe join the discord ( I am there too )

Thank you so much!!!!!!!!!!!!!!
i am trying

**Comment by icinemagr** [comment]
Installed Win10
Python 3.10.6
Your req.txt
and after 6 days everything WORKS now.
c++ 14 is the problem on windows 7 , server 2008 r2 thats why i wrote doesn work

Thanks again for your time!!!!!!!!

**Comment by OzzyHelix** [comment]
I am having this problem on an RX 7800 XT and Arch Linux 
[train.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/14734196/train.log)

**Comment by OzzyHelix** [comment]
it works on my Windows VM with an RTX 3060 attached but not on Linux with the RX 7800 XT why is that?

**Comment by OzzyHelix** [comment]
its annoying because I want to use my AMD card because its more powerful than my 3060 and has more VRAM but this error stops me from using it
