### ISSUE TITLE
Segmentation fault converting wav file

### ISSUE THREAD

**Issue by rmpt** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1606]
I've trained a model, after that I'm trying to convert a wav, but I get this error:

```
./run.sh: line 61: 10020 Segmentation fault: 11  python3 infer-web.py --pycmd python3
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
with the popup saying:
`Something went wrong Connection errored out.`

I'm using `harvest` as the pitch algorithm, the rest is the default.

Running on my own laptop, I have no GPU and source wav file is small (already tried with larger, medium, at this point I'm trying with a 20s wav file).

OS: MacOS 14.1.1

**Comment by Conghdos** [comment]
Have you fixed this error yet? I am currently having the same problem on Mac M2 Max with any audio file and any model.

**Comment by bunnyberserker** [comment]
Im on Mac OS 12.6 getting this similar error.

./run.sh: line 61:  2716 Segmentation fault: 11  python3 infer-web.py --pycmd python3

in addition I also got this

UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

**Comment by BigPines** [comment]
I am having the same issue. MacOS 10.15.3:

In the UI:
Something went wrong
Connection errored out.

In the Terminal:

./run.sh: line 61: 19677 Segmentation fault: 11  python3 infer-web.py --pycmd python3

/Users/user/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by BigPines** [comment]
Also happening on MacOS Intel 14.3.1

**Comment by x4080** [comment]
Any solution for mac ?

**Comment by huiyeruzhou** [comment]
Following this issue, I reinstall my env by conda:
https://github.com/facebookresearch/faiss/issues/2317

```sh
conda create -n RVC python=3.8
conda activate RVC
conda install -c pytorch faiss-cpu
```
then **comment the faiss-cpu dependency in requirements.txt**, and run
```sh
pip install -r requirements.txt
```

No more sigsev but still some error. Although vc_single works well, gradio will timeout after 5s.
```sh
pip install "gradio<5.0.0" -U
```

Then, **remove deprecated `concurrency_count` and add `concurrency_limit` to all `btn.click` calling**.
```diff
@@ -1286,6 +1292,7 @@ with gr.Blocks(title="RVC WebUI") as app:
                         ],
                         [info2],
                         api_name="train_extract_f0_feature",
+                        concurrency_limit=1,
                     )
             with gr.Group():
                 gr.Markdown(value=i18n("step3: 填写训练设置, 开始训练模型和索引"))
@@ -1609,11 +1616,12 @@ with gr.Blocks(title="RVC WebUI") as app:
                 gr.Markdown(traceback.format_exc())
 
     if config.iscolab:
-        app.queue(concurrency_count=511, max_size=1022).launch(share=True)
+        app.queue(max_size=1022).launch(share=True, max_threads=40)
     else:
-        app.queue(concurrency_count=511, max_size=1022).launch(
+        app.queue(max_size=1022).launch(
             server_name="0.0.0.0",
             inbrowser=not config.noautoopen,
             server_port=config.listen_port,
             quiet=True,
+            max_threads=40,
         )

```

After all, it works for me now.
