### ISSUE TITLE
Missing English translation

### ISSUE THREAD

**Issue by fire** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#161]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/README.en.md

Update the English readme?

1. What does https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI do?
2. How can I use an existing model?
3. How can I train a new model?
4. How long does it take?
5. What known problems and issues are there?

**Comment by fumiama** [comment]
Well, all languages version now is incomplete. Need to expand it.
