### ISSUE TITLE
RVC can't find the hubert_base

### ISSUE THREAD

**Issue by squingus-dingus** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1625]
Go easy on me, it's my first time here. But the RVC program can't find the hubert_base.pt even though it's in the root folder where it's supposed to be. I'm not sure how to guide it directly to the file, but it is literally _right there_ in the RVC-GUI-pkg folder, so I'm not sure why RVC can't find it. I tried renaming it to the .pth file like someone mentioned somewhere else, but that didn't work. I'm in MacOS 14.0.

`Traceback (most recent call last):
  File "/Users/me/Desktop/RVC-GUI-pkg/rvcgui.py", line 118, in vc_single
    load_hubert()
  File "/Users/me/Desktop/RVC-GUI-pkg/rvcgui.py", line 86, in load_hubert
    models, _, _ = checkpoint_utils.load_model_ensemble_and_task(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/miniconda3/lib/python3.11/site-packages/fairseq/checkpoint_utils.py", line 430, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: hubert_base.pt`

**Comment by CircuitCM** [comment]
You should see a directory in your downloaded repo `assets/hubert` and `hubert_base.pt` make sure it's inside.

**Comment by squingus-dingus** [comment]
There is no `assets/hubert` anywhere I could find. Where would that be? And this is what I'm using: https://github.com/Tiger14n/RVC-GUI/releases

**Comment by CircuitCM** [comment]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/30785886/68fe0980-ea3f-4991-90ab-916085a8a0d6)
Root folder is RVC-GUI.

**Comment by squingus-dingus** [comment]
Yeah, the file is there as the instructions say.
<img width="482" alt="file list" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/154005536/abf6ff74-5505-4455-bf27-8bdc8cb45d44">
