### ISSUE TITLE
1006v2 release exposes 2 different code bases, not fully functional with v2

### ISSUE THREAD

**Issue by alexander-rakhlin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1626]
1006v2 release features 2 different code bases. 

1.
The 1006v2 itself has only 2 configs in /v2 folder: `32k.json` and `48k.json` Hence, with v2+"40k" it uses 40k.json from /v1 folder: 
`infer-web.py`
```python
    if version19 == "v1" or sr2 == "40k":
        config_path = "v1/%s.json" % sr2
``` 
That means that for "40k" v2 it uses v1 config and for 32k and 48k v2 - v2 configs

2.
Different story for 1006v2 v2 notebook. For some strange reason it fetches another codebase. This code has no specific configs for v1 or v2 all are same.
`Retrieval_based_Voice_Conversion_WebUI_v2.ipynb`
```python
!git remote add origin https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git
!git fetch origin cfd984812804ddc9247d65b14c82cd32e56c1133 --depth=1
!git reset --hard FETCH_HEAD
``` 
And `infer-web.py` from this code, doesn't allow to select SR other than "40k" when "v2" selected.

3.
Finally, v2 "40k" checkpoints D40k.pth, G40k.pth are provided within 1006v2 release. And v2 32k and 48k are there as well. All three v2 D/G checkpoints seem ready to use. 

Summary. First code uses v1 40k instead of v2 40k and is okay with v2 32k and 48k. Second code is okay with v2 40k only.

I can't understand:
- why two different code bases are used within 1006v2 release?
- which of them to use with v2? Maybe both not fully compatible with v2

**Comment by RVC-Boss** [comment]
40k config, v2=v1
32k 48k config, v2!=v1
