### ISSUE TITLE
Cant launch RVC. "No NVIDIA GPU found" OR "SystemError: initialization of _internal failed without raising an exception"

### ISSUE THREAD

**Issue by V1Htor** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1629]
When launching go-web.bat i get this error message:

> C:\MINERVA\Programs\AI\RVC1006Nvidia>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
> Traceback (most recent call last):
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\infer-web.py", line 7, in <module>
>     from infer.modules.vc.modules import VC
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\infer\modules\vc\modules.py", line 11, in <module>
>     from infer.lib.audio import load_audio, wav2
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\infer\lib\audio.py", line 4, in <module>
>     import librosa
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\librosa\__init__.py", line 209, in <module>
>     from . import core
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
>     from .convert import *  # pylint: disable=wildcard-import
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\convert.py", line 7, in <module>
>     from . import notation
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\librosa\core\notation.py", line 8, in <module>
>     from ..util.exceptions import ParameterError
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
>     from .utils import *  # pylint: disable=wildcard-import
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\librosa\util\utils.py", line 9, in <module>
>     import numba
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\numba\__init__.py", line 42, in <module>
>     from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
>     from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
>   File "C:\MINERVA\Programs\AI\RVC1006Nvidia\runtime\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
>     from numba.np.ufunc import _internal
> SystemError: initialization of _internal failed without raising an exception

When i try launching it without a runtime it launches, but only in cpu mode:

> C:\MINERVA\Programs\AI\RVC1006Nvidia>py infer-web.py --port 2222
> 2023-12-18 15:22:17 | INFO | configs.config | No supported Nvidia GPU found
> overwrite preprocess and configs.json
> 2023-12-18 15:22:17 | INFO | configs.config | Use cpu instead
> is_half:False, device:cpu
> 2023-12-18 15:22:18 | INFO | __main__ | Use Language: en_US

My PC specs: Ryzen 5 5600, GTX 1080Ti 11GB VRAM.
RVC is RVC1006Nvidia

What i tried to do:

1. Reinstalling python, deleting pip cache, rebooting PC. Installing everything back. About 6 times.
2. Installing other versions of RVC.
3. Reinstalling numba, librose.

None did work.

I had an AMD card before, i deleted all driver leftovers via DDU. Didn't work.

nvidia-smi

> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 546.33                 Driver Version: 546.33       CUDA Version: 12.3     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |=========================================+======================+======================|
> |   0  NVIDIA GeForce GTX 1080 Ti   WDDM  | 00000000:07:00.0  On |                  N/A |
> | 32%   44C    P0              64W / 250W |   1233MiB / 11264MiB |      0%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
> 
> +---------------------------------------------------------------------------------------+
> | Processes:                                                                            |
> |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
> |        ID   ID                                                             Usage      |
> |=======================================================================================|
> |    0   N/A  N/A      1364    C+G   ...rams\Opera\99.0.4788.88_5\opera.exe    N/A      |
> |    0   N/A  N/A      8296    C+G   C:\Windows\explorer.exe                   N/A      |
> |    0   N/A  N/A     10508    C+G   ....Search_cw5n1h2txyewy\SearchApp.exe    N/A      |
> |    0   N/A  N/A     10556    C+G   ...ft Office\root\Office16\WINWORD.EXE    N/A      |
> |    0   N/A  N/A     12548    C+G   ...t.LockApp_cw5n1h2txyewy\LockApp.exe    N/A      |
> |    0   N/A  N/A     14080    C+G   ...ekyb3d8bbwe\PhoneExperienceHost.exe    N/A      |
> |    0   N/A  N/A     14144    C+G   ...GeForce Experience\NVIDIA Share.exe    N/A      |
> |    0   N/A  N/A     14584    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
> |    0   N/A  N/A     15656    C+G   ...\cef\cef.win7x64\steamwebhelper.exe    N/A      |
> |    0   N/A  N/A     16004    C+G   ...cordPTB\app-1.0.1050\DiscordPTB.exe    N/A      |
> |    0   N/A  N/A     17232    C+G   ...siveControlPanel\SystemSettings.exe    N/A      |
> |    0   N/A  N/A     18304    C+G   ...2.0_x64__cv1g1gvanyjgm\WhatsApp.exe    N/A      |
> |    0   N/A  N/A     19248    C+G   ...5n1h2txyewy\ShellExperienceHost.exe    N/A      |
> |    0   N/A  N/A     19616    C+G   ...1.0_x64__8wekyb3d8bbwe\Video.UI.exe    N/A      |
> |    0   N/A  N/A     19724    C+G   ...12.0_x64__8wekyb3d8bbwe\GameBar.exe    N/A      |
> +---------------------------------------------------------------------------------------+

**Comment by THE-SINDOL** [comment]
you need to install this before : Microsoft C++ Build Tools.

**Comment by V1Htor** [comment]
> Microsoft C++ Build Tools

I have it installed

**Comment by THE-SINDOL** [comment]
just unpack this one https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z?download=true and hit go-web.bat
