### ISSUE TITLE
Bad quality at the end after converting

### ISSUE THREAD

**Issue by ringi1970** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1630]
I tested RVC-fork with a good tutorial on Youtube from "AI Tools Search".
I have a RODE NT1A microphone and spoke (recorded with Presonus Studio One) one short sentence and took a little bit EQ on it.
Then downloaded a free "John Lennon" voice and converted it.
The output wave file sounded like it is a 64bit mp3 file. Very bad quality, no depth
Then i trained 5 hours an own Lennon voice (seperated his voice from "A Working Class Hero" with 5000 epochs), but the result sounded also like it was a bad mp3 file. 
What did I wrong?

Thanks for help

**Comment by THE-SINDOL** [comment]
You have few things to do on your mp3 file.
https://rentry.co/TrainingVoiceModels
https://rentry.org/RVC_making-models
