### ISSUE TITLE
How much storage space is needed, and can I run RVC on an external drive?

### ISSUE THREAD

**Issue by rvcuser** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1632]
How many GB of free space do I need to train and use a model? Can I install RVC on an external drive and train from there? Thanks very much.

**Comment by H46K3RL0L** [comment]
Not an expert, take note of that before reading. Yes, you can. I personally have it on an external 1TB drive, but total size per training seems to be a bit under 2 gb. 1 gb in the logs folder, 200-500 for an index file, and above 50 mb for the model in the assets\weights folder.
