### ISSUE TITLE
NEW Runtime, stacktrace, f0fail, CUDA and other errors on feature extraction that make no sense...

### ISSUE THREAD

**Issue by takearushfan82** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1634]
Hi all.  Feature extraction is giving me errors regardless of if I choose dio, harvest, rmv, etc.  What I don't understand is that it was working perfectly fine.  This is not a new version (I don't believe) since the last time I successfully trained a model.  I merely reformatted Windows since then, redownloaded RVC and now it's acting up.  Is there a memory issue?  There shouldn't be, as it was just working a few weeks ago.  Nothing is new with my hardware either, unless Windows updated something that broke RVC for me. 
 Here's the log file.  I tried to embed it but it's way too long:

[extract_f0_feature.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/13713311/extract_f0_feature.log)

**Comment by THE-SINDOL** [comment]
just re-install all stuff.
