### ISSUE TITLE
The go-web.bat file doesn't work

### ISSUE THREAD

**Issue by MattyG7** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1637]
I have fully extracted the zip, double clicked go-web.bat and this appears:
```
C:\Users\NAME\Documents\AI\Retrieval-based-Voice-Conversion-WebUI\RVC1006Nvidia>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
'runtime\python.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\mlgre\Documents\AI\Retrieval-based-Voice-Conversion-WebUI\RVC1006Nvidia>pause
Press any key to continue . . .
```

How do I fix this?
It happens with the Intel and Nvidia version of RVC.
I have Git and Python v3.10.11 installed.

**Comment by MattyG7** [comment]
Well, I got off that error by changing "runtime\python.exe" to "C:\Users\NAME\AppData\Local\Programs\Python\Python310\python.exe" but now I get this:
```
Traceback (most recent call last):
  File "C:\Users\NAME\Documents\AI\Retrieval-based-Voice-Conversion-WebUI\RVC1006Nvidia\infer-web.py", line 7, in <module>
    from infer.modules.vc.modules import VC
  File "C:\Users\NAME\Documents\AI\Retrieval-based-Voice-Conversion-WebUI\RVC1006Nvidia\infer\modules\vc\modules.py", line 18, in <module>
    from infer.modules.vc.pipeline import Pipeline
  File "C:\Users\NAME\Documents\AI\Retrieval-based-Voice-Conversion-WebUI\RVC1006Nvidia\infer\modules\vc\pipeline.py", line 14, in <module>
    import parselmouth
ModuleNotFoundError: No module named 'parselmouth'
```

I tried installing parselmouth with "Pip install parselmouth" but that has this error:
```
Collecting parselmouth
  Using cached parselmouth-1.1.1.tar.gz (33 kB)
  Preparing metadata (setup.py) ... done
Collecting googleads==3.8.0 (from parselmouth)
  Using cached googleads-3.8.0.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in googleads setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

How do I get rvc to just work like everyone else is able to? fgs :( :/

**Comment by JesseGreer990** [comment]
`pip install praat-parselmouth`

**Comment by THE-SINDOL** [comment]
the pre-package works fine, if you have download this one and hit go-web.bat no need to run requirement.txt because is pre-made, you can find all dependancie installed on runtime folder's : https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006Nvidia.7z?download=true 
and you need to install this before : Microsoft C++ Build Tools.

**Comment by MattyG7** [comment]
It can't work fine. It doesn't run. There's no python.exe in the runtime folder. Is a path or something missing maybe in wherever they're listed?
```
'runtime\python.exe' is not recognized as an internal or external command,
operable program or batch file.
```
Yeh I have Microsoft C++ Build Tools is installed.
Thank you in advance if anyone knows how to fix this.

**Comment by MattyG7** [comment]
Nevermind, the solution is here: https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/667
