### ISSUE TITLE
No pth file getting generated after training for 20 epochs. Screen getting corrupted while running.

### ISSUE THREAD

**Issue by linuxtroubleshooting** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1644]
This is my system:
OS: Ubuntu 22.06
CPU: Ryzen 3 3200G
RAM: 16GB
GPU: Radeon RX 6500 XT

When I followed the instructions given in this project's read me file, I installed CUDA version of Pytorch, asking for this on Pytorch forums, a user there resolved the issue. So after that I followed installation instructions on Pytorch, I installed the ROCm version of Python and I was able to run this project. 

I added a 11 minute 16-bit wave file with 69MB file size, in the Train tab I give a new experiment name, I paste the folder location containing the file and click process data, after it is completed successfully, I click on feature extraction, after this is completed, I click on the Train model button. I let it run at the default settings, so after running for 20 epochs it shows message in Chinese with some log file. 

I go to the inference tab and I don't see my project in the drop down list. I try to check it in the logs folder, there is a folder with the experiment name I gave but there is no pth file in the folder. 

When I check the train.log, there is an entry "Train Epoc 1: [0%]"

**Comment by astorlucas** [comment]
Did you found any solution? I'm experiencing the same problem now. Thanks.
