### ISSUE TITLE
Add Pesto for pitch estimation

### ISSUE THREAD

**Issue by dillfrescott** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1645]
Very new technique. Could prove really good.

https://github.com/SonyCSLParis/pesto

**Comment by Tps-F** [comment]
I read a paper on it a while back that interested me too.
I'll give it a shot.

**Comment by yxlllc** [comment]
According to the results in the paper, it currently performs worse than crepe, both for clean and noisy vocals. In terms of speed, it seems to be on the same level as rmvpe, but rmvpe is stronger than crepe on average. In addition, the new fcpe is even faster than rmvpe and stronger than crepe. So pesto may not be considered at the moment. 

Of course, if you change the dataset for training, the performance may be improved. We will give it a try after the author updates the training code.

**Comment by Tps-F** [comment]
Uh, sure.
I'll try a few more to improve result
