### ISSUE TITLE
A卡（RX 6600XT）是只能在linux中使用吗？

### ISSUE THREAD

**Issue by Leox0717** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1648]
Windows10 + RX 6600XT 没有办法用上显卡吗，还是需要指定pytorch版本？

**Comment by Misaka-Biu** [comment]
使用DML版本 不过效率不太行
" For AMD/Intel GPU users:
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z "

**Comment by LeonardoSidney** [comment]
> 使用DML版本 不过效率不太行 " For AMD/Intel GPU users: https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z "

Could you explain this better, because I downloaded both this package and the project (github (I also checked out the project commit)) and I didn't notice any difference(in my case, I use arch linux), it has the same errors (I have a 7900xtx). Does this zip package have anything different about the project?

**Comment by GUUser91** [comment]
@LeonardoSidney
What errors are you getting? I also have a 7900 xtx and I use artix linux and training works. The only problem is that inference with rmvpe takes too long, it took me 71 seconds to convert a 4 minute song. I'm using the nightly february 1 rocm builds of pytorch.

**Comment by LeonardoSidney** [comment]
> @LeonardoSidney What errors are you getting? I also have a 7900 xtx and I use artix linux and training works. The only problem is that inference with rmvpe takes too long, it took me 71 seconds to convert a 4 minute song. I'm using the nightly february 1 rocm builds of pytorch.

@GUUser91 
I can try what you said with the nightly compilation, currently I get a rather sinister error:
https://gitlab.freedesktop.org/drm/amd/-/issues/3056#note_2246903
I'll get back to you soon about the nightly compilation.

**Comment by Leox0717** [comment]
> 使用DML版本 不过效率不太行 " For AMD/Intel GPU users: https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z "

这个效率和cpu相比如何，不会不如用cpu吧
![01266607](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/55872966/e7672d71-d2df-4244-9d4d-9537057e8ea2)

**Comment by Leox0717** [comment]
.



> 使用DML版本 不过效率不太行 " For AMD/Intel GPU users: https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z "

这个包里面怎么只看到了realtime的gui，没有看到能用来训练的gui

**Comment by Leox0717** [comment]
> 使用DML版本 不过效率不太行 " For AMD/Intel GPU users: https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z "

https://pan.baidu.com/s/1mEs9Jmi2tBot4AgH6ZWp-w?from=init&pwd=eqea 这里找到个有go-web-dml.bat的整合包
