### ISSUE TITLE
return _VF.stft error

### ISSUE THREAD

**Issue by Haxhom** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1654]
I'm stuck at 1 epoch every time I try to train the model. I tried with harvest and rmvpe as my dataset quality is a bit low, but it shows the same errors.  Here are my configurations and the errors:
<img width="857" alt="WindowsTerminal_HJhqPtXU6e" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/76244194/6d4f0911-e209-48eb-97bb-3edaff7da176">
<img width="686" alt="explorer_VctcZa7cc6" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/76244194/1a85e3df-d8e3-43b2-96e2-7789ccc7c2e4">
<img width="859" alt="WindowsTerminal_elr8D7Pl5c" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/76244194/c48099e9-e3f6-4b0b-bcfc-7e80414c05d2">
I've got 4 GB of RAM only, Intel UHD graphics, maybe RVC doesn't support it?
How can I fix those errors if its possible?

**Comment by yxlllc** [comment]
This seems to be a warning rather than an error

**Comment by Haxhom** [comment]
Yeah my bad but I'm still somehow stuck on 1 epoch.... how. to. fix. it?

**Comment by Haxhom** [comment]
anyone?

**Comment by THE-SINDOL** [comment]
try to download new release, updated 7 days ago : https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/RVC1006AMD_Intel.7z
