### ISSUE TITLE
Training stuck at 1 epoch

### ISSUE THREAD

**Issue by Haxhom** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1655]
<img width="857" alt="WindowsTerminal_HJhqPtXU6e" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/76244194/f811c488-f528-4a89-9792-cd15d1bec778">

I've been training 4 hours but its still on 0%...

This is the configuration:
<img width="686" alt="explorer_VctcZa7cc6" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/76244194/fc740231-a80a-4e63-a682-b0a647b40201">
The audio quality is a bit low but the dataset is around 20-30min long cutten into 9s files. My RAM is 4GB..

How to fix this?

**Comment by H46K3RL0L** [comment]
Before reading please note I am not an expert, so do not take anything I tell you to do as fact. First of all, you need more ram, I have 16GB, and it works fairly well. What is your GPU? you need a good gpu to use this. I have an RTX 4070 laptop gpu, which has 8GB Vram and it takes about a minute per half hour. This gpu is 14.7 Teraflops (How many trillions of floating point operations per second.) Also, try increasing batch size per gpu. Default is 4, but for me putting it between 9 and 11 gets the highest speed.

**Comment by Haxhom** [comment]
I have 4GB of ram 💀
