### ISSUE TITLE
29/12/2023. /content/drive/MyDrive/project-main Your dataset folder is empty.

### ISSUE THREAD

**Issue by AlexeiPatrovnei** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1665]
When I was trying to make a model in RVC for osme reason it's telling me this weird errod about: Your Dataset folder is empty.
I wonder where do I need to put the dataset folder to and here I provide a screenshot.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/155137876/c1600d39-7fc1-476a-8747-e6dda1722794)

**Comment by ADR3-N** [comment]
In colab, there is the dataset folder for the RVC application, and there is your MyDrive dataset. Try one or the other and see if it helps.
