### ISSUE TITLE
Can it replace Elevenlabs?

### ISSUE THREAD

**Issue by rutvik106** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1667]
I just want to know that is it possible to use this tool on my AWS Server to create voices for my voice cloning product? Currently I am using Elevenlabs to do it. And it is very costly.

**Comment by H46K3RL0L** [comment]
Don't quote me on this, but it should be possible with some changes to the code. I think these would be pretty big changes though because this is voice CONVERSION, not voice GENERATION.

**Comment by 78Alpha** [comment]
It needs to be combined with a TTS tool. This just applies the voice properties to audio. You have some options for TTS with ups and downs.

- Tortoise (Old, slow, but allows for synthesizing completely new voices and cloning existing voices with accent)
- XTTS (Clone a single voice or multiple voices as different speakers, including accent)
- Piper (Clones a voice, no emotion and slow to train)
- StyleTTS (Can learn the style of a voice and clone it, allowing for control of emotional inflection, but needs 24 GB VRAM+ for training)
- SUNO (It can make voices, lots of features, no real voice cloning. A voice can be cloned but not trained, so it will have poor quality)
- Built-ins (AWS, Azure?, Edge, so on)
