### ISSUE TITLE
The rvc real time gui, just crashes, and show no error on the cmd

### ISSUE THREAD

**Issue by murasakll** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1668]
every thing that shows on the cmd is only this and nothing else

> #this is when i run the progam

```
D:\RVC1006Nvidia>runtime\python.exe gui_v1.py
is_half:True, device:cuda:0
```

> #this is when i press the audio conversion

```
Input device: 16:SteelSeries Sonar - Microphone (SteelSeries Sonar Virtual Audio Device) (Windows DirectSound)
Output device: 69:Fone de ouvido do headset (Astro A20 Voice) (Windows WDM-KS)
cuda_is_available: True
Index search enabled
```

> #is just it nothing else, beyond this point the progam is just frozen, and eventually windows will say that the program has stopped responding.

Initially I thought it would be something with my Windows Defender, I deactivated and reinstalled the program, but nothing changed, I also tried to change which type of sound system it will use, but without success, I thought about using another program, and the other It works normally, but with much worse quality than this program, I hope someone knows how to fix this :(
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/129218432/2335a499-4e41-4f6b-89db-75c6ac209fb7)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/129218432/fe1714a9-ff9d-4d73-9056-4ab0ea14608a)

**Comment by murasakll** [comment]
I don't even know what I did, I reinstalled everything and it started working again, but now it keeps giving an "audio block passed." in the log, but the program itself is working normally '-' here's a tip if you have an error that you can't fix To know what it is, simply reinstall Torch 2.0.1 and I did that and it returned '-'

**Comment by alizebuild** [comment]
same problem . I will have a try with your methods

**Comment by WongKahLok09** [comment]
Hey, I probably fixed it. At first my response threshold isnt set to -60, and I found out theres more than one voicemeter input which might be the cause that makes me stop responding. After fixed two of this the text "audio block passed" appears and eventually everything goes well. Hope it helps.

**Comment by WongKahLok09** [comment]
Hey, I probably fixed it. At first my response threshold isnt set to -60, and I found out theres more than one voicemeter input which might be the cause that makes me stop responding. After fixed two of this the text "audio block passed" appears and eventually everything goes well. Hope it helps.

Below attached my settings, kindly refers.

![Image](https://github.com/user-attachments/assets/42207fe3-d3e6-4084-a2ab-859b97131302)
