### ISSUE TITLE
Is It Possible to Use CPU & RAM for Training?

### ISSUE THREAD

**Issue by TechVillain** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1669]
For inference, I run RVC on CPU and RAM, it is a little slow, but works.

### CPU Training

For Training, I only have 2GB of Nvidia VRAM, it won't work even with batch size of 1. It's a laptop, so it's impossible to replace the GPU without abandoning the whole computer with already installed programs.

Google Colab is not a good option either, as it's based on Linux and being complicated to setup for noobs like me.

**The questions is, is it possible to modify the source code, and run training with CPU and RAM?**

It will be slow, but that's ok. As long as it allows the training to run. 

I have 12GB of RAM, Intel Quadcore i7 CPU, and I only need to train one model of Jay Chou's voice.

Please let me know what source code I can modify to make it happen.

**Comment by kubinka0505** [comment]
not in colab, as `FileNotFoundError: [Errno 2] No such file or directory: '/content/arsvc/logs/SciFun/3_feature256'`

**Comment by bleriot14** [comment]
I am also fallowing this issue. Any chance ?

**Comment by thefellaguy** [comment]
I train locally on a laptop with 6 cores and 32 gigs ram. Harvest works well.

**Comment by thefellaguy** [comment]
no special setup. just make sure the files are in the right place. git clone the repo, then pulled the filed from hugging face that go in pretrained_v2 folder. im on a linux laptop with no gpu. 6 cores 32 gigs ram. epochs were between  2:30 and 3:15. total time for 20  epochs was about 55 mins. it did want python 3.8, so i had to install than and i modified the run script to use a python 3.8 venv. (default python on this laptop is 3.12) it was pretty cut and dry. im gonna move it to my server later. that has more hp, should be able to go faster.

**Comment by TechVillain** [comment]
Wow, you are getting around 22 epochs per hour, on a CPU, that's impressive! If you leave it cooking during the night and go to bed sleep, the next morning you wake up you get about 150 epochs. Normally a 200 to 300 epoch model is considered a high quality model.

How many minutes of audio do you have for the training dataset? Is it sing or speech, or both?

With your 32GB RAM, what batch size number did you set? I assume the training didn't use up the full 32GB memory, am I right?

Also, I assume, in your Python 3.8 venv, you installed the torch-cpu version, not the torch-cuda version, in order to enable CPU training, right?

My Discord account is the same name as my GitHub account. Add me as a friend. I'm interested in hearing your CPU training experience, and how accurate is your model compare to the source speaker.


________________________________

**Comment by thefellaguy** [comment]
sent you a friend request, but I'm not a fan of putting it online :P

pytorch came down with running the run.sh file that came down with the git repo.  the last lines of the log file before training are:
`Retrieval-based-Voice-Conversion-WebUI/.venv/lib64/python3.8/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
move model to cpu
`
launching sytem default python can't import torch. launcing the python the rvc venv shows this:
`>>> print(torch.__version__)
2.3.0+cu121
>>> 
`
quick look on the filesystem for torch maxes out my terminal frame buffer. So no idea.
