### ISSUE TITLE
我是用RX 7800xt显卡在ubuntu系统下部署了rvc，但是我在训练一个语音模型的时候遇到一个问题。

### ISSUE THREAD

**Issue by Tomcatcoming** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1670]
当我进行到“训练模型”这一步的时候，出现了
![1](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/155366855/aa6361a7-a84f-4cde-badf-a83903594d0e)
这张图片的样子，在几秒钟过后，正如
![2](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/155366855/d2e85b05-8f13-4ff2-940b-da796d899ec1)
这张图显示的，它跑完了一个模型。但是我发现weights文件夹里面没有我训练的模型文件，请问这个是什么问题？

**Comment by fumiama** [comment]
训练结束不代表训练完成。更何况你训练时间如此短，这说明程序遇到了异常终止。你需要查看日志排查问题。
