### ISSUE TITLE
训练结束上面有模型下面没有模型

### ISSUE THREAD

**Issue by luminghly** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1671]
训练结束了，刷新音色列表和索引路径的位置没有我训练的模型😢，自动检索所以路径的位置又能找到我的模型，为什么呢？

这个是显示的
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.63 GiB already allocated; 0 bytes free; 5.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ms903x1** [comment]
CUDA out of memory.意味着训练代码因为爆显存而终止了，训练并没有成功。
