### ISSUE TITLE
Pydantic or predictbody problems ?

### ISSUE THREAD

**Issue by J-Collignon** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1673]
Hello,
i'm fairly new to the platform and the whole ai training procedure, but i had an idea in mind and i wanted to try it out. so i followed the tutorials i could find and the documentation, i correctly isolated the vocals and hashed the audio with Adobe in 9 separate files of less than ten seconds, linked correctly the files folder into the web-ui, but upon clicking on Start Processing, i caught some errors in the CMD that i haven't seen popping up anywhere else, so here goes :

2024-01-01 16:57:39 | ERROR | root | Task exception was never retrieved
future: <Task finished name='n2m4xmw2ave_14' coro=<Queue.process_events() done, defined at C:\Users\---\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['C:\\Users\\---...on_hash': 'n2m4xmw2ave'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "C:\Users\---\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Users\---\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Users\---\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "C:\Users\---\Desktop\Mangio-RVC-v23.7.0\runtime\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['C:\\Users\\---...on_hash': 'n2m4xmw2ave'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
    
i have legit no idea what to do and i would be very thankful  for your help
have a nice day and happy new year :)

**Comment by THE-SINDOL** [comment]
This one is mangio-fork and we no solve this problem here... 
Happy New Year

**Comment by chhandsomed** [comment]
Have you solved this problem? I have the same problem.
