### ISSUE TITLE
Is RVC multilingual?

### ISSUE THREAD

**Issue by dhruv1710** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1679]
After looking at the architecture I think RVC isn't multilingual, it uses VCTK dataset which is only English and Hubert base which is also language dependent and trained in English. I think the RMVPE model is not language dependent so that does not matter.

There are a few videos where they say that they converted one persons voice to other persons where they both spoke Hindi, so all this information is contradicting any help would be great.

**Comment by Lukasis150** [comment]
If you have a Hindi dataset, you can fine-tune pretrained model so it will learn Hindi. There could be an English bias, but it depends on how much data you have and also how you train it.

**Comment by dhruv1710** [comment]
The HuBert model is trained on English,the RVC model is trained on English and I don't know about language dependency of RMVPE but as far as I know it's trained on chinese songs. So do I fine tune all models?

**Comment by dillfrescott** [comment]
I regularly train on Japanese only datasets and English works great.

**Comment by dhruv1710** [comment]
@dillfrescott Suppose you train an embedder on Japanese words how will it be compatible with English?

**Comment by dillfrescott** [comment]
Its learning the sound of the voice, not the words, so it doesnt matter what language they are speaking in the dataset

**Comment by trivikramak** [comment]
How accurate would it be to say that it's learning the sound of voice independent of language/words. Are there any model/architecture decisions which point to this?

**Comment by KushATrivedi** [comment]
> I regularly train on Japanese only datasets and English works great.

Hi @dhruv1710 @dillfrescott  @Lukysoon ! 
Any documentation on finetuning the pre-trained RVC model on our own dataset (instead of VCTK dataset)?

**Comment by Lukysoon** [comment]
Hi!

Currently I'm running experiment that I'm freezing some modules of VITS model to preserve pronounciation.

My current pipeline:

1. Create base model from scratch with all data I have (in future base model I want to balance languages according to phonemes distribution with [Allosaurus](https://github.com/xinjli/allosaurus))
2. Finetune language specific model (all data for concrete language)
3. Finetune speaker specific model (all data for one speaker)

In the last step, I want to freeze layers (enc_p and flow) to preserve pronounciation from preceding finetunings.
I will share results.

**Comment by wuhai2438187057** [comment]
> 它学习的是声音的声音，而不是单词，因此他们在数据集中说什么语言并不重要

存在影响，会有一些声音发不出来

**Comment by utkarsh2299** [comment]
Hi @Lukysoon Any updates on your work? I also wanted to try something similar for indic languages. Any points would be of great help. Thanks.
