### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by hack1exe** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1681]
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by hack1exe** [comment]
i fixed it

**Comment by Zeze42** [comment]
> i fixed it

Hi, how did you fixed it?
