### ISSUE TITLE
Using Collab Pro, Training finishes and Collab disconnects, causing all the trained data to disappear?

### ISSUE THREAD

**Issue by YuvoBowmar4244** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1682]
I ran a 400 Epoch training session on paid Collab and left for a few hours. Came back and everything processed fine and finished, but the runtime had disconnected and RVC was unmounted from my drive, apparently deleting all of the work that had done.  What am I supposed to do? I get why Collab wants to disconnect since the process finished and nothing was happening, but does that data go anywhere? I reconnected and remounted, but there's nothing in the weights and logs folders, since I guess it's a new instance. What's the method here I should be following?

**Comment by ms903x1** [comment]
You need to save the PTH in real-time to Google Cloud Drive during training

 
笔记

**Comment by orkars** [comment]
Before start, you can change your path to a drive location. after that you can do all the things, train or inference. they will not be unmounted or disappeared.
