### ISSUE TITLE
Apple M1 error when running run.sh - dlopen symbol not found

### ISSUE THREAD

**Issue by dumbchildren** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1695]
the script stops when it tries to import lxml.etree:

import lxml.etree as ET
ImportError: dlopen(/opt/homebrew/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_exsltDateXpathCtxtRegister'

**Comment by DimitriGrimm** [comment]
Use Python 3.9 instead of 3.8.
