### ISSUE TITLE
Error while preprocessing data

### ISSUE THREAD

**Issue by srtrakzh** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1706]
After updating RVC, I suddenly received this error while preprocessing.

runtime\python.exe trainset_preprocess_pipeline_print.py "D:\RVC AI\RVC-beta\RVC-beta0717\datasets\Carti" 40000 8 D:\RVC AI\RVC-beta\RVC-beta0717/logs/PlayboiCarti False
Traceback (most recent call last):
  File "D:\RVC AI\RVC-beta\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 25, in <module>
    f = open("%s/preprocess.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RVC/preprocess.log'

Any ideas? Thanks in advance

**Comment by fumiama** [comment]
You are using a self-modified version of RVC, so we cannot provide further help to you since our original repo works well.
