### ISSUE TITLE
Error in the step2a

### ISSUE THREAD

**Issue by MohammadrezaHomaei** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1707]
To train a voice, I put the directory of my voice, but when I click on process data button, I face with this error:

['trainset_preprocess_pipeline_print.py', 'D:\\folder', '40000', '3', 'D:\\RVC\\Mangio-RVC-v23.7.0/logs/test', 'False']

**Comment by gmlcjf0326** [comment]
me too...
