### ISSUE TITLE
Powercut during AI training

### ISSUE THREAD

**Issue by farcast3r** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1708]
I was training an AI voice for several days and unfortunately we had a powercut - IIRC I had checkpoints every 10 epochs, how can I resume the training from the last epoch checkpoint or will I need to start the process from scratch?

**Comment by danablend** [comment]
Hey there!

There are 1000+ issues on this repository.

If you go to "Issues" and search for "resume training", there are many people who figured out how to do this already with explanations :-)

Hope you get it to work my friend.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/17946756/ec0045a8-22b3-4e67-9957-ecddde2551d6)
