### ISSUE TITLE
win11启动报错

### ISSUE THREAD

**Issue by nyaasuki** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1729]
版本	Windows 11 专业版
版本	22H2
安装日期	‎2024/‎1/‎15
操作系统版本	22621.3007
体验	Windows Feature Experience Pack 1000.22681.1000.0
--------------
这台电脑升级 win11后就无法运行了 具体报错如下 看起来似乎是音频驱动问题？
目前检查了voicemeet运行良好，也尝试自己安装环境运行 同样报错
<img width="856" alt="Snipaste_2024-01-16_10-57-03" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/39569579/10a96434-dcb3-4d4f-879f-17b4251cf731">

**Comment by yxlllc** [comment]
index文件没对上？

**Comment by nyaasuki** [comment]
index 文件是对上的，但是各种软件的几轮重装（包括这个项目的文件），突然恢复了，我已经没办法复现这个错误了。。。
