### ISSUE TITLE
Request: set minimum delay in real time

### ISSUE THREAD

**Issue by hobolyra** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1741]
The idea would be to set a minimum delay before the real-time conversion plays. Say you set it to 500 ms, then even if it converts the audio in say, 100ms, the program will still wait till at least 500ms (or whatever it's set to) before output. 

This would allow for better video/audio sync when using real-time. Not sure if this is even feasible but figured I would throw the idea out here.

**Comment by yxlllc** [comment]
You can increase the sampling length parameter to increase the delay. The algorithm delay of the audio stream is currently displayed in the GUI, which has nothing to do with the inference speed.
