### ISSUE TITLE
添加CPU推理功能

### ISSUE THREAD

**Issue by invatoric** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1756]
添加CPU推理功能，允许用户选用CPU推理。

**Comment by Whbgz** [comment]
可能gpu24h的活，cpu至少一个月，跑模型算法这些东西本来就是gpu的活

**Comment by songdong3015991** [comment]
我GPU是坏的，只能用CPU跑。而且我的CPU连diffsinger都跑得起来

**Comment by Den4ikSeekers** [comment]
Yes, that would be interesting, agreed. Slow, but steady :)
