### ISSUE TITLE
如果浏览器语言是中文但webui仍然是英语|一个解决方法（疑似没人写过，分享一下）

### ISSUE THREAD

**Issue by ImAlexBlock** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1759]
把\i18n\locale下的zh_CN.json直接改成en_US.json，原来的en_US.json删掉就好

**Comment by trackcan** [comment]
这种方式更友好一点：修改 infer-web.py中的 i18n = I18nAuto(language="zh_CN")

**Comment by ImAlexBlock** [comment]
草，这么早的都被找到了😂
