### ISSUE TITLE
GTX 950 4GB VRAM  cuda out of memory

### ISSUE THREAD

**Issue by medalawi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1760]
HI Could you please make RVC work on   4GB GPU while other vocal clone AI s  run without issue on this GPU.
 - V1 is working on this GPU with 1 batch size and 2 epoch every 1 hour   too slow   
 - on V2 I got Cuda out of memory 
I hope someone make a lite version of RVC for poor GPU Thanks.

**Comment by THE-SINDOL** [comment]
I think 4go IS lityle short for rvc, why not but better cards rtx 3060 12go IS cheap one. And which ai voice clone you know ???

**Comment by ydlmz** [comment]
Better to use single-core GPU with a larger memory.
