### ISSUE TITLE
Mix index files. 

### ISSUE THREAD

**Issue by Abedalhkeem-z** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1764]
Hello everyone, during the mixing of two pth models, is it feasible to combine two index files also or what is the deal?

**Comment by 78Alpha** [comment]
It blends the features. So if one has noise and the other has a hum, you would hear a slightly noise hum. If you have voices with heavy audio filters and blend them with the index of a normal voice, the audio filter would carry over. This lets you apply affects or change accents, etc.
