### ISSUE TITLE
Problems with third party uvr models

### ISSUE THREAD

**Issue by s1rne** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1765]
I have problems with using third party uvr models.
When I loading and started third party uvr models (e.g. 17_HP-Wind_Inst-UVR.pth from [uvr_models](https://huggingface.co/seanghay/uvr_models/tree/main)), that then an error appears:

server console:
```
Traceback (most recent call last):
  File "/home/user/parent-folder/infer/modules/uvr5/modules.py", line 101, in uvr
    del pre_fun.model
UnboundLocalError: local variable 'pre_fun' referenced before assignment
```

web window:
```
...
stg3_full_band_net.aspp.conv5.conv.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
```

why is this happening? after all, the processing of models should be the same. 
Some models from via the link above is correcy worked (e.g. 6_HP-Karaoke-UVR.pth).
I understand what this project don't intended for UVR how main instrument, but i think what connecting other uvr models not the most complex algorithm.

Also I  readed code uvr part, and noticed that for onnx model was written separate function. Why? This doesn't allow connect third party oonx models

about the software:latest version of the rvc project (branch is main)

**Comment by THE-SINDOL** [comment]
Hi uvr séparation works only with provide/downlaod base uvr from rvc project. If you want use fancy uvr go to download uvr5 and mvsep.com.

**Comment by s1rne** [comment]
I started looking for third-party uvr models because the standard ones were cracking after separation. But I realized what was going on and no longer need to use third-party uvr models. The problem was solved by reducing the volume of the input file

This issue may be closed for me
