### ISSUE TITLE
How to run in Mac M2 cpu?

### ISSUE THREAD

**Issue by zhouhao27** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1767]
The Google Colab version always got interrupted. So I try to run it locally in my Mac M2 machine.

Based on the document, I run `run.sh` and got the following error message:

> raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

Any idea? Is there anybody having experience running RVC in a Mac machine? Thanks.

**Comment by leoua7** [comment]
Same problem on M1 pro machine.

**Comment by XXXXRT666** [comment]
just run infer_webui.py directly in the zsh

**Comment by zhouhao27** [comment]
Finally I fixed the issue by following the way to install Sovits environment. Here is what I did:

1. conda create -n rvc python=3.10
2. conda activate rvc
3. python -m pip install -U pip setuptools wheel 
4. pip install torch torchvision torchaudio

After this, just run `./run.sh`.
