### ISSUE TITLE
Train a female voice but the result is a male voice

### ISSUE THREAD

**Issue by Tuanbui88** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1770]
-I trained a girl's voice (naming A1), 
-on tab model inference, I chose A1.pth, and add a wave file (also a female voice). However, the result always gives me a male voice all the time. I leave the Tranpose at 0. When I changed it from 1-12, it won't matter. Please help

I followed the tutorial here:
https://www.youtube.com/watch?v=pdYXr8fd2xs

**Comment by THE-SINDOL** [comment]
Hi and if add male voice with a1.pth and inference -7 or 7 what's you have ?
