### ISSUE TITLE
Increasing inference quality (steps / iterations)? Possible?

### ISSUE THREAD

**Issue by JoaCHIP** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1773]
In Stable Diffusion you can increase the number of "steps" (iterations) to increase the quality (which also increases render times). Is there a way to do something similar with RVC? I've been trying to read the code, but I don't know python, so it's hard.

PS: I'm not talking about training, just normal inference using existing models. And I don't need RVC to be real-time. I prefer quality, and I don't mind having to wait a bit longer.

**Comment by rekvizitt** [comment]
You can control the quality of the finished audio using various audio processing methods **(pm, harvest, crepe, rmvpe)**. Each method offers different quality of the final audio, and it depends on the power of your computer, i.e. it will take different time to create the audio.

Screenshot from go-web.bat (the methods I was talking about):

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/58174945/e5b2f313-b0e0-4236-983e-8466aef4cf0d)

**Comment by JoaCHIP** [comment]
Hello, and thank you for your fast reply. I've tried comparing all four settings, and it seems the difference is how they detect the base pitch of the input as far as I can tell. "harvest" and "crepe" tend to find the base pitch, whereas rmvpe seems to find higher harmonics, but is sometimes less "shifty" than "harvest" and "crepe". And "pm" doesn't give me very good results.

However, the choice between those four option only seems to affect pitch detection, as far as I can tell. They do not seem to affect the actual _quality_ of the generation.

And of course, I've also systematically tested all the other parameters offered in the UI. None of them seem to really correspond to the "steps" or "number of iterations" setting that (for example) Stable Diffusion offers.

So I wonder if there's a hidden setting somewhere in the code that I can access?

**Comment by rekvizitt** [comment]
> So I wonder if there's a hidden setting somewhere in the code that I can access?

Probably, not
