### ISSUE TITLE
我的intel arc a770显卡显示不支持

### ISSUE THREAD

**Issue by lionshen** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1774]
是否需要下载什么

**Comment by lionshen** [comment]
![微信截图_20240128211735](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/103938352/24096c1a-998c-489e-b0ce-0abd8efdbe19)
![微信截图_20240128211830](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/103938352/e907a772-6d97-4d80-88c9-8586ce344b54)

**Comment by rekvizitt** [comment]
You can find the solution [here](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1734)

Note that the person there was adding an Nvidia card, and you need to add your own by Intel
