### ISSUE TITLE
针对 go-realtime-gui.bat打开RVC变声器后控制台出现UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte错误的第二种解决方案，无需设置Windows10的默认编码为UTF-8

### ISSUE THREAD

**Issue by guoyaoyang0522** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1776]
因设置Windows10的默认编码为UTF-8会导致其他软件乱码
因此在与GPT共同钻研一晚上后，给出第二种解决方案，实测成功
修改第三方库 sounddevice.py 文件中的第 578 行，
问题发生的原因是无法使用utf-8编码格式解码音频驱动名（如中文特殊字符）

解决方案
修改第三方库 sounddevice.py 文件中的第 578 行代码
整合包下该文件路径示意
RVC1006Nvidia\runtime\Lib\site-packages\sounddevice.py
原代码 name = name_bytes.decode('utf-8')

使用更宽容的错误处理方式 'replace' 或 'ignore'，把无法解码的字符替换为占位符或者忽略无法解码的字符，解码过程就能够继续进行
把 name = name_bytes.decode('utf-8') 

改为
name = name_bytes.decode('utf-8', errors='replace') 
使用错误处理方式 'replace'，将无法解码的字符替换为占位符
或者
name = name_bytes.decode('utf-8', errors='ignore') 
使用错误处理方式 'ignore'，忽略无法解码的字符
二选一就好

**Comment by gaoyuoppa** [comment]
有用，解决了，赞

**Comment by shenyunet** [comment]
有用，解决了，赞

**Comment by MarinoAdmas** [comment]
解决了...谢谢
