### ISSUE TITLE
In the vocals separation section, I cannot see or select the models for voice separation. like HP2 or HP5

### ISSUE THREAD

**Issue by Rae99** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1783]
In a YouTube tutorial, I saw models like hp2 and hp5. But I've got nothing.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/109961661/b9c33898-c843-4392-8606-972e21b60667)

**Comment by THE-SINDOL** [comment]
Hi, please Check folder assets\uvr5_weights , if there are files, if not go to tools folder and launch dlmodels.bat.
