### ISSUE TITLE
Why is the final processing taking forever? I'm sure something went wrong, but it never reports any issue.

### ISSUE THREAD

**Issue by Rae99** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1786]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/109961661/6123cebb-a60d-4413-9d32-5f2c922d2641)

I've tried a few times. The first time it took 2 hours and still no outcome. It's really frustrating:(

**Comment by THE-SINDOL** [comment]
Hi, please show all screen, and cmd screen.
