### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by AlexNikMak** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1788]
Hi 
I am trying to train RVC(rmvpe-gpu) model using several gpus:
rtx3070 8gb
quadro m2000 4gb
quadro m2000 4gb

I get this error:
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 2; 4.00 GiB total capacity; 3.21 GiB already allocated; 0 bytes free; 3.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
It's very strange because I can use this gpus for training, but separately.

My batch size is already at 1. Please guide me where I can manually adjust max_split_size_MB.

**Comment by ydlmz** [comment]
You can use single GPU but with larger NVRAM size. Nvidia SLI is not currently supported.
