### ISSUE TITLE
I got an erron when I train my model, how to solve this?

### ISSUE THREAD

**Issue by riovijey** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1789]
File "C:\Users\vijey\Desktop\Feb 1, 2024 10_43 pm\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: '1,'
![Screenshot 2024-02-02 125116](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/38461158/d70ad50e-a758-4bdc-bca6-7845feb973b2)

**Comment by THE-SINDOL** [comment]
Hi, please don't use Space, spécial character in path.
