### ISSUE TITLE
Are there any other pre-trained voice model for training?

### ISSUE THREAD

**Issue by zhouhao27** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1790]
I'm trying to train my own voice in Chinese. It works quite well. The sound quality is really good. But there is one problem. The way of my speaking is not like a Chinese. It sounds like speaking by a foreigner. I'm wondering if it's because of the pre-trained base voice model  is not from a Chinese speaker? Are there any other pre-trained base voice model I can use? Thanks.

**Comment by gaoyuoppa** [comment]
小本子？
