### ISSUE TITLE
如何解决runtime\python.exe ### webui.py找不到指定路径的问题？

### ISSUE THREAD

**Issue by heweiwei666** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1791]
![QQ图片20240203180238](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/154526530/97b78c22-aca5-480c-ba81-efe181318141)
如何解决runtime\python.exe ### webui.py找不到指定路径的问题？

**Comment by talentestors** [comment]
在github这个可不是一个好问题
