### ISSUE TITLE
low cpu&gpu load also long epoch times

### ISSUE THREAD

**Issue by stephen7943** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1792]
English is not my native language; please excuse my typing errors.

My configuration: 

- Intel i9 12900
- NVIDIA GeForce GTX 2080 super 8GB
- 128.0 GB RAM
- cuda 12.1
- Windows 10 Pro 22H2
- Python 3.8.18
- Pytorch 2.1.2

When I start training, each epoch takes about 750~800secs, and also the CPU and CPU loading is just really low.., but the GPU memory is almost used.

Did anyone have some idea, how to fix this problem?

English is not my native language; please excuse my typing errors.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/94160194/46a06d0b-3773-4f2a-9003-98bb05affb0e
![螢幕擷取畫面 2024-02-06 115931](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/94160194/1b8c7732-2812-4727-bcf5-e872ccae104d)
![螢幕擷取畫面 2024-02-06 120204](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/94160194/09600ccb-2e01-4710-9306-993dc24c3579)
![螢幕擷取畫面 2024-02-06 120223](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/94160194/041cb165-2ba0-4ee8-85af-b615e1ef3b5c)

**Comment by Frioo** [comment]
Same here. During processing and other tasks the hardware was going full tilt, however training seems to be behaving in an odd way. Ryzen 5 7600X, RTX 2080, 24G RAM.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/22414778/3e1ada7c-04c3-4cb4-8775-1b3a42e546f3)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/22414778/6e53dc10-792a-4f72-bf66-597a07b4e1f1)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/22414778/8aaaa6f8-35ea-49cd-b42a-ada8466277b5)
