### ISSUE TITLE
没有index文件

### ISSUE THREAD

**Issue by EatKFCinMc** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1793]
一键训练后没有index文件，点击train feature index只会在output information那里快速闪一下，然后就变回原样并且任然没有index输出。版本为最新版本，训练选项均为默认选项，依赖项全部安装，显卡是rtx3050。configs文件夹中的config文件也删过一次了也没用。

**Comment by Gilinfen** [comment]
> 一键后训练没有index文件，点击train feature index训练只会在输出信息那里快速闪一下，然后就变回原样并且任然没有index输出。版本为最新版本，选项默认选项，依赖项全部安装，显卡是rtx3050。configs文件夹中的config文件也删过一次也没有用。

解决了吗，我也是一直没有index文件。
