### ISSUE TITLE
由requirements.txt安装时报错

### ISSUE THREAD

**Issue by AlexCreeper** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1795]
![QQ图片20240208025958](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/42467560/ecb2fce8-e1ff-4f60-a0db-33a0fe6ac051)
![QQ图片20240208030005](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/42467560/e9dcf348-fe44-4cf2-8319-09a6bfbec9db)

**Comment by AlexCreeper** [comment]
上图大部分解决，系py版本问题，现在出现了新问题。。
![QQ截图20240208032055](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/42467560/9c67d9e5-c2a6-49c6-8d26-80c4b9f32ff4)

**Comment by ChangXinze** [comment]
你翻下前面，是不是缺少VC++14 .https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/ 到这里下载然后安装

**Comment by AlexCreeper** [comment]
> 你翻下前面，是不是缺少VC++14 .https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/ 到这里下载然后安装

非常感谢，此问题已解决，然而omegaconf似乎又出了问题，如图：
![QQ截图20240208211209](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/42467560/75dab9eb-7667-4930-a4a4-8d51a1aada8c)
py version 3.1.0
pip version 24.0
我用ai搜索，答复如下：

> [这个报错是因为您安装的 omegaconf 2.3.0 版本与 fairseq 0.12.2 和 hydra-core 1.0.7 的要求不兼容，导致 pip 无法解决依赖关系](https://blog.csdn.net/RLCSDN3402/article/details/135494034)[1](https://blog.csdn.net/RLCSDN3402/article/details/135494034)[2](https://www.bytezonex.com/archives/16.html)。要解决这个问题，您可以尝试以下方法：
> 
> [降级 omegaconf 到 2.0.6 版本，这是 fairseq 0.12.2 和 hydra-core 1.0.7 共同支持的版本](https://blog.csdn.net/qq_52431436/article/details/133694357)[3](https://blog.csdn.net/qq_52431436/article/details/133694357)。您可以使用以下命令来执行：
> pip install omegaconf==2.0.6
> 
> [升级 fairseq 和 hydra-core 到最新版本，它们已经支持 omegaconf 2.3.0 版本](https://download.pytorch.org/whl/cu118)[4](https://download.pytorch.org/whl/cu118) 。您可以使用以下命令来执行：
> pip install --upgrade fairseq hydra-core

然而，不管如何操作，上述DEPRECATION仍然会出现

**Comment by ChangXinze** [comment]
这个只是警告，应该不影响使用吧。

**Comment by AlexCreeper** [comment]
当时数天后已经解决，但忘了将其标记为已解决。但还是感谢您的回复！

发自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: Xinze Chang ***@***.***>
发送时间: 2024年3月6日 14:23
收件人: RVC-Project/Retrieval-based-Voice-Conversion-WebUI ***@***.***>
抄送: AlexCreeper ***@***.***>; Author ***@***.***>
主题: Re: [RVC-Project/Retrieval-based-Voice-Conversion-WebUI] 由requirements.txt安装时报错 (Issue #1795)


这个只是警告，应该不影响使用吧。

―

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
