### ISSUE TITLE
Translate README.md into english.

### ISSUE THREAD

**Issue by ArKam** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1796]
Hi team, I think it would be really useful to translate the main README.md file to english if possible.
If you don't want to replace the main README.md with the english one I do perfectly understand, could we in this case get a README_en.md ?

Thanks a lot for the good works!

**Comment by Tps-F** [comment]
@ArKam 
en readme is here
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/en/README.en.md
