### ISSUE TITLE
Should the training dataset contains laughter, breathing, or sigh sound?

### ISSUE THREAD

**Issue by ngphuchoangnam** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1797]
I'm wondering if I should keep breathing sounds in my dataset. In addition, would including samples such as laughter help with laughter conversion?

**Comment by Mojobones** [comment]
In my experience breathing is good. If there's a ton of it maybe cut some of it out, but it's good for it to hear breathing and can help it sound more natural. 

For laughter, it depends. It'll learn how that person laughs but not necessarily how others laugh. So trying to convert laughter might not work well unless the audio you're converting purposefully laughs similar to the source audio the model was trained on.
