### ISSUE TITLE
GPU Acceleration for Apple Silicon? 

### ISSUE THREAD

**Issue by an-internet-user001** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1800]
Hello,

I have an M2 Mac Studio and have been following this repository for awhile now.  I know in the past it was not possible to train models on Apple Silicon while also leveraging GPUs for acceleration/processing power.   Has this changed based on recent releases and updates to PyTorch/MPS?   Thanks for all your hard work here!

**Comment by Excurl** [comment]
any update, looking for more...
