### ISSUE TITLE
For some reason I can't open the easyGUI. I get this instead. What does it mean?

### ISSUE THREAD

**Issue by wairyfon** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1801]
![g](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/159484819/8c9e8118-0a78-42c3-b5ab-d68854843cf8)

**Comment by W055** [comment]
fixed it with `pip install gradio_client==0.8.1 `

**Comment by wairyfon** [comment]
> fixed it with `pip install gradio_client==0.8.1 `

How do i do that? Sorry, I don't really know much about this stuff TT
