### ISSUE TITLE
filenotfound error

### ISSUE THREAD

**Issue by armagithub** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1805]
I can do 'process data' and 'feature extraction' just fine, but when i do the one click training it get this error FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Project\\RVC-beta-v2-0528/logs/barry/3_feature256'..

I do have to say that i don't have an NVIDEA GPU, but this error seems unrelated to that?

**Comment by liang-fei-fan** [comment]
I replace my folder from "D:\rvc2\RVC1006NVIDIA\z\" -> "D:\\rvc2\\RVC1006NVIDIA\\z\\", and it works...
I don't know why...
![z](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/60847638/926f5b02-1811-4db4-9f0b-008ac7ea7390)

**Comment by liang-fei-fan** [comment]
> I replace my folder from "D:\rvc2\RVC1006NVIDIA\z" -> "D:\\rvc2\\RVC1006NVIDIA\\z\\", and it works... I don't know why... ![z](https://private-user-images.githubusercontent.com/60847638/303841570-926f5b02-1811-4db4-9f0b-008ac7ea7390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NzQ2NTQsIm5iZiI6MTcwNzU3NDM1NCwicGF0aCI6Ii82MDg0NzYzOC8zMDM4NDE1NzAtOTI2ZjViMDItMTgxMS00ZGI0LTlmMGItMDA4YWM3ZWE3MzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE0MTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGE1MzY1M2Q4YmQ1NmY4ZWViMzA1YzhjZThlMGRjY2E1MjZiYmEyNzI3ZGMxZWZlNDIxZGIyMmQ5YTY1NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x7sxHwlfXIDBZbIAySfp_A9lx77tPEc1X0m4Gz1FXTc)

**Comment by liang-fei-fan** [comment]
> > I replace my folder: "D:\rvc2\RVC1006NVIDIA\z" -> "D:\\rvc2\\RVC1006NVIDIA\\z\\", and it works... I don't know why... ![z](https://private-user-images.githubusercontent.com/60847638/303841570-926f5b02-1811-4db4-9f0b-008ac7ea7390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NzQ2NTQsIm5iZiI6MTcwNzU3NDM1NCwicGF0aCI6Ii82MDg0NzYzOC8zMDM4NDE1NzAtOTI2ZjViMDItMTgxMS00ZGI0LTlmMGItMDA4YWM3ZWE3MzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDE0MTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGE1MzY1M2Q4YmQ1NmY4ZWViMzA1YzhjZThlMGRjY2E1MjZiYmEyNzI3ZGMxZWZlNDIxZGIyMmQ5YTY1NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x7sxHwlfXIDBZbIAySfp_A9lx77tPEc1X0m4Gz1FXTc)
