### ISSUE TITLE
RVC GUI not running 

### ISSUE THREAD

**Issue by OmaBatser69** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1806]
I installed RVC GUI, unzipt it and tried to run it but it keep giving this error message. What does this mean and how do i resolve it. I'm not into coding stuff so I'm sorry if it is an obvious flaw.

![Screenshot 2024-02-10 153702](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/159633575/da264051-528f-4c6a-9fa3-b387038346b1)

**Comment by iammmmmmm** [comment]
You are not using python. It is recommended to download the complete package and try again.
