### ISSUE TITLE
Questions abotu producing a voice that looks like HUMAN voice, less ROBOTIC, Less MONOTONIC etc, with more emotions, intonations, pitch tone, etc..?

### ISSUE THREAD

**Issue by APISeeker** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1808]
Hello,
Once I trained a model and obtained a "modelOfaVoice.pth",
Where can I go to use it in an effiscient way to obtain very nice voices that looks like human?

Do you guys try to IMPROVE the training BEFORE making the ".pth" file, or do you have ways to use the good enough .pth model to go make voices that look like human and with goods intionation etc?

I am looking for ways to produces voices that do not look "MADE UP", intead it"a almost if not completely look like HUMAN.
So for example, maybe methods to let words be pronounced differently "Hello this is Jim" -> " Helloo, This is.. Jim! or "Hello, thiiiis is Jim." etc etc..

Anyway, the question anyway is : where do you guys use your .pth files? 
And can you post process the audios produced further to make it real human? Thanks.
Ps. Can we open the "discussions" sectino of this repository?

**Comment by EraBawer** [comment]
same question

**Comment by APISeeker** [comment]
If you find @EraBawer  please tell me.

**Comment by Den4ikSeekers** [comment]
I'm also interested in this.

**Comment by Metalhead33** [comment]
A little bit of de-essing helps.
