### ISSUE TITLE
无法打开webui

### ISSUE THREAD

**Issue by sebastian-cao** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1809]
报错：
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by showkeyjar** [comment]
+1

**Comment by sebastian-cao** [comment]
> +1
已解决，更新Tensorflow和protobuf

**Comment by sebastian-cao** [comment]
> +1

已解决，更新Tensorflow和protobuf

**Comment by showkeyjar** [comment]
> > +1
> 
> 已解决，更新Tensorflow和protobuf

已解决，升级 wandb 解决

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
