### ISSUE TITLE
[Help me!] All Training attempts generated the same voice.  

### ISSUE THREAD

**Issue by Ahm3dRN** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1810]
I've been trying to train my own model on a dataset I gathered. 
I used more than one person's voice, I first tried creating a model of a voice the dataset was 12 minutes of audio with 50 epochs the voice was nothing near. then I tried 100 epochs same exact voice. I changed the dataset to a different person as a different model and it's the same exact voice again. I tried a different dataset I used this time for 5x 2 min audio files. all the audio files are of good quality.
I did this with 5 different models 5 different datasets (voices) and ranging epochs of 50-200 and they all generated the same exact voice regardless.  I'm really new to this I need help to figure out what's wrong. 

I'm running on NVIDIA GeForce GTX 1660 SUPER

**Comment by Ahm3dRN** [comment]
> I'm having the exact same issue and couldn't find anything on google or anyone coming up with the same problem. Every voice I test has the same generic sound now. it was working a few days ago. I've tested models with 500 epochs. I've tested smaller and larger datasets, I've tested multiple chunk data sets or one long 40 minute one.
> 
> Same voice. It's like it's not training at all on the data given.

Hi, I could solve this issue by downloading the compatible version of the tool  from hugging face. I used `RVC1006Nvidia.7z`  from hugging face repo. previously i tried cloning the repo and installing the tools but idk what is it but something wasn't right.

**Comment by Vana2793** [comment]
> Hi, I could solve this issue by downloading the compatible version of the tool from hugging face. I used `RVC1006Nvidia.7z` from hugging face repo. previously i tried cloning the repo and installing the tools but idk what is it but something wasn't right.

I'm using google colab version as I don't have the GPU currently to run it locally. Do you possibly have any tips for that?

**Comment by Ahm3dRN** [comment]
> > Hi, I could solve this issue by downloading the compatible version of the tool from hugging face. I used `RVC1006Nvidia.7z` from hugging face repo. previously i tried cloning the repo and installing the tools but idk what is it but something wasn't right.
> 
> I'm using google colab version as I don't have the GPU currently to run it locally. Do you possibly have any tips for that?

Are you using a paid version as far as i know colab no longer allow that on  a free runtime.
as for colab I didn't try this specific project but I think it should also apply here u can download the file and unzip it and run using the python runtime provided with the zip file. again I haven't tried this but it should work.

**Comment by Vana2793** [comment]
> Are you using a paid version as far as i know colab no longer allow that on a free runtime. as for colab I didn't try this specific project but I think it should also apply here u can download the file and unzip it and run using the python runtime provided with the zip file. again I haven't tried this but it should work.

I have an AMD card, so I don't know if that will help. As far as I understand, RVC isn't very AMD friendly.
Yeah, google prevented it, but there are a few people who've put in the code and linked their colab to make it work anyway. I'm saving up to upgrade my GPU asap.

**Comment by Vana2793** [comment]
> there is also [RVC1006AMD_Intel.7z](https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/RVC1006AMD_Intel.7z). before u pay for colab consider checking alternatives as well. good luck.

What kind of alternatives? I will give the DL a shot :)
