### ISSUE TITLE
Failed to trainn voice

### ISSUE THREAD

**Issue by Antonin2938** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1811]
Hello !!
When I click on one-click training, it gives me an errorit's. It's the same thing when I click on Train feature index and Train the model.
I also tried another RVC repository, but still the same error...

Error : 

2024-02-14 14:23:45 | INFO | __main__ | Use gpus: 0
2024-02-14 14:23:45 | INFO | __main__ | "runtime\python.exe" infer/modules/train/train.py -e "mi-test" -sr 32k -f0 1 -bs 4 -g 0 -te 20 -se 20 -pg assets/pretrained_v2/f0G32k.pth -pd assets/pretrained_v2/f0D32k.pth -l 1 -c 0 -sw 0 -v v2
INFO:mi-test:{'data': {'filter_length': 1024, 'hop_length': 320, 'max_wav_value': 32768.0, 'mel_fmax': None, 'mel_fmin': 0.0, 'n_mel_channels': 80, 'sampling_rate': 32000, 'win_length': 1024, 'training_files': './logs\\mi-test/filelist.txt'}, 'model': {'filter_channels': 768, 'gin_channels': 256, 'hidden_channels': 192, 'inter_channels': 192, 'kernel_size': 3, 'n_heads': 2, 'n_layers': 6, 'p_dropout': 0, 'resblock': '1', 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'resblock_kernel_sizes': [3, 7, 11], 'spk_embed_dim': 109, 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [20, 16, 4, 4], 'upsample_rates': [10, 8, 2, 2], 'use_spectral_norm': False}, 'train': {'batch_size': 4, 'betas': [0.8, 0.99], 'c_kl': 1.0, 'c_mel': 45, 'epochs': 20000, 'eps': 1e-09, 'fp16_run': True, 'init_lr_ratio': 1, 'learning_rate': 0.0001, 'log_interval': 200, 'lr_decay': 0.999875, 'seed': 1234, 'segment_size': 12800, 'warmup_epochs': 0}, 'model_dir': './logs\\mi-test', 'experiment_dir': './logs\\mi-test', 'save_every_epoch': 20, 'name': 'mi-test', 'total_epoch': 20, 'pretrainG': 'assets/pretrained_v2/f0G32k.pth', 'pretrainD': 'assets/pretrained_v2/f0D32k.pth', 'version': 'v2', 'gpus': '0', 'sample_rate': '32k', 'if_f0': 1, 'if_latest': 1, 'save_every_weights': '0', 'if_cache_data_in_gpu': 0}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\Téléchargement\RVC1006Nvidia\infer\modules\train\train.py", line 140, in run
    train_dataset = TextAudioLoaderMultiNSFsid(hps.data.training_files, hps.data)
  File "D:\Téléchargement\RVC1006Nvidia\infer\lib\train\data_utils.py", line 23, in __init__
    self.audiopaths_and_text = load_filepaths_and_text(audiopaths_and_text)
  File "D:\Téléchargement\RVC1006Nvidia\infer\lib\train\utils.py", line 282, in load_filepaths_and_text
    filepaths_and_text = [line.strip().split(split) for line in f]
  File "D:\Téléchargement\RVC1006Nvidia\infer\lib\train\utils.py", line 282, in <listcomp>
    filepaths_and_text = [line.strip().split(split) for line in f]
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte

**Comment by Ahm3dRN** [comment]
I think this could be due to the characters in the path of the files. could u try having the files in paths that don't have non-English characters?  for example "0xe9" is é and I can see it in the path of the logs u posted. I often get this error when I have a path URL in Arabic some libraries can't handle them and it produces this error.

**Comment by Antonin2938** [comment]
Thank !!
