### ISSUE TITLE
How to install on a MacBook

### ISSUE THREAD

**Issue by User-444** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1813]
I got recommended to use this voice conversion AI though i don't know how to install it what so ever, cause i can't find a download button or an easy to understand way to download the Ai and set it up.

**Comment by MENJI-TRIWATER** [comment]
maybe you can follow this web
https://zhuanlan.zhihu.com/p/680205937?utm_id=0
my laptop is m2pro silicon, by following the web , though i couldn't train models locally but the  inference process still ok

**Comment by jathoo** [comment]
Looks like the shell script is not working properly

**Comment by dieoriginal** [comment]
anybody on mac??? damn mac is really hyped up, you cant do nothing
