### ISSUE TITLE
"Unfortunately there is no compatible GPU available to support your training" issue using AMD Radeon 530

### ISSUE THREAD

**Issue by bljn** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1817]
Hello all,

I've been giving training my own ai voice model a go using Mangio RVC, but it looks like I've run into the dreaded imcompatible GPU program a few people before me have. I've seen some of you having the same issue, though from what I could see not of them were using AMD GPUs. In one of the issues I've read someone reccommend installing cuda, though from what I could gather those are only for NVIDIA products (sorry, not very savvy with tech stuff). 

At first looked like I could still continue while wilfully ignoring the problem, but even though I would get the typical success message (you know, the one with those kanji\hanzi characters), but upon looking at my command prompt it didn't look like anything worthwhile was happening, and my pth files where nowhere to be seen in the "weights" folder. I think making my gpu somehow compatible would solve this, though that remains to be seen.

Can anyone recommend some sort of solution for me short of having to buy a different GPU? Would updating OpenGL help?

Thank you all in advance!

**Comment by Gboy12345** [comment]
AMD GPUs are sadly not directly supported by RVC AI due to its reliance on Nvidia's CUDA libraries... I also suffer from this :(

**Comment by TechVillain** [comment]
> AMD GPUs are sadly not directly supported by RVC AI due to its reliance on Nvidia's CUDA libraries... I also suffer from this :(

I am running on an Nvidia card but I don't have enough VRAM for the training.

So, on the README file, it says if you install RVC based on Intel i card, you can run training based on OpenGL.

Is this true?
  

![Screenshot_20240318_174641](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/131915615/5ae313bd-23f5-4235-bb30-9697f5472b9e)

**Comment by Sinvanor** [comment]
I also would like to know if this is possible to at all use an AMD one in anyway. I will be buying a new GPU in the future, as mine is literally a decade old, but Nvidia growing into a monopoly is not cool in my book. Not to mention that because they own the AI market right now, they are overpriced to hell and back.
