### ISSUE TITLE
RTX 4080 support

### ISSUE THREAD

**Issue by westNeighbor** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1822]
I have NVIDIA RTX 4080 GPU. I followed the instructions but whatever the cuda versions I tried (cuda toolkit 11.8, 12.2, 12.3), it all gives No supported Nvidia GPU found, I am wondering are there any instructions about 40xx card instruction to run it correctly. Also tried the python to print the torch cuda version, seems no cuda device found.
![Screenshot 2024-02-16 202337](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/143965219/3cf249fc-5ff3-49be-aa0d-f69f80a3d497)

**Comment by westNeighbor** [comment]
Never mind, just the RVC1006Nvidia.7z one, it works.

**Comment by sv3nk** [comment]
Have you figured out why torch does not see your GPU? I am running into the same problem.

**Comment by westNeighbor** [comment]
> Have you figured out why torch does not see your GPU? I am running into the same problem.

Yep, I add two CUDA paths (I installed two CUDA versions), just keep one PATH, the torch finds the GPU.
