### ISSUE TITLE
 I can't extract RVC1006AMD_Intel.7z.

### ISSUE THREAD

**Issue by YoichiSa** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1826]
I am using a PC with the following specifications.
 AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz.
I downloaded the 7zip file from the following URL and tried to extract it with 7zip console, but I can't extract it, only some screen appears to open for a moment and then close immediately.
For AMD/Intel GPU users:.
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC1006AMD_Intel.7z

I tried from linux, not from powershell, but no luck. Do you know what the cause is?

**Comment by yxlllc** [comment]
Maybe your file is broken, try redownload it?
