### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by EbiDesa** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1828]
when training mode:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB (GPU 0; 4.00 GiB total capacity; 5.68 GiB already allocated; 0 bytes free; 5.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by SirBitesalot** [comment]
Lower Batchsize or buy GPU with more memory

**Comment by amink69** [comment]
i have GPU 3050 Ti and didn't use 1% of GPU memory
but show me same error with Insufficient memory (3GB)
how i can solve my problem ?
