### ISSUE TITLE
Windows: Failed to load audio: ffmpeg error

### ISSUE THREAD

**Issue by TadavomnisT** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1831]
Hi, despite doing all of the things mentioned in #659 , still facing the issue on windows:

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/63199745/4485d249-0603-4fa2-ae4b-e9ef0aca79bb)

The error occurs during the runtime:

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/63199745/6c0b11f7-145b-4a4a-968e-895777ab4b52)

______________

Ffmpeg is intalled alright:

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/63199745/f5ba1d05-08b7-4787-a959-7330a0016081)

______________

Any tips will be welcomed.

**Comment by Abedalhkeem-z** [comment]
Make sure to give the file path or every parameter is given. NoneType means that something is provided is None like there is no audio path which results to None value

**Comment by TadavomnisT** [comment]
@Abedalhkeem-z  Thanks.
