### ISSUE TITLE
"File Not Found" Error when try to process dataset to train new voice

### ISSUE THREAD

**Issue by brandonjhendrix** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1833]
When I made a new voice dataset and copy-paste the path name to RVC v2 and hit "process," I always get this error message:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Med/preprocess.log'

Putting no spaces in the voice dataset file name and experiment name did not fix this problem.

What do?

**Comment by Abedalhkeem-z** [comment]
Give the path of the folder where the trainingdata (audio) exists.  preprocess.log is a file where the ouput (text/logs) of preprocess step will be saved. You could maybe create this file if not exists.

**Comment by lolo9538** [comment]
Add a similar issue but in my case it was actually because ffmpeg was not installed, the error was confusing

winget install ffmpeg
 reload venv
