### ISSUE TITLE
Error creating Docker image in requirements.txt for praat-parselmouth and onnxruntime-gpu packages

### ISSUE THREAD

**Issue by ridleytech** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1839]
When running **docker build -t rt/voice-conversion-ui, I get these errors**  on a Mac with M1

**onnxruntime-gpu error:**

ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
#18 17.32 ERROR: No matching distribution found for onnxruntime-gpu

**praat-parselmouth error:**

Failed to build praat-parselmouth
#18 257.4 ERROR: Could not build wheels for praat-parselmouth, which is required to install pyproject.toml-based project

I also tried commenting them out in requirements.txt and adding them to the Dockerfile and got the same result.

RUN pip install praat-parselmouth
RUN pip3 install onnxruntime-gpu

How do I fix these errors?

**Comment by ouarrtaha** [comment]
same here

**Comment by ouarrtaha** [comment]
I fixed that by removing `onnxruntime-gpu; sys_platform != 'darwin'`from requirements.txt, 
and installing `libx11-dev`in dockerfile

```
...
# Install dependencies to add PPAs
RUN apt-get update && \
    apt-get install -y -qq ffmpeg aria2 libx11-dev && apt clean && \
    apt-get install -y software-properties-common && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
    ...
```
