### ISSUE TITLE
Mac M2 can not run the inference

### ISSUE THREAD

**Issue by XXXXRT666** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1843]
I have tried running both inference and batch inference, but it always stuck there, but I can run inference without using refer the index file
my python version is 3.9.12
PyTorch version is 2.3.0.dev20240222, it's a nightly build version, should I install the stable one?

**Comment by koosq** [comment]
I encountered the same problem as you. I noticed this error when running webUI. I don’t know if it is related.

`/Users/qrviom2/Retrieval-based-Voice-Conversion-WebUI1006/.venv/lib/python3.8/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
/Users/qrviom2/Retrieval-based-Voice-Conversion-WebUI1006/.venv/lib/python3.8/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")`

**Comment by FEXAQAQ** [comment]
> 我遇到了和你一樣的問題。我在運行 webUI 時注意到這個錯誤。不知道有沒有關係。
> 
> `/Users/qrviom2/Retrieval-based-Voice-Conversion-WebUI1006/.venv/lib/python3.8/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix' warnings.warn(f"Could not get documentation group for {cls}: {exc}") /Users/qrviom2/Retrieval-based-Voice-Conversion-WebUI1006/.venv/lib/python3.8/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix' warnings.warn(f"Could not get documentation group for {cls}: {exc}")`

I also encountered related problems, I don’t know if it will have any impact.  :(

**Comment by chenqan** [comment]
> > 我遇到了和你一样的问题。我在运行 webUI 时注意到这个错误。不知道有没有关系。
> > `/Users/qrviom2/Retrieval-based-Voice-Conversion-WebUI1006/.venv/lib/python3.8/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix' warnings.warn(f"Could not get documentation group for {cls}: {exc}") /Users/qrviom2/Retrieval-based-Voice-Conversion-WebUI1006/.venv/lib/python3.8/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix' warnings.warn(f"Could not get documentation group for {cls}: {exc}")`
> 
> 我也遇到了相关问题，不知道有没有影响。 :(

I also encountered the same problem as you，has it been resolved?

**Comment by FEXAQAQ** [comment]
> > > 我遇到了和你一样的问题。我在运行 webUI 时注意到这个错误。不知道有没有关系。
> > > `/Users/qrviom2/Retrieval-based-Voice-Conversion-WebUI1006/.venv/lib/python3.8/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix' warnings.warn(f"Could not get documentation group for {cls}: {exc}") /Users/qrviom2/Retrieval-based-Voice-Conversion-WebUI1006/.venv/lib/python3.8/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix' warnings.warn(f"Could not get documentation group for {cls}: {exc}")`
> > 
> > 
> > 我也遇到了相关问题，不知道有没有影响。 :(
> 
> I also encountered the same problem as you，has it been resolved?

I haven't found a solution yet, if I find one I will share it :)
I've been using it so far and the functions seem to be normal.

**Comment by Tps-F** [comment]
@XXXXRT666 Can you give me more details?

**Comment by XXXXRT666** [comment]
> @XXXXRT666 Can you give me more details?

Yes, of course. I run it on python 3.9(anaconda) and python3.11(3.11 requirements installed).
After I click the convert button, It does do the inference work, but no output.
<img width="1394" alt="截屏2024-05-02 15 40 04" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/157766680/7bd4953d-8ebb-40a2-9543-eefaaa2cfdca">
After clicking unload
<img width="1429" alt="截屏2024-05-02 15 45 38" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/157766680/86ec3e54-a91b-41ff-8c22-50ebbafac3d4">
I think it stuck at inference.
<img width="1249" alt="截屏2024-05-02 15 40 56" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/157766680/dc91532b-38b5-4db3-8fb3-6583d7004424">
using crepe, index

**Comment by XXXXRT666** [comment]
setting index ratio zero or just not using
<img width="1244" alt="截屏2024-05-02 15 49 25" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/157766680/d9905ada-62f9-4ed5-b156-f3d0dd2b5f66">
<img width="1237" alt="截屏2024-05-02 16 34 03" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/157766680/90e3b33b-03a1-4c2f-baca-52d8f79e281f">
Also, memory not released after unloading the model, I think it is related to PyTorch

the program stuck at `score, ix = index.search(npy, k=8)` (infer.modules.vc.pipeline.vc)

**Comment by XXXXRT666** [comment]
For training, `index.train(big_npy)` will lead to Segmentation fault

**Comment by XXXXRT666** [comment]
I've test the run.sh, the same result

**Comment by Tps-F** [comment]
@XXXXRT666 Thanks, I'll fix

Just to confirm, Does the inference work better if the index ratio is set to zero?

**Comment by XXXXRT666** [comment]
> @XXXXRT666 Thanks, I'll fix
> 
> 
> 
> Just to confirm, Does the inference work better if the index ratio is set to zero?

Yes, because [` if (... and index_rate != 0): `](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/infer/modules/vc/pipeline.py#L244) will skip index.search() if the index rate is zero.

**Comment by Tps-F** [comment]
@XXXXRT666 
In the meantime, I've fixed the problem of memory not being freed up. #2035

**Comment by XXXXRT666** [comment]
Thank you for your great efforts.

**Comment by dkenw** [comment]
fyi, `index.search` hangs because `faiss` is causing segfault when `pytorch` is imported. It's faiss's glitch. Faiss suggests macOS users to install via conda, which should in theory fix it.

for macOS users, you either:
- use conda for faiss instead of pip.
- build faiss from source yourself and install its python binding
- change the code to spawn a separate subprocess to use faiss

**Comment by XXXXRT666** [comment]
> fyi, `index.search` hangs because `faiss` is causing segfault when `pytorch` is imported. It's faiss's glitch. Faiss suggests macOS users to install via conda, which should in theory fix it.
> 
> for macOS users, you either:
> 
> * use conda for faiss instead of pip.
> * build faiss from source yourself and install its python binding
> * change the code to spawn a separate subprocess to use faiss

Thank you very much, this indeed worked.

**Comment by XXXXRT666** [comment]
> fyi, `index.search` hangs because `faiss` is causing segfault when `pytorch` is imported. It's faiss's glitch. Faiss suggests macOS users to install via conda, which should in theory fix it.
> 
> for macOS users, you either:
> 
> * use conda for faiss instead of pip.
> * build faiss from source yourself and install its python binding
> * change the code to spawn a separate subprocess to use faiss

@Tps-F

**Comment by x4080** [comment]
@XXXXRT666 How do you solve this problem ?

**Comment by XXXXRT666** [comment]
use conda to install， or install it from source code

**Comment by x4080** [comment]
@XXXXRT666 Thanks for the tip

**Comment by x4080** [comment]
Hi, I still cannot make it work using conda and pip, maybe I'm doing something wrong ? What I did was :
```
conda create -n env python=3.10
conda activate env
pip install -r requirements.txt
python ./infer-web.py
```

any help ? TIA

**Comment by x4080** [comment]
Ok I got it to work, here's the solution 
```
conda create -n env python=3.10
conda activate env
pip install -r requirements.txt
pip uninstall numba faiss-cpu 
conda install conda-forge::numba pytorch::faiss-cpu
python ./infer-web.py
```

**Comment by mushjacob** [comment]
Tried this, but still getting this error. Using M4 Mac with conda python3.10. Please help

`2025-02-22 16:12:57 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "/Users/mishaeljacob/Documents/RVC/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/modules.py", line 188, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "/Users/mishaeljacob/Documents/RVC/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/pipeline.py", line 375, in pipeline
    self.vc(
  File "/Users/mishaeljacob/Documents/RVC/Retrieval-based-Voice-Conversion-WebUI/infer/modules/vc/pipeline.py", line 219, in vc
    logits = model.extract_features(**inputs)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/fairseq/models/hubert/hubert.py", line 535, in extract_features
    res = self.forward(
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/fairseq/models/hubert/hubert.py", line 437, in forward
    features = self.forward_features(source)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/fairseq/models/hubert/hubert.py", line 392, in forward_features
    features = self.feature_extractor(source)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/fairseq/models/wav2vec/wav2vec2.py", line 895, in forward
    x = conv(x)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 375, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/anaconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 370, in _conv_forward
    return F.conv1d(
NotImplementedError: Output channels > 65536 not supported at the MPS device. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.`

**Comment by Hakanaou** [comment]
I'm in a similar case than @mushjacob, I have a Mac M4 Pro. I used classical installation, with Python 3.10 (but didn't use condo).

EDIT: In my case, the solution to force device to cpu worked. Just open the config.py file and replace on line 170

self.device = self.instead = "mps"

with

self.device = self.instead = "cpu"

It circumvents altogether Metal but at least it should work on the Apple Silicone devices.
