### ISSUE TITLE
你好，抖音上有人使用你们的软件进行售卖。

### ISSUE THREAD

**Issue by EightFennel** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1845]
具体商家ID：RyanAIGC
平台：易知课堂
课程名称：Bingo变声器（含虚拟形象）
售价：39.9rmb

**Comment by Yaodada12** [comment]
> 具体商家ID：RyanAIGC 平台：易知课堂 课程名称：Bingo变声器（含虚拟形象） 售价：39.9rmb

这合法吗，不会被起诉？

**Comment by yxlllc** [comment]
> > 具体商家ID：RyanAIGC 平台：易知课堂 课程名称：Bingo变声器（含虚拟形象） 售价：39.9rmb
> 
> 这合法吗，不会被起诉？
mit 是允许售卖软件的，不过必须包含版权声明和许可声明

**Comment by TangYB945** [comment]
> > 具体商家ID：RyanAIGC 平台：易知课堂 课程名称：Bingo变声器（含虚拟形象） 售价：39.9rmb
> 
> 这合法吗，不会被起诉吗？

我觉得你有点呆，你可以了解一下开源协议在做回复

**Comment by fumiama** [comment]
赚信息差罢了，没卖上千算良心的。
