### ISSUE TITLE
Averaging models

### ISSUE THREAD

**Issue by drfeinberg** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1846]
Hello,
Is it possible to average two or more trained models together? I can train a model that has 2 people in it, effectively doing the same thing, but I have already trained many voices and would like to average them together.  Is this possible?
Best,
David Feinberg

**Comment by Mojobones** [comment]
You can do this using Okada's voice changer. https://github.com/w-okada/voice-changer you can upload two .pth files, use the model merger to get a combined pth file, and then find it on your filesystem to use in other places. 

There might be a smoother way to do it, but it's been how I do it.

**Comment by drfeinberg** [comment]
Thanks!
