### ISSUE TITLE
拉取代码之后出现

### ISSUE THREAD

**Issue by ashoneyy** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1847]
![85C11AC901BB751955B2FEEE93BA7D6C](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/82497265/ee816aeb-95b4-4641-900e-069c8290fcb7)
 
之前启动是正常的, 拉取新代码之后出现如图错误，缺失的文件应该也都补上去了，请帮忙看一下如何解决，非常感谢

**Comment by RVC-Boss** [comment]
你上次的版本是哪天拉的代码包？哪个分支？

**Comment by RVC-Boss** [comment]
这个报错是索引和模型不同版本（v1混搭v2.），不支持，很可能不是版本原因
