### ISSUE TITLE
Submachine gun sound in the realtime conversion (gui_v1.py) in M1 system

### ISSUE THREAD

**Issue by breadjuice** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1848]
Does this mean that M1 cannot run this well?

**Comment by yxlllc** [comment]
It may be that the computing power is not enough. Try adjusting the performance parameters (increasing the delay) to see if it works properly.

**Comment by breadjuice** [comment]
And some parts of my sound are missing after converted, this doesn't improve even I improve the inference time.
<img width="1186" alt="image" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/30001126/d1c4878e-d0ca-4374-ba04-9375118f63dc">
Any suggestions?

**Comment by breadjuice** [comment]
> It may be that the computing power is not enough. Try adjusting the performance parameters (increasing the delay) to see if it works properly.

Thanks for your response!
I tried improve the inference time, there would be less submachine gun sound, but there's still a question that some parts of my sound are missing after converted, this doesn't improve after I improve the inference time. Do you have any other suggestions?
<img width="928" alt="image" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/30001126/51e3f1fd-48ac-4671-9a72-5d1d5b8faa22">
