### ISSUE TITLE
2333333 steps pth files issue

### ISSUE THREAD

**Issue by kalomaze** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#185]
There seems to be a bug where pth files will a lot of the times save with this number of steps in the filename, which can be confusing and misleading. For example, when I go back to train a model that was sitting at 800 epochs, it started from ~400 epochs, because there were older pth files with this 2333333 issue. I'm not sure what triggers it, because the other latest pths were in the folder, and deleting the 23333 pth files made it so I could resume training from ~800 epochs luckily, but it can be annoying

**Comment by fumiama** [comment]
The program will choose the biggest number of the .pth filename but not the real epoch count on resuming. We can find a way to fix it.
