### ISSUE TITLE
Could not build wheels for c104, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Temuulen-the-maker** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1857]
Hello everyone, I direly need to install this package. I see people solving 'building wheel' problem for other packages; I need it solved for c104 package.

The error message reads so:
---------------------------------------------------------------------------------------------------------------------------------------
Building wheels for collected packages: c104
  Building wheel for c104 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for c104 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [129 lines of output]
      running bdist_wheel
      running build
      running build_ext
      -- Building for: Visual Studio 17 2022
      -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
      -- The C compiler identification is MSVC 19.38.33130.0
      -- The CXX compiler identification is MSVC 19.38.33130.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - broken
      CMake Error at C:/Users/ext_tpurevdorj/AppData/Local/Temp/pip-build-env-y9g3y7oc/overlay/Lib/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

**and bunch directories printed ...... then it tells**

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for c104
Failed to build c104
ERROR: Could not build wheels for c104, which is required to install pyproject.toml-based projects
---------------------------------------------------------------------------------------------------------------------------------------

I updated pip, setuptools, wheel, and cmake with following command:
**python -m pip install --upgrade pip setuptools wheel cmake**

Please, people around the world, help me on this.

**Comment by yuyudingmi** [comment]
so am i

**Comment by RobertSvebeck** [comment]
I got this also, and the solution for me was to make sure Microsoft C++ Build Tools is correctly installed.

https://visualstudio.microsoft.com/visual-cpp-build-tools/

![Untitled](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/26415252/0e8a05d5-ee41-439c-b104-67d2beb871f5)
