### ISSUE TITLE
游戏内使用有问题

### ISSUE THREAD

**Issue by tomh500** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1858]
正常使用没问题，但是打开游戏，例如CS2 彩虹六号等，音频转换的输出就会一卡一卡的，或者一个字符卡很多次，不输出，游戏开窗口模式也是这样，，除非鼠标点击一下游戏外面，就算我给python在任务管理器设置实时优先级也不能在游戏内正常使用，操作系统是windows11 rtx4060laptop python3.10

**Comment by yxlllc** [comment]
可能是操作系统调度问题，不在焦点分配的硬件资源就减少了，试试设置进程优先级之类的操作

**Comment by singularity2000** [comment]
我也有同样的问题，想知道调整优先级有用吗
