### ISSUE TITLE
Better docs on api?

### ISSUE THREAD

**Issue by K0shachiyamyatA** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1884]
i didn't understand anything from those build into gradio.

**Comment by Kamikadashi** [comment]
For inference, use [1614](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/1614). The Gradio API is slow and broken.

**Comment by K0shachiyamyatA** [comment]
> For inference, use [1614](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/1614). The Gradio API is slow and broken.

Thx
