### ISSUE TITLE
.wav-contains nan

### ISSUE THREAD

**Issue by InkyKnight** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1885]
I'm trying to get this AI voice to work, but when I get to Feature Extraction it looks like it's going fine (at least as far as I can tell), then it starts spitting out a bunch of numbered wavs and telling me they contain nan.

Here's just a small sample:
76_1.wav-contains nan
78_1.wav-contains nan
79_1.wav-contains nan
79_2.wav-contains nan
81_1.wav-contains nan
81_2.wav-contains nan

If anyone knows what the problem is, please explain the solution like I'm an idiot, because when it comes to this, I am.

**Comment by max-fff** [comment]
Yoo, have you found a solution??
