### ISSUE TITLE
UPDATE Training TIPS

### ISSUE THREAD

**Issue by nadare881** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#189]
Now that the 0428 update has been applied, I will modify some of my training tips.

I aim to create the Japanese and English versions in April.

**Comment by fire** [comment]
Thanks. I think you mean May?

**Comment by nadare881** [comment]
I will create a draft this Saturday and Sunday. Reflection may be in May, but we will start as soon as possible.
