### ISSUE TITLE
why no 22k sampling rate model?  为什么没有22k采样率的模型？

### ISSUE THREAD

**Issue by igbeller** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1899]
any specific reason why the base model was trained for 32k, 40k, 48k, and not 22050 (22k) Hz? are there any downsides or limitations?
基础模型为什么是以32k、40k、48k进行训练，而不是22050（22k）Hz？有没有什么不足或限制？

22k might be easier to train and faster in inference or not?
可能使用22k的采样率会更容易进行训练，并且推理速度更快，是这样吗？

thank you kindly for your efforts!
谢谢你的友善

**Comment by igbeller** [comment]
additionally, for training a 22k model from scratch, what are good values for the config and how do you derive those?
另外，从头开始训练一个22k模型，对于配置来说有哪些好的数值，以及如何得出这些数值？


```py
  "data": {
    "max_wav_value": 32768.0,
    "sampling_rate": 32000,
    "filter_length": 1024,
    "hop_length": 320,
    "win_length": 1024,
    "n_mel_channels": 80,
    "mel_fmin": 0.0,
    "mel_fmax": null
  }
```
also `segment_size`
and these

```py
    "resblock_kernel_sizes": [3,7,11],
    "resblock_dilation_sizes": [[1,3,5], [1,3,5], [1,3,5]],
    "upsample_rates": [12,10,2,2],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [24,20,4,4],
```

**Comment by RVC-Boss** [comment]
不支持22.05k
