### ISSUE TITLE
双显卡rvc怎么选择用哪个显卡？

### ISSUE THREAD

**Issue by tanqhstudy** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1900]
我的电脑有两个显卡1和2，我怎么设置rvc在显卡2上运行？

**Comment by RVC-Boss** [comment]
训练根据卡号
推理在https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/configs/config.py#L46里面改
cuda:0是第一个卡，1是第二个卡，0和1代表啥不知道的话进训练界面有提示卡号和卡型号的对应关系。
