### ISSUE TITLE
Converted audio file using a custom trained model includes a lot of noise

### ISSUE THREAD

**Issue by ShreyasDan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1903]
I've trained a couple of models, one with V1 40KHz setting and the other with V2 48KHz setting. But when I use those models to convert a vocals file, the converted vocals file has a lot noise which sounds like distortion and sawtooth wave. What can I change in my training settings that can help me successfully train a model which converts the audio files without adding any noise?
Thanks in advance!

**Comment by mchao123** [comment]
Check the clip for other sounds and try to remove them

**Comment by ShreyasDan** [comment]
Which clip are you talking about? The vocals tracks that I used for training the model don't have any noise.
