### ISSUE TITLE
How to train a high-quality model

### ISSUE THREAD

**Issue by sunnyhui** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1904]
I am currently attempting to train a base model, but it is difficult to achieve a level of similarity comparable to that of existing open-source models. I was wondering if there are any specific techniques or strategies for effectively training a base model. I would greatly appreciate a detailed response.

**Comment by jupinter** [comment]
> I am currently attempting to train a base model, but it is difficult to achieve a level of similarity comparable to that of existing open-source models. I was wondering if there are any specific techniques or strategies for effectively training a base model. I would greatly appreciate a detailed response.

我最近也在做类似的事情，用现有的预训练模型在某些情况下存在发音异常，所以也希望重训一个更好的模型。但是训了一段时间之后效果仍不理想。
