### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by adadadada321321** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1906]
I am having raceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
PS C:\TCHT\Retrieval-based-Voice-Conversion-WebUI> error why that may possıble ?

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
