### ISSUE TITLE
No pretrain model specified

### ISSUE THREAD

**Issue by Lukysoon** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1908]
Hi, I'm wondering what if I fill blank string in the pretrain model field "Load pre-trained base model G path" and same for the D field "Load pre-trained base model D path". What happens? 

Does it use some pretrain model or not?

Thank you :-)

**Comment by Lukasis150** [comment]
I see in code that it copes this situation. For example it log it to the console on [this line](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/7728caad546c8d5dab17e724b41fbe9b28edaf30/infer-web.py#L552).

And there is also [if condition in train.py ](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/7728caad546c8d5dab17e724b41fbe9b28edaf30/infer/modules/train/train.py#L225)about whether the pretrained generator exists. 
But I don't see any "else" to cope situation when it doesn't exists.
