### ISSUE TITLE
Index file missing after training locally

### ISSUE THREAD

**Issue by BRLTS** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1911]
I've been completed training my model locally, but when I check the logs folder, I can't find the index file of the model.

![Amazon2 22_03_2024 23_32_03](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/85918402/17c4631b-27fc-43c0-adee-a251bf5b212b)
![C__WINDOWS_system32_cmd exe 22_03_2024 23_30_52](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/85918402/7a672539-0b4b-4cb2-9b98-09f6f2a6fd39)

Does anyone know where the index file saved after the training?

**Comment by james-bond-007** [comment]
一样的情况，没有ckpt文件，也没有index文件
