### ISSUE TITLE
Can I start training on one PC and then continue on another PC?

### ISSUE THREAD

**Issue by farcast3r** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1917]
I started training a new model with a target of 200 epochs and around 2-3 hours of audio files, and with 13 GPU cores I get around 4 epochs per day. I understand that this is very slow and it's advisable to use less audio referencing files but, for my purposes, it's very important to have a very high quality and accurate model.

I have a checkpoint for epoch 40 and I'm noticing the impact on my PC's performance while I'm working - would it be possible to transfer everything in the RVCBeta folder to another PC and resume training? 

If so, would I need to change any settings or pathnames etc. to match the initial settings? Or is it better to just start from scratch?

**Comment by Mojobones** [comment]
You can transfer stuff, yes. Just keep the file structure the same and it should pick back up on your most recent checkpoint. Also, ensure all your settings in the web UI are consistent with your first training (Ex. batch size, inference method, bitrate, so on)
