### ISSUE TITLE
总是显示这个呜呜呜呜呜

### ISSUE THREAD

**Issue by zhang3485977506** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1919]
![屏幕截图 2024-03-24 220903](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/109056799/3993af4e-b9e4-45d5-8419-8d4fb6ac911c)

**Comment by Tps-F** [comment]
Use it instead.

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/requirements-py311.txt
