### ISSUE TITLE
attributeerror: 'nonetype' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by nattyraz** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1920]
I am experiencing an issue with the Pinokio, specifically when using RVC installed within this environment. The main problem arises during the execution of audio processing tasks
Environment:

Operating System: Windows 10 (version 10.0.22631.3296)
Hardware: NVIDIA GeForce RTX 3090
Python Environment: Managed with Conda
Project: Pinokio, with RVC installed for audio processing

Issue Details:
While running an audio inference task through a Gradio interface in the Pinokio project, I encounter the following error:

csharp
Copy code
AttributeError: 'NoneType' object has no attribute 'tobytes'
This error seems to occur during a postprocessing step where the application attempts to convert audio data to bytes for further processing or output.

Steps to Reproduce:

Set up and activate the project environment.
Run the application/script that initiates the Gradio interface for audio processing.
Attempt to process an audio file, leading to the AttributeError mentioned above.
Expected Behavior:
The application should process the audio file without encountering an AttributeError, allowing for successful audio manipulation and display in the Gradio interface.

Actual Behavior:
An AttributeError occurs, indicating a failure in handling the audio data correctly, possibly due to the data being None or improperly loaded.

**Comment by ic1149** [comment]
1. Don't use conda, use python 3.8
2. Make sure ffmpeg and ffprobe is installed as mentioned in readme
