### ISSUE TITLE
嗷嗷，请教大佬们，RVC如何在CPU和内存上进行训练呢？

### ISSUE THREAD

**Issue by TechVillain** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1924]
大佬们，这个问题骚扰我好久了，嗷嗷！

我有一张Nvidia的显卡，但是只有2G的显存，理论上是不能用来训练的。

升级显卡也做不到，因为是笔记本电脑，显卡是锡焊在主板上的。

更换电脑也做不到，因为过去装了很多音乐制作的软件，都自定义配置好了，没办法重新安装。

使用Colab也做不到，因为Colab是基于Linux系统的，而我想在本地的Windows系统上进行训练，借此来学习RVC的运作。而且Colab最近在严打语音方面的DeepFake，甚至连相关的Gradio界面也会被封禁。

嗷嗷！

所以，我希望大佬们可以指点迷津，如何用CPU和内存来进行训练？

我知道会很慢，但是我只需要训练一个周杰伦的模型就够了，而且我可以在晚上睡觉的时候开机训练，训练几个星期都可以接受。

**我的系统是：**
Intel i7 4th Gen Quadcore CPU 
12GB RAM 
Windows 7 Professional 64 Bit
Nividia GeForce GTX 660M

请问是否在环境里安装一个CPU版本的PyTorch就足够了？

如果不安装directml相关的依赖，比如onnxruntime-directml之类的，RVC能不能用来训练呢？因为我的系统是Windows 7，无法安装DirectX 12，所以系统不支持directml。

嗷嗷，期待有大佬能够回复啊！

**Comment by beck-8** [comment]
又想马儿跑，又想马儿不吃草

**Comment by beck-8** [comment]
没有那能力，就不要学徐凤年一样什么都要

**Comment by XUANHLGG** [comment]
这这这...配置也太差了吧，建议花点钱去AutoDL租机子跑吧，挺便宜的，一个小时2.51元，200轮差不多一个多小时就完事了，推理的话如果显卡支持CUDA就可以在本地跑，去这个网页看看有没有你的显卡 https://www.nvidia.cn/geforce/technologies/cuda/supported-gpus/ 电脑可以装个双系统Windows10避免兼容性问题，硬盘没地方了可以用USB3.0的U盘制作WinToGo

**Comment by XUANHLGG** [comment]
这这这...配置也太差了吧，建议花点钱去 AutoDL 租机子跑吧，挺便宜的，一个小时 2.51 元，200 轮差不多一个多小时就完事了，推理的话，GTX 660M 支持 CUDA ，电脑可以装个双系统 Windows10 避免兼容性问题，硬盘没地方了可以用至少 USB 3.2 Gen 1 的 U 盘制作 Windows To Go
其实 2GB 显存训练也是可以的，显卡列表那里虽然不会显示但是其实是可以用的，我的 MX150 2GB 低压版就可以跑，但是非常慢罢了
