### ISSUE TITLE
The Train Section isn't generating the archive .pth to the weight

### ISSUE THREAD

**Issue by viktoryosef** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1926]
Hi There,
I made download and Model Inference works good, but The Train Section to clone my voice isn't generating the archive .pth to anyplace, RVC just generated a folder in logs folder with the .index archive, but the final archive .pth to use on Model Inference isn't working.
What Can I do to fix this issue? Can you help me?

**Comment by james-bond-007** [comment]
look for it in assets/weights, you will find it, named as what you Enter the experiment name. or you search experiment name.pth
在 assets/weights 目录下查找，你会找到它，它的名字就是您输入的实验名称。或者您搜索 实验名称.pth。

**Comment by parthdshah9** [comment]
There's no new .pth file generated under assets/weights or any sub folder of the root folder(RVC-beta).
