### ISSUE TITLE
Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by qwe1433223** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#193]
building 'fairseq.libbleu' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by Tps-F** [comment]
Please install Visual Studio and Microsoft C++ Build Tools

**Comment by CellerX** [comment]
> 请安装 Visual Studio 和 Microsoft C++ Build Tools

感谢。解决了，只用装Build Tools就行

**Comment by Zorbin** [comment]
请问怎么解决的

**Comment by Tps-F** [comment]
https://github.com/Tps-F/sd-webui-blip2#install-build-tools

Other repositories, but try this one

**Comment by Zorbin** [comment]
I've try it, stil not work

**Comment by Tps-F** [comment]
Can you elaborate on the error?

**Comment by Zorbin** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

**Comment by Tps-F** [comment]
https://developer.microsoft.com/ja-jp/windows/downloads/windows-sdk/

please download and run this

**Comment by Zorbin** [comment]
i've been download the microsoft tools from the official website. And it solved my problem.

**Comment by tcafranz** [comment]
I've done all of these answers and I still get the error
