### ISSUE TITLE
Add Support For Apple MLX Backend 

### ISSUE THREAD

**Issue by Acelogic** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1932]
Add Support For Apple MLX Backend for possible training implementation on Apple Silicon Devices

Code: https://github.com/ml-explore/mlx
Docs: https://ml-explore.github.io/mlx/build/html/index.html

**Comment by Excurl** [comment]
waiting for this..

**Comment by lextoumbourou** [comment]
If anyone is still interested, I'm working on this now. See https://github.com/lextoumbourou/mlx-rvc

**Comment by Acelogic** [comment]
https://github.com/Acelogic/Retrieval-based-Voice-Conversion-MLX 

Finished the implementation and got working on iOS and training

**Comment by lextoumbourou** [comment]
Awesome! Well done. I did a search for it but didn't find that repo.

**Comment by Acelogic** [comment]
Yeah, I got a few cleaning up to do on the repo, been working on the LTX-2 port as that's in high demand
