### ISSUE TITLE
Problem numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### ISSUE THREAD

**Issue by Madriix** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1938]
In the output of Vocal/accompaniment separation and reverb removal, I get this error:

> 2.wav.reformatted.wav->Traceback (most recent call last):
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\infer\modules\uvr5\modules.py", line 74, in uvr
>     pre_fun._path_audio_(
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\infer\modules\uvr5\vr.py", line 300, in _path_audio_
>     wav_instrument = spec_utils.cmb_spectrogram_to_wave(
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\infer\lib\uvr5_pack\lib_v5\spec_utils.py", line 397, in cmb_spectrogram_to_wave
>     spectrogram_to_wave(
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\infer\lib\uvr5_pack\lib_v5\spec_utils.py", line 295, in spectrogram_to_wave
>     wave_left = librosa.istft(spec_left, hop_length=hop_length)
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\runtime\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
>     return f(*args, **kwargs)
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\runtime\lib\site-packages\librosa\core\spectrum.py", line 394, in istft
>     dtype = util.dtype_c2r(stft_matrix.dtype)
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\runtime\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
>     return f(*args, **kwargs)
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\runtime\lib\site-packages\librosa\util\utils.py", line 2185, in dtype_c2r
>     np.dtype(complex): np.dtype(np.float).type,
>   File "C:\Users\Mcdo\AppData\Roaming\Python\Python38\site-packages\numpy\__init__.py", line 305, in __getattr__
>     raise AttributeError(__former_attrs__[attr])
> AttributeError: module 'numpy' has no attribute 'float'.
> `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\infer\modules\uvr5\modules.py", line 82, in uvr
>     pre_fun._path_audio_(
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\infer\modules\uvr5\vr.py", line 300, in _path_audio_
>     wav_instrument = spec_utils.cmb_spectrogram_to_wave(
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\infer\lib\uvr5_pack\lib_v5\spec_utils.py", line 397, in cmb_spectrogram_to_wave
>     spectrogram_to_wave(
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\infer\lib\uvr5_pack\lib_v5\spec_utils.py", line 295, in spectrogram_to_wave
>     wave_left = librosa.istft(spec_left, hop_length=hop_length)
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\runtime\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
>     return f(*args, **kwargs)
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\runtime\lib\site-packages\librosa\core\spectrum.py", line 394, in istft
>     dtype = util.dtype_c2r(stft_matrix.dtype)
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\runtime\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
>     return f(*args, **kwargs)
>   File "C:\Users\Mcdo\Desktop\Mangio\Retrieval-based-Voice-Conversion\runtime\lib\site-packages\librosa\util\utils.py", line 2185, in dtype_c2r
>     np.dtype(complex): np.dtype(np.float).type,
>   File "C:\Users\Mcdo\AppData\Roaming\Python\Python38\site-packages\numpy\__init__.py", line 305, in __getattr__
>     raise AttributeError(__former_attrs__[attr])
> AttributeError: module 'numpy' has no attribute 'float'.
> `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by Reviem0** [comment]
Found a fix for this.
You have to downgrade numpy to 1.23.5
You can open your venv and run this
```
pip install --upgrade numpy==1.23.5
```

**Comment by Madriix** [comment]
@Reviem0 ah yes thank you

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
