### ISSUE TITLE
ModuleNotFoundError: No module named 'infer.modules'

### ISSUE THREAD

**Issue by Lukww** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1943]
Does anyone know how to fix this?
I just installed with all of the pretrained models so I'm not sure what's happening.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/89819768/4c4f937b-9537-4ba2-b6ff-159a75b99014)

If anyone could help please tell me

**Comment by kronkinatorix** [comment]
I'm not sure why the dependencies with repo just hate to load. Like, the pathing is correct and _____?

Anyway. 

Opening up infer-web.py and slapping something like: 

sys.path.insert(2, '................/RVC-nvidia/assets/weights')
sys.path.insert(3, '............/RVC-nvidia/configs')
sys.path.insert(1, /.........../RVC-nvidia/venv/lib/python3.10/site-packages')
sys.path.insert(4, '/............../RVC-nvidia//tools/infer/lib/infer_pack/modules')
sys.path.append('/............./RVC-nvidia/tools/infer/lib/infer_pack/modules')

into it for whatever won't load may fix it. sys.path.append() will likely work but if it doesn't then you can' slap the path.insert on there to make sure it loads whatever problematic little fucker isn't loading first. 

so in your case try adding: sys.path.append("D:\Restrieval-based-Voice-Conversion-WebUI-main\Retrieval-based-Voice-Conversion-WebUI-main") to the top of your infer-web.py file  near where all the import statements are.

**Comment by Lukww** [comment]
I'm not sure if me adding that caused the error to change or if it was something else I did but i've started getting this error instead.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/89819768/085cac33-b908-463f-89e7-243b97a35f9b)

Hopefully its easier to fix

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
