### ISSUE TITLE
macOS / Web UI- ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by danielraban** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1944]
Hi I have followed the steps to run the GUI but face this error when running the command:

```
(.venv) (rvc) ➜  Retrieval-based-Voice-Conversion-WebUI git:(main) ✗ python infer-web.py

Traceback (most recent call last):
  File "/Users/danielraban/projects/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

<img width="1149" alt="Screenshot 2024-03-31 at 15 03 28" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/11539276/936da346-be2c-438d-ac69-4bdd39be5df2">

```
Chip: `Apple M2 Max`
macOS: `14.3.1 (23D60)`
Python Version: `Python 3.9.6`
```

Please let me know if anyone has a solution or has encountered this before. 

Thank you.

**Comment by Tps-F** [comment]
just install python-doetnv

**Comment by danielraban** [comment]
Was able to get the application running after manually running installs rather than `./run.sh`
