### ISSUE TITLE
GUI queue keep loading forever with no logs

### ISSUE THREAD

**Issue by shaungao94** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1951]
I can spin up the GUI and change settings but all the widgets and the main process freeze at the queue loading phase forever, the server running with no logs.

**Comment by shaungao94** [comment]
Reinstalled the entire package solved my issue

**Comment by Morrigan-Ship** [comment]
how you did it?
i have same problem from full package download from releases section last version

**Comment by korobak** [comment]
hey, i have the exact same issue, can you explain more about how you solved it ?
