### ISSUE TITLE
how do i change webui language?

### ISSUE THREAD

**Issue by thesbt** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1955]
im using Turkish Windows so my WebUI is also Turkish. How can i change WebUI language to English?

**Comment by 1iminal** [comment]
rename `tr_TR.json` in `/i18n/locale/` folder to something else (ex. `_tr_TR.json`), this will force the startup script to pick up the default en_US locale

**Comment by Tps-F** [comment]
hmm.I'll make it easy

**Comment by thesbt** [comment]
> rename `tr_TR.json` in `/i18n/locale/` folder to something else (ex. `_tr_TR.json`), this will force the startup script to pick up the default en_US locale

worked, thank you.
