### ISSUE TITLE
macOS M1 webUI一键训练时error

### ISSUE THREAD

**Issue by nawoobobo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1960]
File "/opt/anaconda3/envs/RVC/lib/python3.11/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

  File "/Users/rw/Downloads/RVC/infer/lib/audio.py", line 43, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "/Users/rw/Downloads/RVC/infer/modules/train/extract/extract_f0_rmvpe_dml.py", line 19, in <module>
    import torch_directml
ModuleNotFoundError: No module named ‘torch_directml'

  File "/Users/rw/Downloads/RVC/infer-web.py", line 756, in train1key
    click_train(
  File "/Users/rw/Downloads/RVC/infer-web.py", line 497, in click_train
    & set([name.split(".")[0] for name in os.listdir(f0nsf_dir)])
                                          ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rw/Downloads/RVC/logs/mi-test/2b-f0nsf’

上面是我出现的几个error message
已经尝试好几次重新安装ffmpeg，但没有效果；

我的硬件mac mini M1，内存8G，系统版本macOS 14.2
软件官网下载anaconda，RVC整合包(/Users/rw/Downloads/RVC)
训练集(/Users/rw/Downloads/mi-test)

There are error message.
I have tried to install ffmpeg, uninstall ffmpeg and install ffmpeg many times. However, it didn’t work.
Download anaconda from official website.

```
# 安装ffmpeg
cd Downloads
cd RVC
brew install ffmpeg

# 创建环境、安装依赖
conda create -n RVC python=3.11
conda activate RVC
pip3 install -r requirements.txt
pip3 uninstall torch torchaudio
pip3 install --pre torch torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

# 安装aria2
brew install aria2 

# 安装assets预模型
cd assets
pip3 install huggingface_hub
huggingface-cli download --resume-download lj1995/VoiceConversionWebUI/hubert --local-dir-use-symlinks False 
huggingface-cli download --resume-download lj1995/VoiceConversionWebUI/pretrained --local-dir-use-symlinks False 
huggingface-cli download --resume-download lj1995/VoiceConversionWebUI/uvr5_weights --local-dir-use-symlinks False 
huggingface-cli download --resume-download lj1995/VoiceConversionWebUI/pretrained_v2 --local-dir-use-symlinks False 

# 修复python 3.11 fairseq bug
pip install git+https://github.com/One-sixth/fairseq.git

# 执行webUI(使用python 3.11)
sh ./run.sh
```

**Comment by fumiama** [comment]
看报错
```
ModuleNotFoundError: No module named ‘torch_directml'
```
你代码调用了`dml`，但是`MacOS M1`无论如何用不到，所以考虑你下错了整合包。有能力的话建议直接使用`dev`版本。整合包都是给`Windows`用户准备的。

**Comment by nawoobobo** [comment]
发现是在我webUI界面选到gpu的模型所以报错，现在点rmvpe已解决
I found that I clicked on the gpu option  and it has been solved now.
