### ISSUE TITLE
运行go-realtime-gui后没有界面，一直显示is_half:True, device:cuda:0

### ISSUE THREAD

**Issue by yuanfeng-net** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1966]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/19276615/aa6ae7d7-24ae-4dc9-976f-b91c5e259d19)

**Comment by colasama** [comment]
可以试试这个 @
↓
> 如果是win11系统的话，试试把unicode utf-8打开，我通过这个办法解决了

_Originally posted by @butata-hg in https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1546#issuecomment-1858820000_
