### ISSUE TITLE
problem in installing requirements-dml.txt  

### ISSUE THREAD

**Issue by emai24volts** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1975]
I'm a newbie and don't really know how to use em sry...

when installing⬇️
ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9
ERROR: Could not find a version that satisfies the requirement onnxruntime-directml (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml

I use anaconda, my python version is 3.9.15
I tried changing my python version in to 3.8 and 3.10, but it'll just gone error like require other python version...

in Mac OS 14.4.1, intel

**Comment by ic1149** [comment]
Maybe try not to use anaconda, I couldn't get it working with RVC. Try using vanilla python. Anaconda has too many issues with RVC in my experience.

**Comment by fumiama** [comment]
The native `venv` can also be a good choice. See `./run.sh` for more information.
