### ISSUE TITLE
MacOS M1, use sh ./run.sh error(Mac m1 芯片运行报错)

### ISSUE THREAD

**Issue by Karos44** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1977]
The terminal give this back:
```
Traceback (most recent call last):
  File "infer-web.py", line 26, in <module>
    from fairseq import checkpoint_utils
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/__init__.py", line 40, in <module>
    import fairseq.scoring  # noqa
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/__init__.py", line 55, in <module>
    importlib.import_module("fairseq.scoring." + module)
  File "/opt/homebrew/Cellar/python@3.8/3.8.19/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/bleu.py", line 14, in <module>
    from fairseq.scoring.tokenizer import EvaluationTokenizer
  File "/opt/homebrew/lib/python3.8/site-packages/fairseq/scoring/tokenizer.py", line 8, in <module>
    import sacrebleu as sb
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/utils.py", line 595, in <module>
    from .dataset import DATASETS, SUBSETS, DOMAINS, COUNTRIES  # noqa: E402
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/dataset/__init__.py", line 28, in <module>
    from .wmt_xml import WMTXMLDataset
  File "/opt/homebrew/lib/python3.8/site-packages/sacrebleu/dataset/wmt_xml.py", line 3, in <module>
    import lxml.etree as ET
ImportError: dlopen(/opt/homebrew/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_exsltDateXpathCtxtRegister'

```
what should i do? There's the same error in [https://huggingface.co/lj1995/VoiceConversionWebUI/discussions/8](url) and nobody gave a response...(my english is poor sorry!)

**Comment by ic1149** [comment]
嘗試安裝 lxml 4.9.4
pip 例子: `pip install lxml=4.9.4`

**Comment by Karos44** [comment]
在這裡輸入要轉換的內容經過嚐試，我隻能安裝靜態版的lxml,即--no-binary :all: lxml，而安裝4.9.4會出現如下報錯(I can only install the static version of lxml, that is, --no-binary :all: lxml. When installing 4.9.4, the following error will appear)：`  Building wheel for lxml (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [175 lines of output]
      Building lxml version 4.9.4.
      /private/var/folders/09/h7bd7dl545qbt6y2ptvhfrl80000gn/T/pip-install-xgnnlqar/lxml_058ac3d303884762a14d652d1fb69351/setup.py:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Building without Cython.
      Building against libxml2 2.12.6 and libxslt 1.1.39
      Building against libxml2/libxslt in one of the following directories:
        /opt/homebrew/Cellar/libxml2/2.12.6/lib
        /opt/homebrew/Cellar/libxslt/1.1.39/lib
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14.2-arm64-cpython-39
      creating build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/_elementpath.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/sax.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/__init__.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/builder.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/doctestcompare.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/usedoctest.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/cssselect.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/ElementInclude.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      creating build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      creating build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/defs.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/clean.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/builder.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      copying src/lxml/html/diff.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/html
      creating build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/etree_api.h -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/lxml.etree.h -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/objectify.pyx -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/etree.pyx -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/public-api.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/xmlid.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/cleanup.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/xslt.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/xpath.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/debug.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/serializer.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/classlookup.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/saxparser.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/objectpath.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/relaxng.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/xinclude.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/iterparse.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/parser.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/dtd.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/apihelpers.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/xmlerror.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/readonlytree.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/extensions.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/xmlschema.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/schematron.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/docloader.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/nsclasses.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/parsertarget.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/xsltext.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/proxy.pxi -> build/lib.macosx-14.2-arm64-cpython-39/lxml
      copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/c14n.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/__init__.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.macosx-14.2-arm64-cpython-39/lxml/includes
      creating build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources
      creating build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/rng
      creating build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl
      creating build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-14.2-arm64-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.macosx-14.2-arm64-cpython-39
      creating build/temp.macosx-14.2-arm64-cpython-39/src
      creating build/temp.macosx-14.2-arm64-cpython-39/src/lxml
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/libxml2/include -I/usr/local/opt/libxslt/include -I/usr/local/opt/libxml2/include -I/usr/local/opt/libxslt/include -DCYTHON_CLINE_IN_TRACEBACK=0 -I/opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2 -I/opt/homebrew/Cellar/libxslt/1.1.39/include -Isrc -Isrc/lxml/includes -I/Users/eden/.pyenv/versions/3.9.2/include/python3.9 -c src/lxml/etree.c -o build/temp.macosx-14.2-arm64-cpython-39/src/lxml/etree.o -w -flat_namespace
      src/lxml/etree.c:113221:38: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
        __pyx_v_self->_c_ctxt->sax->serror = __pyx_f_4lxml_5etree__receiveParserError;
                                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:117709:25: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
          __pyx_v_sax->serror = __pyx_f_4lxml_5etree__receiveParserError;
                              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:181971:28: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
        __pyx_v_xpathCtxt->error = __pyx_f_4lxml_5etree__receiveXPathError;
                                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:219245:60: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
        xmlRelaxNGSetParserStructuredErrors(__pyx_v_parser_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2/libxml/relaxng.h:156:30: note: passing argument to parameter 'serror' here
                                               xmlStructuredErrorFunc serror,
                                                                      ^
      src/lxml/etree.c:219663:60: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
          xmlRelaxNGSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2/libxml/relaxng.h:185:31: note: passing argument to parameter 'serror' here
                                                xmlStructuredErrorFunc serror, void *ctx);
                                                                       ^
      src/lxml/etree.c:220552:59: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
        xmlSchemaSetParserStructuredErrors(__pyx_v_parser_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2/libxml/xmlschemas.h:156:30: note: passing argument to parameter 'serror' here
                                               xmlStructuredErrorFunc serror,
                                                                      ^
      src/lxml/etree.c:221095:59: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
          xmlSchemaSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2/libxml/xmlschemas.h:185:30: note: passing argument to parameter 'serror' here
                                               xmlStructuredErrorFunc serror,
                                                                      ^
      src/lxml/etree.c:221860:66: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
          xmlSchemaSetValidStructuredErrors(__pyx_v_self->_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_error_log));
                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2/libxml/xmlschemas.h:185:30: note: passing argument to parameter 'serror' here
                                               xmlStructuredErrorFunc serror,
                                                                      ^
      src/lxml/etree.c:223037:63: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
          xmlSchematronSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2/libxml/schematron.h:106:31: note: passing argument to parameter 'serror' here
                                                xmlStructuredErrorFunc serror,
                                                                       ^
      9 errors generated.
      Compile failed: command '/usr/bin/clang' failed with exit code 1
      creating var
      creating var/folders
      creating var/folders/09
      creating var/folders/09/h7bd7dl545qbt6y2ptvhfrl80000gn
      creating var/folders/09/h7bd7dl545qbt6y2ptvhfrl80000gn/T
      cc -I/opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2 -I/opt/homebrew/Cellar/libxslt/1.1.39/include -I/usr/include/libxml2 -c /var/folders/09/h7bd7dl545qbt6y2ptvhfrl80000gn/T/xmlXPathInit0phdx8ey.c -o var/folders/09/h7bd7dl545qbt6y2ptvhfrl80000gn/T/xmlXPathInit0phdx8ey.o
      /var/folders/09/h7bd7dl545qbt6y2ptvhfrl80000gn/T/xmlXPathInit0phdx8ey.c:3:5: warning: 'xmlXPathInit' is deprecated [-Wdeprecated-declarations]
          xmlXPathInit();
          ^
      /opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2/libxml/xpath.h:562:1: note: 'xmlXPathInit' has been explicitly marked deprecated here
      XML_DEPRECATED
      ^
      /opt/homebrew/Cellar/libxml2/2.12.6/include/libxml2/libxml/xmlversion.h:447:43: note: expanded from macro 'XML_DEPRECATED'
      #    define XML_DEPRECATED __attribute__((deprecated))
                                                ^
      1 warning generated.
      cc var/folders/09/h7bd7dl545qbt6y2ptvhfrl80000gn/T/xmlXPathInit0phdx8ey.o -L/opt/homebrew/Cellar/libxml2/2.12.6/lib -L/opt/homebrew/Cellar/libxslt/1.1.39/lib -lxml2 -o a.out
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
ERROR: Could not build wheels for lxml, which is required to install pyproject.toml-based projects
`

**Comment by Karos44** [comment]
It works! I opened the UI, but then it says "Unfortunately there is no compatible GPU available to support your training".I have no idea now... @oyouchano

**Comment by wastu01** [comment]
我有成功啟動訓練用介面，想請教 mac 如何開啟 go-realtime-gui.bat

**Comment by ic1149** [comment]
.bat 是 windows 用的
在 Mac/Linux 請使用 run.sh

**Comment by wastu01** [comment]
你好，我有成功執行 run.sh 有跑出訓練用的介面，但我想要使用的功能是 RVC 實時變聲，想請教如何開啟下列所述的介面？
https://youtu.be/fLMcu4n-Xl0?list=PLK7sA3zrSa4vOyDXdg05yhqDg-qd_LRPn&t=240

**Comment by wastu01** [comment]
我有查看 go-realtime-gui.bat 似乎是執行 `gui_v1.py`
接續手動執行 `python3 gui_v1.py`
爆錯訊息：
```
➜  Retrieval-based-Voice-Conversion-WebUI git:(main) python3 gui_v1.py 
Traceback (most recent call last):
  File "xx/Retrieval-based-Voice-Conversion-WebUI/gui_v1.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
➜  Retrieval-based-Voice-Conversion-WebUI git:(main) 
```

**Comment by wastu01** [comment]
OK 我成功啟動了該介面，另外安裝這兩個套件
➜  ~ pip install sounddevice
➜  ~ pip install FreeSimpleGUI 
<img width="794" alt="截圖 2024-05-01 凌晨12 26 46" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/47618277/06f52be8-f5aa-4442-90d3-0e59cdb2fd98">

**Comment by maxingan2412** [comment]
same error here, wish it can be solved, tyvm
