### ISSUE TITLE
how to open web-ui

### ISSUE THREAD

**Issue by yyfTrinity** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1979]
Why is there no local URL or public URL after starting the web, only a few links in the picture? 
How to open the webui?

thanks

![131u--070-kjnd1231](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/66110485/7f47938c-375e-4443-b0b7-c89cc36d6067)

**Comment by fumiama** [comment]
Currently colab notebook may not be able to use because goole's policy.
