### ISSUE TITLE
Gpu Not Found

### ISSUE THREAD

**Issue by Shqn3** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1980]
it says no gpu found when i do the python infer-web.py command tho i have a 4070 and it pops up in my device manager so idk

**Comment by sv3nk** [comment]
I have the same issue :(

**Comment by sv3nk** [comment]
It seems like torch.cuda does not recognize the gpu.
A simple 
`import torch
print(torch.cuda.device_count())`

returns 0.

**Comment by sv3nk** [comment]
I just figured it out. This is due to the wrong pytorch download. 
Use this: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
