### ISSUE TITLE
[Bug] python3 infer-web.py crashes on launch io.UnsupportedOperation: not readable

### ISSUE THREAD

**Issue by mr-segfault** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#199]
Using the current version of RVC (pulled moments prior to this bug report)

Cannot launch the infer-web.py program as seen below:

(Retrieval-based-Voice-Conversion-WebUI) user@machine:~/Retrieval-based-Voice-Conversion-WebUI$ python3 infer-web.py
Use Language: en_US
16系显卡强制单精度
Traceback (most recent call last):
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 82, in <module>
    config = Config()
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/config.py", line 22, in __init__
    self.x_pad, self.x_query, self.x_center, self.x_max = self.device_config()
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/config.py", line 66, in device_config
    strr = f.read().replace("true", "false")
io.UnsupportedOperation: not readable

**Comment by mr-segfault** [comment]
I'm able to check out a previous commit and launch, so something must be going on with the latest infer-web.py update

**Comment by Tps-F** [comment]
I found the cause. I'll fix it right away.

**Comment by mr-segfault** [comment]
Thank you kindly!
