### ISSUE TITLE
infer-web.py 获取显存失败

### ISSUE THREAD

**Issue by KOUymA** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#201]
![image](https://user-images.githubusercontent.com/72074577/235281992-be8ea748-0e5a-41c6-9df6-a3a5684bced1.png)
![image](https://user-images.githubusercontent.com/72074577/235282024-a4d20e23-bdf9-4b57-ba97-429010fe6198.png)
使用的是autodl 拉取最新的代码

**Comment by Tps-F** [comment]
Can you run this code and let us know the results?

```
import torch

gpu_mem = None

device = "cuda:0"
gpu_name = torch.cuda.get_device_name(int(device.split(":")[-1]))
i_device = int(device.split(":")[-1])

if (
    "16" in gpu_name
    or "P40" in gpu_name.upper()
    or "1070" in gpu_name
    or "1080" in gpu_name
):
    print("16系显卡强制单精度")
    gpu_mem = int(
        torch.cuda.get_device_properties(i_device).total_memory / 1024 / 1024 / 1024
        + 0.4
    )

print(gpu_mem)
print(type(gpu_mem))
```

**Comment by Tps-F** [comment]
I'll fix it now.

**Comment by KOUymA** [comment]
> Can you run this code and let us know the results?
> 
> ```
> import torch
> 
> gpu_mem = None
> 
> device = "cuda:0"
> gpu_name = torch.cuda.get_device_name(int(device.split(":")[-1]))
> i_device = int(device.split(":")[-1])
> 
> if (
>     "16" in gpu_name
>     or "P40" in gpu_name.upper()
>     or "1070" in gpu_name
>     or "1080" in gpu_name
> ):
>     print("16系显卡强制单精度")
>     gpu_mem = int(
>         torch.cuda.get_device_properties(i_device).total_memory / 1024 / 1024 / 1024
>         + 0.4
>     )
> 
> print(gpu_mem)
> print(type(gpu_mem))
> ```

![image](https://user-images.githubusercontent.com/72074577/235282345-eb56cb04-712a-4da6-b541-504fcc0122a9.png)
这是结果

**Comment by Tps-F** [comment]
Thank you!
