### ISSUE TITLE
Crepe support for F0 extraction in training and inference.

### ISSUE THREAD

**Issue by Mixomo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#202]
For the new version: Crepe support for F0 extraction in training and inference.

Thank you

**Comment by RVC-Boss** [comment]
ok. Next version

**Comment by tomakorea** [comment]
That's a very good idea !

**Comment by GreatestOfAllTimee** [comment]
any update on this features?

**Comment by RVC-Boss** [comment]
> any update on this features?

Inference supported now.

**Comment by GreatestOfAllTimee** [comment]
> Inference supported now.

Great and Thanks! I trained my model using Harvest, did it take effect if I only using Crepe on inference? And future plan to add Crepe on train?
