### ISSUE TITLE
训练速度异常缓慢

### ISSUE THREAD

**Issue by bby-tree** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2020]
跑一个epoch需要大概3分钟，看了同性能的显卡发现只需要不到一分钟
并且第一个epoch需要大约20分钟
观察实验文件夹后发现在第一个epoch的时候，一直在./0_gt_wavs文件夹下生成*.pt文件
不知道是否与我修改infer_web.py中代码使其能用amd显卡进行音高提取有关
修改后代码片段如下
`
if torch.cuda.is_available() or ngpu != 0:
    for i in range(ngpu):
        gpu_name = torch.cuda.get_device_name(i)
        if any(
            value in gpu_name.upper()
            for value in [
                "10",
                "16",
                "20",
                "30",
                "40",
                "A2",
                "A3",
                "A4",
                "P4",
                "A50",
                "500",
                "A60",
                "70",
                "80",
                "90",
                "M4",
                "T4",
                "TITAN",
                "4060",
                "L",
                "6000",
                "6600"#使amd显卡能够被正常识别
            ]
        ):
`
请问如何解决这个问题

- 系统环境：
- OS： Arch Linux x86_64
- Kernel：6.8.7-arch1-1 
- GPU：GPU: AMD ATI Radeon RX 6600/6600 XT/6600M
- Python版本：Python 3.8.19
- torch版本：'2.1.1+rocm5.6'

**Comment by Tps-F** [comment]
Check #2024
