### ISSUE TITLE
Slow processing in ROCm

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2024]
I am not sure if this is the problem, but I will report it in due course.
The process of using rmvpe.pt is very slow, it takes 4 minutes (First run took 8 minutes) on the RX6600 while it takes about 1 minute on the GTX1650.
Please let me know if there is any information you need. I will report anything.
Time:
npy: 1.46s, f0: 83.20s, infer: 136.64s.

Kubuntu 22.04
Kernel 6.5.0.28
Ryzen 5 5500
DDR4 3733 32GB
rx6600 8GB
ROCm 6.0.2

**Comment by GUUser91** [comment]
I used to have slow processing too on my 7900 xtx. This is how I fixed it. I'm not sure this solution will work for you though. I disable the igpu in the bios. I put in export MIOPEN_FIND_MODE=2 and export HSA_OVERRIDE_GFX_VERSION=11.0.0 in the bashrc file. Then I install the stable build of pytorch.
>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.7

There is also a stable build of rocm 6.0. I haven't tried that one though.
>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.0

**Comment by Bocchi-Chan2023** [comment]
> I used to have slow processing too on my 7900 xtx. This is how I fixed it. I'm not sure this solution will work for you though. I disable the igpu in the bios. I put in export MIOPEN_FIND_MODE=2 and export HSA_OVERRIDE_GFX_VERSION=11.0.0 in the bashrc file. Then I install the stable build of pytorch.
> 
> > pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.7
> 
> There is also a stable build of rocm 6.0. This one also produces fast Inference.
> 
> > pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.0

Sorry for the late update, but that method doesn't seem to work.

**Comment by Bocchi-Chan2023** [comment]
Somehow, the GPU utilization seems to be hovering around 50% and not running at full speed
