### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by Drivetheblue** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2028]
The automatically calculated log interval is known to be very inaccurate and can cause delays between an epoch finishing and Tensorboard writes. If you would like, you can manually define a log interval here.

AssertionError                            Traceback (most recent call last)
[<ipython-input-14-45317fb71b81>](https://localhost:8080/#) in <cell line: 9>()
      7 
      8 
----> 9 assert 'pretrain_type' in locals(), "Hold up, you need to download a pretrain! Please run the \"Download Pretrained Model\" cell before continuing."
     10 
     11 

AssertionError: Hold up, you need to download a pretrain! Please run the "Download Pretrained Model" cell before continuing.

**Comment by Tps-F** [comment]
Please download pretrained model first
