### ISSUE TITLE
继续训练时速度会变慢

### ISSUE THREAD

**Issue by revaraver** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2032]
这两天反复测试发现在继续之前的模型训练时，速度会奇慢无比
继续训练指的是在之前训练的基础上，在web界面的训练下填写之前训练过的模型名称，参数与之前保持相同，的情况下点击训练/一键训练
我的首次训练基本上都是半分钟左右一epoch，但是在二次训练时都会变成3分钟以上才能完成1epoch
想知道是否有其他人有跟我相似的情况

其他补充说明：我测试过多种batch_size，都会出现二次训练时速度减慢的情况。并且我的配置json文件中的16精度选项是打开着的

**Comment by revaraver** [comment]
进一步测试后发现重启机器之后速度会变快。后续我会继续测试是否有在不重启情况下释放显卡负载的方法

**Comment by revaraver** [comment]
进一步测试后发现重启机器之后速度会恢复，变快。后续我会继续测试是否有在不重启情况下释放显卡负载的方法

**Comment by markgao-916** [comment]
训练一个epoch大概需要多长时间呢？
