### ISSUE TITLE
No proper pth file output

### ISSUE THREAD

**Issue by Ttwing9999** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2064]
[train.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/15359118/train.log)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/140862247/e36b7072-6645-4da6-a188-24374df668d2)
[preprocess.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/15359122/preprocess.log)
[extract_f0_feature.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/15359125/extract_f0_feature.log)
No proper output, index is created but no pth

**Comment by parthdshah9** [comment]
@Ttwing9999 how did you get it working?
