### ISSUE TITLE
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at the same time

### ISSUE THREAD

**Issue by Amazon90** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2072]
環境設定：
Windows 11 專業版 23H2 22631.3593
NVIDIA GeForce RTX4070 Ti 32.0.15.5585
git 2.45.1
python 3.10.11
ffmpeg 2024-05-23-git-ece95dc3dc
```
(runtime) D:\Git\Retrieval-based-Voice-Conversion-WebUI>pip list
Package                   Version
------------------------- ------------
absl-py                   2.1.0
aiofiles                  23.2.1
altair                    5.3.0
annotated-types           0.7.0
antlr4-python3-runtime    4.8
anyio                     4.3.0
attrs                     23.2.0
audioread                 3.0.1
av                        12.0.0
bitarray                  2.9.2
certifi                   2022.12.7
cffi                      1.16.0
charset-normalizer        2.1.1
click                     8.1.7
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.2.1
cycler                    0.12.1
Cython                    3.0.10
decorator                 5.1.1
dnspython                 2.6.1
einops                    0.8.0
email_validator           2.1.1
exceptiongroup            1.2.1
fairseq                   0.12.2
faiss-cpu                 1.8.0
fastapi                   0.111.0
fastapi-cli               0.0.4
ffmpeg-python             0.2.0
ffmpy                     0.3.1
filelock                  3.13.1
flatbuffers               24.3.25
fonttools                 4.51.0
fsspec                    2024.5.0
future                    1.0.0
gradio                    4.29.0
gradio_client             0.16.1
grpcio                    1.64.0
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.1
humanfriendly             10.0
hydra-core                1.0.7
idna                      3.4
importlib_resources       6.4.0
Jinja2                    3.1.3
joblib                    1.4.2
json5                     0.9.25
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
librosa                   0.9.1
llvmlite                  0.42.0
local-attention           1.9.1
lxml                      5.2.2
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
mpmath                    1.3.0
networkx                  3.2.1
numba                     0.59.1
numpy                     1.23.5
omegaconf                 2.0.5
onnxruntime-gpu           1.18.0
orjson                    3.10.3
packaging                 24.0
pandas                    2.2.2
pillow                    10.2.0
pip                       24.0
platformdirs              4.2.2
pooch                     1.8.1
portalocker               2.8.2
praat-parselmouth         0.4.3
protobuf                  5.27.0
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pycparser                 2.22
pydantic                  2.7.1
pydantic_core             2.18.2
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
pyreadline3               3.4.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
pywin32                   306
pyworld                   0.3.2
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.2
resampy                   0.4.3
rich                      13.7.1
rpds-py                   0.18.1
ruff                      0.4.5
sacrebleu                 2.4.2
scikit-learn              1.5.0
scipy                     1.13.1
semantic-version          2.10.0
setuptools                65.5.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
soundfile                 0.12.1
starlette                 0.37.2
sympy                     1.12
tabulate                  0.9.0
tensorboard               2.16.2
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
threadpoolctl             3.5.0
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.0.1+cu117
torchaudio                2.0.2+cu117
torchcrepe                0.0.20
torchfcpe                 0.0.4
torchvision               0.15.2+cu117
tornado                   6.4
tqdm                      4.66.4
traitlets                 5.14.3
typer                     0.12.3
typing_extensions         4.9.0
tzdata                    2024.1
uc-micro-py               1.0.3
ujson                     5.10.0
urllib3                   2.2.1
uvicorn                   0.29.0
watchfiles                0.21.0
websockets                11.0.3
Werkzeug                  3.0.3
```
錯誤復現：
1.git clone https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git
2.cd Retrieval-based-Voice-Conversion-WebUI
3.python -m venv runtime
4.runtime\Scripts\activate
5.pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
6.pip install -r requirements.txt
7.ffmpeg.exe和ffprobe.exe置於路徑D:\Git\Retrieval-based-Voice-Conversion-WebUI\
8."D:\Git\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\gradio\component_meta.py"檔案中，
所有read_text()取代為read_text(encoding='utf-8')
9.python infer-web.py --update

錯誤訊息如下：
```
(runtime) D:\Git\Retrieval-based-Voice-Conversion-WebUI>python infer-web.py --update
D:\Git\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\threadpoolctl.py:1214: RuntimeWarning:
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
2024-05-24 18:34:42 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 4070 Ti
2024-05-24 18:34:42 | INFO | configs.config | Half-precision floating-point: True, device: cuda:0
2024-05-24 18:34:44 | INFO | infer.lib.rvcmd | checking hubret & rmvpe...
2024-05-24 18:34:44 | INFO | infer.lib.rvcmd | checking pretrained models...
2024-05-24 18:34:45 | INFO | infer.lib.rvcmd | checking pretrained models v2...
2024-05-24 18:34:46 | INFO | infer.lib.rvcmd | checking uvr5_weights...
2024-05-24 18:34:47 | INFO | infer.lib.rvcmd | all assets are already latest.
2024-05-24 18:34:47 | INFO | __main__ | Use Language: zh_TW

```

**Comment by Amazon90** [comment]
go-web.bat

`D:\Git\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\threadpoolctl.py:1214: RuntimeWarning:
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
2024-05-24 17:04:45 | INFO | configs.config | Found GPU NVIDIA GeForce RTX 4070 Ti
2024-05-24 17:04:45 | INFO | configs.config | Half-precision floating-point: True, device: cuda:0
2024-05-24 17:04:47 | INFO | __main__ | Use Language: zh_TW
2024-05-24 17:04:47 | ERROR | __main__ | Cannot find empty port in range: 7897-7897. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
請按任意鍵繼續 . . .`

**Comment by Amazon90** [comment]
go-realtime-gui.bat

`Traceback (most recent call last):
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\gui_v1.py", line 85, in <module>
    import FreeSimpleGUI as sg
ModuleNotFoundError: No module named 'FreeSimpleGUI'
請按任意鍵繼續 . . .
`

**Comment by fumiama** [comment]
> ... this can cause random crashes or deadlocks on `Linux` when loaded in the
> same Python program.

Linux下有问题，Windows下可忽略此提示。

> Cannot find empty port in range: 7897-7897

端口被占用，更换端口号后重新启动。（即`--port 1234`）

> ModuleNotFoundError: No module named 'FreeSimpleGUI'

对于`gui`，还需安装`requirements-win-for-realtime_vc_gui.txt`

**Comment by Amazon90** [comment]
> > ...這可能會導致在同一個 Python 程式中載入時隨機崩潰或死鎖。`Linux`
> 
> Linux下有問題，Windows下可忽略此提示。
> 
> > 在範圍內找不到空埠：7897-7897
> 
> 埠被佔用，更換埠號后重新啟動。（即）`--port 1234`
> 
> > ModuleNotFoundError：沒有名為“FreeSimpleGUI”的模組
> 
> 對於，還需安裝`gui``requirements-win-for-realtime_vc_gui.txt`

透過安裝pip install -r requirements-win-for-realtime_vc_gui.txt，go-realtime-gui.bat執行檔已可用，但界面繁體中文化支援不完善，請下見圖：
![RVCGUI](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/72290820/efac95e8-6ad9-4f43-98f2-2e9c3e7b6125)

**Comment by Amazon90** [comment]
> > > ...這可能會導致在同一個 Python 程式中載入時隨機崩潰或死鎖。`Linux`
> > 
> > 
> > Linux下有問題，Windows下可忽略此提示。
> > > 在範圍內找不到空埠：7897-7897
> > 
> > 
> > 埠被佔用，更換埠號后重新啟動。（即）`--port 1234`
> > > ModuleNotFoundError：沒有名為“FreeSimpleGUI”的模組
> > 
> > 
> > 對於，還需安裝`` gui``requirements-win-for-realtime_vc_gui.txt ``
> 
> 透過安裝pip install -r requirements-win-for-realtime_vc_gui.txt， go-realtime-gui.bat執行檔已可用， 但介面繁體中文化支援不完善，請下見圖： ![RVCGUI](https://private-user-images.githubusercontent.com/72290820/333860541-efac95e8-6ad9-4f43-98f2-2e9c3e7b6125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTAzNDcsIm5iZiI6MTcxNjcxMDA0NywicGF0aCI6Ii83MjI5MDgyMC8zMzM4NjA1NDEtZWZhYzk1ZTgtNmFkOS00ZjQzLTk4ZjItMmU5YzNlN2I2MTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA3NTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2OWUxNmU1OTgyOTQ5OTdkOTZiNzdkMDBiZmEwNzFlZTg3M2UyYzJmMTgyMDdjY2U4NzZmNmMxNWFkNGYwYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BmzPKoC6F1OXw00My_0DKu6TwyVsGlK0fsIPYCB6slk)

去掉對埠號的指定，修改go-web.bat檔為以下内容後問題已解決。
```
@echo off
call runtime\Scripts\activate
python infer-web.py --pycmd runtime\python.exe --nocheck
pause
```

**Comment by Amazon90** [comment]
> > ...這可能會導致在同一個 Python 程式中載入時隨機崩潰或死鎖。`Linux`
> 
> Linux下有問題，Windows下可忽略此提示。
> 
> > 在範圍內找不到空埠：7897-7897
> 
> 埠被佔用，更換埠號后重新啟動。（即）`--port 1234`
> 
> > ModuleNotFoundError：沒有名為“FreeSimpleGUI”的模組
> 
> 對於，還需安裝`gui``requirements-win-for-realtime_vc_gui.txt`

去掉對埠號的指定，修改go-web.bat檔為以下内容後問題已解決。
```
@echo off
call runtime\Scripts\activate
python infer-web.py --pycmd runtime\python.exe --nocheck
pause
```

**Comment by Amazon90** [comment]
> > ...這可能會導致在同一個 Python 程式中載入時隨機崩潰或死鎖。`Linux`
> 
> Linux下有問題，Windows下可忽略此提示。
> 
> > 在範圍內找不到空埠：7897-7897
> 
> 埠被佔用，更換埠號后重新啟動。（即）`--port 1234`
> 
> > ModuleNotFoundError：沒有名為“FreeSimpleGUI”的模組
> 
> 對於，還需安裝`gui``requirements-win-for-realtime_vc_gui.txt`

以下警告事項僅在linux下會發生程式崩潰，在windows下可忽視，那麽請教windows下如何將之從命令提示符中隱藏？
```
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
```

**Comment by fumiama** [comment]
> > > ...這可能會導致在同一個 Python 程式中載入時隨機崩潰或死鎖。`Linux`
> 
> > 
> 
> > Linux下有問題，Windows下可忽略此提示。
> 
> > 
> 
> > > 在範圍內找不到空埠：7897-7897
> 
> > 
> 
> > 埠被佔用，更換埠號后重新啟動。（即）`--port 1234`
> 
> > 
> 
> > > ModuleNotFoundError：沒有名為“FreeSimpleGUI”的模組
> 
> > 
> 
> > 對於，還需安裝`gui``requirements-win-for-realtime_vc_gui.txt`
> 
> 
> 
> 以下警告事項僅在linux下會發生程式崩潰，在windows下可忽視，那麽請教windows下如何將之從命令提示符中隱藏？
> 
> ```
> 
> Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
> 
> the same time. Both libraries are known to be incompatible and this
> 
> can cause random crashes or deadlocks on Linux when loaded in the
> 
> same Python program.
> 
> Using threadpoolctl may cause crashes or deadlocks. For more
> 
> information and possible workarounds, please see
> 
>     https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md
> 
> 
> 
>   warnings.warn(msg, RuntimeWarning)
> 
> ```

这个报错源自threadpoolctl这个包，这个包应该只在dml环境有用，正常使用是用不上的，你把它uninstall应该就可以了。

**Comment by fumiama** [comment]
> > > ...這可能會導致在同一個 Python 程式中載入時隨機崩潰或死鎖。`Linux`
> 
> > 
> 
> > Linux下有問題，Windows下可忽略此提示。
> 
> > 
> 
> > > 在範圍內找不到空埠：7897-7897
> 
> > 
> 
> > 埠被佔用，更換埠號后重新啟動。（即）`--port 1234`
> 
> > 
> 
> > > ModuleNotFoundError：沒有名為“FreeSimpleGUI”的模組
> 
> > 
> 
> > 對於，還需安裝`gui``requirements-win-for-realtime_vc_gui.txt`
> 
> 
> 
> 透過安裝pip install -r requirements-win-for-realtime_vc_gui.txt，
> 
> go-realtime-gui.bat執行檔已可用，
> 
> 但介面繁體中文化支援不完善，請下見圖：
> 
> ![RVCGUI](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/72290820/efac95e8-6ad9-4f43-98f2-2e9c3e7b6125)
> 
> 

你可以完善繁体中文翻译并提交PR。翻译位于i18n目录下的对应json文件。

**Comment by Amazon90** [comment]
THANKS!!

**Comment by Amazon90** [comment]
> > > > ...這可能會導致在同一個 Python 程式中載入時隨機崩潰或死鎖。`Linux`
> > 
> > 
> > > 
> > 
> > 
> > > Linux下有問題，Windows下可忽略此提示。
> > 
> > 
> > > 
> > 
> > 
> > > > 在範圍內找不到空埠：7897-7897
> > 
> > 
> > > 
> > 
> > 
> > > 埠被佔用，更換埠號后重新啟動。（即）`--port 1234`
> > 
> > 
> > > 
> > 
> > 
> > > > ModuleNotFoundError：沒有名為“FreeSimpleGUI”的模組
> > 
> > 
> > > 
> > 
> > 
> > > 對於，還需安裝`` gui``requirements-win-for-realtime_vc_gui.txt ``
> > 
> > 
> > 以下警告事項僅在linux下會發生程式崩潰，在windows下可忽視，那麽請教windows下如何將之從命令提示符中隱藏？
> > ```
> > 
> > Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
> > 
> > the same time. Both libraries are known to be incompatible and this
> > 
> > can cause random crashes or deadlocks on Linux when loaded in the
> > 
> > same Python program.
> > 
> > Using threadpoolctl may cause crashes or deadlocks. For more
> > 
> > information and possible workarounds, please see
> > 
> >     https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md
> > 
> > 
> > 
> >   warnings.warn(msg, RuntimeWarning)
> > ```
> 
> 这个报错源自threadpoolctl这个包，这个包应该只在dml环境有用，正常使用是用不上的，你把它uninstall应该就可以了。

threadpoolctl不可以uninstall，會出現以下錯誤訊息：
```
Traceback (most recent call last):
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 9, in <module>
    from infer.modules.vc.modules import VC
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\modules.py", line 18, in <module>
    from infer.modules.vc.pipeline import Pipeline
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\infer\modules\vc\pipeline.py", line 12, in <module>
    import librosa
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import decompose
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\librosa\decompose.py", line 19, in <module>
    import sklearn.decomposition
  File "D:\Git\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\sklearn\__init__.py", line 83, in <module>
    from threadpoolctl import ThreadpoolController
ModuleNotFoundError: No module named 'threadpoolctl'
請按任意鍵繼續 . . .
```
既如此不去管它就好，再次感謝您的解答！

**Comment by fumiama** [comment]
我印象中这个包并不是必须的，@yxlllc 可以看看。

**Comment by Amazon90** [comment]
> > > > ...這可能會導致在同一個 Python 程式中載入時隨機崩潰或死鎖。`Linux`
> > 
> > 
> > > 
> > 
> > 
> > > Linux下有問題，Windows下可忽略此提示。
> > 
> > 
> > > 
> > 
> > 
> > > > 在範圍內找不到空埠：7897-7897
> > 
> > 
> > > 
> > 
> > 
> > > 埠被佔用，更換埠號后重新啟動。（即）`--port 1234`
> > 
> > 
> > > 
> > 
> > 
> > > > ModuleNotFoundError：沒有名為“FreeSimpleGUI”的模組
> > 
> > 
> > > 
> > 
> > 
> > > 對於，還需安裝`` gui``requirements-win-for-realtime_vc_gui.txt ``
> > 
> > 
> > 透過安裝pip install -r requirements-win-for-realtime_vc_gui.txt，
> > go-realtime-gui.bat執行檔已可用，
> > 但介面繁體中文化支援不完善，請下見圖：
> > ![RVCGUI](https://private-user-images.githubusercontent.com/72290820/333860541-efac95e8-6ad9-4f43-98f2-2e9c3e7b6125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTkyNjMsIm5iZiI6MTcxNjcxODk2MywicGF0aCI6Ii83MjI5MDgyMC8zMzM4NjA1NDEtZWZhYzk1ZTgtNmFkOS00ZjQzLTk4ZjItMmU5YzNlN2I2MTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEwMjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYmVmYTYxOTQ2NDJiYjdlODA2N2YzZmFlYTViOWU5ZTcwNzAyZmFjODQxMjEyZGE4ZmQxMjU2ZjZmNjE4YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RFtj5GTjzPI1JOCT9xcYKducZ91eBQabqQ-DXdvY7LY)
> 
> 你可以完善繁体中文翻译并提交PR。翻译位于i18n目录下的对应json文件。

我修改了該路徑下的檔案，但我并不會提交pr，抱歉。
[zh_TW.json](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/15447078/zh_TW.json)

**Comment by fumiama** [comment]
> 我修改了該路徑下的檔案，但還沒有學會如何提交pr，抱歉。

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/41315874/127e87bc-cadb-47e2-a8d1-c3c1fd862012)

文件上有一个“笔🖊”的图标，点击之后按提示更改，最后open pull request即可。

**Comment by Amazon90** [comment]
> > 我修改了該路徑下的檔案，但還沒有學會如何提交pr，抱歉。
> 
> 
> 
> ![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/41315874/127e87bc-cadb-47e2-a8d1-c3c1fd862012)
> 
> 
> 
> 文件上有一个“笔🖊”的图标，点击之后按提示更改，最后open pull request即可。

謝謝😊，明天我試看看。
