### ISSUE TITLE
RVC uses Hubert or Contentvec?

### ISSUE THREAD

**Issue by blaise-tk** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2078]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/133521603/3010e1ad-b950-4e3f-9174-93d4ce54f729)

> https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/hubert_base.pt?download=true

but then...
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/133521603/009471cf-b5b3-4848-b8e1-3c5e773a9791)

---

my doubt arises because using the hubert downloaded from facebook, the hubert base, the results are strange, but using the original contentvec there is no problem even though in theory we use “hubert base”

I know that contentvec has a similar structure to hubert, but I would like to know which weights we are using, the facebook one or the contentvec one

thanks 💗

@RVC-Boss

**Comment by RVC-Boss** [comment]
cvec
