### ISSUE TITLE
Can someone explain how to add model?

### ISSUE THREAD

**Issue by lioriky6** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#211]
I downloaded this locally and followed all the steps but I don't have any models.
Let's assume I download a zip file of a vocal, what am I supposed to do to add the model?

Thanks.

**Comment by fumiama** [comment]
add xxx.pth to weights folder and place xxx.index/xxx.npy to wherever you know and refer them in the infer page.

**Comment by lioriky6** [comment]
What i

> add xxx.pth to weights folder and place xxx.index/xxx.npy to wherever you know and refer them in the infer page.

I don't have xxx.index or xxx.npy
I have only G_89600.pth D_89600.pth and config file

**Comment by lextoumbourou** [comment]
@lioriky6 you might have a model intended for so-vits-svc (not RVC). Check out [this](https://github.com/voicepaw/so-vits-svc-fork/tree/main/src/so_vits_svc_fork) repo.

**Comment by lioriky6** [comment]
> @lioriky6 you might have a model intended for so-vits-svc (not RVC). Check out [this](https://github.com/voicepaw/so-vits-svc-fork/tree/main/src/so_vits_svc_fork) repo.

I think you are right. Thanks I'll try
