### ISSUE TITLE
Unable to open web UI when executing in google colab

### ISSUE THREAD

**Issue by jerry900106** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2114]
After executing "launch webUI" it shows:
/content/Retrieval-based-Voice-Conversion-WebUI
python3: can't open file '/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py': [Errno 2] No such file or directory

**Comment by akashuki** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2109

**Comment by jerry900106** [comment]
Thank u
