### ISSUE TITLE
Provide clarifications on hubert model

### ISSUE THREAD

**Issue by deiteris** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2121]
I've been experimenting with different embedders a bit and figured that the `hubert_base.pt` provided by RVC-Project is not an actual Facebook's HuBERT model ([huggingface link](https://huggingface.co/facebook/hubert-base-ls960)). It has the same architecture, but possibly based on a different model (contentvec?).

To compare and verify this, I downloaded the Facebook's HuBERT Base model from `fairseq` repo that is provided here:
https://github.com/facebookresearch/fairseq/tree/main/examples/hubert

The model loads successfully with `fairseq`, inference with RVC model works but produces incorrect results.

So could anyone clarify what is the model that RVC-Project provides?

**Comment by RVC-Boss** [comment]
it's contentvec'5 500class model.

**Comment by deiteris** [comment]
@RVC-Boss, thanks for clarification. May I suggest renaming the model to avoid confusion in this case?
