### ISSUE TITLE
wasapi 独占模式下声音会频繁撕裂，想问在rvc内部可以修改wasapi的缓冲值吗[Buffer Size]

### ISSUE THREAD

**Issue by WolfEllobo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2147]
我使用wasapi独占模式下效果之非常的好，延迟也会很低，但是会间断出现声音撕裂的情况。
我个人感觉应该是缓冲过低造成的，想问大佬有没有办法可以解决，或者想请教如何增加缓冲值。
wasapi 独占效果太好了，已经回不去了！！

**Comment by WolfEllobo** [comment]
> 拉高采样长度吧，牺牲一点延迟
并不行，不是采样长度的事...。我换了一台电脑试了试，就不会爆音了。貌似是硬件的原因，每次爆音都是性能波动比较打大的时候，类似于打开浏览器关闭浏览器，游戏加载时。我试试吧内存、cpu频率调低试试.....

**Comment by WolfEllobo** [comment]
还是不行，我退回了一个版本，发现好了。

**Comment by woOzZ2** [comment]
> 还是不行，我退回了一个版本，发现好了。

请问回退到哪个版本了，我在20240604中出现同样的问题

**Comment by godisme1220** [comment]
抱歉，我退回去仍然不能用，到底是發生甚麼事情?
