### ISSUE TITLE
如何增强模型的咬字能力？

### ISSUE THREAD

**Issue by ILG2021** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2148]
应用场景对发音的准确度有比较要的要求，而且是唱歌。知道的可以给指点下了，谢谢。

**Comment by Mixomo** [comment]
Hello, @Nian-Ci I would like to improve the pronunciation of the RVC in other languages, and after having tested different pretrain models, I came to the conclusion that it would be necessary to train contenvec with the desired language. 

However, I can't understand the instructions in the ContentVec repository, is there any tutorial or resources where I can get more enlightening information about the training and the necessary files, or how to generate them? 

Thank you very much.

**Comment by Mixomo** [comment]
Sweet! Take your time, No rush. I really appreciate the efforts! 
Best of luck!

**Comment by Tiooo111** [comment]
Hello, @Nian-Ci  this issue has been resolved now?
