### ISSUE TITLE
No supported Nvidia GPU found

### ISSUE THREAD

**Issue by JeanS795** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2171]
I've tried most of the solutions proposed in the other similar issues. However it still does not work on my part since i'm getting : 
```
2024-06-28 18:38:09 | INFO | configs.config | No supported Nvidia GPU found
overwrite preprocess and configs.json
2024-06-28 18:39:38 | INFO | configs.config | Use cpu instead
is_half:False, device:cpu
```
I have installed : 
```
torch                  2.3.1+cu118
torchvision            0.18.1+cu118
```

and my GPU is getting detected : 
```
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
1
>>> torch.cuda.get_device_name(0)
'NVIDIA GeForce GTX 1050 Ti'
```
I am using this version of RVC : 2.2.231006
If anyone got any ideas I would be happy to try them out.
Thanks.

**Comment by Hagoel-git** [comment]
i have the same issue, do you figured how to fix that?
