### ISSUE TITLE
針對 G.pth 和 D.pth生成的名字有問題

### ISSUE THREAD

**Issue by DvoDan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#220]
![epochzxc](https://user-images.githubusercontent.com/132544253/236124700-7dbefd69-878a-4f8d-9fe1-6ff384b51e5d.PNG)
不管epoch 設定多少 都會變成 G_2333333 D_2333333

這導致底下的手動備份時會有問題
![epoch50](https://user-images.githubusercontent.com/132544253/236125086-e1986c57-b9dd-443f-bb70-58918b9f36fd.png)

**Comment by RVC-Boss** [comment]
那是因为你webui勾了只保存最后一个epoch

**Comment by DvoDan** [comment]
是的 我勾選了 
但為什麼最後一個epoch要命名為2333333而不是依 epoch的大小來命名
