### ISSUE TITLE
关于训练结束后没有index的解决办法 （请加入文档）

### ISSUE THREAD

**Issue by fmc202** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2209]
很多人反应训练集过大导致没有index，其实只是需要写入的index过大 导致时间过长。多等一会就好了。建议开发者把这点highlight到faq里， 或在infer.py 训练index那里用tqdm显示进度

**Comment by RVC-Boss** [comment]
一直有print进度，只是没用tqdm
而且什么时候完成也是不定期的
