### ISSUE TITLE
No supported Nvidia GPU found。4070s not supported？

### ISSUE THREAD

**Issue by Tina-Serria** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2228]
when i run infer-web.py.it shows "No supported Nvidia GPU found".i have installed torch and  cuda 12.6

**Comment by heartgold512** [comment]
4070 is supported, i in fact had the same problem, try reinstalling or closing terminal and re running RVC and Xtts finetune. There are some videos on youtube one of which I use my 4070 locally so yes it is possible and is supported

**Comment by kalbright3275** [comment]
If an NVIDIA GPU driver is not available, the program will run in CPU mode instead.

**Comment by Tina-Serria** [comment]
> 4070 is supported, i in fact had the same problem, try reinstalling or closing terminal and re running RVC and Xtts finetune. There are some videos on youtube one of which I use my 4070 locally so yes it is possible and is supported

Actually,i dont know wether i forget some steps or do somting wrong,because i dont know is the project support RTX 4070 Super

**Comment by Tina-Serria** [comment]
> If an NVIDIA GPU driver is not available, the program will run in CPU mode instead.

i know that, the terminal shows the tip.but i want to run with 4070s

**Comment by kalbright3275** [comment]
> i know that, the terminal shows the tip.but i want to run with 4070s

I understand. Is the RTX 4070 Super a GPU driver, I'm just curious?

**Comment by heartgold512** [comment]
I believe 4070 Super will work, as Kal said maybe its a driver issue?
which you can sort from "Geforce experience" app to download the gpu driver which nvidea will find for your system

**Comment by Tina-Serria** [comment]
> > i know that, the terminal shows the tip.but i want to run with 4070s
> 
> I understand. Is the RTX 4070 Super a GPU driver, I'm just curious?

it's another model of 4070，America don't have this model？

**Comment by Tina-Serria** [comment]
I know where i went wrong.Its my first time to use pytorch and cuda.So i dont know cuda is also a library like python,java.Both of them have different version.As a result pytorch doesnt support the newest cuda 12.6 that i installed previously.
