### ISSUE TITLE
i have this error when i launch go-web.bat

### ISSUE THREAD

**Issue by mrgame12310** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2270]
Retrieval-based-Voice-Conversion-WebUI-main>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
The specified path could not be found.

**Comment by shanedk** [comment]
It's a bug they need to fix. Python isn't in a "runtime" subfolder on Windows. Just replace it to wherever the path of your python.exe is, possibly venv\Scripts\python.exe (if "venv" is what you called your virtual environment).

**Comment by mrgame12310** [comment]
thanks for the respond but how do i fix it ? i have never coded in my entire life so i m a bit scared of doing shit to the code
