### ISSUE TITLE
go-realtime-gui is crashing when i press "start conversation"

### ISSUE THREAD

**Issue by mrgame12310** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2288]
i add my model but i don't change the logs
i change the mic and headphone and press start and it crash

**Comment by mrgame12310** [comment]
just the gui stop working
and i don't kn why

**Comment by mrgame12310** [comment]
ok i fixed it by changing my output by (windows directsound) to (MME)

**Comment by awz66661** [comment]
How did you choose the MME output? I use Voicemeeter, but there is no MME in the RVC output options
![image](https://github.com/user-attachments/assets/6ce15ebd-a273-4104-94c9-18505176dfc4)

**Comment by ynd6** [comment]
![屏幕截图 2024-12-29 010118](https://github.com/user-attachments/assets/f7199e99-a55e-4df8-afdb-bb2f3023fbe3)
为什么我改了还是无响应
