### ISSUE TITLE
请问有底模训练的项目吗

### ISSUE THREAD

**Issue by treya-lin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2297]
感谢！很好的项目。

看到说底模是在VCTK上面训练的。请问假如想要自己用VCTK复现底模的训练，有哪个仓库可以参考吗？还是说训练方法代码是保密的？

**Comment by RVC-Boss** [comment]
楼上正解

**Comment by Ayin1412** [comment]
> 其实就是训练多说话人模型，然后把权重裁掉一部分捏

请问本质还是训练VITS模型吗，裁剪掉一部分是指模型内的花名册吗，从多说话人变成但说话人是吗？
