### ISSUE TITLE
Input dimensions can not fit the model when run in onnx.

### ISSUE THREAD

**Issue by Zer0TheObserver** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2298]
![image](https://github.com/user-attachments/assets/b290935f-1071-4ee5-8108-8cb27b148600)

I'm using "onnx_inference_demo.py"
and "vec-256-layer-9" as vac.
Here's all shape of inputs:
![image](https://github.com/user-attachments/assets/e2df7eb1-72b0-457f-ae01-5b9cff27dcb0)

**Comment by samolego** [comment]
You have the v2 version of the model, you need to use `vec-768-layer-12`. The above is for v1 only afaik.

**Comment by Zer0TheObserver** [comment]
> You have the v2 version of the model, you need to use `vec-768-layer-12`. The above is for v1 only afaik.

Thanks reply, now i'm using code like this:
`import soundfile

from onnx_inference import OnnxRVC

hop_size = 512
sampling_rate = 40000  # 采样率
f0_up_key = 0  # 升降调
sid = 0  # 角色ID
f0_method = "dio"  # F0提取算法
model_path = "testWeight.onnx"  # 模型的完整路径
vec_name = (
    "vec-768-layer-9"  # 内部自动补齐为 f"pretrained/{vec_name}.onnx" 需要onnx的vec模型
)
wav_path = "123.wav"  # 输入路径或ByteIO实例
out_path = "out.wav"  # 输出路径或ByteIO实例

model = OnnxRVC(
    model_path, vec_path=vec_name, sr=sampling_rate, hop_size=hop_size, device="cpu"
)

audio = model.inference(wav_path, sid, f0_method=f0_method, f0_up_key=f0_up_key)

soundfile.write(out_path, audio, sampling_rate)
`
I'm using vec-768-layer-9 now, but i got somthing even strange now:
![image](https://github.com/user-attachments/assets/e8c7e1a9-788a-4ab6-a7b1-e2b1136d840b)

**Comment by samolego** [comment]
Yeah, I'm sadly stuck here as well. If I find anything, I'll post here.
If you manage to solve it before, I'd be glad if you share the info :)

**Comment by samolego** [comment]
@Zer0TheObserver see https://github.com/codename0og/RVC_Onnx_Infer/issues/4
The export onnx function in this repo seems to be a little broken, I've used https://github.com/codename0og/hifi_testing_new for exporting and it seems to work!

**Comment by Zer0TheObserver** [comment]
> @Zer0TheObserver see [codename0og/RVC_Onnx_Infer#4](https://github.com/codename0og/RVC_Onnx_Infer/issues/4) The export onnx function in this repo seems to be a little broken, I've now used https://github.com/codename0og/hifi_testing_new for exporting and it seems to work!

Thanks reply, I've tried it also, It does work perfectly.

**Comment by zhixingheyixsh** [comment]
我也遇到这个问题了，看报错是在 /enc_p/encoder/attn_layers.0/Reshape_10，应该是infer/lib/infer_pack/attentions.py 中Encoder 中的 Mutiheadattention 里有个reshape,但是我看forward里是没有的，反而上一层 TextEncoder 的forward里有几个reshape.
@Zer0TheObserver 
另外，请问你的vec-768-layer-12.onnx 是在哪儿块下载的？是这个地址吗https://huggingface.co/NaruseMioShirakana/MoeSS-SUBModel

**Comment by Zer0TheObserver** [comment]
> 我也遇到这个问题了，看报错是在 /enc_p/encoder/attn_layers.0/Reshape_10，应该是infer/lib/infer_pack/attentions.py 中Encoder 中的 Mutiheadattention 里有个reshape,但是我看forward里是没有的，反而上一层 TextEncoder 的forward里有几个reshape. @Zer0TheObserver 另外，请问你的vec-768-layer-12.onnx 是在哪儿块下载的？是这个地址吗https://huggingface.co/NaruseMioShirakana/MoeSS-SUBModel

抱歉……已经完全不记得了……应该是的。

**Comment by chen-Mengjiang** [comment]
嗨，我在用vec-256-layer-9.onnx推理的时候，std::vector<float> wav16k；wav16k.size()<= 320，执行session->Run()会出错。请问是有限制采样最小长度吗？

**Comment by RXXZWW** [comment]
请问还有关于onnx导出部分的代码吗，我点开对应的这个链接https://github.com/codename0og/hifi_testing_new，已经是404找不到了
