### ISSUE TITLE
一键训练step3错误

### ISSUE THREAD

**Issue by ldcivan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#231]
报错内容如下：
<pre>
INFO:21:{'train': {'log_interval': 200, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 1, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 40000, 'filter_length': 2048, 'hop_length': 400, 'win_length': 2048, 'n_mel_channels': 125, 'mel_fmin': 0.0, 'mel_fmax': None, 'training_files': './logs\\21/filelist.txt'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 10, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'use_spectral_norm': False, 'gin_channels': 256, 'spk_embed_dim': 109}, 'model_dir': './logs\\21', 'experiment_dir': './logs\\21', 'save_every_epoch': 5, 'name': '21', 'total_epoch': 20, 'pretrainG': 'pretrained/f0G48k.pth', 'pretrainD': 'pretrained/f0D48k.pth', 'gpus': '0', 'sample_rate': '40k', 'if_f0': 1, 'if_latest': 1, 'if_cache_data_in_gpu': 0}
WARNING:21:C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\train is not a git repository, therefore hash value comparison will be ignored.
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [localhost.sangfor.com.cn]:51545 (system error: 10049 - 在其上下文中，该请求的 地址无效。).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [localhost.sangfor.com.cn]:51545 (system error: 10049 - 在其上下文中，该请求的 地址无效。).
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
gin_channels: 256 self.spk_embed_dim: 109
INFO:21:loaded pretrained pretrained/f0G48k.pth pretrained/f0D48k.pth
Traceback (most recent call last):
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 534, in <module>
    main()
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 50, in main
    mp.spawn(
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 148, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\train\utils.py", line 206, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\train_nsf_sim_cache_sid_load_pretrain.py", line 166, in run
    net_g.module.load_state_dict(
  File "C:\Users\ldciv\Desktop\Retrieval-based-Voice-Conversion-WebUI-main\RVC-beta\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        Unexpected key(s) in state_dict: "dec.noise_convs.4.weight", "dec.noise_convs.4.bias", "dec.ups.4.bias", "dec.ups.4.weight_g", "dec.ups.4.weight_v", "dec.resblocks.12.convs1.0.bias", "dec.resblocks.12.convs1.0.weight_g", "dec.resblocks.12.convs1.0.weight_v", "dec.resblocks.12.convs1.1.bias", "dec.resblocks.12.convs1.1.weight_g", "dec.resblocks.12.convs1.1.weight_v", "dec.resblocks.12.convs1.2.bias", "dec.resblocks.12.convs1.2.weight_g", "dec.resblocks.12.convs1.2.weight_v", "dec.resblocks.12.convs2.0.bias", "dec.resblocks.12.convs2.0.weight_g", "dec.resblocks.12.convs2.0.weight_v", "dec.resblocks.12.convs2.1.bias", "dec.resblocks.12.convs2.1.weight_g", "dec.resblocks.12.convs2.1.weight_v", "dec.resblocks.12.convs2.2.bias", "dec.resblocks.12.convs2.2.weight_g", "dec.resblocks.12.convs2.2.weight_v", "dec.resblocks.13.convs1.0.bias", "dec.resblocks.13.convs1.0.weight_g", "dec.resblocks.13.convs1.0.weight_v", "dec.resblocks.13.convs1.1.bias", "dec.resblocks.13.convs1.1.weight_g", "dec.resblocks.13.convs1.1.weight_v", "dec.resblocks.13.convs1.2.bias", "dec.resblocks.13.convs1.2.weight_g", "dec.resblocks.13.convs1.2.weight_v", "dec.resblocks.13.convs2.0.bias", "dec.resblocks.13.convs2.0.weight_g", "dec.resblocks.13.convs2.0.weight_v", "dec.resblocks.13.convs2.1.bias", "dec.resblocks.13.convs2.1.weight_g", "dec.resblocks.13.convs2.1.weight_v", "dec.resblocks.13.convs2.2.bias", "dec.resblocks.13.convs2.2.weight_g", "dec.resblocks.13.convs2.2.weight_v", "dec.resblocks.14.convs1.0.bias", "dec.resblocks.14.convs1.0.weight_g", "dec.resblocks.14.convs1.0.weight_v", "dec.resblocks.14.convs1.1.bias", "dec.resblocks.14.convs1.1.weight_g", "dec.resblocks.14.convs1.1.weight_v", "dec.resblocks.14.convs1.2.bias", "dec.resblocks.14.convs1.2.weight_g", "dec.resblocks.14.convs1.2.weight_v", "dec.resblocks.14.convs2.0.bias", "dec.resblocks.14.convs2.0.weight_g", "dec.resblocks.14.convs2.0.weight_v", "dec.resblocks.14.convs2.1.bias", "dec.resblocks.14.convs2.1.weight_g", "dec.resblocks.14.convs2.1.weight_v", "dec.resblocks.14.convs2.2.bias", "dec.resblocks.14.convs2.2.weight_g", "dec.resblocks.14.convs2.2.weight_v".
        size mismatch for dec.noise_convs.0.weight: copying a param with shape torch.Size([256, 1, 96]) from checkpoint, the shape in current model is torch.Size([256, 1, 80]).
        size mismatch for dec.noise_convs.1.weight: copying a param with shape torch.Size([128, 1, 16]) from checkpoint, the shape in current model is torch.Size([128, 1, 8]).
        size mismatch for dec.noise_convs.2.weight: copying a param with shape torch.Size([64, 1, 8]) from checkpoint, the shape in current model is torch.Size([64, 1, 4]).
        size mismatch for dec.noise_convs.3.weight: copying a param with shape torch.Size([32, 1, 4]) from checkpoint, the shape in current model is torch.Size([32, 1, 1]).
        size mismatch for dec.conv_post.weight: copying a param with shape torch.Size([1, 16, 7]) from checkpoint, the shape in current model is torch.Size([1, 32, 7]).
</pre>

**Comment by RVC-Boss** [comment]
操作不规范

你上个配置保存过pth，然后换了新配置，又不改实验名，就接着上次不一样的配置结构用新的结构接着训，是对不上的

**Comment by ldcivan** [comment]
> 操作不规范
> 
> 你上个配置保存过pth，然后换了新配置，又不改实验名，就接着上次不一样的配置结构用新的结构接着训，是对不上的

所以想请教一下如何完全清除过往配置？我直接删除了logs内的内容，还需要删除其它文件嘛？先谢谢了ＴＴ

**Comment by RVC-Boss** [comment]
新老实验名别一样就行了

**Comment by fjibj** [comment]
我遇到了相同的问题，我把实验目录（logs/实验名）整个删除了再做也不行吗？ @RVC-Boss

**Comment by ZJ-CAI** [comment]
> 我遇到了相同的问题，我把实验目录（logs/实验名）整个删除了再做也不行吗？ @RVC-Boss

把weights目录下的同名文件也删了，然后再重新训练
