### ISSUE TITLE
why total epcoh is 1000? 

### ISSUE THREAD

**Issue by margo2130** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2337]
how can i train epoch 2000-2500?
i already trained 990. i want train more.
but in the web ui, the maximum is 1000.

![image](https://github.com/user-attachments/assets/383b9e17-97da-43f4-bc2a-259cdb387ab4)

**Comment by RVC-Boss** [comment]
Continuing to increase the number of total training epochs will not significantly improve the few shot fine tuning quality.
