### ISSUE TITLE
Can we please have release notes in english? It is very hard for implementors to detect/track breaking changes, etc.

### ISSUE THREAD

**Issue by sgsavu** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#235]
We should also try to use M.m.p versioning (where M is major, m is minor and p is patch: eg. 2.4.3) which makes this more obvious just from the version number

**Comment by scf4** [comment]
Perhaps you could contribute PRs for translated release notes, given how relatively easy a task language translation is in 2023? Not to sound rude but this just seems like such a demanding request IMO

**Comment by scf4** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/5d7609a413eecbc5a062200f1417462be79328ee/Changelog_EN.md

**Comment by sgsavu** [comment]
> Perhaps you could contribute PRs for translated release notes, given how relatively easy a task language translation is in 2023? Not to sound rude but this just seems like such a demanding request IMO

I pray for you my son you find the help you seek.
