### ISSUE TITLE
Only start "Step 1: Processing data" after press "One-click training"

### ISSUE THREAD

**Issue by ChoiDo575** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2351]
After preprocessing and extract featured step, I hit "One-click training" button and it show "Step 1: Processing data" only in the Output information box.
In CMD, after hitting one click training, it run preprocess again and it wouldn't do anything more. Can anyone help me...
![image](https://github.com/user-attachments/assets/e288abc8-5021-4866-97be-c66876d1df51)

**Comment by 240db** [comment]
The one-click training button might be broken. Make sure you have gradio==3.48.0 by 
```bash
pip install gradio==3.48.0
```

The gradio version in requirements.txt is known to be buggy and since this project relies on it,make sure to get a working gradio version

**Comment by ChoiDo575** [comment]
> The one-click training button might be broken. Make sure you have gradio==3.48.0 by
> 
> ```shell
> pip install gradio==3.48.0
> ```
> 
> The gradio version in requirements.txt is known to be buggy and since this project relies on it,make sure to get a working gradio version.
> 
> If that does not fix it, try clicking Train model then Train feature index, that worked for me when selecting harvest. But inference was broken, now that I upgraded to the working gradio version, it should all be working as I have checked in the Inference tab (works again)

this worked with me.
thank you!!!

**Comment by pwatx** [comment]
非常好的建议，为什么还没人修复呢？
