### ISSUE TITLE
Seemingly accident update to the April 28th release

### ISSUE THREAD

**Issue by kalomaze** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#236]
RVC-Beta.7z on the hugging face page was accidentally updated by mistake yesterday morning central time. (In the timezone where most of the developers live, I'm thinking this was ~9 or 10pm roughly I believe?) In addition to this, the updated20230428.zip file was silently updated and replaced. This makes me think it wasn't intentional, as it still reads april 28th in the filename, and no new release tag was properly created. The RVC-beta.7z that was updated also fails to properly launch go-web.bat, and the updated20230428.zip has similar problems (complaints about a missing english translation on the newest commit as of the accident?)

To remedy this for the people using Google Colab, I made my own fork that has a backup download of the updated20230428.zip:
https://github.com/kalomaze/Retrieval-based-Voice-Conversion-WebUI/releases/tag/20230428updated

If this wasn't a mistake, or I am misunderstanding the situation, please let me know. I also have a backup of the RVC-beta.7z as it was before on this google drive:
https://drive.google.com/file/d/1JQ0i16m7WqN76rqpp2THgNMcLDuJFuny/view?usp=sharing

**Comment by RVC-Boss** [comment]
I have fixed it.
