### ISSUE TITLE
go-realtime-gui.bat no response when click start audio conversion

### ISSUE THREAD

**Issue by Bug-This** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2400]
<img width="555" alt="image" src="https://github.com/user-attachments/assets/ceedff58-d799-44a7-90ac-428d232a1bb1">
<img width="559" alt="image" src="https://github.com/user-attachments/assets/dfa2a6da-5090-44bc-a948-5de0670544b8">
The program always get no response when I click start audio conversion with no error in cmd or any where. Do I just have to wait longer or there is a strange bug or I just choose wrong audio in/out put device? 
Using default models and go-web.bat works. Using Nvidia graphics card and amd CPU.
Thanks!

**Comment by Bug-This** [comment]
Solved by using MME input and output with both input and output are virtual.

**Comment by Alexander4750** [comment]
explain how you solved this pleaseee
