### ISSUE TITLE
数据集越多效果反而约不理想可能是因为什么呢

### ISSUE THREAD

**Issue by aioaxz** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#260]
我有一个无底噪纯人声的数据源加起来大约3-5小时长，从中随机抽取30分钟的几百个片段文件跑20epoch（48kHz，pitch harvest，batch size 32）效果很理想，几乎无哑音，电音，用完整的数据集一样的配置再跑一次20epoch反而有一些文件里有电音了。

能想到的可能原因
* 数据集越大是否可能需要跑更多epoch才能得到更理想的结果？
* 可能之前随机选的刚好更多是高音自动处理完美的，完整数据集反而高音没提取好

**Comment by RVC-Boss** [comment]
原因2肯定是错的，随机抽不影响质量。
原因1：多和少都可以试下

**Comment by aioaxz** [comment]
好的感谢，我多试试，有问题再reopen。

**Comment by aioaxz** [comment]
> 原因2肯定是错的，随机抽不影响质量。
换句话说是不是只要输入源达到了一定的时长（比如这里的30分钟）数据集再大其实影响就没那么大了？我理解RVC对短时间的数据(10min)效果很好，但是不太清楚数据源变多一般来说效果是更好，更坏还是没太大区别。



好的感谢，我多试试，有问题再reopen。
