### ISSUE TITLE
No public link

### ISSUE THREAD

**Issue by composition-cassidy** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#262]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/99601533/a1dad682-6bc6-48bc-9526-a0f66c237983)

Google Colab not making the public link..

**Comment by lonesurvivor1984** [comment]
the same

**Comment by lonesurvivor1984** [comment]
Why the public link is failed

**Comment by kalomaze** [comment]
Gradio was down. This can be closed
