### ISSUE TITLE
[bug]找不到推理音色

### ISSUE THREAD

**Issue by lingxues** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#264]
重新安装了RVC-beta程序，然后把训练好的模型复制到logs文件夹下，web页面推理音色没有任何模型

**Comment by happyman2025** [comment]
我也有類似情況，已訓練好，推理過幾次，然後關機。晚上再試，按"刷新音色列表和索引路徑"，推理音色皆為空，但可找到兩個 index 文件 logs\me3-test2-v2/added_IVF2439_Flat_nprobe_1_me3-test2-v2_v2.index 和 logs\me3-test2/added_IVF2439_Flat_nprobe_1_me3-test2_v1.index。

- Retrieval-based-Voice-Conversion-WebUI\weights 中有 me3-test2.pth 和 me3-test2-v2.pth 兩個文件
- Retrieval-based-Voice-Conversion-WebUI\logs 中也有 me3-test2 和 me3-test2-v2 的資料

記憶中，訓練過後好像做了一次 git pull，不知道是否這個原因，現在就是找不到推理音色。

**Comment by Inblac** [comment]
更新后weights 文件夹 移动到了assets文件夹，不再放置在根目录。
手动移动文件夹后可用
