### ISSUE TITLE
Error while extracting existing model // 提取现有模型时出现错误

### ISSUE THREAD

**Issue by samirdigital** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#276]
I have access to a model of an artist that someone had already trained & sent me. This is what the directory is looking like (I manually put it in logs):
(中文翻译：我可以访问到一个已经被别人训练并发送给我的艺术家模型。下面是目录的样子（我手动放在了日志中）：)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/37991980/5cb8778d-456b-4229-b2b5-39a364e8e250)

I'm trying to extract the model so that the model will show up on the "timbre" dropdown, but I'm met with this error:
(中文翻译：我试图提取模型，以便该模型会在“音色”下拉菜单中显示，但是我遇到了这个错误：)
Traceback (most recent call last):
  File "C:\Users\samir\OneDrive\Desktop\RVC-beta\train\process_ckpt.py", line 107, in extract_small_model
    opt["weight"][key] = ckpt[key].half()
AttributeError: 'dict' object has no attribute 'half'

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/37991980/a91c5635-a5b9-4ce8-aedb-d6b6bbd125fe)

I've reinstalled dependences, ensured that the correct pytorch is installed, tried placing the model files outside of the 'logs' folder. Can anyone tell me what I'm doing wrong?
(中文翻译：我已经重新安装了依赖项，确保正确安装了PyTorch，并尝试将模型文件放在“logs”文件夹之外。有人可以告诉我我做错了什么吗？请随意用中文或英文回答，非常感谢你所做的工作。)

**Comment by RVC-Boss** [comment]
You don't need extract it. The model is the extracted one. Just put it into "weights" folder. And click "refresh timbre list".

**Comment by fumiama** [comment]
Put `.pth` file into `weights` folder and refer `.index` file in the `Model inference` tab.
