### ISSUE TITLE
Unable to use (Accompaniment and Vocal Separation) in Colab.

### ISSUE THREAD

**Issue by c469591** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#285]
Hello, I am using Accompaniment and Vocal Separation in Colab, but I encountered an error. This is my configuration in wap.

Input audio folder path  /content/drive/1a.flac
Model HP5-主旋律人声vocals+其他instrumentals HP2-人声vocals+非人声instrumentals
Specify vocals output folder  /content/drive/out/
Specify instrumentals output folder  /content/drive/out/

After conversion, the following error message is displayed. The previous sections in Colab have been confirmed to run successfully and download properly.

Export message
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 252, in uvr
    pre_fun = _audio_pre_(
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer_uvr5.py", line 37, in __init__
    model_size = math.ceil(os.stat(model_path).st_size / 1024)
FileNotFoundError: [Errno 2] No such file or directory: 'uvr5_weights/.pth'

thanks

**Comment by RVC-Boss** [comment]
You can try the latest version.
I uploaded the English named pth file to huggingface.
You can use it now.

**Comment by RVC-Boss** [comment]
https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main/uvr5_weights
put these into uvr5_weights directory
