### ISSUE TITLE
How to do inference on a locally computer after training a model in Colab?

### ISSUE THREAD

**Issue by c469591** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#294]
Hello, 
I trained a model on Colab, but the training is not yet complete. However, I have already downloaded a backup pth and json file. 
Later, I opened rvc wav on my own computer, but I did not see any selectable items in the sound list. 
I tried putting the pth and json files in several folders under the rvc folder, but the result was the same. 
Can you tell me where I should put the pth and json files so that they can be seen in the sound list on the web? Am I missing any necessary files? 
Also, for the inference options, I need to select the index file for the sound, how can I obtain this file? 
I am new to this interesting project, so I have many questions. I hope this won't cause too much trouble. Thank you!

**Comment by fumiama** [comment]
see #211
