### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. help dunno how to fix this

### ISSUE THREAD

**Issue by MDtheSimp** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#312]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116833145/ea6ae483-44b4-4f6e-8677-b77a249dbb19)
while trying to train a voice it always sends me this message

**Comment by Naozumi520** [comment]
Are you setting the batch_size over 1? You may want to lower that

**Comment by MDtheSimp** [comment]
ight found a fix
