### ISSUE TITLE
Optimizer states: important?

### ISSUE THREAD

**Issue by sjkoelle** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#331]
Hi,

I am running the training code locally and porting it to Ray.  I've been looking to use your pretrained checkpoints from Hugging Face.  Unless I am missing something, these do not include optimizer state.  Is there any benefit to warmstarting with the optimizer state for finetuning?

Thanks,
Sam

**Comment by RVC-Boss** [comment]
Based on my experience, optimizer parameters are not important for fine-tuning.
