### ISSUE TITLE
Web version suggestions and errors

### ISSUE THREAD

**Issue by c469591** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#337]
Web version suggestions and errors
Hello,
I have encountered some problems while using rvc web. Firstly, there are some errors when using the batch inference feature:
PS: I am using Brave browser which is based on the chrome core.
1. When using batch inference, if there are .flac files in the input folder, the inference result shows the file extension as .flac. However, these files are actually in wav format. I had to rename the file extension to .wav in order to play them in Foobar.
2. After completing batch inference, when I added other audio files to the input folder and clicked "convert" again, rvc web couldn't find the new files with .wav format. I am not sure if this is related to browser cache.
3. Switching models by using the up and down arrow keys in the combo box for selecting inference models can cause a model to freeze at a certain point. Even after uninstalling the sound, I still couldn't change to another model. I had to restart the entire web page. I suggest adding a "load" button to load the model only when clicked.
Further suggestions:
1. It would be helpful to have a browse button for selecting files and folders on the web inference page, instead of manually typing in the path.
2. It would be convenient if rvc web could save my previous parameter settings when I close the webpage or provide a feature to save templates for repeated use.
3. It would be useful to have a "download" button designed in the same way as the "convert" button after completing the conversion for an input file. The existing download button is almost unnoticeable for screen readers.
Thank you!

**Comment by RVC-Boss** [comment]
Good idea.
