### ISSUE TITLE
Only 4 it/s while training a v2 model with RTX 4090

### ISSUE THREAD

**Issue by Elia1995-Official** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#341]
Hello, when I train a model, whether on Arch Linux or Windows, I get no more than 4 it/s and it's very slow.
Since I have a 4090 I'd be expecting that I should get a bit more, maybe at least 10 it/s, but apparently it's performing the same as a 2070 for some reason!

Is there any way to use xformers to speed it up a little bit?

**Comment by MitPitt** [comment]
Where are you seeing it/s? I only see epochs in the training log

**Comment by Elia1995-Official** [comment]
> Where are you seeing it/s? I only see epochs in the training log

![immagine](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/102905776/8114b0cc-a454-4bd3-9c61-be9057b04e87)

**Comment by Elia1995-Official** [comment]
![immagine](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/102905776/eba567cd-7186-4160-bd7b-dfb82e433987)
Now I'm training another model and it's even slower, half the speed of the one I previously posted.

**Comment by RVC-Boss** [comment]
> Hello, when I train a model, whether on Arch Linux or Windows, I get no more than 4 it/s and it's very slow. Since I have a 4090 I'd be expecting that I should get a bit more, maybe at least 10 it/s, but apparently it's performing the same as a 2070 for some reason!
> 
> Is there any way to use xformers to speed it up a little bit?

I'm testing xformers. Please wait for our experiment results.

**Comment by RVC-Boss** [comment]
@Elia1995-Official A good idea. I use xformers and the speed of inferencing a audio is now faster. Memory attention in xformers is 15x faster than pytorch MHA. I will introduce it in the next version, named Faster-RVC.

**Comment by Edgar-Nino** [comment]
Hi!, @RVC-Boss , is it already implemented?
