### ISSUE TITLE
支持 MP3 格式；升级到 UVR5.5

### ISSUE THREAD

**Issue by ephoton** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#348]
非常棒的项目，使用过程中有两个点希望能进一步优化：

1. 支持 MP3 格式，WAV格式太慢、太占磁盘了；
2. UVR5.5 已经支持了 MDX-Net 模型，有降噪功能，分离人声和背景音的效果更好，希望能升级支持。

**Comment by RVC-Boss** [comment]
1、有计划支持中，但是只有下面的批量导出模式可用，因为上面那个是试听控件
2、本周会上mdx-net的dereverb

**Comment by ephoton** [comment]
超赞👍，可以在主页提供赞助入口，共同助力开源生态健康发展。

**Comment by ephoton** [comment]
> 1、有计划支持中，但是只有下面的批量导出模式可用，因为上面那个是试听控件 2、本周会上mdx-net的dereverb

1. UVR 也可以支持导出 MP3 格式，这个也会影响分离的速度和磁盘空间

**Comment by RVC-Boss** [comment]
> > 1、有计划支持中，但是只有下面的批量导出模式可用，因为上面那个是试听控件 2、本周会上mdx-net的dereverb
> 
> 1. UVR 也可以支持导出 MP3 格式，这个也会影响分离的速度和磁盘空间

好

**Comment by ms903x1** [comment]
But it should be noted that MP3 format can cause lossy compression of audio

**Comment by RVC-Boss** [comment]
> But it should be noted that MP3 format can cause lossy compression of audio

啊这个我想更多人应该是知道的，我设置的默认格式flac，不知道mp3是有损压缩的用户应该不会手工去选mp3。

**Comment by RVC-Boss** [comment]
最新版已支持至今UVR的所有去混响和去延迟模型；批量推理/uvr5导出格式支持wav mp3 flac m4a。
