### ISSUE TITLE
FAQ error???

### ISSUE THREAD

**Issue by jay5656** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#355]
this is the error im getting 

Traceback (most recent call last): File "S:\RVC-beta\infer-web.py", line 1696, in with open("docs/faq_en.md", "r")as f:info = f.read() File "encodings\cp1252.py", line 23, in decode UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 976: character maps to

the installation process:
i got it from here and downloaded "RVC-beta.7z"
https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main

**Comment by RVC-Boss** [comment]
("docs/faq_en.md", "r")
->
("docs/faq_en.md", "r",encoding="utf8")

**Comment by jay5656** [comment]
> ("docs/faq_en.md", "r") -> ("docs/faq_en.md", "r",encoding="utf8")

im just getting constant errors everywhere, so i must have installed it wrong. all i did was download the zip, extract it, and run it. however i do have it on a different drive than where windows is installed (on a S:/ drive rather than C:/) 
i dont have enough space on my C drive to test if this is the issue. so if anyone can test whether the program works on other drives thatd be great
