### ISSUE TITLE
文档可以改下，不是3.8以上就行  

### ISSUE THREAD

**Issue by denganliang** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#356]
PS D:\voice\Retrieval-based-Voice-Conversion-WebUI-main\Retrieval-based-Voice-Conversion-WebUI-main> poetry install
The currently activated Python version 3.11.3 is not supported by the project (^3.8,<3.11).
Trying to find and use a compatible version.

**Comment by Saganaki22** [comment]
im using v3.10.11 and its currently working
