### ISSUE TITLE
V2 GUI改进建议

### ISSUE THREAD

**Issue by Nowebyone** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#375]
V2: 
推理:
推理源做成拖拽选择

伴奏分离: 
如果可以加一个处理队列，按照顺序去跑模型，比如一个音频先进MDX-Net再过MDX-Net然后再输出文件保存
实验名:
实验名配置文件，记录下如BatchSize，当前EpochTarget，保存频率，版本等 做成下拉+输入类的
模型融合: 
做成下拉菜单+输入类型的
模型提取:
配合实验名配置文件做成二级下拉菜单+输入类的[先选实验名，再选步数(如果有多步存档)]

**Comment by Nowebyone** [comment]
个人意见，希望能选择性吸收

**Comment by 625673575** [comment]
我都不知道v2怎么启动，模型现在都没有选择的
