### ISSUE TITLE
Error when training model : wrong arguments?

### ISSUE THREAD

**Issue by User090306** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#377]
usage: train_nsf_sim_cache_sid_load_pretrain.py [-h] -se SAVE_EVERY_EPOCH -te TOTAL_EPOCH [-pg PRETRAING]
                                                [-pd PRETRAIND] [-g GPUS] -bs BATCH_SIZE -e EXPERIMENT_DIR -sr
                                                SAMPLE_RATE -f0 IF_F0 -l IF_LATEST -c IF_CACHE_DATA_IN_GPU
train_nsf_sim_cache_sid_load_pretrain.py: error: unrecognized arguments: -sw 0 -v v1

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/83623940/68426801-110d-43c0-81df-4d04af52b952)

Just updated from the old ver by replacing.

**Comment by User090306** [comment]
Its a stupid mistake , i should download the full package and replace the old one

**Comment by progward** [comment]
@User090306 What exactly did you do? I just did the same thing. Cloned this rep, always checked all files and requirements. Then at the end replaced all files from the latest update from yesterday. Still this error shows up for me when starting to train the model.

**Comment by progward** [comment]
Oh I think I got it. There is this beta package (base) that you must download before. That should be explained better by the devs

**Comment by progward** [comment]
Nah. Downloaded the base package, replaced files. Downloaded the update, replaced files. Still this error.

**Comment by RVC-Boss** [comment]
The updated package published in 0528 is not updated from the oldest version, so something may be missing. I have fixed it now.
