### ISSUE TITLE
Pitch wobble effect with speech generator

### ISSUE THREAD

**Issue by tomakorea** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#40]
Hi, your software is pretty amazing, I can get good results in just 1000 epochs. However, I have some issue on some output files. I'm changing Man voice -> Woman voice (trained model). However, the results often show an unsteady pitch, a slight wobble effect. I was wondering if you could add a slider to smooth out the output pitch (or the input). When I'm using Voice Generator Gui (svcg), there is no such a problem. Maybe because they use Pad and chunk ? or maybe because I use Crepe prediction method?
However, your fork seems very promising, the sound quality is really nice, I just hope there is a way to make the pitch more natural for spoken voice.

**Comment by liujing04** [comment]
We will continue to optimize the accuracy of pitch recognition.

In the future version, we may open the pitch median filter option for users.

**Comment by Tybost** [comment]
> We will continue to optimize the accuracy of pitch recognition.
> 
> In the future version, we may open the pitch median filter option for users.

Looking forward to future updates. =) Great work! 

I don't know why but the update for RVC 5 days ago _(while much faster)_ has made all the trained voice models 20-40% quieter when speaking. It's not a big issue but an undesirable one (I can sidestep by increasing the microphone volume atm) just thought I'd point it out. :P

**Comment by RVC-Boss** [comment]
Pitch mean filter has been added to crepe and harvest when inference.
