### ISSUE TITLE
A6000 没有被webui识别

### ISSUE THREAD

**Issue by SoloPro-Git** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#410]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/57442574/c9bdbeaa-166d-4f84-b89b-5b7e37cd4cd3)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/57442574/a80b81da-a747-47b2-aa62-c132a24be71b)

> 我自己手动添加了

**Comment by RVC-Boss** [comment]
感谢提示，下个版本我加一下白名单
