### ISSUE TITLE
能不能在autodl平台运行实时变声？

### ISSUE THREAD

**Issue by xvm03** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#412]

**Comment by RVC-Boss** [comment]
大佬是怎么在autodl上开windows系统的，求教学

**Comment by RVC-Boss** [comment]
我懂意思了，但是go-realtime-gui那个不行，得接voice-changer

**Comment by ms903x1** [comment]
voice-changer支持远程推理，不过现在还没有voice-changer的autodl镜像。

**Comment by xvm03** [comment]
> 

autodl不支持windows的，问过官方客服了，所以我也也尝试用了voice-changer，但是还是有报错

**Comment by xvm03** [comment]
> > 
> 
> autodl不支持windows的，问过官方客服了，所以我也也尝试用了voice-changer，但是还是有报错



> 

我可以

> 

我可以在本地mac 上启动voice-changer，远程连接autodl的推理吗？另外你有在mac上使用过voice-changer，我一启动选了rvc之后，程序就挂了

**Comment by xvm03** [comment]
> voice-changer支持远程推理，不过现在还没有voice-changer的autodl镜像。

我可以在本地mac 上启动voice-changer，远程连接autodl的rvc推理吗？另外你有在mac上使用过voice-changer，我一启动选了rvc之后，程序就挂了

**Comment by ms903x1** [comment]
我没有mac设备，很遗憾不能帮到你。

**Comment by BoheZhi** [comment]
this can be useful to u https://www.bilibili.com/read/cv24038125
