### ISSUE TITLE
Vocal separator only outputs into wav or flac.

### ISSUE THREAD

**Issue by kazuviking2** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#413]
Only wav or flac output is working, if i select mp3 then it will be a garbled mess of fast clicking and noise.

**Comment by RVC-Boss** [comment]
Would you mind upload your audio so that I can try to check if there are bugs in the codes?

**Comment by kazuviking2** [comment]
One is from wav to mp3, another is from mp3 to mp3. This happens with all 3 HP models. The files haven't been renamed.
[glitched audio.zip](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/11636315/glitched.audio.zip)

**Comment by RVC-Boss** [comment]
I will fix this issue in the next version.
The export of mp3/m4a/ogg will be by ffmpeg.
