### ISSUE TITLE
Exception error in Step3 when launching "One Click Training"

### ISSUE THREAD

**Issue by melodystar2022** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#423]
Hello ,

I have an exception when clicking in "One Click Training"

when I launch the Application I have the following message under GPU information :
Unfortunately, you don't have a GPU to help you train

I attach the full log for the execution that I made

Could you please check , how Can I avoid this issue , or tell me what is needed to be able to generate he model in my case with the configuration that I have

Thanks in advance,
[log_03062023.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/11643531/log_03062023.log)

Melody start

**Comment by RVC-Boss** [comment]
\u202aD:\\RVC\\data
The exp_name path is not correct
