### ISSUE TITLE
Older v2 models don't have their .index end with '_v2'

### ISSUE THREAD

**Issue by kalomaze** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#426]
How much did the generation change? I have a v2 model with a .index that doesn't end in _v2. Should I regenerate that, or is it just a filename thing?

**Comment by RVC-Boss** [comment]
It's just a filename thing for you easier to classify the version, no need care too much about it

**Comment by kalomaze** [comment]
Then why is my regeneration I did on the same model different beyond just the filename? The md5 hashes do not match.
