### ISSUE TITLE
More UVR5 Models

### ISSUE THREAD

**Issue by AWAS666** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#428]
It would be great to have a greater variety of UVR5 models.
Especially the Kim Vocal ones are top notch in their own regard.

Could someone please either add them or provide a conversion tool to convert to .onnx models to the .pth models used in this repo.

**Comment by kazuviking2** [comment]
MVSEP-MDX23 would be a great addition

**Comment by sethtallen** [comment]
Place the .pth files into the uvr5_weights directory.
