### ISSUE TITLE
Error while preprocessing data

### ISSUE THREAD

**Issue by ariikamusic** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#432]
After updating RVC, I suddenly received this error while preprocessing.

Use Language: en_US
16系/10系显卡和P40强制单精度
Running on local URL:  http://0.0.0.0:7865
python trainset_preprocess_pipeline_print.py F:\Suzu 1 40000 12 E:\RVC-beta/logs/Suzu-7min False
Traceback (most recent call last):
  File "E:\RVC-beta\trainset_preprocess_pipeline_print.py", line 20, in <module>
    f = open("%s/preprocess.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: '12/preprocess.log'

Any ideas? Thanks in advance

**Comment by MicheleGuidi** [comment]
Do you have any spaces in your path name? Try removing them and adding quotes before and after when setting the path inside Train tab.

**Comment by ariikamusic** [comment]
> Do you have any spaces in your path name? Try removing them and adding quotes before and after when setting the path inside Train tab.

Ah, that seemed to have solved the issue. Much appreciated!
