### ISSUE TITLE
 ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by Iory1998** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#435]
Hi, 

I used the RVC webui that I unzipped from the RVC-beta.7z folder, and it did work fine, until now...

When I tried to train the model on a new (or even the old dataset that I used previously), I get the following error message:
D:\Git\RVC_WebUI>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
runtime\python.exe trainset_preprocess_pipeline_print.py D:\Git\RVC_WebUI\AK_Training\Singing Dataset 40000 20 D:\Git\RVC_WebUI/logs/mi-test False
Traceback (most recent call last):
  File "D:\Git\RVC_WebUI\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'Dataset'

I thought that maybe the folder was altered or something, so I uncompressed the RVC-beta.7z folder one again and run the webui from it, but again I get the same error message
Could you please tell me what went wrong? 

P.S. I am running both the AUTOMATIC1111 and Oobabooga WebUIs. Could that be an issue?

**Comment by Iory1998** [comment]
[UPDATE] I just changed shortened the name of the Dataset so it does not include any spacing in the folder, and that did the trick.

**Comment by B-Skizzle** [comment]
Thanks! That helped me out.

**Comment by Galaxy1878** [comment]
i found out that "_" are causing the issue too so its better if  you remove every sign from the path

**Comment by Seunfunmi12** [comment]
please how do you change C:\ to D:\

**Comment by StrawsandBerrees** [comment]
> please how do you change C:\ to D:\

You unzip the folder into your D drive directly afaik, it's what I did

**Comment by Niebieski250** [comment]
Can someone help? I get this error even if a name is valid and the folder localization is correct
