### ISSUE TITLE
点击 “训练特征索引” 之后系统崩溃重启

### ISSUE THREAD

**Issue by 493Arceus** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#440]
使用v2版本跑的训练，前面所有的训练都没问题，当点击训练特征索引，输出信息显示training过后几秒钟，系统就直接崩溃重启了。这边也不知道哪里可以找到训练索引的log，所以无法提供日志定位问题，希望有dalao能提供帮助

系统版本：Windows 11 22H2
GPU：4090
内存：64G
磁盘剩余空间：300G+

**Comment by RVC-Boss** [comment]
诡异。难道是爆内存了，但是64G内存已经很大了。你的训练集有几个小时？

**Comment by 493Arceus** [comment]
训练集都是小文件，总时长是一小时2分，训练前内存已经占用掉大概40G了

**Comment by 493Arceus** [comment]
会不会是显卡驱动导致的问题，我安装的是最新版的Studio驱动

**Comment by 493Arceus** [comment]
之前都是跑1000轮的，今天跑了个750轮的也是崩了，是训练集数据太多了的原因吗？大概有646个文件

**Comment by 493Arceus** [comment]
文件缩减到了280个，跑了850轮，训练特征索引的时候还是崩溃

**Comment by RVC-Boss** [comment]
你的faiss是cpu版本的吗

**Comment by 493Arceus** [comment]
应该是，我直接pip install -r了requirements.txt

**Comment by 493Arceus** [comment]
faiss是cpu版本的，然后我发现了一个问题，150个文件总时长23分钟，跑200轮没问题，可以生成索引。之后再次训练跑到500轮生成索引就会崩溃

**Comment by 493Arceus** [comment]
发现了，只有当训练集较多的时候才会出现这种问题，少的时候不会

**Comment by 493Arceus** [comment]
fixed at 230618v2
