### ISSUE TITLE
可以文字轉語音嗎?

### ISSUE THREAD

**Issue by CiaShangLin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#442]
我訓練好我的語音後.pth檔
只能音檔轉音檔嗎?
可以是文字檔然後用這個模型輸出嗎?

**Comment by tomiezhang** [comment]
同求，简单的tts就可以

**Comment by Namarimizu** [comment]
网上随便搜个你觉得靠谱的TTS就行，比如微软那些

**Comment by RVC-Boss** [comment]
先找一个tts出来语义、语气、语调、情感，然后再用rvc转换到你需要的音色。

**Comment by josoonfe** [comment]
> 先找一个tts出来语义、语气、语调、情感，然后再用rvc转换成你需要的音色。

有好用的tts能介绍一个不？
