### ISSUE TITLE
 Is it possible to run without gui in the console?

### ISSUE THREAD

**Issue by Citramones** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#445]
in svc it is possible to put it through the console using svc infer --input_path --output_path is it possible to do this in rvc using different parameters?

**Comment by RVC-Boss** [comment]
https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer-v2-0528.py

**Comment by xDayTripperx** [comment]
> https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer-v2-0528.py

this option doesn't work and provides an error described in [this](https://huggingface.co/lj1995/VoiceConversionWebUI/discussions/4) issue on HuggingFace

**Comment by Citramones** [comment]
> https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer-v2-0528.py

any other options?
