### ISSUE TITLE
How to fix "torch.cuda.OutOfMemoryError"

### ISSUE THREAD

**Issue by Raphy0218** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#447]
I push "One click training" then window said "training index" then I see command prompt then command prompt said↓

"torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 1; 4.00 GiB total capacity; 3.45 GiB already allocated; 0 bytes free; 3.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

What is wrong? And how to fix 0 bytes? Where has "max_split_size_mb"?

**Comment by RainaObi** [comment]
Is only failing at index training or is it also failing while doing the model training? You could try reducing the batch size or changing the dataset.
