### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Compressed\\RVC-beta-v2-0528/logs/mute/0_gt_wavs/mute40k.wav'

### ISSUE THREAD

**Issue by ANRTNT** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#452]
I got this error after training here is the full report:

```
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\Compressed\RVC-beta-v2-0528\train_nsf_sim_cache_sid_load_pretrain.py", line 107, in run
    train_dataset = TextAudioLoaderMultiNSFsid(hps.data.training_files, hps.data)
  File "D:\Compressed\RVC-beta-v2-0528\train\data_utils.py", line 27, in __init__
    self._filter()
  File "D:\Compressed\RVC-beta-v2-0528\train\data_utils.py", line 41, in _filter
    lengths.append(os.path.getsize(audiopath) // (2 * self.hop_length))
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Compressed\\RVC-beta-v2-0528/logs/mute/0_gt_wavs/mute40k.wav'
```

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/tree/main/logs/mute
Download these.

**Comment by ANRTNT** [comment]
> https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/tree/main/logs/mute Download these.

where is the download button?

**Comment by RVC-Boss** [comment]
> > https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/tree/main/logs/mute Download these.
> 
> where is the download button?

I uploaded it to huggingface. Now you can try this.
https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/mute.zip

**Comment by DuckersMcQuack** [comment]
> > > https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/tree/main/logs/mute Download these.
> > 
> > 
> > where is the download button?
> 
> @ANRTNT I uploaded it to huggingface. Now you can try this. https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/mute.zip

tried it, still the same error on my end. Both forward and backward slashes. No spaces in any folder nor file names
