### ISSUE TITLE
why is my epoch making keep getting slower?

### ISSUE THREAD

**Issue by ANRTNT** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#457]
First time when I used to train, It only took 1:20 min to complete each epoch. then it took 6:30 min and then 10:00 min for each

What possibility could it have to become like this?

**Comment by RVC-Boss** [comment]
Same issue:https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/467
The training speed is too fast: It may be caused by some other issues before training. (step1/step2 folder, wav/npy files missing)
You can check the log or command window.
