### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Vasheus** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#459]
when i click one click training at first it was can't find specified paths for certain i tried moving files manuallly from muted to my to ecperiment name folder and after that i repeated the one click training and it's an index error

**Comment by Donkarlon** [comment]
any luck?

**Comment by Liav-Tausi** [comment]
here as well

**Comment by skinnynpale** [comment]
+1
