### ISSUE TITLE
"ImportError: No module named scipy" on step 2a

### ISSUE THREAD

**Issue by Mshriver2** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#463]
When I attempt to click the "process data" button under the "Train" tab, I get the following error in terminal 
```
Traceback (most recent call last):
  File "trainset_preprocess_pipeline_print.py", line 2, in <module>
    from scipy import signal
ImportError: No module named scipy
```

Any ideas what I can do to fix it? scipy is already shown as installed.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/3216992/74e65093-aa65-4e46-9266-f08a175a3829)

**Comment by Mshriver2** [comment]
I have my training folder path set to this folder full of vocal only .wavs (don't know why they say instrumental but they are only vocal)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/3216992/7dda92bf-f5ca-4c99-8115-607a61314432)

**Comment by Mshriver2** [comment]
When running the scipy import command in the python3 interrupter I get the following. So it looks like it is installed so I am a bit confused of what the issue is.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/3216992/0858c378-e430-4242-8a0f-107b9e74f2c6)

**Comment by Mshriver2** [comment]
This is the specific error that goes in the console when clicking "process data".
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/3216992/cdaa09f6-7efd-4b5f-bed4-98db0912052d)

**Comment by i3l3** [comment]
`pip install scipy`

**Comment by Mshriver2** [comment]
> `pip install scipy`

I have done both "pip install scipy" and "pip3 install scipy" both say they are already installed.

**Comment by Mshriver2** [comment]
If I open a python terminal and do "from scipy import signal" it works just fine without error. However when I try to "process data" I get the error that their is no module. So I am very confused to what is happening. I pulled the latest commit today and the issue is still happening.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/3216992/fbf798fc-7e55-4d81-b404-027c005f3f9d)

**Comment by ping42** [comment]
I think it is trying to run the underlying script with python 2, which is normally referred by `python` command used in the script in Linux/Mac.

You could solve this by editing line 39 in `config.py`
change
`"--pycmd", type=str, default="python", help="Python command"`
into
`"--pycmd", type=str, default="python3", help="Python command"`

which could ask the environment to run those scripts with python 3, the one you installed scipy and other packages in.

**Comment by MikuAuahDark** [comment]
I can reproduce this in Windows 11 (native) by running `venv\Scripts\python infer-web.py` directly without activating virtual environment first. The web will run but it won't able to find `scipy`.

Perhaps it tries to run `python` directly and not `sys.executable`?

**Comment by Mshriver2** [comment]
This solved my issue. Thanks guys
