### ISSUE TITLE
Endless errors 

### ISSUE THREAD

**Issue by cinnabarromance** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#467]
Well, thanks to the advice on the forum, I updated the driver for my video card and the error related to the memory of this no longer occurs. But instead, another error appears, and now there is not even an explanation for this error. As I understand it, everyone faces different errors. The question is: how to solve this and when will it work normally? I'm struggling with this program for the third day, while some people on YouTube do it in five minutes. How?

  File "D:\programms\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\torch\distributed\rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError
INFO:mi-test:====> Epoch: 7 [2023-06-07 19:01:51] | (0:02:02.778112)

**Comment by RVC-Boss** [comment]
The training speed is too fast: It may be caused by some other issues before training. (step1/step2 folder, wav/npy files missing)
You can check the log or command window.

**Comment by Caofan0** [comment]
I have the same issue. Did you solve the problem?
