### ISSUE TITLE
How to change the GPU used by RVC

### ISSUE THREAD

**Issue by Siren124** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#470]
How to change the GPU used by RVC

**Comment by RVC-Boss** [comment]
config.py
You can specify specific GPU to inference.
For training, there is a textbox. "0-1-2-3" like this.

**Comment by ymmbb8882ymmbb** [comment]
那怎样进行多gpu训练呢，现在显示是超出索引错误
