### ISSUE TITLE
[BUG]python-CFFI

### ISSUE THREAD

**Issue by Siren124** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#471]
Python-CFFI error
×
Exception ignored from cffi callback <function
_StreamBase._init_.<locals>.callback_ptr at Ox000001345CFB7790>:Traceback (most recent call last):
File "F:RVC-beta-v2-0528yruntime\libysite-packagesjsounddevice.py""line 886, in callback_ptr
return _wrap_callback(
File "F:\RvC-beta-v2-0528yruntimevlibisite-packagesjsounddevice.py".line 2687, in _wrap_callback
callback(*args)
File "F:RVC-beta-v2-05281gui.py", line 508, in audio_callbackself.rvc.infer(self.resampler1(torch.from_numpy(self.input_wav)”)File "F:RVC-beta-v2-0528gui.py", line 160, in infer
logits = self.model.extract_features(**inputs)
File
"F:ARVC-beta-v2-0528%runtime\libysite-packagesifairseq\modelsihubertthubert.py", line 535, in extract_features
res = self.forward(
File
"F:RVC-beta-v2-0528runtime\libysite-packagesifairseqymodelshuberthubert.py", line 437, in forward
features = self.forward_features(source)File
"F:RVC-beta-v2-0528%runtime\libysite-packagesifairseq\models\hubertthubert.py", line 392, in forward_features
features = self.feature_extractor(source)File
"F:RVC-beta-v2-0528yruntime\libysite-packagesjtorchinnimodules\module.py", line 1501, in_call_impl
return forward_call(*args,**kwargs)File
"F:RVC-beta-v2-0528yruntime\lib\site-packagesifairseqymodels\wav2vec]wav2vec2.py", line 895, in forward
x = conv(x)
File
"F:RVC-beta-v2-0528%runtime\libisite-packages\torch\nn\modulesimodule.py", line 1501, in_call_impl
return forward_call(*args, **kwargs)File
"F:RVC-beta-v2-0528yruntime\libysite-packages\torch\nnimodules\container.py", line 217, in forward
input = module(input)
File
"F:RVC-beta-v2-0528关runtime\libysite-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)File
"F:}RVC-beta-v2-0528关runtime\libysite-packages\torch\nnkmodules\conv.py", line 313, in forward
return self._conv_forward(input, self. weight, self.bias)File
"F:{RVC-beta-v2-0528%runtime\libysite-packagesjtorchinnimodulesyconv.py", line 3o9, in _conv_forward
return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type(torch.cuda.FloatTensor) should be the same
确定

**Comment by RVC-Boss** [comment]
Update the lastest gui.py，it will automatically use the right precesion.
