### ISSUE TITLE
ImportError: DLL load failed while importing _ufuncs: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by yukgor** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#472]
纯小白，救救孩子吧，能装的都装了，一直执行go-web.bat一直提示：ImportError: DLL load failed while importing _ufuncs: %1 不是有效的 Win32 应用程序。
![Snipaste_2023-06-08_02-34-29](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/118077453/498ab366-f921-4f73-95a6-9313a91f7295)

**Comment by RVC-Boss** [comment]
系统是啥？

**Comment by yukgor** [comment]
> 系统是啥？

Windows 11专业版22H2(22621.1778)

**Comment by yukgor** [comment]
重启电脑又正好了。
