### ISSUE TITLE
__array_function__ internals

### ISSUE THREAD

**Issue by helpmeoricry** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#474]
File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

concatewhat?????

**Comment by helpmeoricry** [comment]
this is showing up when i'm loading the One click training

**Comment by xPr0xi** [comment]
Same, currently using 20 minutes of training data, assumed that would be enough.

**Comment by RVC-Boss** [comment]
OSError: Model file not found: hubert_base.pt
Maybe you need rename it to hubert_base.pth

**Comment by xPr0xi** [comment]
> OSError: Model file not found: hubert_base.pt Maybe you need rename it to hubert_base.pth

Yep got it working I think, thx (still training, but seems to be actually running now)

**Comment by Duonic** [comment]
> > OSError: Model file not found: hubert_base.pt Maybe you need rename it to hubert_base.pth
> 
> Yep got it working I think, thx (still training, but seems to be actually running now)

Hey, can you please explain how you ended up making it work? Just by renaming the file from pt to pth?

**Comment by xPr0xi** [comment]
For me, hubert_base.pt had disappeared entirely from my dir (unsure how), so just simply replacing it fixed the issue. Idk that it matters whether its name .pt or .pth

Not sure what to tell you sorry
