### ISSUE TITLE
生成的歌声有很多电音和沙哑的声音

### ISSUE THREAD

**Issue by Luke9086** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#483]
这是怎么回事？
我用了24分钟的数据

**Comment by Luke9086** [comment]
【【AI陶喆】Cover遇见】 https://www.bilibili.com/video/BV14o4y1T7nJ/?share_source=copy_web&vd_source=043dbfd9d31c8a90293bfecb9f97b67c
这个是成品，我觉得不满意。可莉的声音就没问题。我再检查一下
【【AI可莉】Cover-我会自己上厕所】 https://www.bilibili.com/video/BV1Zh4y19735/?share_source=copy_web&vd_source=043dbfd9d31c8a90293bfecb9f97b67c

**Comment by RVC-Boss** [comment]
> 我觉得可能是训练集里有一些和声没去除干净。

区和生可以试试webui包里的去伴奏-HP5模型
