### ISSUE TITLE
能训练自己的底模吗

### ISSUE THREAD

**Issue by yellow122** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#489]
不知道一开始的两个D、G底模是怎么训练的，想要用自己的训练集训练底模。是不是找个单人比较大的训练集训练完以后的模型可以当做自己的底模？

**Comment by ms903x1** [comment]
等多说话人出来吧

**Comment by liziru** [comment]
> 等多说话人出来吧

@ms903x1 你好，感谢工作，请问多说话人模型啥时候出来

**Comment by wuhai2438187057** [comment]
可以，挺容易的，多说人模型而已，我都练了两个了
