### ISSUE TITLE
有考虑过webui用tensorRT推理，手机端用ncnn推理吗？

### ISSUE THREAD

**Issue by nonametao** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#490]

**Comment by nonametao** [comment]
用pytorch推理效率感觉会比较低？顺便问下模型剪枝有没有搞

**Comment by RVC-Boss** [comment]
大佬可以来贡献代码的呢
确实有这个需求

**Comment by pamzerbhu** [comment]
tensorRT现在在做吗？我现在正在做Dx ml的推理，这样可以支持intel amd的卡了

**Comment by nonametao** [comment]
准备今天开始动工，话说有没有个开发者群啥的 沟通方便一点



---原始邮件---
发件人: "Zhang, ***@***.***&gt;
发送时间: 2023年6月10日(周六) 凌晨1:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RVC-Project/Retrieval-based-Voice-Conversion-WebUI] 有考虑过webui用tensorRT推理，手机端用ncnn推理吗？ (Issue #490)




 
tensorRT现在在做吗？我现在正在做Dx ml的推理，这样可以支持intel amd的卡了

**Comment by pamzerbhu** [comment]
咱俩先加上把，我也没进开发者群

**Comment by nonametao** [comment]
OK，你直接加我qq就好



---原始邮件---
发件人: "Zhang, ***@***.***&gt;
发送时间: 2023年6月10日(周六) 中午1:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RVC-Project/Retrieval-based-Voice-Conversion-WebUI] 有考虑过webui用tensorRT推理，手机端用ncnn推理吗？ (Issue #490)




 
咱俩先加上把，我也没进开发者群

**Comment by pamzerbhu** [comment]
多少

**Comment by nonametao** [comment]
761048532

**Comment by Yaodada12** [comment]
@nonametao @pamzerbhu @RVC-Boss 大佬们进展如何啊？我最近在做RVC的mac端部署，但是发现hubert模型转不了coreml。大佬们有尝试嘛？这里是我遇到的问题：[https://github.com/apple/coremltools/issues/2099](url)
