### ISSUE TITLE
Empty Weights Folder

### ISSUE THREAD

**Issue by Arthwick** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#495]
Under the train tab, I set the setting on step 3 to save a small finished model to the "weights" directory for every epoch matching the specified "save frequency". And I set my settings and clicked on one-click training and saw that my Retrieval-based Voice Conversion WebUI was working when it was finished it said "all-feature-done" and it was really quick which was a red flag because I assumed the processing time would be much longer but it was quick. I go to the weights folder to find nothing. It seems like the one-click-training didn't complete and I don't really know what is happening or what to do. 

all-feature-456
all-feature-done

**Comment by AleDZMP** [comment]
Same here
