### ISSUE TITLE
萌新不懂就问为啥训练的48k会报错这个

### ISSUE THREAD

**Issue by fatexeno** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#498]
![UO)T~H`7E@O2`UP7H ~PQ@A](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/126556591/28e0d225-ee33-40bf-804e-0b6cd0d4ad3e)
![K639S9F4C1@ P}A){K4W48V](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/126556591/7e8a092b-ad82-486f-8f9b-b85c8697a7f7)

**Comment by fatexeno** [comment]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/126556591/57fc60f8-05b0-444b-8ff7-8de0216bb846)

**Comment by RVC-Boss** [comment]
跟48k没关系
索引用added
