### ISSUE TITLE
[Feature request] Segmentation of audio based on parts to improve vocal output of long songs

### ISSUE THREAD

**Issue by kalomaze** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#502]
There could be an advanced setting that detects where silence happens based on a threshold, and does each inference of long vocal pieces separately, then properly combines it into one full output audio. This would help for some songs, especially ones with long quiet sections, as those can have issues with strange raspiness and cutting in and out when returning to vocals after long silent periods (though it is quite rare.)

There would also likely be positive mild improvements in the non-extreme cases of better inference audio, as it would more closely match the training data (in length). The silence detection could be somewhat long, and require, let's say, over 1 seconds of silence under -40db in order for it to start another segmented 'piece.'

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/66376113/f1951291-e1f4-41a6-9d4e-8742a28e364b)

This would also prevent errors on longer pieces of audio in the vast majority of cases. If possible, a segment could be 'force split up' if it exceeds an extremely long length (Let's say, 5 minutes of uninterrupted speaking.)

You could call this setting 'Auto-segment' and mention in the blurb that it is meant to improve inference quality and increase possibilities of longer audio. You could also mention that it may take longer due to processing separately.

**Comment by RVC-Boss** [comment]
Good idea.

**Comment by kalomaze** [comment]
One thing I might add, for non GPU / limited RAM systems, there could be a compatibility mode tick that will segment as much as possible to prevent errors and has lower criteria for segmenting. Let's say 0.5s of silence is the segment threshold, for example. And the maximum length of a segment is 15s or 30s, or something around that length. To prevent abrupt cutoffs, you could make it cut at the center of the quietest average 0.25s in the segment and start the next segment from that point. Either that, or the numbers are directly configurable within the GUI.

**Comment by RVC-Boss** [comment]
'advanced settings' good idea

**Comment by epietrocola** [comment]
Is there any news regarding this? I tried to infer a 6 minutes voice file with a lot of silence between sentences and the inference quality of the result is way lower than the quality I get when using a single wavefile of 4 seconds extracted from the same previous long file
