### ISSUE TITLE
Inferencing voice dropdown is empty

### ISSUE THREAD

**Issue by RodgerE1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#503]
I've updated the project as per the instructions, but the 'Inferencing voice:' dropdown in the WebUI is still empty. I've also downloaded and loaded the pre-trained models as instructed. Could you please help me resolve this issue?

**Comment by RodgerE1** [comment]
Ignore that comment above please. ChatGPT-4 made it automatically and I think we should keep it as evidence. If anyone is curious:  https://www.reddit.com/r/OpenAI/comments/146xl6u/this_is_scary_posting_stuff_by_itself/?utm_source=reddit&utm_medium=usertext&utm_name=ChatGPT&utm_content=t1_jntbuhu

**Comment by noobAIcoder** [comment]
Evidence that GPT-4 can use plugins?

**Comment by sethtallen** [comment]
I'm not really sure what you're talking about regarding ChatGPT-4, what steps you took that didn't work, or if you still have an issue. 
You need to put the .pth file of your model under the models/ directory, and ensure that your .index files are placed under logs/[model name]/ to select during infer. Refresh the voice list. It should list everything under models/

**Comment by RodgerE1** [comment]
I got it working thank you! While I was working on it I was testing GPT-4 and put one of the errors in. Instead of searching for the answer it auto posted that message. It's not supposed to do that without permission.

**Comment by drumtard** [comment]
I don't have a models/ directory in the rvc folder. I'm so confused 😭

**Comment by drumtard** [comment]
and where would my .pth file be? i can't see it. i only see the index files in the logs/ directory

**Comment by sethtallen** [comment]
@drumtard Apologies- I meant the weights directory, not the models directory. After you generate a model there should be a [model_name].pth file in there. If you're importing a model that someone else generated, you'd put it in that directory.

**Comment by kronkinatorix** [comment]
where dot he index files come from? 

What do they contain? I'm looking to fiinfer from a pretrained model - I ca;n't fiond bupkis about thj einmdex file.s

**Comment by navid3a** [comment]
The same is happening to me too! The drop-down menu is empty and I couldn’t find the .pth file 😕

**Comment by jarwix** [comment]
File .pth should be in the "weights" folder. Next, it should appear in the menu "Inferencing voice".
