### ISSUE TITLE
Error on m1 Mac mini with macOS Ventura 13.4

### ISSUE THREAD

**Issue by iamqk** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#506]
Release [updated0528v2](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases/tag/updated0528v2)

when install dependency use pip install -r requirements.txt or manually install onnxruntime-gpu(I think this pack do not support Mac)

will give error:
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu

**Comment by ping42** [comment]
perhaps you can try to install onnxruntime instead of onnxruntime-gpu
`pip install onnxruntime`

**Comment by iamqk** [comment]
> perhaps you can try to install onnxruntime instead of onnxruntime-gpu
> `pip install onnxruntime`

Thx that fix the problem
