### ISSUE TITLE
Wrong naming for HP3 model output files. 使用HP3模型分离人声伴奏时，输出的文件命名错误。

### ISSUE THREAD

**Issue by XiangyiZhang** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#509]
When using HP3 model to split instrument and vocal, the _vocal_ audio is the instument, while the _instrument_ file is the vocal.
使用HP3模型分离人声伴奏时，opt/下的instrument音频实际上是人声，vocal是伴奏。其他模型则不会有这个问题。

**Comment by RVC-Boss** [comment]
我注意到了，以后有空修复一下。
