### ISSUE TITLE
Question on further training...

### ISSUE THREAD

**Issue by T-oasterO-ven** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#511]
Using the final saved G and D pth files under the logs 
would it be possible to continue training with an expanded dataset (i.e. same audio file but updated with additional audio from the same voice at the end of the wav file) or would it negatively effect the results of the training?

**Comment by RVC-Boss** [comment]
Add data and continue training:
e.g.
exp1:
  data_a,exp_name:data_a
exp2:
  data_a+data_b
you can create another exp named data_a+b
and copy the latest G and D from data_a to data_a+b (also data path you should use the all data path)
click one-key training, the exp will process all data, exact all feature, and continue training from G and D.

**Comment by ayaayams** [comment]
> باستخدام ملفات G و D pth النهائية المحفوظة ضمن السجلات ، سيكون من الممكن مواصلة التدريب باستخدام مجموعة بيانات موسعة (أي نفس الملف الصوتي ولكن يتم تحديثه بصوت إضافي من نفس الصوت في نهاية ملف wav) أو سيكون له تأثير سلبي نتائج التدريب؟

Can you explain to me how to add the sound after I installed the tool and the interface appeared, or send me a video explaining how to bring files PHT and config
