### ISSUE TITLE
After training the model with one-click training, run go-realtime-gui.bat, and the program exits when you click Start Audio Conversion.

### ISSUE THREAD

**Issue by wulusai2333** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#516]
使用一键训练训练好了模型,运行`go-realtime-gui.bat`,配置好了,点击`开始音频转换`时程序退出
模型训练采样率为默认的40k和48k,使用的显卡`NVIDIA GeForce RTX 3090`,填好`输入训练文件夹路径`使用一键训练,其他配置没有变动
`D:\project\RVC-beta\RVC-beta-v2-0528>runtime\python.exe gui.py
input device:1:麦克风 (HUAWEI USB-C HEADSET) (MME)
output device:5:Realtek Digital Output (Realtek (MME)
{'hubert_path': 'hubert_base.pt', 'pth_path': 'logs\\ganyu48\\G_2220.pth', 'index_path': 'logs\\ganyu48\\added_IVF3435_Flat_nprobe_1_ganyu48_v1.index', 'npy_path': "你不需要填写这个You don't need write this.", 'pitch': 12.0, 'samplerate': 44100, 'block_time': 1.0, 'buffer_num': 1, 'threhold': -30.0, 'crossfade_time': 0.08, 'extra_time': 0.05, 'I_noise_reduce': False, 'O_noise_reduce': False, 'index_rate': 0.5}
using_cuda:True
index search enabled
load model(s) from hubert_base.pt
Traceback (most recent call last):
  File "D:\project\RVC-beta\RVC-beta-v2-0528\gui.py", line 79, in __init__
    self.tgt_sr = cpt["config"][-1]
KeyError: 'config'`

**Comment by RVC-Boss** [comment]
选错模型了，在weights下头找

**Comment by wulusai2333** [comment]
非常感谢,已经解决了 @RVC-Boss
