### ISSUE TITLE
Sound Module?

### ISSUE THREAD

**Issue by Mal009** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#523]
I'm trying to install and I keep getting this

Traceback (most recent call last):
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 24, in <module>
    from MDXNet import MDXNetDereverb
  File "C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\MDXNet.py", line 1, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'
PS C:\TCHT\Retrieval-based-Voice-Conversion-WebUI>

is what I keep getting, any clues?

**Comment by zSenzy** [comment]
Came here to search for the same answer

**Comment by Efendiminati** [comment]
not a dev but i saw the error caused by requirment of "microsoft c++ 14.0 or greater" in the dialogue  so i downloaded the build tool from microsoft site and it solved the problem for me 

https://visualstudio.microsoft.com/visual-cpp-build-tools/ - visual studio build tools

**Comment by kevinhuerterscousin** [comment]
can anyone help me with what specifically i have to download in the visual studio build?

**Comment by RVC-Boss** [comment]
You can update the code to the latest main branch, where this version dependency issue has already been resolved.
