### ISSUE TITLE
Web inference fails due to insufficient memory

### ISSUE THREAD

**Issue by c469591** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#525]
Web inference fails due to insufficient memory

**Comment by c469591** [comment]
I have friends using 4g graphics card and 6g graphics card, in the time of pushing the situation of insufficient memory

**Comment by RVC-Boss** [comment]
reduce batch size

**Comment by c469591** [comment]
Can we add the parameter for reasoning to the reverse webpage in the future? Currently, the method involves directly modifying config.py, which is less convenient. Thank you.
