### ISSUE TITLE
最新版本的 go-realtime-gui.bat 运行知乎按任意键以后会退出程序。

### ISSUE THREAD

**Issue by 2354452553** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#527]
E:\RVC-beta-v2-0528>E:\RVC-beta-v2-0528\runtime\python.exe gui.py

E:\RVC-beta-v2-0528>pause
请按任意键继续. . .

**Comment by wally94** [comment]
> E:\RVC-beta-v2-0528>E:\RVC-beta-v2-0528\runtime\python.exe gui.py
> 
> E:\RVC-beta-v2-0528>pause
> 请按任意键继续. . .

应该是没有输入设备，也就是没有麦克风。装个虚拟声卡试试

**Comment by 2354452553** [comment]
> > E:\RVC-beta-v2-0528>E:\RVC-beta-v2-0528\runtime\python.exe gui.py
> > E:\RVC-beta-v2-0528>pause
> > 请按意键继续。. .
> 
> 应该是没有输入设备，也就是没有麦克风。装个虚拟声卡考试

问题解决了

**Comment by 2354452553** [comment]
try捕获了一下错误，提示的是`'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte`，经过大佬提示，更改了位于系统设置中的国家地区中的高级设置，里面有一个utf-8的编码设置，打上对钩重启电脑OK了

**Comment by ArtoriaShu** [comment]
> 

感谢，已解决问题

**Comment by FrosenMercure** [comment]
按照上述操作全部进行一次之后仍然有pause，这个怎么解决呀，有大佬知道吗

**Comment by cooper1x** [comment]
> 按照上述操作全部进行一次之后仍然有pause，这个怎么解决呀，有大佬知道吗

我也是这个问题，怎么解决啊

**Comment by alltales** [comment]
66666
