### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by cinnabarromance** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#529]
I got to Model Inference, and then this happened. What should I do?

Traceback (most recent call last):
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\infer-web.py", line 161, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

Traceback (most recent call last):
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "D:\programms\RVC-beta\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by VAM-Kitten** [comment]
I get the same error. Standalone, latest version.

**Comment by Ma5onic** [comment]
@VAM-Kitten, I tried that but still get the error 😢

**Comment by Rainbowgunsh** [comment]
@VAM-Kitten I trained it with it set to TRUE and I still get the error

**Comment by cinnabarromance** [comment]
> I get the same error. Standalone, latest version. I have the FFMPEG in the system path.
> 
> EDIT: This error only happens if you use model that has been trained with the 'model pitch guidance' set to FALSE. If you want to use that model, you have to set "Protect the artifact of voiceless consonant and breath. 0.5: don' use it. The number smaller, the stronger protection." to **0.5** - the error goes away.

It is not working, I tried too.

**Comment by yingshow** [comment]
I have the same problem, how to solve it?

**Comment by cinnabarromance** [comment]
It seems that this problem just went down due to new problems that appeared. BUT I still have not found an answer and a solution to the problem, like other users. What to do?

**Comment by Ma5onic** [comment]
If you are on windows make sure that your path has a `\` at the end. 
You will also get this error if the audio can't be found.

**Comment by cinnabarromance** [comment]
> If you are on windows make sure that your path has a `\` at the end. You will also get this error if the audio can't be found.

This error persists no matter what I do. I correctly indicated the address and the name of the song, I subtracted the values, as mentioned above. Nothing works.

**Comment by Phxlnk1** [comment]
I believe I have found the fix, download hubert_base.pt here:

https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main
and place it in the same directory as go-web.bat

restart the webui and try again, seems to have fixed my issue. voice doesn't sound as i expected but it may just be bad training on my end

**Comment by Rainbowgunsh** [comment]
> I believe I have found the fix, download hubert_base.pt here:
> 
> https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main and place it in the same directory as go-web.bat
> 
> restart the webui and try again, seems to have fixed my issue. voice doesn't sound as i expected but it may just be bad training on my end

Mine already had that file in the right place originally and when I did it again replacing the original file with the new one you referenced (incase it got updated)  still didn't work :(

**Comment by Phxlnk1** [comment]
> > I believe I have found the fix, download hubert_base.pt here:
> > https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main and place it in the same directory as go-web.bat
> > restart the webui and try again, seems to have fixed my issue. voice doesn't sound as i expected but it may just be bad training on my end
> 
> Mine already had that file in the right place originally and when I did it again replacing the original file with the new one you referenced (incase it got updated) still didn't work :(

ah, sorry to hear. It seems for me my download did not contain all the necessary files

I've seen some suggestions in other threads stating you might have luck by removing spaces from the input file name and making sure it's .wav, perhaps try downloading someone else's model and weights to see if it could be model dependent?

**Comment by Rainbowgunsh** [comment]
> I've seen some suggestions in other threads stating you might have luck by removing spaces from the input file name and making sure it's .wav, perhaps try downloading someone else's model and weights to see if it could be model dependent?

tried with a few different models but still no luck :(

**Comment by leaper-max** [comment]
> I get the same error. Standalone, latest version. I have the FFMPEG in the system path.
> 
> EDIT: This error only happens if you use model that has been trained with the 'model pitch guidance' set to FALSE. If you want to use that model, you have to set "Protect the artifact of voiceless consonant and breath. 0.5: don' use it. The number smaller, the stronger protection." to **0.5** - the error goes away.

I've trained my model with pitch guidance. I Tried 0 protection 0.33 and 0.5, harvest crepe and pm give the same error.
Anyone had luck in solving this?

**Comment by Rainbowgunsh** [comment]
I fixed the issue. You need to add ".wav" to the end of your file (if wav) EXAMPLE: \instrument_Balling song.mp3_10.wav <-- add wav to end of directory NOT rename. If mp3 do ".mp3" etc etc

**Comment by youngboi2C** [comment]
>  I fixed the issue. You need to add ".wav" to the end of your file (if wav) EXAMPLE: \instrument_Balling song.mp3_10.wav <-- add wav to end of directory NOT rename. If mp3 do ".mp3" etc etc

I'm sorry, I don't quite understand what you said. Do I need to add a .wav suffix to the filename of the wav file?

**Comment by nightwalkerrrrr** [comment]
> > I fixed the issue. You need to add ".wav" to the end of your file (if wav) EXAMPLE: \instrument_Balling song.mp3_10.wav <-- add wav to end of directory NOT rename. If mp3 do ".mp3" etc etc
> 
> I'm sorry, I don't quite understand what you said. Do I need to add a .wav suffix to the filename of the wav file?

What he's saying is you have to add the file type suffix when entering the path for the file in the PROGRAM, so D:\acapella\vocals.wav not D:\acapella or D:\acapella\vocals

**Comment by Chaoriticle** [comment]
提醒一下各位，我出现这个问题是因为没有选择推理音色，以为只要选择index路径就可以。顺便一提，模型文件最好直接放在`weight`文件夹下，否则无法查找到。

> As a reminder, I had this problem because I didn't select the inference tone, thinking that I just had to select the index path. By the way, it's best to put the model files directly under the `weight` folder, otherwise they won't be found.

**Comment by Hellzicke** [comment]
It might be a GPU error?
I had exact same issue with my GTX 980 Ti 6gb, problem gone with my RTX 4070 12gb

**Comment by gigamesh** [comment]
I'm getting this with every model I've found. I tried the suggestions above (file name is "vox.wav"). 

Any other ideas?

**Comment by ardanimo** [comment]
Using HP2 instead of HP3 to seperate vocals solved it for me.

**Comment by ClasSiXdAk1nG** [comment]
> > > I fixed the issue. You need to add ".wav" to the end of your file (if wav) EXAMPLE: \instrument_Balling song.mp3_10.wav <-- add wav to end of directory NOT rename. If mp3 do ".mp3" etc etc
> > 
> > 
> > I'm sorry, I don't quite understand what you said. Do I need to add a .wav suffix to the filename of the wav file?
> 
> What he's saying is you have to add the file type suffix when entering the path for the file in the PROGRAM, so D:\acapella\vocals.wav not D:\acapella or D:\acapella\vocals

actually fixxed it!

**Comment by tahirsab** [comment]
i have solved this, we are doing a little mistake while choosing the path of the file. do not copy from uper bar just right click on the file we want to use and simply copy the file path, that's it

**Comment by anoneditor** [comment]
I had this problem for a while, I looked everywhere but I didn't find a solution until I solved it myself..just copy the path like this..don't use any other method..
![solotion](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/151642009/757086ab-eb46-4609-b760-4d027eef1b9b)

**Comment by anoneditor** [comment]
> I get the same error. Standalone, latest version. I have the FFMPEG in the system path.
> 
> EDIT: This error only happens if you use model that has been trained with the 'model pitch guidance' set to FALSE. If you want to use that model, you have to set "Protect the artifact of voiceless consonant and breath. 0.5: don' use it. The number smaller, the stronger protection." to **0.5** - the error goes away.

I had this problem for a while, I looked everywhere but I didn't find a solution until I solved it myself..just copy the path like this..don't use any other method.. 
I had this problem for a while, I looked everywhere but I didn't find a solution until I solved it myself..just copy the path like this..don't use any other method..
![Uploading solotion.png…]()

**Comment by bartvangogh** [comment]
I’ve had the same issue, with the dtype. I solved it by updating Python to 3.11. All issues gone!

**Comment by anoneditor** [comment]
tnx bro i did this and its working fine for now 😃♥️

**Comment by SpiderBraider** [comment]
Hey, another person having problems with this same error... Info:
* System: Windows 10
* Python 3.10.11 (doesn't work with 3.11 onwards on Windows)
* No supported GPU
* Installed dependencies with requirements-dml.txt and Visual Studio Build Tools 2022

The wav file I was testing with was 16-bit, so that isn't the issue... Swapping out backslashes for slashes didn't work either :-\

It looks like there's an error with making the pipeline in vc/modules.py, based on this error from trying to pass a single file through the batch tab:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/117629528/0b271ed7-b908-4ceb-9c42-9be9fbed7b85)

**Comment by Drausio72** [comment]
> I had this problem for a while, I looked everywhere but I didn't find a solution until I solved it myself..just copy the path like this..don't use any other method.. ![solotion](https://private-user-images.githubusercontent.com/151642009/284590182-757086ab-eb46-4609-b760-4d027eef1b9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDcwMTIsIm5iZiI6MTcxMTkwNjcxMiwicGF0aCI6Ii8xNTE2NDIwMDkvMjg0NTkwMTgyLTc1NzA4NmFiLWViNDYtNDYwOS1iNzYwLTRkMDI3ZWVmMWI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNzM4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDY3NDNjZGEzOGI2MDUxMWIwMjUyZDI0MDYzMjM3YmUwNTYwNWVlMGM1ODFhMDdhZmJhOTA2YmNjNTI2NDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UFCoW5QJsiqUqWivfjBo0ce99eI0Vb9ARcqbF2h0tYc)

Worked for me! Thanks. It gets a bit weird, though...

"C:\Users\hello\Desktop\FNM\Digging.wav.wav"

**Comment by bartvangogh** [comment]
Sometimes the same issue shows up again and I think it mistly occurs when the audio that needs to be converted is not on 44Khz, or when the audio has a silent start of more than 0.5 seconds.

**Comment by codyherzog** [comment]
Strangely, this problem went away for me when I renamed the file to have no spaces.

**Comment by codyherzog** [comment]
> Strangely, this problem went away for me when I renamed the file to have no spaces.

Update: Various non-letter characters in the file name also seem to cause this problem for me. I had a file name with dashes and it was failing until I removed the dashes. It seems safest to have paths and file names with just letters and nothing else.

**Comment by jiuexika** [comment]
In fact, just add double quotation marks to the path of the file.
