### ISSUE TITLE
What is the difference between the v1 and v2 models?

### ISSUE THREAD

**Issue by loboere** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#531]
Should I retrain the models to v2 for better quality?

**Comment by RVC-Boss** [comment]
Theoretically better quality.
You can have a try, it  doesn't cost much.

**Comment by loboere** [comment]
mm ok, is it possible to convert models v1 to v2 without training from 0?mm ok, is it possible to convert models v1 to v2 without training from 0?

**Comment by RVC-Boss** [comment]
No, the input  feature is not the same.

**Comment by niizam** [comment]
@RVC-Boss I would like to ask about training the RVC V2 model, which requires more VRAM compared to training the RVC V1 model. With a 4GB VRAM, the RVC V1 model is sufficient for training with a batch size of 1 on the GPU. However, it's not the case with the RVC V2 model. Is it possible to optimize it?
