### ISSUE TITLE
RuntimeError: Cannot install on Python version 3.11.4; only versions >=3.7,<3.11 are supported.

### ISSUE THREAD

**Issue by Hatde** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#534]
How do I install Pythons supported version so it can run?
<img width="739" alt="Runtimeerror" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/136676869/49f9e80b-4d0c-4190-b2dd-e6351d608d4b">

**Comment by RVC-Boss** [comment]
What packages were you installing when meets this version error?

**Comment by Mugen-CC** [comment]
IIRC I got this error trying to install Poetry. You have to just install a python version in that supported range.

**Comment by WezneR** [comment]
Assuming that you have installed Poetry, you can try ' poetry env use python_exe_path' before 'poetry install'.
Replace 'python_exe_path' with the path of Python excutable whose version >=3.7,<3.11.

**Comment by cliplicht** [comment]
on my ENV Python >= 3.11

1) pip install pip-upgrader
2) pip-upgrade .\requirements.txt --skip-virtualenv-check

**Comment by therealestkris** [comment]
> on my ENV Python >= 3.11
> 
> 1. pip install pip-upgrader
> 2. pip-upgrade .\requirements.txt --skip-virtualenv-check

This did the trick for me. Thank you!

**Comment by RVC-Boss** [comment]
You can update the code to the latest main branch, where this version dependency issue has already been resolved.
