### ISSUE TITLE
Can I increase epoch manually (more than 1000 epochs)? (我可以手动增加纪元吗？)

### ISSUE THREAD

**Issue by OwOisMyLife** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#539]
So yesterday I just trained with someone's voice. But the result is still like a robot. Even though I have done 1000 epochs and there are 25 datasets when combined it is more than 10 minutes. From that many datasets, I have also minimized the noise. However, the training results are not satisfactory. The voice still sounds like a robot. I thought, maybe 1000 epochs is still not enough. Can I add them manually?

所以昨天我只是用别人的声音进行训练。但结果还是像个机器人。尽管我做了1000个epochs，有25个数据集，但加起来也超过了10分钟。从这么多的数据集中，我也把噪音降到最低。然而，训练的结果并不令人满意。语音听起来仍然像机器人。我想，也许1000个epochs还是不够的。我可以手动添加它们吗？

**Comment by RVC-Boss** [comment]
You can search 1000 in infer-web.py and change it and restart webui.
