### ISSUE TITLE
On the RVC colab, I now get errors with the newest update

### ISSUE THREAD

**Issue by Optic-the-Wolf** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#540]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/65792938/b63ecaf7-55ff-465d-9f18-fce4ebc946d2)

Also, I tried to remove that message (I did what the warning suggested) and now training errors out, I didn't test inference though, so I'm unsure if that's broken or not.

~~SOLUTION: Downgrade gradio to v3.34.0~~ Edit: Still broken, just differently broken.

**Comment by droughtsoftware** [comment]
Hey, I posted what I believe is a fix in here: https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/538#issuecomment-1594034690 Check it out, hopefully it'll help you.

**Comment by zawaliph** [comment]
Same issue

**Comment by Optic-the-Wolf** [comment]
I found the solution: Downgrade gradio to **v3.34.0**, and everything should work fine.

**Comment by Optic-the-Wolf** [comment]
I found the solution: Downgrade gradio to **v3.34.0**, and everything should work fine.

**Comment by Optic-the-Wolf** [comment]
Nevermind. It still doesn't work.
