### ISSUE TITLE
Support for AMD RX 5700

### ISSUE THREAD

**Issue by AzzySama** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#547]
Hi there,
First of all, thank you for making this excellent fun-to-use tool!
But no matter what I did I always got the "No supported N-card found, use CPU for inference" error with my GPU card being AMD Radeon RX 5700, It would be awesome if you guys could add the support for my GPU if it isn't already supported.
Thank you again!

**Comment by Tps-F** [comment]
Sorry, AMD GPU have not been supported now.
Please see #272
