### ISSUE TITLE
Colab can't start web

### ISSUE THREAD

**Issue by Nrx838** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#549]
/content/Retrieval-based-Voice-Conversion-WebUI
Use Language: en_US
2023-06-16 16:13:15.539160: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-16 16:13:15.592641: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-16 16:13:16.580038: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-06-16 16:13:18 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 87, in <module>
    class ToolButton(gr.Button, gr.components.FormComponent):
AttributeError: module 'gradio.components' has no attribute 'FormComponent'. Did you mean: 'IOComponent'?

**Comment by MurphyEdward** [comment]
Same issue

**Comment by zawaliph** [comment]
Same issue

**Comment by AzzySama** [comment]
Same here

**Comment by RRRea** [comment]
open infer-web.py and change 
class ToolButton(gr.Button, gr.components.FormComponent):
to
class ToolButton(gr.Button, gr.components.IOComponent):

**Comment by Tps-F** [comment]
I talked about it on Discord,
You can change
`!pip3 install faiss-gpu fairseq gradio ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.2`
to 
`!pip3 install faiss-gpu fairseq gradio==3.35.1 ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.2`

>open infer-web.py and change
class ToolButton(gr.Button, gr.components.FormComponent):
to
class ToolButton(gr.Button, gr.components.IOComponent):

That right.
or use  `gr.components.base.FormComponent`

This issue will fix on #543

**Comment by Nrx838** [comment]
thx

**Comment by TranPhuongNghi** [comment]
> I talked about it on Discord, You can change `!pip3 install faiss-gpu fairseq gradio ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.2` to `!pip3 install faiss-gpu fairseq gradio==3.35.1 ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.2`
> 
> > open infer-web.py and change
> > class ToolButton(gr.Button, gr.components.FormComponent):
> > to
> > class ToolButton(gr.Button, gr.components.IOComponent):
> 
> That right. or use `gr.components.base.FormComponent`
> 
> This issue will fix on #543

excuse me, change after or before run it?  I still can't find a fix..

**Comment by an-internet-user001** [comment]
Can confirm, downgrading to 3.4 version fixed the issue for me and web-URL launched with no issue.  thanks!

**Comment by Tps-F** [comment]
> excuse me, change after or before run it? I still can't find a fix..

change before run!

**Comment by Sahgee** [comment]
> 

I wish that this could work for me, but I am still getting the following error message. Any help will be greatly appreciated: 

![2Screenshot 2023-07-17 150432](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/139819407/93baef41-0344-494e-af77-944055ca950e)
![1Screenshot 2023-07-17 150337](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/139819407/d249529c-6d2e-4d93-90dd-4a748e82b760)
