### ISSUE TITLE
Can someone explain to me how to use the Realtime-GUI?

### ISSUE THREAD

**Issue by TheMeIonGod** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#550]
I haven't seen like any documentation for the Realtime-GUI, and I haven't been able to get it working on my own. Could someone clarify what the Hubert File is? Is that something I need to change? Also, is the correct .pth file the one in the weights folder? According to Windows, there is no .index file in any directory. So, what am I supposed to put there, if anything? (Putting nothing results in a crash.) Additionally, what is a .npy file? Plus general tips about real-time usage would be greatly appreciated.

**Comment by foodornt** [comment]
lmao apparently no one cares to help unless the issue is written in chinese
