### ISSUE TITLE
port 7897

### ISSUE THREAD

**Issue by b67ko** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#554]
![2023-06-17_13-03-51](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/136893562/31943f51-e263-4e70-b936-8cd5a5d23c1c)

What is the problem ? 
please help me

**Comment by RVC-Boss** [comment]
try
pip install gradio==3.14.0

**Comment by b67ko** [comment]
Where do I do this?

**Comment by RVC-Boss** [comment]
runtime\python.exe -m pip install gradio==3.14.0

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved.
