### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by frossi65** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#555]
Can somebody please explain how to see the tensorboard graphs for loss?
i am using the windows setup

**Comment by RVC-Boss** [comment]
logdir=logs

**Comment by W-D-D** [comment]
tensorboard --logdir=Path-RVC-log-folder
ex. tensorboard --logdir=C:\AI\VoiceClone\RVC\logs

**Comment by DrMemoryFish** [comment]
> run cmd: tensorboard --logdir=Path-RVC-log-folder ex. tensorboard --logdir=C:\AI\VoiceClone\RVC\logs
> 
> in tensorboard -> Scalars -> search at the top for g /total

when i click Launch_Tensorboard.bat i get this error:

```
E:\AI\rvc\RVC-beta\RVC-beta-v2-0618>tensor-launch.py

[main 2023-07-05T03:22:19.867Z] update#setState idle
[main 2023-07-05T03:22:26.591Z] No ptyHost heartbeat after 6 seconds
[main 2023-07-05T03:22:49.869Z] update#setState checking for updates
[main 2023-07-05T03:22:50.010Z] update#setState idle
[20640:0705/042420.004:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```
