### ISSUE TITLE
Train Model not doing anything?

### ISSUE THREAD

**Issue by Mugen-CC** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#558]
When I click Train Model, these lines appear on the cmd
```
write filelist done
use gpus:
python train_nsf_sim_cache_sid_load_pretrain.py -e riko -sr 40k -f0 1 -bs 1 -te 20 -se 5 -pg pretrained_v2/f0G40k.pth -pd pretrained_v2/f0D40k.pth -l 0 -c 0 -sw 0 -v v2
```
and then nothing happens.

I'm using an AMD Radeon RX 6800 which RVC doesn't support. I had to change the extract_feature_print.py slightly to get Feature Extraction to work (#512 ).

The output information just gives 
```
训练结束, 您可查看控制台训练日志或实验文件夹下的train.log
```
which google translates to 'After the training is over, you can check the console training log or train.log under the experiment folder'. I haven't seen any train.log in the experiment folder.

**Comment by Phtewart** [comment]
I have same problem at latest version.  On RVC-beta20230516 works fine.

**Comment by Haxhom** [comment]
same

**Comment by kalbright3275** [comment]
Same here, and there is no **train.log** file or anything.
(Is it even possible to train models using CPU mode?)
