### ISSUE TITLE
Does batch processing process in parallel? 

### ISSUE THREAD

**Issue by kalomaze** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#561]
I was wondering if the batch processing feature on the interface processes all files at once by doing threading (since pm and harvest are on the primarily CPU), or each separately at a time. I was mainly wondering because if you properly separated the pieces of a larger inference audio from the silence, you could process them all at once and potentially reap both performance and quality improvements, for long single file inference.

**Comment by RVC-Boss** [comment]
Yes it's a good idea but I need time to support it.

**Comment by treya-lin** [comment]
> Yes it's a good idea but I need time to support it.
Hi Any update on this? Is it possible to infer in batch now?
