### ISSUE TITLE
Sample rate setting in inference distorts output audio speed as a whole randomly

### ISSUE THREAD

**Issue by kalomaze** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#563]
Setting 44100 as an option for the resampler causes only the first conversion to work. After that, it speeds up the audio to match sample rate requirements. Doesn't work as intended.

A similar strange phenomenon can happen when adjusting harvest median filtering, but you can transpose down to make it match. Seems to impact transpose pitch rather than 'real' pitch. Very odd glitchy behavior that seems rather inconsistent. I can set it to 5, convert, and it sounds fine; changing to 'zero' afterwards will break the transpose and cause it to climb upwards. Repeating this process can cause transpose to go even higher.

**Comment by Typhoon859** [comment]
Yes, this issue still happens for me.
