### ISSUE TITLE
inferencing voice dropdown will not populate

### ISSUE THREAD

**Issue by r3dd3n** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#573]
Output message when trying to batch run: 
  
File "C:\Users\r3dd3n\Desktop\RVC-beta-v2-0528\infer-web.py", line 168, in vc_single
    if_f0 = cpt.get("f0", 1)
NameError: name 'cpt' is not defined

no clue why it wont populate the influencing voice dropdown

**Comment by Skizzie** [comment]
Got the same error? No idea why. It seems like I'm only getting this error when trying to batch run using crepe.
