### ISSUE TITLE
Train tab doesn't detect my GPU [RTX 2060]

### ISSUE THREAD

**Issue by Blackh4n** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#574]
In train tab, at the "Step 2b" Im getting this error message:
**Unfortunately, there is no compatible GPU available to support your training.**
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/43624420/d8097088-3677-4792-83f5-fa87b467926d)

**Comment by RVC-Boss** [comment]
Pytorch need cuda support.

**Comment by faik-sevim** [comment]
https://developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda_12.1.1_531.14_windows.exe install this for win 10

**Comment by MikuAuahDark** [comment]
There's no need to install CUDA. PyTorch ships with CUDA runtime.

Follow the instruction on how to install PyTorch here: https://pytorch.org/get-started/locally/

**Comment by adDossari** [comment]
please, can you help me my GPU is Intel's Iris Xe Graphics what can I do?

**Comment by noonADM** [comment]
Unfortunately, there is no compatible GPU available to support your training.

???

**Comment by elianli** [comment]
Same issue here. Used 4 NVIDIA L4s on Google Cloud with Windows Server, tried python then import torch then print(torch.cuda.is_available()),returned true. So IDK why it still have a problem here.

**Comment by adDossari** [comment]
> Same issue here. Used 4 NVIDIA L4s on Google Cloud with Windows Server, tried python then import torch then print(torch.cuda.is_available()),returned true. So IDK why it still have a problem here.

My problem still exists, but I found another way to do it through Google Colab.

**Comment by FelipeCODX** [comment]
> Same issue here. Used 4 NVIDIA L4s on Google Cloud with Windows Server, tried python then import torch then print(torch.cuda.is_available()),returned true. So IDK why it still have a problem here.

Did you find a solution for this?

**Comment by stevencol** [comment]
PS C:\Users\steve\Escritorio\Applio-3.2.7> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
Looking in indexes: https://download.pytorch.org/whl/cu124
Requirement already satisfied: torch in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (2.5.1+cu118)
Requirement already satisfied: torchvision in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (0.20.1+cu118)
Requirement already satisfied: torchaudio in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (2.5.1+cu118)
Requirement already satisfied: filelock in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.10.0)
Requirement already satisfied: networkx in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.3)
Requirement already satisfied: fsspec in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torch) (2024.2.0)
Requirement already satisfied: setuptools in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torch) (70.0.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from torchvision) (10.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\steve\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (2.1.5)
PS C:\Users\steve\Escritorio\Applio-3.2.7>

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. 

The GPU detection logic has been fixed and is now working properly.
