### ISSUE TITLE
Can Retrieval-based-Voice-Conversion-WebUI run on MacOS apple silicon/m1?

### ISSUE THREAD

**Issue by shadowzoom** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#575]
Can Retrieval-based-Voice-Conversion-WebUI run on MacOS apple silicon/m1?

**Comment by hustnaive** [comment]
I encountered an error like the following on my M1 Pro：

ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.13.1

**Comment by Tps-F** [comment]
> Can Retrieval-based-Voice-Conversion-WebUI run on MacOS apple silicon/m1?

Yes!

**Comment by phenomboy** [comment]
> Any devs here? I'm running rvc-beta on local macos M1 chip. I need change a PyTorch code in inner-web.py to use M1 gpu power instead cpu, here is fix for this https://stackoverflow.com/questions/72416726/how-to-move-pytorch-model-to-gpu-on-apple-m1-chips but i don't know what to change in inner-web.py

Did you ever solve that ? if so i'm looking for ways to use that on mac

**Comment by anthonyvip3** [comment]
Si tienes sonoma o MacOS 14 te diria que lo borres no funciona esa version para rvc local tiene mucho errores te recomiendo mas monterrey o sonoma
