### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by AbramovS1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#578]
What kind of mistake is this? I searched the whole Internet couldn't fix anything
Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://0.0.0.0:7897
runtime\python.exe trainset_preprocess_pipeline_print.py E:\AI VOICE\Retrieval-based-Voice-Conversion-WebUI\voice 40000 6 E:\AI VOICE\Retrieval-based-Voice-Conversion-WebUI/logs/test False
Traceback (most recent call last):
  File "E:\AI VOICE\Retrieval-based-Voice-Conversion-WebUI\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'VOICE\\Retrieval-based-Voice-Conversion-WebUI\\voice'

Traceback (most recent call last):
  File "C:\Users\Evgen\Desktop\RVC-beta-v2-0528\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'VOICE\\Retrieval-based-Voice-Conversion-WebUI\\voice'

**Comment by MattTDK** [comment]
I got this error too whenever I try and process data while training

**Comment by RVC-Boss** [comment]
AI VOICE
no space
