### ISSUE TITLE
Unable to train models

### ISSUE THREAD

**Issue by 5909c** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#579]
I understand that this isn't really an bug, more how the software is written, but I run on AMD hardware, both CPU and GPU, and there's no way for me to run the Cuda code that RVC uses, the web UI doesn't pick up even my CPU, if there is any kind of workaround or fix for this, I'd be very grateful, because I'm currently unable to train vocies at all.

**Comment by ns-studios** [comment]
Same here! I can generate indexes and features, but not the pth file

**Comment by Tommy2003-star** [comment]
> Same here! I can generate indexes and features, but not the pth file

This is exactly the problem I'm facing. Can you guys help us with this problem?

**Comment by TheTrustedComputer** [comment]
Me too! I have an all-AMD system running Linux, and training requires a modern NVIDIA GPU, which I don't have and can't afford. However, I do have a very old GTX 550 Ti lying around, but I don't think it has a version of CUDA that RVC needs.

Please support training on non-NVIDIA cards as much as you can. I'm dying to train my own models and test them against a variety of audio samples!

**Comment by HardikJain02** [comment]
> Same here! I can generate indexes and features, but not the pth file

Did you get it fixed?

**Comment by ns-studios** [comment]
No. I had to use a cloud computer option that had a good enough Nvidia GPU.
> Did you get it fixed?

**Comment by HardikJain02** [comment]
What causes this problem exactly?

**Comment by ns-studios** [comment]
It seems to fail silently at this:
use gpus:                                                                                                               
runtime\python.exe train_nsf_sim_cache_sid_load_pretrain.py -e myvoice -sr 40k -f0 1 -bs 1 -te 20 -se 5 -pg pretrained/f0G40k.pth -pd pretrained/f0D40k.pth -l 0 -c 0 -sw 0 -v v1                                                                 
If I give it GPU 0-1:
use gpus: 0-1                                                                                                           
runtime\python.exe train_nsf_sim_cache_sid_load_pretrain.py -e myvoice -sr 40k -f0 1 -bs 1 -g 0-1 -te 20 -se 5 -pg pretrained/f0G40k.pth -pd pretrained/f0D40k.pth -l 0 -c 0 -sw 0 -v v1

**Comment by PKLR7** [comment]
> No. I had to use a cloud computer option that had a good enough Nvidia GPU.
> 
> > Did you get it fixed?

Can you elaborate on how did you do that

**Comment by ns-studios** [comment]
@PKLR7 I rented a machine from a vps provider. The latest version of rvc (the intel/AMD one) let me train using my regular computer, although it took about an hour per epoch. However, the newest version doesn't work at all for rendering; it just immediately fails with any of the algorithms.
