### ISSUE TITLE
In Colab, the epochs progress strangely fast, and an unfinished voice synthesis is generated.

### ISSUE THREAD

**Issue by mikisayakamitakihara** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#58]
In Colab, when I run training with the current ipynb notebook, the epochs progress very quickly (about 1 epoch in 6 seconds with Tesla T4 and batch size 14), and even after training for about 300 epochs, a low-quality, grainy voice synthesis weight.pth file is generated. I have over 1000 training files totaling more than 50 minutes. Is everyone else experiencing the same issue?

**Comment by mikisayakamitakihara** [comment]
There might have been too many files with low volume. I'm trying to resolve it now.

**Comment by fumiama** [comment]
Reduce the epoch round may fix this (ex. limit to <= 200 epochs)

**Comment by mikisayakamitakihara** [comment]
I'll give that a try as well. Thank you for the advice.   After normalizing the volume, the progress of the epochs became faster, and the results improved somewhat.　　　　I might write the results of various settings changes I make after this here.

**Comment by fumiama** [comment]
Ok. Looking forward to your result.
