### ISSUE TITLE
Data not processing

### ISSUE THREAD

**Issue by MattTDK** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#582]
Whenever i try and process data on the train tab there is always an error and nothing would appear in the output box.
![Screenshot 2023-06-19 184649](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/86790371/63310a5c-5e6e-46f1-845c-28b58213a6d1)
Are there any fixes to this? so far I have found nothing to fix the problem.

**Comment by RVC-Boss** [comment]
My Computer
no space
