### ISSUE TITLE
Getting index file from existing model

### ISSUE THREAD

**Issue by zenithilia** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#588]
Let's say I downloaded someone's model, or made one myself, but forgot the index file. Is there a way to recreate it from what was already trained, or do I have to restart from 0?

**Comment by RVC-Boss** [comment]
You can click "train the index" and model is not needed to train again

**Comment by RVC-Boss** [comment]
> You can click "train the index" and model is not needed to train again

If you alaready have the feature you don't need to extract them again, or you should click data preprocess and feature extract
