### ISSUE TITLE
Requesting a task without running the webui

### ISSUE THREAD

**Issue by mohsenemx** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#591]
I have a telegram bot that recieves a vocal file and then changes it to x singer.

But How do I request a task via command line?
Something like `python file.py --x-model --path-to-input-file --path-to-output` is what I mean.
is there anything like this already implemented?

**Comment by RVC-Boss** [comment]
https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/myinfer-v2-0528.py
