### ISSUE TITLE
'Process data' function in 'Train' won't work. Any ideas?

### ISSUE THREAD

**Issue by 808verb** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#592]
After I click ''Process Data' the 'Output Information'' block just flashes once and shows no data.

When I check the log file, It only shows the export map with an empty 'preprocess.log' file and no .wav files. 

I have the data set map stored in:
"C:\Program Files\RVC-beta-v2-0618\training data sets\circles"

The data set is 15 .wav files, max 9 seconds
I have 260 GB free space on c drive
I have 12 CPU processes. Also tried to lower this. 

Tried: 
- Edge, Chrome
- Turned off hardware acceleration
- Run as admin
- V1 and V2
- Different sample rates

Nothing happens!

Any ideas?

**Comment by scrimagames** [comment]
same issue. I think because I don't have enough audio files? or do they need to be trained a certain way? straight up wav audio voice files right?

**Comment by baaron4** [comment]
Just had the same problem, looking at the output log it seemed that it was source folder name related. Get rid of any spaces in your folder names and it worked for me

**Comment by BRLTS** [comment]
Ahh... It's worked, thx for the tips, I've just rewrite the folder name without spaces

**Comment by SrBorrego** [comment]
Same issue here, but removing the spaces in the files names didnt helped. Im using aroun 2+ min of audio to sample it, should I need more?

**Comment by Host10000** [comment]
> Same issue here, but removing the spaces in the files names didnt helped. Im using aroun 2+ min of audio to sample it, should I need more?

Just had the same issue, tried multiple audio files, didn't fix. Eventually went back through the folder paths and realized there was a space in the folder > unzipped folder > data. Even as a c# user, I forgot how finicky code and programs are with 0's and spaces.

**Comment by xcloudx01** [comment]
Is there another solution? I've tried literally putting it in C:\Test and naming my files 1.wav and 2.wav, but I have the same issue. No output with a blank preprocess.log file

**Comment by xcloudx01** [comment]
Note that the "Enter the experiment name:" cannot contain spaces either. For example "Human Male" won't work, but "Human_Male" will work.
