### ISSUE TITLE
No module named 'gradio', stuck at final installment

### ISSUE THREAD

**Issue by SilverAsh60** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#599]
Traceback (most recent call last):
  File "D:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 22, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

**Comment by dorian-bucaille** [comment]
Currently getting the same error

**Comment by RVC-Boss** [comment]
You can update the code to the latest main branch, where this version dependency issue has already been resolved.
