### ISSUE TITLE
Two questions about Hubert encoder

### ISSUE THREAD

**Issue by lbong2** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#602]
The HuBERT_base model is basically known as an English-learned model. 
1. If I could change this to a model learned in my own language, would I get a better quality output?
2. I checked the code and it seems that I only use (extract_features) and (final_proj) layer of Hubert model, is it correct that I understand?

**Comment by RVC-Boss** [comment]
1、It needs experiments.
2、Yes.

**Comment by lbong2** [comment]
@RVC-Boss Thank you for your answer.
