### ISSUE TITLE
One-Click Training locks up and does not progress with Epoch

### ISSUE THREAD

**Issue by VertofChest** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#603]
Hello, I am attempting to train my voice model, however when I click One-Click Training, the progress halts after a certain point with the last message in the console being "INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration."

What is going on here? And how long should training take, exactly?
[extract_f0_feature.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/11830914/extract_f0_feature.log)
[preprocess.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/11830916/preprocess.log)
[train.log](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/11830918/train.log)

**Comment by Traxier** [comment]
Have you fixed it yet? I'm having the same problem.

**Comment by Tsar** [comment]
Updating gradio like described here https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2355 helped me.
