### ISSUE TITLE
go-realtime GUI。有些人对规范有疑问，除非输入索引文件的文件路径，否则无法使用它

### ISSUE THREAD

**Issue by mikisayakamitakihara** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#604]
关于 updated0618v2 go-realtime GUI。

关于 go-realtime GUI。

除非输入索引文件的文件路径否则无法使用它的新规范可能对很多人来说都是一个问题，有许多 RVC 模型在没有附加索引文件的情况下分发，并且许多技术不太精通的人给出了在上面

**Comment by mikisayakamitakihara** [comment]
最好有一个规范，即使常规索引文件的路径输入为空，也可以使用 RVC

**Comment by Yurzi** [comment]
I think I have fixed this issue, pr #609

**Comment by BotLifeGaming** [comment]
> About updated0618v2 go-realtime GUI.
> 
> About the go-realtime GUI.
> 
> The new spec that you can't use it unless you enter the file path to the index file may be a problem for many, there are many RVC models distributed without an additional index file, and many less tech-savvy people give on top

Your Index to your model is usually in the opt folder then your trained voice folder if you save it all in one folder like I do. if not the Index will be where ever you saved your trained voice.
