### ISSUE TITLE
运行go-web.bat和infer-web.py都报错

### ISSUE THREAD

**Issue by LootDust** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#605]
配置是DELL G15，Win11系统，RTX4060显卡，16G内存
下载releases中updated0618v2的zip压缩包后移动到空文件夹解压（已安装Python3.11.4，路径是E:/Python/Python311)，完成后运行go-web.bat报错，具体如图：
![RVC-issue](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/92685802/aff0d127-088e-4b39-bdd0-4e87347219c9)
我翻了一下issues发现有人的报错跟我一样（标题是Cannot even open anything with go-web.bat，#431，已关闭），但是按他的说法是没有下载全文件，但是我文件夹里go-web.bat和infer-web.py都有，如图：
![RVC-issue-2](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/92685802/cf54be47-250c-42be-a668-9a938b266663)
然后我尝试用终端直接运行infer-web.py，也报错，提示缺少faiss模块，如图：
![RVC-issue-1](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/92685802/8bd73973-495b-43f9-8a26-ab766b09796a)
实在不知道怎么办了，README.md也看过了，不知道怎么解决，所以来发个issue求救
感激不尽

**Comment by LootDust** [comment]
尝试性地打开gui.py，在用pip额外安装了PySimpleGUI、sounddevice、noisereduce和fairseq四个库以及其依赖项后gui.py还是报错了，截图如下：
![RVC-issue-3](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/92685802/069c0b44-ab98-4216-8db3-e91bfe608380)

**Comment by LootDust** [comment]
尝试修改了一下环境变量后，go-web.bat能运行了，但是还是报错infer-web.py缺少faiss库

**Comment by VSEdison** [comment]
你应该是下载了更新包，试下下载完整包重新解压到一个新的文件夹

**Comment by RVC-Boss** [comment]
pip install: x
runtime\python.exe -m pip install : √

**Comment by LootDust** [comment]
> pip install: x
> runtime\python.exe -m pip install : √

请问这个在哪里输入？

**Comment by LootDust** [comment]
> 你应该是下载了更新包，试下下载完整包重新解压到一个新的文件夹

并没有，我下载的都是Source Code(zip)，我可以肯定不是更新包，再者0618v2版本并没有更新包，应该不是这个问题

**Comment by VSEdison** [comment]
source code是不完整的，完整包是4个G左右的包含了所有环境不用再额外pip install

**Comment by LootDust** [comment]
> source code是不完整的，完整包是4个G左右的包含了所有环境不用再额外pip install

了解了，谢谢，这就尝试一下

**Comment by LootDust** [comment]
已解决，感谢各位帮助
