### ISSUE TITLE
how to combine voices ? 

### ISSUE THREAD

**Issue by KabetzuriBoii** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#608]
i was told one could merge multiple voices into one and create a original new voice . 
No idea how to pull that off though .

**Comment by Yurzi** [comment]
you can try to use the `ckpt processing` tab in gradio webui

**Comment by TripleKiller666** [comment]
Very simplified Explanation:
Step 1:Train Model A and Model B
Step 2:Go to "ckpt Processing"
Step 3:Insert Full Path in "Path to Model A:", same for B (ex. "G:\RVC-Webui\weights\keanu_en.pth" Model A, "G:\RVC-Webui\weights\franksinatra_en.pth" Model B)
Step 4: Choose how much of Model A you want to Dominate in the generated Model (Weight (w) for Model A) 0.5 means 50% of the Voice, and if you just want to mix 2 Voices, is generally good enough to leave as it is.
You can still try out other combinations latter.
Step 5: Don´t forget to give the new Model a Name, and set it to the same Version as the Models you trained before (so if both were v2, then this Model is v2 as well), mixing different Versions didn´t work for me, so either stick with v1+v1 or v2+v2.
Step 6: Test the new Model on the Inference Tab!
