### ISSUE TITLE
Train tab doesn't detect M1 Pro's integrated GPU

### ISSUE THREAD

**Issue by onuralpkrc** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#617]
Is M1 Pro's integrated GPU supported for training. From the previous issues posts, it seems like it is supported, but the program states that no compatible gpu was found in my computer.

**Comment by wizoomer95** [comment]
I have an M1 Max MacBook Pro, and I'm experiencing the same issue.  Is there really no fix for this?
