### ISSUE TITLE
GPU Detection mobile rtx 3060

### ISSUE THREAD

**Issue by tcordata** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#618]
![image_2023-06-23_233446989](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/137562569/93d1ef1f-e90c-4cd7-9cd6-dec76b344888)
![Opera Snapshot_2023-06-23_233507_localhost](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/137562569/442f3388-d026-49d9-b9e0-274a8bcd1bca)

pytorch: Version: 2.0.1
cuda cudnn:11.8
nvidia driver:536.23

I have mobile rtx 3060 (6gb) with ryzen 5600h cpu
tried to update everything etc. and still cant load the gpu

any suggestions?

**Comment by RVC-Boss** [comment]
Your pytorch version is wrong.(CPU version)

**Comment by tcordata** [comment]
> 

is tihs why gpu not detected? and what should I do?

**Comment by tcordata** [comment]
I've tried pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 and it was not updating pytorch healthy (just succes message) instead I added --upgrade 

`pip3 install torch torchvision torchaudio --upgrade --index-url https://download.pytorch.org/whl/cu118`

now it detects my gpu thanks for the information @RVC-Boss
