### ISSUE TITLE
Need Mangio Crepe AI for better voice training

### ISSUE THREAD

**Issue by takilung** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#627]
As explained, also we need Index. It doesn't export index atm.

**Comment by TripleKiller666** [comment]
WDYM?
We have index Files already:
"G:\RVC-Webui\logs\keanu_en\added_IVF88_Flat_nprobe_1_keanu_en_v2.index"
It generates them after successful training for however many Epochs you set it to.

Also, you didn´t really explain what Crepe would do better than what we already have available...
