### ISSUE TITLE
Does RVC use all of my files (regarding the numbered folders in the log path)? 

### ISSUE THREAD

**Issue by KatieBelli** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#631]
I noticed that all my files are in the logs folder _0_gt_wavs_ but in the other folders numbered 1-3 I noticed that some of them are missing there.

Does RVC still use all of my files for training? Or does it automatically delete some files? I'm confused about this.

**Comment by RVC-Boss** [comment]
It will automatically skip segments that are not suitable for training.

**Comment by marksch2807** [comment]
I have completed training a model on RVC which works but would know like to remove unwanted files. The training files I used have already removed but would now want excess pth files removed, can this be done without breaking my trained model....I just need to free up some space?
