### ISSUE TITLE
After you do a model inference convert. Where and how to change the ouput location? (non-batch)

### ISSUE THREAD

**Issue by KneePham** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#632]

**Comment by TripleKiller666** [comment]
File should be generated with a Temporary Filename in your TEMP Folder.
But isn´t rightclicking the File in Gradio enough to download it to any Location you want?

**Comment by KneePham** [comment]
That's old I don't see any files from the project root/temp directory. ./TEMP

**Comment by RVC-Boss** [comment]
You can download it in webui.
Also temp file will be gernerated in TEMP folder.
But when you restart webui, the TEMP will be cleaned up first, and you can't get the audio generated last time using webui.
