### ISSUE TITLE
questions about training a multi-speaker model

### ISSUE THREAD

**Issue by suzhenghang** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#634]
Are there any differences in training a multi-speaker compared to single-speaker?
After adding corresponding data and IDs to filelist.txt，more speakers require more epoch? could you give some suggestions, thanks in advance.  @RVC-Boss

**Comment by RVC-Boss** [comment]
It is recommended that the sample size of different speakers should not differ too much.
More epochs can make the trained model's inferred speech timbre more similar to the target speaker.
