### ISSUE TITLE
GPU not found on UBUNTU 22.04.2

### ISSUE THREAD

**Issue by ariikamusic** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#641]
Hi! I'm trying to train on Linux Ubuntu 22.04.2, and I have torch version 2.0.1+cu118, but for some reason it will not recognize my GPU. I have an NVIDIA 1660GTX SUPER. Any ideas?

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135545749/f6f0252f-740b-4d32-8b0e-c0efd4987e1c)

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/135545749/41a36e07-b16b-4b2f-bab9-9ea4740b4c05)

Thanks in advance!

**Comment by blackhole077** [comment]
@ariikamusic 
First, this is likely an issue that is unrelated to this particular project unless you've trained models without issues previously. As such, let's go over some basic steps that may help troubleshoot the problem:
1. Check the `nvidia-smi` command and make sure your GPU shows up properly.
2. Check that you have the proper CUDA-related packages, such as CUDAToolkit, by running `apt list --installed | grep cuda` (you can replace `cuda` with other package names as well to check that you have them installed.
3. Check that you've installed the proper version of PyTorch.
4. Run the following Python code and determine if PyTorch can see your GPU:
```python
import torch
print(f"PyTorch Version: {torch.__version__}")
print(f"GPUs Detected?: {torch.cuda.is_available()}")
print(f"Number of GPUs detected: {torch.cuda.device_count()}")
print(f"GPU 0 Device Information: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'N/A'}")
```
or if you want a one-liner:
```shell
python -c "import torch;print(f'PyTorch Version: {torch.__version__}');print(f'GPUs Detected?: {torch.cuda.is_available()}');print(f'Number of GPUs detected: {torch.cuda.device_count()}');print(f'GPU 0 Device Information: {torch.cuda.get_device_name(0) if torch.cuda.is_available()} else None');"
```

Once you have more information we can continue debugging the problem. My current guess is that your installation of PyTorch is not correct, or that PyTorch 2.0 does not support your card (though that is unlikely).

**Comment by RVC-Boss** [comment]
You installed CPU version pytorch environment.

**Comment by ariikamusic** [comment]
@blackhole077 @RVC-Boss thank you for explaning! I will investigate the issue and try the solution you've provided me with. If any other issues occur, I will reply to the thread. I'm relatively new to Linux hahaha
