### ISSUE TITLE
[GO-REALTIME-GUI] Can realtime gui use GPU?

### ISSUE THREAD

**Issue by gengzhichen** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#645]
realtime gui seems using CPU now.
Is there any way to force it using GPU?

**Comment by kalomaze** [comment]
Mangio fork has the option to use Crepe or Crepe-tiny which run off the GPU iirc:
https://github.com/Mangio621/Mangio-RVC-Fork

**Comment by RVC-Boss** [comment]
@gengzhichen Now it can use GPU.

**Comment by gengzhichen** [comment]
Thank you very much
