### ISSUE TITLE
unable to launch of public links

### ISSUE THREAD

**Issue by screensguru** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#647]
After i updated my mac and chrome, I was unable to create the public links in colab.

The msg shown below:

"Setting up a public link... we have recently upgraded the way public links are generated. If you encounter any problems, please report the issue and downgrade to gradio version 3.13.0"

what should i do?

**Comment by TripleKiller666** [comment]
Could be that you simply need to setup a Password as well.
Other than that, you can still try to downgrade Gradio to Version 3.13.0:
pip install gradio==3.13.0

**Comment by screensguru** [comment]
> 

how to setup a password? thanks in advance

**Comment by screensguru** [comment]
> 

how to set up a password? thanks in advance
