### ISSUE TITLE
Artefacting when speech has breath / Quality improvement ?

### ISSUE THREAD

**Issue by tomakorea** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#65]
Hi, great work ! I'm so excited about your future updates. I noticed that the outputs usually don't handle well the Breaths. It creates artefacting most of the time. I was wondering if during training Breaths should be removed or kept to get the best results?
Also, would it be possible to use a high quality mode? like training and generating in 48Khz 24bits? is going over 1000 epochs also could get better and more natural results ?
The new generations of GPUs got more and more Vram, so it would be great to be able to use it at full power (for example 24gb of Vram).
Thanks for the great work!

**Comment by liujing04** [comment]
It is because that the preprocess of training dataset drops the breath because the volume of breath is lower than threshold, and therefore breath is not fully trained.
We will collect some breath wavs and add them to training dataset to solve this problem.
