### ISSUE TITLE
create the last step ‘index’ error

### ISSUE THREAD

**Issue by zannnnnn122** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#650]
I finished step 1,2and3a.When I train last step,index, there are two types of errors. I don't know how to solve it, I hope to get some help.
If you need more details,plz let me know.

**Comment by zannnnnn122** [comment]
Sorry for Image upload error. Here is text for one of error.

Init 1/3 with method random
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
Inertia for init 1/3: 2541709.75
Init 2/3 with method random
Inertia for init 2/3: 2533778.0
Init 3/3 with method random
Inertia for init 3/3: 2536180.75
[MiniBatchKMeans] Reassigning 4096 cluster centers.
Minibatch step 1/4123: mean batch inertia: 102.75743103027344
[MiniBatchKMeans] Reassigning 4030 cluster centers.
Minibatch step 2/4123: mean batch inertia: 96.69242095947266, ewa inertia: 96.69242095947266
Minibatch step 3/4123: mean batch inertia: 87.30839538574219, ewa inertia: 96.23728166272069
Minibatch step 4/4123: mean batch inertia: 83.59808349609375, ewa inertia: 95.62426161925757
Minibatch step 5/4123: mean batch inertia: 82.00260925292969, ewa inertia: 94.96359107548096
Minibatch step 6/4123: mean batch inertia: 80.32125091552734, ewa inertia: 94.25341564481501
Minibatch step 7/4123: mean batch inertia: 79.2042007446289, ewa inertia: 93.52350617978604
Minibatch step 8/4123: mean batch inertia: 77.86848449707031, ewa inertia: 92.76421417836032
Minibatch step 9/4123: mean batch inertia: 78.25422668457031, ewa inertia: 92.06045805025569
Minibatch step 10/4123: mean batch inertia: 76.47032165527344, ewa inertia: 91.30431308247736
Minibatch step 11/4123: mean batch inertia: 76.56755828857422, ewa inertia: 90.58955840064023
Minibatch step 12/4123: mean batch inertia: 76.3224868774414, ewa inertia: 89.89758406097555
Minibatch step 13/4123: mean batch inertia: 75.5287094116211, ewa inertia: 89.2006721172004
Minibatch step 14/4123: mean batch inertia: 75.06291961669922, ewa inertia: 88.5149699438448
[MiniBatchKMeans] Reassigning 2030 cluster centers.
Minibatch step 15/4123: mean batch inertia: 75.28545379638672, ewa inertia: 87.87331859406815
Minibatch step 16/4123: mean batch inertia: 74.18080139160156, ewa inertia: 87.20921099958967
Minibatch step 17/4123: mean batch inertia: 74.20442199707031, ewa inertia: 86.5784592529636
Minibatch step 18/4123: mean batch inertia: 73.80818176269531, ewa inertia: 85.95908166595883
Minibatch step 19/4123: mean batch inertia: 73.74021911621094, ewa inertia: 85.36644852953928
Minibatch step 20/4123: mean batch inertia: 73.39217376708984, ewa inertia: 84.7856782671742
Minibatch step 21/4123: mean batch inertia: 73.9621353149414, ewa inertia: 84.26072022129735
Minibatch step 22/4123: mean batch inertia: 72.99752807617188, ewa inertia: 83.71443853101027
Minibatch step 23/4123: mean batch inertia: 72.58474731445312, ewa inertia: 83.17463183573113
Minibatch step 24/4123: mean batch inertia: 73.53788757324219, ewa inertia: 82.70723530402454
Minibatch step 25/4123: mean batch inertia: 73.17109680175781, ewa inertia: 82.24471830238708
Minibatch step 26/4123: mean batch inertia: 72.92548370361328, ewa inertia: 81.79272146497158
Minibatch step 27/4123: mean batch inertia: 73.17036437988281, ewa inertia: 81.3745242308296
[MiniBatchKMeans] Reassigning 1320 cluster centers.
Minibatch step 28/4123: mean batch inertia: 72.66722869873047, ewa inertia: 80.95220735477747
Minibatch step 29/4123: mean batch inertia: 72.76921081542969, ewa inertia: 80.5553197652265
Minibatch step 30/4123: mean batch inertia: 72.75704956054688, ewa inertia: 80.17709197919238
Minibatch step 31/4123: mean batch inertia: 72.11953735351562, ewa inertia: 79.78628851035516
Minibatch step 32/4123: mean batch inertia: 71.5551528930664, ewa inertia: 79.38706610341606
Minibatch step 33/4123: mean batch inertia: 71.01248931884766, ewa inertia: 78.98088658500193
Minibatch step 34/4123: mean batch inertia: 71.8293228149414, ewa inertia: 78.63402502975488
Minibatch step 35/4123: mean batch inertia: 71.63385009765625, ewa inertia: 78.29450605991585
Minibatch step 36/4123: mean batch inertia: 71.47457122802734, ewa inertia: 77.96372900492047
Minibatch step 37/4123: mean batch inertia: 71.0222396850586, ewa inertia: 77.62705637518069
Minibatch step 38/4123: mean batch inertia: 71.91345977783203, ewa inertia: 77.34993838175562
Minibatch step 39/4123: mean batch inertia: 71.182861328125, ewa inertia: 77.05082590692797
Minibatch step 40/4123: mean batch inertia: 71.85535430908203, ewa inertia: 76.79883775208343
[MiniBatchKMeans] Reassigning 987 cluster centers.
Minibatch step 41/4123: mean batch inertia: 70.75200653076172, ewa inertia: 76.50555738024019
Minibatch step 42/4123: mean batch inertia: 70.72810363769531, ewa inertia: 76.22534221962084
Minibatch step 43/4123: mean batch inertia: 70.46759796142578, ewa inertia: 75.94608299851551
Minibatch step 44/4123: mean batch inertia: 71.32210540771484, ewa inertia: 75.72181315905927
Minibatch step 45/4123: mean batch inertia: 71.20420837402344, ewa inertia: 75.50270256001951
Minibatch step 46/4123: mean batch inertia: 70.56766510009766, ewa inertia: 75.26334585097119
Minibatch step 47/4123: mean batch inertia: 71.08039093017578, ewa inertia: 75.06046627162247
Minibatch step 48/4123: mean batch inertia: 71.06494140625, ewa inertia: 74.86667733071513
Minibatch step 49/4123: mean batch inertia: 70.31243896484375, ewa inertia: 74.64578994813104
Minibatch step 50/4123: mean batch inertia: 70.45311737060547, ewa inertia: 74.44243904787474
Minibatch step 51/4123: mean batch inertia: 69.97917175292969, ewa inertia: 74.22596389849706
Minibatch step 52/4123: mean batch inertia: 70.66864776611328, ewa inertia: 74.05342873753693
Minibatch step 53/4123: mean batch inertia: 70.67794799804688, ewa inertia: 73.8897128655052
Minibatch step 54/4123: mean batch inertia: 71.08818054199219, ewa inertia: 73.75383435137145
Minibatch step 55/4123: mean batch inertia: 70.68251037597656, ewa inertia: 73.60487053799781
Minibatch step 56/4123: mean batch inertia: 70.45808410644531, ewa inertia: 73.45224668246456
Minibatch step 57/4123: mean batch inertia: 70.23043823242188, ewa inertia: 73.2959841466583
Minibatch step 58/4123: mean batch inertia: 70.41521453857422, ewa inertia: 73.15626250553252
Minibatch step 59/4123: mean batch inertia: 70.41124725341797, ewa inertia: 73.02312515401908
Minibatch step 60/4123: mean batch inertia: 69.96045684814453, ewa inertia: 72.8745811535826
Minibatch step 61/4123: mean batch inertia: 70.5274429321289, ewa inertia: 72.7607414340402
Minibatch step 62/4123: mean batch inertia: 69.9365234375, ewa inertia: 72.62376263078353
Minibatch step 63/4123: mean batch inertia: 69.77900695800781, ewa inertia: 72.48578771946585
Minibatch step 64/4123: mean batch inertia: 70.2335433959961, ewa inertia: 72.3765504961182
Minibatch step 65/4123: mean batch inertia: 69.84111785888672, ewa inertia: 72.2535782153625
Minibatch step 66/4123: mean batch inertia: 69.62854766845703, ewa inertia: 72.12626030177799
[MiniBatchKMeans] Reassigning 361 cluster centers.
Minibatch step 67/4123: mean batch inertia: 70.69947052001953, ewa inertia: 72.05705886015998
Minibatch step 68/4123: mean batch inertia: 70.32763671875, ewa inertia: 71.97317929578283
Minibatch step 69/4123: mean batch inertia: 69.84019470214844, ewa inertia: 71.86972634797253
Minibatch step 70/4123: mean batch inertia: 69.82870483398438, ewa inertia: 71.7707337472775
Minibatch step 71/4123: mean batch inertia: 70.28894805908203, ewa inertia: 71.69886492181837
Minibatch step 72/4123: mean batch inertia: 69.79792022705078, ewa inertia: 71.60666625667803
Minibatch step 73/4123: mean batch inertia: 69.32759857177734, ewa inertia: 71.496128060122
Minibatch step 74/4123: mean batch inertia: 69.00839233398438, ewa inertia: 71.37546915100003
Minibatch step 75/4123: mean batch inertia: 69.37251281738281, ewa inertia: 71.27832276857121
Minibatch step 76/4123: mean batch inertia: 69.22714233398438, ewa inertia: 71.17883744501
Minibatch step 77/4123: mean batch inertia: 69.68324279785156, ewa inertia: 71.1062988643566
Minibatch step 78/4123: mean batch inertia: 69.41020965576172, ewa inertia: 71.02403599715072
Minibatch step 79/4123: mean batch inertia: 68.83438110351562, ewa inertia: 70.91783445490339
[MiniBatchKMeans] Reassigning 384 cluster centers.
Minibatch step 80/4123: mean batch inertia: 69.44644165039062, ewa inertia: 70.84646969987048
Minibatch step 81/4123: mean batch inertia: 69.26766204833984, ewa inertia: 70.76989516385943
Minibatch step 82/4123: mean batch inertia: 69.74703979492188, ewa inertia: 70.72028514632063
Minibatch step 83/4123: mean batch inertia: 69.46515655517578, ewa inertia: 70.6594095295804
Minibatch step 84/4123: mean batch inertia: 68.86286926269531, ewa inertia: 70.57227463558078
Minibatch step 85/4123: mean batch inertia: 69.58650970458984, ewa inertia: 70.52446355984054
Minibatch step 86/4123: mean batch inertia: 69.61791229248047, ewa inertia: 70.48049446544134
Minibatch step 87/4123: mean batch inertia: 69.23182678222656, ewa inertia: 70.41993221241358
Minibatch step 88/4123: mean batch inertia: 69.81620025634766, ewa inertia: 70.39065030820824
Minibatch step 89/4123: mean batch inertia: 69.34571838378906, ewa inertia: 70.33996954465991
Minibatch step 90/4123: mean batch inertia: 69.72348022460938, ewa inertia: 70.31006888919191
Minibatch step 91/4123: mean batch inertia: 69.60970306396484, ewa inertia: 70.27610009758341
Minibatch step 92/4123: mean batch inertia: 69.85035705566406, ewa inertia: 70.25545092232555
[MiniBatchKMeans] Reassigning 390 cluster centers.
Minibatch step 93/4123: mean batch inertia: 70.01844787597656, ewa inertia: 70.24395591956838
Minibatch step 94/4123: mean batch inertia: 69.28459930419922, ewa inertia: 70.19742568669307
Minibatch step 95/4123: mean batch inertia: 69.16033172607422, ewa inertia: 70.1471250761296
Minibatch step 96/4123: mean batch inertia: 69.38605499267578, ewa inertia: 70.11021203706758
Minibatch step 97/4123: mean batch inertia: 69.51000213623047, ewa inertia: 70.08110095781655
Minibatch step 98/4123: mean batch inertia: 69.76508331298828, ewa inertia: 70.06577362867638
OpOeOpOnpenBLAS : PrBLASenBLAS : penBL : Program ogris Tam iProgram is Ts Terminated. Because you trieermiAnd aS : Programted. Because you tried to allocate tooto   allocate toomis Tera many nmerminaimytnemeatod memer. Beodycr. re aygiusBece  regioyaonouns.ss.
e you
Th tried Tuithiso al s lt locliraibrabitrree ady r twytoaso  waa oslb  builocltmate u atoony  mto supanilmemoy memtryorp reg yoit regionsons.ort
 . This
a mTsuaxlihippos imulrbribrarmary wy t a m of was5aa buximum ils buo0 tf 50 thtilr ht to suppretoeaoradstd   ss-a -  upemaximui pmteo hritt ehoa ef mr 5aximum or0rf  th5 er0 thrbureeildads Openbuea iBLAld Od-Sps
e -wieinBLAS ttheit a
hhewe lirr rebu rebarguild ilth d eaOOpepe nr lBnBaLAS
NLrwith agUASeM
w_lriTa NHrgeREADtUrSh a v NM_THa lRluaUEerM_THA geDoRr NUS EMrvAD a_S luevas or sleTett t HuheRe  enor sethe virent tvironmeoEhnnAetmDS en v tvaenvirarial onue mentvbo alrvae OPEriableNr set theBiable OPEL ONA envPESirN_BoBNUMLLA_TnSAHm_SRentENU A_M_DSvTNUM_THREAD aHStrREAi oDS
abtatlo o

sua suae fffOPENBLficieicieAS_n sutntllyffNUM_ yiTH smacielsmnlRall t EADnnlS to
uyuambm  ebesrsrmau..ll  ffTThic isinu ehmentlyisr small bernumber. Thiro s.r tyerro epr ri Thctyparoilir typiccls ayael orllcroly occr yurtycu os pirsccw wuhehrcn s en whalletty ocche shnuoe rs tftso wafwhetwr harseneoe  f tthattth whe sareotalftware thatre ti  hatrerelies  elirsoneli
 eesosOpenBn  onoL

OAS cOnpen
apBLASOle penclnBasBLl LAlBASsLA  SScBL f AaucallS nslfuncc lttioiBsns foLArom maS  nnfuys ncBf tLrtiAom mhonsrea from mSanany tdy hs trefunct in adiphsons ir fnear araparlleadom many thlls ilr,n paraleeall,ds  o oel, or when r when yiyrono u pwrur  computer has hcameoron armyllpoe
uur cectol, or when emputer has more
pyrcpour cu cores  ou cores ththan wanmph huawhtsaae ttrm   hOOoapprs moeenrneBe

LAScBc pLpwuAua c s orSccesonf o wtrigheaured to ssah than w n whahconaanft Oit Ogured penBLAtdpSolenBLAS w handle.
ae
D:\change\RVC-beta>pause

**Comment by zannnnnn122** [comment]
There is a another one.

Init 1/3 with method random
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
Inertia for init 1/3: 2514473.0
Init 2/3 with method random
Inertia for init 2/3: 2522327.75
Init 3/3 with method random
Inertia for init 3/3: 2514495.25
[MiniBatchKMeans] Reassigning 4096 cluster centers.
Minibatch step 1/4123: mean batch inertia: 103.46958923339844
[MiniBatchKMeans] Reassigning 3987 cluster centers.
Minibatch step 2/4123: mean batch inertia: 95.65587615966797, ewa inertia: 95.65587615966797
Minibatch step 3/4123: mean batch inertia: 87.3228988647461, ewa inertia: 95.25171427881398
Minibatch step 4/4123: mean batch inertia: 83.77593231201172, ewa inertia: 94.69512166373515
Minibatch step 5/4123: mean batch inertia: 81.5537109375, ewa inertia: 94.0577435588618
Minibatch step 6/4123: mean batch inertia: 79.70337677001953, ewa inertia: 93.36153526805296
Minibatch step 7/4123: mean batch inertia: 78.8574447631836, ewa inertia: 92.65806515274414
Minibatch step 8/4123: mean batch inertia: 78.27894592285156, ewa inertia: 91.96065633146743
Minibatch step 9/4123: mean batch inertia: 76.87303924560547, ewa inertia: 91.22888430291016
Minibatch step 10/4123: mean batch inertia: 76.90290832519531, ewa inertia: 90.53405300896787
Minibatch step 11/4123: mean batch inertia: 76.45818328857422, ewa inertia: 89.85135224314234
Minibatch step 12/4123: mean batch inertia: 75.42832946777344, ewa inertia: 89.15181403414645
Minibatch step 13/4123: mean batch inertia: 75.77925872802734, ewa inertia: 88.50322507091495
Minibatch step 14/4123: mean batch inertia: 75.42442321777344, ewa inertia: 87.8688835901691
[MiniBatchKMeans] Reassigning 1979 cluster centers.
Minibatch step 15/4123: mean batch inertia: 75.14704132080078, ewa inertia: 87.2518551839296
Minibatch step 16/4123: mean batch inertia: 74.43780517578125, ewa inertia: 86.63035456424038
Minibatch step 17/4123: mean batch inertia: 73.6889877319336, ewa inertia: 86.0026788878703
Minibatch step 18/4123: mean batch inertia: 74.6119384765625, ewa inertia: 85.45021091561756
Minibatch step 19/4123: mean batch inertia: 74.10350799560547, ewa inertia: 84.89987882765686
Minibatch step 20/4123: mean batch inertia: 73.77182006835938, ewa inertia: 84.3601513090001
Minibatch step 21/4123: mean batch inertia: 74.25167846679688, ewa inertia: 83.86987523457037
Minibatch step 22/4123: mean batch inertia: 72.604248046875, ewa inertia: 83.32347544107117
Minibatch step 23/4123: mean batch inertia: 73.7516098022461, ewa inertia: 82.8592256197946
Minibatch step 24/4123: mean batch inertia: 73.0467758178711, ewa inertia: 82.38330710623433
Minibatch step 25/4123: mean batch inertia: 72.3138656616211, ewa inertia: 81.89492411305325
Minibatch step 26/4123: mean batch inertia: 72.58373260498047, ewa inertia: 81.44331737758456
Minibatch step 27/4123: mean batch inertia: 72.6320571899414, ewa inertia: 81.01595806000886
[MiniBatchKMeans] Reassigning 1312 cluster centers.
Minibatch step 28/4123: mean batch inertia: 72.70526123046875, ewa inertia: 80.61287681510002
Minibatch step 29/4123: mean batch inertia: 72.79718017578125, ewa inertia: 80.23380382088266
Minibatch step 30/4123: mean batch inertia: 72.07632446289062, ewa inertia: 79.8381538528499
Minibatch step 31/4123: mean batch inertia: 72.36316680908203, ewa inertia: 79.47560578436908
Minibatch step 32/4123: mean batch inertia: 72.01358032226562, ewa inertia: 79.11368637201427
Minibatch step 33/4123: mean batch inertia: 72.20275115966797, ewa inertia: 78.77849566225629
Minibatch step 34/4123: mean batch inertia: 71.52497863769531, ewa inertia: 78.42668922144917
Minibatch step 35/4123: mean batch inertia: 71.68085479736328, ewa inertia: 78.09950614722794
Minibatch step 36/4123: mean batch inertia: 71.99955749511719, ewa inertia: 77.80364950042629
Minibatch step 37/4123: mean batch inertia: 71.82128143310547, ewa inertia: 77.51349568811209
Minibatch step 38/4123: mean batch inertia: 71.29092407226562, ewa inertia: 77.21169164389109
Minibatch step 39/4123: mean batch inertia: 71.62266540527344, ewa inertia: 76.94061549945967
Minibatch step 40/4123: mean batch inertia: 71.32933807373047, ewa inertia: 76.66846013912307
[MiniBatchKMeans] Reassigning 950 cluster centers.
Minibatch step 41/4123: mean batch inertia: 71.73887634277344, ewa inertia: 76.42936794092711
Minibatch step 42/4123: mean batch inertia: 71.19278717041016, ewa inertia: 76.17538592963017
Minibatch step 43/4123: mean batch inertia: 70.93849182128906, ewa inertia: 75.92138872097941
Minibatch step 44/4123: mean batch inertia: 70.917724609375, ewa inertia: 75.67870351652793
Minibatch step 45/4123: mean batch inertia: 70.6812973022461, ewa inertia: 75.43632182947037
Minibatch step 46/4123: mean batch inertia: 70.91995239257812, ewa inertia: 75.21727114666602
Minibatch step 47/4123: mean batch inertia: 70.87779235839844, ewa inertia: 75.00679992528623
Minibatch step 48/4123: mean batch inertia: 71.36738586425781, ewa inertia: 74.83028289181152
Minibatch step 49/4123: mean batch inertia: 71.25393676757812, ewa inertia: 74.65682474774147
Minibatch step 50/4123: mean batch inertia: 71.3143539428711, ewa inertia: 74.49470990698471
Minibatch step 51/4123: mean batch inertia: 70.72184753417969, ewa inertia: 74.31172043049527
Minibatch step 52/4123: mean batch inertia: 71.03797149658203, ewa inertia: 74.15293870341911
Minibatch step 53/4123: mean batch inertia: 70.32894897460938, ewa inertia: 73.96746947357927
Minibatch step 54/4123: mean batch inertia: 70.71511840820312, ewa inertia: 73.80972557517924
Minibatch step 55/4123: mean batch inertia: 70.27978515625, ewa inertia: 73.63851817732801
Minibatch step 56/4123: mean batch inertia: 70.07532501220703, ewa inertia: 73.46569797147686
Minibatch step 57/4123: mean batch inertia: 70.52632904052734, ewa inertia: 73.3231341754156
Minibatch step 58/4123: mean batch inertia: 70.60165405273438, ewa inertia: 73.19113831293319
Minibatch step 59/4123: mean batch inertia: 70.39854431152344, ewa inertia: 73.05569332081026
Minibatch step 60/4123: mean batch inertia: 70.97993469238281, ewa inertia: 72.95501591803186
Minibatch step 61/4123: mean batch inertia: 69.51446533203125, ewa inertia: 72.7881440609756
Minibatch step 62/4123: mean batch inertia: 70.49615478515625, ewa inertia: 72.67697914790463
Minibatch step 63/4123: mean batch inertia: 70.26535034179688, ewa inertia: 72.56001153840542
Minibatch step 64/4123: mean batch inertia: 70.87654113769531, ewa inertia: 72.47836070228378
Minibatch step 65/4123: mean batch inertia: 70.89623260498047, ewa inertia: 72.40162511967903
Minibatch step 66/4123: mean batch inertia: 70.25929260253906, ewa inertia: 72.29771878357637
[MiniBatchKMeans] Reassigning 350 cluster centers.
Minibatch step 67/4123: mean batch inertia: 69.62667846679688, ewa inertia: 72.16816932723448
Minibatch step 68/4123: mean batch inertia: 69.51192474365234, ewa inertia: 72.03933748611534
Minibatch step 69/4123: mean batch inertia: 70.57901763916016, ewa inertia: 71.96850978611027
Minibatch step 70/4123: mean batch inertia: 70.25596618652344, ewa inertia: 71.88544885629408
Minibatch step 71/4123: mean batch inertia: 69.83320617675781, ewa inertia: 71.78591201226168
Minibatch step 72/4123: mean batch inertia: 70.43829345703125, ewa inertia: 71.72055049372165
Minibatch step 73/4123: mean batch inertia: 69.10247802734375, ewa inertia: 71.5935700574653
Minibatch step 74/4123: mean batch inertia: 68.9555892944336, ewa inertia: 71.46562403900042
Minibatch step 75/4123: mean batch inertia: 69.3132095336914, ewa inertia: 71.36122871136966
Minibatch step 76/4123: mean batch inertia: 69.5753402709961, ewa inertia: 71.27461044691134
Minibatch step 77/4123: mean batch inertia: 70.10629272460938, ewa inertia: 71.21794528734486
Minibatch step 78/4123: mean batch inertia: 70.50637817382812, ewa inertia: 71.18343321647578
Minibatch step 79/4123: mean batch inertia: 69.79534149169922, ewa inertia: 71.1161086885876
[MiniBatchKMeans] Reassigning 379 cluster centers.
Minibatch step 80/4123: mean batch inertia: 69.5608901977539, ewa inertia: 71.04067826220479
Minibatch step 81/4123: mean batch inertia: 69.13639831542969, ewa inertia: 70.94831783234616
Minibatch step 82/4123: mean batch inertia: 69.15612030029297, ewa inertia: 70.86139356749092
Minibatch step 83/4123: mean batch inertia: 69.48844909667969, ewa inertia: 70.79480370410928
Minibatch step 84/4123: mean batch inertia: 69.73965454101562, ewa inertia: 70.74362738918073
Minibatch step 85/4123: mean batch inertia: 69.1792221069336, ewa inertia: 70.66775138965338
Minibatch step 86/4123: mean batch inertia: 69.18224334716797, ewa inertia: 70.59570202443544
Minibatch step 87/4123: mean batch inertia: 69.61512756347656, ewa inertia: 70.54814269426662
Minibatch step 88/4123: mean batch inertia: 69.66595458984375, ewa inertia: 70.5053552497637
Minibatch step 89/4123: mean batch inertia: 68.98465728759766, ewa inertia: 70.43159912072991
Minibatch step 90/4123: mean batch inertia: 69.19989013671875, ewa inertia: 70.37185939001613
Minibatch step 91/4123: mean batch inertia: 69.58576202392578, ewa inertia: 70.3337324902576
Minibatch step 92/4123: mean batch inertia: 68.99826049804688, ewa inertia: 70.26896009821849
[MiniBatchKMeans] Reassigning 375 cluster centers.
Minibatch step 93/4123: mean batch inertia: 68.81282043457031, ewa inertia: 70.19833514336534
Minibatch step 94/4123: mean batch inertia: 69.03727722167969, ewa inertia: 70.14202209500327
Minibatch step 95/4123: mean batch inertia: 68.56661224365234, ewa inertia: 70.06561235739053
Minibatch step 96/4123: mean batch inertia: 69.39645385742188, ewa inertia: 70.03315716780283
OpenBLAS : Program is Terminated. Because you tried to allocate too many memory regions.
This library was built to support a maximum of 50 threads - either rebuild OpenBLAS
with a larger NUM_THREADS value or set the environment variable OPENBLAS_NUM_THREADS to
a sufficiently small number. This error typically occurs when the software that relies on
OpenBLAS calls BLAS functions from many threads in parallel, or when your computer has more
cpu cores than what OpenBLAS was configured to handle.

**Comment by zannnnnn122** [comment]
The first problem occurs when I use a lower number of processes. The second problem appears when I use 30 processes.By the way, I am using 5950x 3080ti with 32GB ram.

**Comment by RVC-Boss** [comment]
The second problem is weird, because https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/infer-web.py#L13 this line has already set the environment variable OPENBLAS_NUM_THREADS

**Comment by zannnnnn122** [comment]
I tried to retrain the model, but the problem remains the same. I guess it is because I am using too big material. Because this did not happen with previous material that was about an hour long.

inibatch step 100/4123: mean batch inertia: 69.41400146484375, ewa inertia: 69.96922383319882
Minibatch step 101/4123: mean batch inertia: 69.32368469238281, ewa inertia: 69.9379142179097
OpenBLAS : Program is Terminated. Because you tried to allocate too many memory regions.
This library was built to support a maximum of 50 threads - either rebuild OpenBLAS
with a larger NUM_THREADS value or set the environment variable OPENBLAS_NUM_THREADS to
a sufficiently small number. This error typically occurs when the software that relies on
OpenBLAS calls BLAS functions from many threads in parallel, or when your computer has more
cpu cores than what OpenBLAS was configured to handle.

**Comment by HerzogVonWiesel** [comment]
I have the same issue, don't know why it is marked as closed when it's still prominent

**Comment by TeuMasaki** [comment]
Manually assign `set OPENBLAS_NUM_THREADS=1` in the same terminal before running the bat file solved it for me.

It seems that this variable has not been set correctly for Windows PC.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/583/files

**Comment by KCKCC** [comment]
another error here 
```
...
Minibatch step 429/7937: mean batch inertia: 19.140943908691405, ewa inertia: 19.026682970182534
Minibatch step 430/7937: mean batch inertia: 19.042236328125, ewa inertia: 19.027074871601677
Minibatch step 431/7937: mean batch inertia: 18.995516967773437, ewa inertia: 19.02627970008044
Minibatch step 432/7937: mean batch inertia: 19.0922119140625, ewa inertia: 19.027941008739464
Minibatch step 433/7937: mean batch inertia: 19.260760498046874, ewa inertia: 19.033807413190583
Minibatch step 434/7937: mean batch inertia: 18.869248962402345, ewa inertia: 19.029660997308284
Minibatch step 435/7937: mean batch inertia: 18.857196044921874, ewa inertia: 19.02531535954681
Minibatch step 436/7937: mean batch inertia: 19.15046844482422, ewa inertia: 19.028468869670583
Minibatch step 437/7937: mean batch inertia: 18.94288024902344, ewa inertia: 19.02631227416123
Converged (lack of improvement in inertia) at step 437/7937
OMP: Error #179: Function pthread_mutex_init failed:
OMP: System error #22: Invalid argument
run.sh: line 62: 25739 Segmentation fault: 11  python3.8 infer-web.py --pycmd python3.8

```
but the model is still useable, what's the effect of this step?
