### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 40: invalid start byte

### ISSUE THREAD

**Issue by UmutDeniz26** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#652]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/76654674/3c1468ec-1e8e-482f-852b-1258c663c302)

I got this error while training the model with one-click training.

**Comment by RVC-Boss** [comment]
It may be caused by the path of the wav in your trainingset, some special char that utf8 doesn't support is in the path.

**Comment by Han-Zhong** [comment]
> ![image](https://private-user-images.githubusercontent.com/76654674/249801596-3c1468ec-1e8e-482f-852b-1258c663c302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTIxMTQsIm5iZiI6MTcwMzQ5MTgxNCwicGF0aCI6Ii83NjY1NDY3NC8yNDk4MDE1OTYtM2MxNDY4ZWMtMWU4ZS00ODJmLTg1MmItMTI1OGM2NjNjMzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA4MTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNzVkOTFjNjI2NjBjZjQ0OTY0YjUzYmQ4OTQzNjUyNDI5N2Q1NzMzMzIxYjQ4MzNhZDIwNzI2MjA1ODkyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BOROp0MWJoV83T7cH4sV34ZYCiu6HRp2pl8O7u5yvK8)
> 
> I got this error while training the model with one-click training.

I have experienced similar problem, using a .wav file which contains some chinese album title information, just clean those information will fix.

**Comment by badralhetar** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/652#issuecomment-1868864181

I have experienced similar problem, using a .wav file which contains some chinese album title information, just clean those information will fix.
