### ISSUE TITLE
What batch size per GPU should I use?

### ISSUE THREAD

**Issue by Vzdroidplayz** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#656]
Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
RAM: 16.0 GB (15.7 GB usable)
RTX 3050

**Comment by Chilluminati91** [comment]
Start with 30 then work your way down until you dont get memory allocation errors anymore. Then substract 2 and you got your value.

**Comment by RVC-Boss** [comment]
Try batch size2 first, if oom error is caused, then batch size 1.

**Comment by pierluigizagaria** [comment]
Is there a rule to choose the batch size? Should I increase is as far as the GPU can handle? Bigger batch size should be slower on converging.
