### ISSUE TITLE
运行go-web.bat报错

### ISSUE THREAD

**Issue by 18319522387** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#657]
runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897

系统找不到指定的路径

**Comment by MazenVR** [comment]
Windows firewall block the port

**Comment by Skyler-Sun** [comment]
I met the same question, and my firewall is closed.

**Comment by Skyler-Sun** [comment]
> runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
> 
> 系统找不到指定的路径

This may help #605

**Comment by Skyler-Sun** [comment]
整合包链接
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC-beta.7z

**Comment by RVC-Boss** [comment]
要么你自己配环境修改命令，要么下载7z包
