### ISSUE TITLE
invalid literal for int() with base 10: 'TIME' 

### ISSUE THREAD

**Issue by AJKurano** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#664]
I am getting an error please help me!

runtime\python.exe trainset_preprocess_pipeline_print.py E:\OneDrive\REAL TIME VOICE CHANGER AI (RVC)\RVC Friend Vocals\RVC-beta-v2-0618\Samples 40000 14 E:\OneDrive\REAL TIME VOICE CHANGER AI (RVC)\RVC Friend Vocals\RVC-beta-v2-0618/logs/friend False
Traceback (most recent call last):
  File "E:\OneDrive\REAL TIME VOICE CHANGER AI (RVC)\RVC Friend Vocals\RVC-beta-v2-0618\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'TIME'

**Comment by RVC-Boss** [comment]
It's because RVC doesn't support space in path now.

**Comment by boks14344** [comment]
> 

whats the solution pls

**Comment by AJKurano** [comment]
> > 
> 
> 
> 
> whats the solution pls

All you have to do is put the code in a folder that doesn't have spaces in its name. Make sure that its directory has no space at all.
