### ISSUE TITLE
Why was hop size of 10ms chosen?

### ISSUE THREAD

**Issue by jmasterx** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#666]
Hello!

I notice the models use hop size of 10ms, but a lot of papers for SVS suggest 5ms. Is there a reason this hop size was used?

**Comment by RVC-Boss** [comment]
Because the pretrained self supervised feature model RVC used only supports 16k-320hop. (And nearly all hubert series SSL feature only supports 16k-320hop)
