### ISSUE TITLE
myinfer.py 执行不下去了

### ISSUE THREAD

**Issue by fangg2000** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#681]
我以为改了

`from infer_pack.models import SynthesizerTrnMs256NSF as SynthesizerTrnMs256NSFsid, SynthesizerTrn256NSFkm as SynthesizerTrnMs256NSFsid_nono`

就可以了，想不到还有其他异常，UP主能更新个可以正常执行的出来么？我想要个命令行执行直接出来结果的，非常感谢啊

**Comment by fangg2000** [comment]
嗐，我执行了infer_batch_rvc.py发现是可以的，是不是表示照着这个改？

**Comment by RVC-Boss** [comment]
可以

**Comment by fangg2000** [comment]
谢谢，这个问题已经解决了。能说下关于hubert_base.pt的作用吗？这个是不是底模，类似预训练模型？是的话，我想自己做一个别的类型的。

**Comment by HenryCheung898** [comment]
> 

hello,能说一下这个问题怎么解决的吗？我用了infer_batch_rvc.py也还是有错误，程序会自动pause，有时候推理出来的声音很慢，有时候推理不出来。

**Comment by fangg2000** [comment]
之前myinfer.py无法推理，然后我使用infer_batch_rvc.py可以正常推理，你说的“程序会自动pause，有时候推理出来的声音很慢，有时候推理不出来”这个问题到目前为此我没有发现，但我猜测可能的原因是你训练的语音和项目提供的底模匹配度不高，所以会出现推理效果很差的情况。要证明这个猜测对不对很简单，就用标贝语音训练的模型来试。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年7月10日 4:19
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [RVC-Project/Retrieval-based-Voice-Conversion-WebUI] myinfer.py 执行不下去了 (Issue #681)


hello,能说一下这个问题怎么解决的吗？我用了infer_batch_rvc.py也还是有错误，程序会自动pause，有时候推理出来的声音很慢，有时候推理不出来。

―

**Comment by liziru** [comment]
> 谢谢，这个问题已经解决了。能说下关于hubert_base.pt的作用吗？这个是不是底模，类似预训练模型？是的话，我想自己做一个别的类型的。

可能是decoder模型
