### ISSUE TITLE
Is there any way to speed up harvest on new input files?

### ISSUE THREAD

**Issue by maxiedaniels** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#682]
I know there’s been caching implemented to speed up inferences after the first inference, but is there no way to speed up the initial inference??

Crepe just doesn’t sound as stable or good to me (this is with high quality singing data). Also crepe doesn’t seem to get any faster if I change the batch size in vc_infer_pipeline.py.

**Comment by RVC-Boss** [comment]
In the next version I will achieve multi-processing for harvest

**Comment by maxiedaniels** [comment]
> In the next version I will achieve multi-processing for harvest

That would be fantastic, thank you! Just so I understand, does the current harvest method do some calculation on the input file and then cache it somehow for future inferences? If so, does that get cached to memory or is it on disk?

**Comment by RVC-Boss** [comment]
Better pitch method RMVPE is supported. Now harvest is not needed.
