### ISSUE TITLE
Error as an output, help

### ISSUE THREAD

**Issue by MattTDK** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#690]
On vocals/accompaniment separation & reverberation removal whenever i click the convert button i get an error on the output information
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/86790371/6f150455-30ee-4a01-ac45-24c906589c56)
are there any fixes to this?

**Comment by RVC-Boss** [comment]
If you want just to separate one file: you should delete this directory line
