### ISSUE TITLE
Tutorial for training from cli?

### ISSUE THREAD

**Issue by futorio** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#692]
Hi, I would like to train an RVC model on a server without a GUI, using only the command line interface (CLI). What steps do I need to follow in order to train the model using my own data? Thank you.

**Comment by crapIBuilt** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/FAQ-(Frequently-Asked-Questions)
Read Q7.
