### ISSUE TITLE
有没有使用mac进行安装的小伙伴？训练原声的时候显示成功了，但是特征检索库是空的是什么情况？log下没有那个index的文件。

### ISSUE THREAD

**Issue by Kar1chan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#695]
你们能成功吗？特征库是空的
![97fb60f77711616a4392e237e2d627d9](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/89959368/d0777a03-c8b1-456d-ad5f-563215029a77)
推理音色是有的
![eb6b92a1dffef34a91ea64a7a3c226c7](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/89959368/42fcdd79-820b-4e06-8c14-b084b85c1e0f)

**Comment by Nemophilister** [comment]
用Mac安装了吗 我也想问😊

**Comment by Naozumi520** [comment]
同問，能成功推理而效果不錯，但是不知道沒有這個影不影響。

**Comment by yayuanli** [comment]
The same issue here.

**Comment by Naozumi520** [comment]
@yayuanli You're right. Some functions are not supported by MPS with PYTORCH_ENABLE_MPS_FALLBACK it can be done on the CPU. But the issue here is the .index file is not being generated during training. If you click 训练特征索引, you will noticed the script crash. Do we know 训练特征索引 is not currently supported.

**Comment by Naozumi520** [comment]
@Kar1chan Try to downgrade faiss-cpu to 1.7.0.

**Comment by lennondong** [comment]
> 你们能成功吗？特征库是空的 ![97fb60f77711616a4392e237e2d627d9](https://private-user-images.githubusercontent.com/89959368/251323917-d0777a03-c8b1-456d-ad5f-563215029a77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MjgyOTIsIm5iZiI6MTcwMjYyNzk5MiwicGF0aCI6Ii84OTk1OTM2OC8yNTEzMjM5MTctZDA3NzdhMDMtYzhiMS00NTZkLWFkNWYtNTYzMjE1MDI5YTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA4MTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNzM3MGY1NjgzZDVmMjM5NjFkYjY4Yjg1NjExOGI3OWQ3ODY2NmQ3NGRhNDY3MjdjYzRkNjU5OWYwYjRiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dma1viqR16sqm_2wM2x4YPdAdK4XJyWuohLdl-VhlZY) 推理音色是有的 ![eb6b92a1dffef34a91ea64a7a3c226c7](https://private-user-images.githubusercontent.com/89959368/251323943-42fcdd79-820b-4e06-8c14-b084b85c1e0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MjgyOTIsIm5iZiI6MTcwMjYyNzk5MiwicGF0aCI6Ii84OTk1OTM2OC8yNTEzMjM5NDMtNDJmY2RkNzktODIwYi00ZTA2LThjMTQtYjA4NGI4NWMxZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA4MTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MmJkYTY4NWE0ZGJkMmI0NzMwOTczYTk0Zjk1NTFmMDQ0ZDU3OGQxM2VlNjljOTU1MThhOWIxMWMzNGU0YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DBcMb-7TK88sVk0T8aSZyRlda8ileaKlZ3tronG1Io0)

请问，你Mac上装的是哪个版本？我连运行都运行不起来，一直报错。直接下载的beta.7z文件中，都没有run.sh文件。

**Comment by zhouhao27** [comment]
我也安装不了，Mac mini m2， Mac OS 14.0

**Comment by wastu01** [comment]
我想請教大家 Mac 如何啟動實時變聲的介面，目前有透過 `./run.sh`成功啟動訓練用的介面

**Comment by XXXXRT666** [comment]
使用conda安装faiss-cpu
