### ISSUE TITLE
go-realtime-gui CMD窗口卡住不往下走了

### ISSUE THREAD

**Issue by hulululu7654321** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#698]
2080ti，webui已可用，系统地区，勾选了用utf-8解码，requirements和requirements for gui依赖也都装好了
go-realtime-gui.bat点开后一直卡在 E:\RVC-beta-v2-0618>runtime\python.exe gui.py
也不报错也不闪退，系统里的py310和runtime文件夹里的py39运行都会这样。
想请教下大大是什么问题导致的。
![Snipaste_2023-07-07_00-59-17](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116489967/dbbd3b3e-24f8-4f1a-94ee-ba1b5c585e87)
![Snipaste_2023-07-07_01-00-23](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116489967/dec9c10a-2cbf-4dd8-a320-062212f9a415)
![Snipaste_2023-07-07_01-02-59](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116489967/c49c2799-4d36-490b-b015-5145710664ad)
![Snipaste_2023-07-07_01-06-41](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116489967/30566d20-8d7f-4109-907e-34f0e3e70e2d)

**Comment by hulululu7654321** [comment]
重启电脑后运行go-realtime-gui ，卡在了新的地方
![Snipaste_2023-07-07_01-22-45](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116489967/6cf6f924-619a-4d32-8ef8-233f67ac1d5f)

**Comment by Pijulin** [comment]
右键 用管理员权限运行bat试试

**Comment by hulululu7654321** [comment]
> 右键 用管理员权限运行bat试试

尝试了，会直接闪退。
然后我尝试了在几个关键点print了一下，发现是最后一步gui =GUI（）的时候会卡住，前面的都正常print出来了，这可能是什么原因呢？日本人做的voice changer我也会卡住，感觉像是我的电脑在生成UI的步骤有什么冲突？

![DA%%U924%EW`V{(C)KHD5 A](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/116489967/2eb8f5c8-f730-45a4-924c-2d27e50d5233)

**Comment by sligter** [comment]
解决了吗楼主？我也是同样问题

**Comment by 741MiaMelano** [comment]
我也是同样的问题，请问解决了吗？

**Comment by sligter** [comment]
> 

我把Unicode UTF-8打开可以了

**Comment by 741MiaMelano** [comment]
> > 
> 
> 我把Unicode UTF-8打开就可以了

非常感谢，我打开后也可以了

**Comment by RVC-Boss** [comment]
编码问题最新main分支已解决，bat文件开头会设置编码
