### ISSUE TITLE
Start training can't know the progress %

### ISSUE THREAD

**Issue by minimoonleaf** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#702]
Start training can't know the progress %

Is there a way to know the current progress?
The cmd show the 20% 50%... a lot of different progress, can not understand what it means?
like this:
...
INFO:Zumndamon_Model:Train Epoch: 9 [20%]
INFO:Zumndamon_Model:[4200, 9.990004373906418e-05]
INFO:Zumndamon_Model:loss_disc=3.959, loss_gen=3.062, loss_fm=7.881,loss_mel=17.356, loss_kl=1.535
INFO:Zumndamon_Model:Train Epoch: 9 [50%]
INFO:Zumndamon_Model:[4400, 9.990004373906418e-05]
INFO:Zumndamon_Model:loss_disc=4.060, loss_gen=2.972, loss_fm=7.563,loss_mel=18.711, loss_kl=1.495
INFO:Zumndamon_Model:====> Epoch: 9 [2023-07-07 13:35:13] | (1:11:57.773330)
...
If there is no such function, is there a chance to add the function of displaying progress?

**Comment by ahmaddarwesh** [comment]
it's quite simple. Just look for this line:
`INFO:Zumndamon_Model:====> Epoch: 9 [2023-07-07 13:35:13] | (1:11:57.773330)
`
You can see that the current **epoch is 9**. The training will end when the epoch number matches the value you set for the `"Total training epochs"` option before starting the training.

Enjoy

**Comment by Ttwing9999** [comment]
what does the `INFO:Zumndamon_Model:loss_disc=4.060, loss_gen=2.972, loss_fm=7.563,loss_mel=18.711, loss_kl=1.495` mean
