### ISSUE TITLE
No module named 'faiss'

### ISSUE THREAD

**Issue by Mshriver2** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#703]
Hi, after installing the requirements I try to launch the web interface with python but I get the following error.

`Traceback (most recent call last):
  File "infer-web.py", line 21, in <module>
    import faiss
ModuleNotFoundError: No module named 'faiss'
`
and when I try to install it with pip it says it is not found. Any ideas? I am running Windows 10.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/3216992/1cc05438-c5ff-4f93-a064-5af9670e5f9d)

**Comment by Mshriver2** [comment]
I also tried `pip install faiss-gpu`, but got the following error.
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/3216992/642f8189-860f-4a78-8410-8bdccfa09e9f)

**Comment by paolobettelini** [comment]
`pip install faiss` and `pip install numpy`

**Comment by RVC-Boss** [comment]
You should specify the pip corresponding to the location of the Python environment you want to call, and then enter 
xxx/xxx/pip install -r requirements.txt
no "install faiss", but "install faiss-cpu"

**Comment by Mshriver2** [comment]
Thanks, that fixed it
