### ISSUE TITLE
Add an option to automatically extract and save weights when saving checkpoints

### ISSUE THREAD

**Issue by Tiger14n** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#71]
Just a suggestion that i think would help a lot, to add an option that extracts and saves a weight file automatically when saving a checkpoint, ./weights/$experimentName_$steps.pth, to easily watch and read progress

**Comment by liujing04** [comment]
ok, next version

**Comment by tomakorea** [comment]
Good idea !

**Comment by RVC-Boss** [comment]
Done. You can update RVC to use this feature.
