### ISSUE TITLE
 Can RVC, like training in other fields, support the feature of resuming training from the interrupted position? If it doesn't currently support it, will it be added in future versions?

### ISSUE THREAD

**Issue by 6get-xiaofan** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#712]
Can RVC, like training in other fields, support the feature of resuming training from the interrupted position? If it doesn't currently support it, will it be added in future versions?

**Comment by RVC-Boss** [comment]
You can continue training by clicking "train the model" using the same exp_name and more total_epoch.
