### ISSUE TITLE
go-web.bat doesn't open the website

### ISSUE THREAD

**Issue by Hugoyim0097** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#721]
When I click go-web.bat it doesn't open the website and cmd doesn't list the command, How to fix it please?

**Comment by Paintshooter22** [comment]
i don't know if this will help but if the path to the RVC beta folder has a space it won't work, for example "F:\Program Files\RVC" the space in between "Program Files" was my problem so i moved the RVC file  and it worked. hope this helps.

**Comment by playboiyetti** [comment]
running not the same issue. I am running this on Mac. I have moved he folder but still nothing.
![Screen Shot 2023-11-14 at 2 42 41 PM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/69122082/c9831465-687f-43b8-bb6d-b8927c3dcca1)
 any ideas? it worked when I first install it but now this is what pops up when I try to run it

**Comment by playboiyetti** [comment]
Running into the same issue. I am running this on Mac OS. it was running when I first installed it . but now I run into this. any ideas thanks
![Screen Shot 2023-11-14 at 2 42 41 PM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/69122082/dad421a2-3e72-4fc0-bd85-6a8294c7b27b)

**Comment by ReconNinja117** [comment]
Having the same issue.  I open the batch file and it doesn't work for no reason.

**Comment by Tps-F** [comment]
@playboiyetti Mac can't run batch file
You can use `run.sh`
