### ISSUE TITLE
Cannot run with go-web.bat

### ISSUE THREAD

**Issue by srinoom** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#726]
I cannot run RVC with go-web.bat, it said "The system cannot find the specified."

But if I run RVC with infer-web.py it can start browser nomally.
![Screenshot 2023-07-11 105142](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/115764008/8c1d65c7-2127-4e79-b55e-2a124cdb21b5)

**Comment by RVC-Boss** [comment]
You didn't download the 7z package.

**Comment by srinoom** [comment]
thank you, that's work!!!
