### ISSUE TITLE
How to inference to all audio files in the directory

### ISSUE THREAD

**Issue by kontomac** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#731]
Is there a way to infer to multiple files at once? Something like --recursive in so-vits-svc

**Comment by RVC-Boss** [comment]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/129054828/69b5f09f-16d4-443d-a62c-1afde4d1acc2)
default tab, in the bottom, here is the batch inference tool
