### ISSUE TITLE
res raised

### ISSUE THREAD

**Issue by roar-pixel** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#741]
when i start the voice changer my res raised, what to do?
![Screenshot_3](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/61620451/2aebeb71-1243-4e57-a899-f4534f3c17cf)

**Comment by ms903x1** [comment]
Please come to this warehouse to ask questions   https://github.com/w-okada/voice-changer
