### ISSUE TITLE
pee

### ISSUE THREAD

**Issue by pixisnorter** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#742]
why is rvc-beta.7z not even in the download area. every tutorial says to download that but i cant even find it.

**Comment by Naozumi520** [comment]
<img width="1094" alt="Screenshot 2023-07-13 at 11 46 09 AM" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/52615455/64b5b763-3ee1-43f1-bcaf-5ba887241244">
What do you mean?

**Comment by Nitch-dev** [comment]
> why is rvc-beta.7z not even in the download area. every tutorial says to download that but i cant even find it.

here you go: https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main
Download the one saying RVC-beta.7z 
extract it also please make sure you use python3.8 else it wont work then run `run.sh` if your own linux/macos after that stuff will install then run `python3 infer-web.py` it will start localhost website in browser 
if on windows just click the bat file to run it nothing need stated up :) 
Enjoy
