### ISSUE TITLE
How to get good results from voice lines taken from videogames game files

### ISSUE THREAD

**Issue by antomanc** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#747]
I tried training some models with different voice lines taken from a videogame, they were all about 10 minutes long, but I could't managed to get good results. The audio i used had all the different speaches very close to each others, like 0.5s. I tried training with 200/250 epochs but the results was always not clear. Also I noticed that the model could not reproduce silence very well, it filled it with random noises. How can I improve the results? Unfortunately the game files voice lines are all max 10/11 minutes long, so the duration is not something i can change.

**Comment by mhalagha** [comment]
Seems like your training dataset is of low quality. For low quality training datasets, increasing the epochs will NOT result in a better result. First, try to improve your training datasets - remove background noise, split the training audio into multiple files per speaker. Please note that RVC currently support only a single speaker. If you want to do multiple speakers, you have to create multiple experiments (one for each speaker) then mix them using a third party software.

**Comment by antomanc** [comment]
> Seems like your training dataset is of low quality. For low quality training datasets, increasing the epochs will NOT result in a better result. First, try to improve your training datasets - remove background noise, split the training audio into multiple files per speaker. Please note that RVC currently support only a single speaker. If you want to do multiple speakers, you have to create multiple experiments (one for each speaker) then mix them using a third party software.

Yes I trained only one speaker at the time. The voice lines are perfect in audio quality, but all the phrases are very short (max 2/3 seconds per phrase). Maybe this is the problem.

**Comment by mhalagha** [comment]
I doubt that is the issue, my training audio sample phrases are short as well and I seems to get good results. Try mixing all your sample phrases in a single file and see of that improve your results
