### ISSUE TITLE
sing Local GUI with Computation on a Remote Cloud Server for Real-Time Voice Changing

### ISSUE THREAD

**Issue by 121380-zyh** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#750]
I have a project that I want to deploy on a cloud server with high GPU capabilities, while I want to run the GUI on my local machine. My local machine has an RX590 + i5 12600kf configuration, and the cloud server has a 3080 + 12-core CPU configuration.

I want to use the 'go-realtime-gui.bat' GUI for real-time voice changing, but I want the computation to be done on the cloud server, not on my local machine. I was thinking of using an SSH tunnel so that I can call the program from the command line on my local machine, and the sound can come out from my local machine but the computation is done on the server.

Is there a way to achieve this? Can I send the audio data from my local machine to the cloud server for processing, and then send the processed data back to my local machine? Any advice or suggestions would be greatly appreciated

**Comment by silverDent** [comment]
@121380-zyh  did you get solution for this?
