### ISSUE TITLE
Error after training complete while saving added*.index

### ISSUE THREAD

**Issue by ahmed-ansari-31** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#751]
After training complete in RVC v2 model. There is some error and it does not saving the file of added*.index in log folder because of this error. 

```INFO:noorenSadiq-wav-100:Training is done. The program is closed.
INFO:noorenSadiq-wav-100:saving final ckpt:Success.
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 534, in <module>
    main()
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 50, in main
    mp.spawn(
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 149```

**Comment by masanbasa3k** [comment]
Hello,

I've looked into the issue you encountered during the training of the RVC v2 model. I examined the provided code snippet, and it seems that there is an error related to the saving process. The error indicates that the `added*.index` file is not being saved in the log folder.

The code itself appears to be correct. However, to address the error, you can try the following steps:

1. Check the file paths: Verify that the file paths specified using `os.path.join` are accurate. Ensure that the folders exist and have the necessary write permissions.

2. Verify file permissions: Confirm that you have the appropriate permissions to create and write files in the relevant folders. Check that the user running the code has the required permissions.

3. Validate dependencies: Ensure that you have the correct versions of all dependencies (libraries, modules, etc.) for the code to function properly. If necessary, use specific versions or configure other dependencies accordingly.

If you have followed these steps and the issue persists, They will help you in this issue probably

I hope this information is helpful. I tried to help to the best of my ability. Feel free to reach out if you need any further assistance.

Best regards!

**Comment by RVC-Boss** [comment]
> After training complete in RVC v2 model. There is some error and it does not saving the file of added*.index in log folder because of this error.
> 
> ```
> INFO:noorenSadiq-wav-100:saving final ckpt:Success.
> Traceback (most recent call last):
>   File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 534, in <module>
>     main()
>   File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 50, in main
>     mp.spawn(
>   File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
>     while not context.join():
>   File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 149, in join
>     raise ProcessExitedException(
> torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 149```
> ```

try click "train the index"
