### ISSUE TITLE
Cannot separate track

### ISSUE THREAD

**Issue by LordMilutin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#753]
Hi, 
I am having issue separating instrumental and vocals, as there is no model available:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/76582100/83771474-1b71-49ee-8f9e-60b0b82a5aa4)

Also, this is the error:
Traceback (most recent call last):
File "/app/infer-web.py", line 393, in uvr
     del pre_fun.model
 UnboundLocalError: local variable 'pre_fun' referenced before assignment
 clean_empty_cach

Any tips on how to fix this?

**Comment by jkmurray123** [comment]
Same here, can't find a fix. first run it ran fine. moved the folder and then it wouldnt run. tried a fresh download and still same error.

**Comment by LordMilutin** [comment]
> Same here, can't find a fix. first run it ran fine. moved the folder and then it wouldn't run. tried a fresh download and still same error.

I fixed it by downloading again hubert_base.pt and pretrained, pretrained_v2 and uvr5_weights.
