### ISSUE TITLE
can't uninstall RVC???

### ISSUE THREAD

**Issue by occuItic** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#755]
there's two .dll files (which add up to 841 mb) that refuse to let me delete them. it constantly says they're being used by another program, even though i don't have rvc running.

i tried command prompt del file, didn't work. ran as administrator and it didn't work.
tried process explorer, the .dlls didn't even show up so it didn't work.

this is extremely frustrating as i'm trying to save space in my pc, and rvc stopped working for me a while ago anyway. literally made a github account just to post this.

**Comment by Aeeroid** [comment]
Did you ever figure out how to uninstall it? I've got the same problem.
