### ISSUE TITLE
CKPT Fusion Error: The size of tensor a (768) must match the size of tensor b (256) at non-singleton dimension 1

### ISSUE THREAD

**Issue by abc123807** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#761]
Whenever I try to fuse two models together under the ckpt processing tab, I get this error:

Traceback (most recent call last):
  File "C:\Users\me\Documents\RVC-beta\RVC-beta-v2-0618\train\process_ckpt.py", line 198, in merge
    alpha1 * (ckpt1[key].float()) + (1 - alpha1) * (ckpt2[key].float())
RuntimeError: The size of tensor a (768) must match the size of tensor b (256) at non-singleton dimension 1

**Comment by RVC-Boss** [comment]
v1 model can't be merged with v2 model
