### ISSUE TITLE
内测FasterRVC-RealTime-fix_v1版本延迟跟以前的版本一样！

### ISSUE THREAD

**Issue by xypiaofei** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#764]
使用内测FasterRVC-RealTime-fix_v1版本同样的参数跟之前6.15、5.28版本延迟一样，延迟都是大概2秒，延迟没有减小，是需要安装什么运行库，或者设置哪里吗？非常感谢。Win11、 i9-13900K 、GTX4090.

**Comment by RVC-Boss** [comment]
建议直接更新即将发布的0716版本，音高推荐新上的rmvpe，如果想用以前的，0416pm，0528harvest，调低采样长度，然后再看看延迟怎么样
采样长度=延迟
推理时间>采样长度会出现机关枪（卡顿）
