### ISSUE TITLE
how long does trining take

### ISSUE THREAD

**Issue by runtimefred** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#770]
how long does training take ? its been 2 hours so far and the dos cursor is just blinky blinky  If is a lot longer no problem ill leave it overnight

**Comment by dan691** [comment]
depeneds on the numbers of epochs you selected and how much does it take for one to be procesed

**Comment by RVC-Boss** [comment]
depeneds on total_epoch and length_dataset
