### ISSUE TITLE
inferance voice blank

### ISSUE THREAD

**Issue by runtimefred** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#773]
i have done the one click training (all processes complete) and also the separation (all processes complete) but when i press the refresh voice list button the Inferencing voice: drop down stays blank. I know its me but your help would be appreciated thanks in advance

**Comment by code-house10** [comment]
I have same problem ..any one can help us ?

**Comment by gigamesh** [comment]
same here

**Comment by AleDZMP** [comment]
Same for me

**Comment by michelle-w-br** [comment]
same for me
