### ISSUE TITLE
issue in culab

### ISSUE THREAD

**Issue by Ali99997** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#782]
/content/Retrieval-based-Voice-Conversion-WebUI
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 7, in <module>
    import faiss
ModuleNotFoundError: No module named 'faiss'

**Comment by RECKENEFIN** [comment]
Same problem here. I found the part where it downloads and installs faiss-cpu, and that operation completed without issue.

I can confirm that everything was working when I used it yesterday.

**Comment by akashuki** [comment]
Please someone help 

/content/Retrieval-based-Voice-Conversion-WebUI
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 7, in <module>
    import faiss
ModuleNotFoundError: No module named 'faiss'

**Comment by Sahgee** [comment]
I am having the same issue, and it is a result of the codependencies not being installed properly in the first cell. I posted my issue, and hopefully when I get an answer I can repost it here to help

**Comment by itssmizusu** [comment]
/content/Retrieval-based-Voice-Conversion-WebUI
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 21, in <module>
    import faiss
ModuleNotFoundError: No module named 'faiss'

how can i fix it?

**Comment by playbyan1453** [comment]
in #786 fixed the issue, install a specific pyworld version like this `pyworld==0.3.2`

**Comment by Ali99997** [comment]
> in #786 fixed the issue, install a specific pyworld version like this `pyworld==0.3.2`

how??????

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/786
In this issue someone pointed out the correct installation steps for environmental dependencies

**Comment by RVC-Boss** [comment]
pip install faiss-cpu==1.7.2
