### ISSUE TITLE
Crashing when converting

### ISSUE THREAD

**Issue by theman12222** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#783]
Every time I try to convert it starts converting, stays for a few seconds while it says the program is not responding, then closes. It doesnt give me an error message just says "Press any key to continue" Please help.
<img width="857" alt="Screenshot 2023-07-17 125932" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/112595465/ea2c4601-6bd5-4da0-a90c-7c88e5afb059">

**Comment by RVC-Boss** [comment]
Audio whose path contains space or () may cause error when inference.

**Comment by theman12222** [comment]
Unfortunately that did not solve my issue, i have it on a usb drive and edited the name so there's no spaces or () and nothing changed

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. You can now drag and drop audio files into the frontend instead of entering their file paths manually.
