### ISSUE TITLE
 problem

### ISSUE THREAD

**Issue by noonADM** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#784]
I have a problem:

Unfortunately, there is no compatible GPU available to support your training.

**Comment by Sahgee** [comment]
If you are using Google Colab just try updating the GPU choice in the runtime settings

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. 

The GPU detection logic has been fixed and is now working properly.
