### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by LordMilutin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#785]
I have about 30 minutes of voice data that I trained my model with, and I set 200 epochs.

If I were to add 5 more minutes and set 250 epochs, will it start from the beginning or will it add those new minutes to the existing model and do 50 epochs instead of 250?

Thanks!

**Comment by RVC-Boss** [comment]
step1: put all 35min to path2
step2: exp_name2+path2 -> process dataset and extract feature
step3: copy the latest G and D file of exp_name1 (your previous experiment) into exp_name2 folder
step4: click "train the model", and it will continue training from the beginning of 200epoch

**Comment by Localcrack** [comment]
I am doing such ting but I got following error.

RuntimeError: The expanded size of the tensor (12800) must match the existing size (5200) at non-singleton dimension 1.  Target sizes: [1, 12800].  Tensor sizes: [5200]

**Comment by monnomestjay** [comment]
Same here, I followed the steps and still got this: 

RuntimeError: The expanded size of the tensor (12800) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [1, 12800].  Tensor sizes: [0]
