### ISSUE TITLE
Error installing co-dependencies: Failed building wheel for pyworld / failed to install pyproject.toml

### ISSUE THREAD

**Issue by Sahgee** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#786]
I have been using the RVC WebUI all week, but today is the first time that I am having an issue installing the co-dependencies in the first cell which as a result cannot start the web. The following errors are what I get as seen in the screenshot and copied code below. Any help will be greatly appreciated, as the only thing that has changed is my physical location/wi-fi. 

![1Screenshot 2023-07-17 150337](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/139819407/75894465-d0d2-48d9-861e-d4275be09226)
![2Screenshot 2023-07-17 150432](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/139819407/6572b2f1-f1d2-4424-b7eb-26ce8aab960c)

Building wheels for collected packages: pyworld
  error: subprocess-exited-with-error
  
  × Building wheel for pyworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pyworld (pyproject.toml) ... error
  ERROR: Failed building wheel for pyworld
Failed to build pyworld
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects

**Comment by aaabcbaa** [comment]
Yeah I just started to have this exact problem this morning. Everything was fine yesterday.

**Comment by clopylol** [comment]
Some issue

**Comment by Sahgee** [comment]
> Yeah I just started to have this exact problem this morning. Everything was fine yesterday.

I have been trying to fix it all day to avail. Nothing seems to be working which is very frustrating. Hopefully someone else has an answer soon. I have tried installing all of the upgrades, and I have tried all of the codes below. Let me know if you find anything out, because I have projects I have to work on ASAP.

!apt-get -y install build-essential python3-dev ffmpeg
!pip3 install --upgrade setuptools wheel
!pip3 install --upgrade pip
!sudo apt-get install build-essential
!pip install faiss-cpu
!pip install ffmpeg-python
!pip install pyproject.toml
!pip install fairseq

**Comment by allthingssecurity** [comment]
Same error since morning for me.

**Comment by grimoire-vc** [comment]
Try running

"pip install pyworld==0.3.2"

On Colab, you'll need the exclamation point at the start.

I'm not certain if this is the solution, I'm still messing with it, but it did successfully build the wheel at least!

**Comment by akashuki** [comment]
> 

It is working thank you

**Comment by grimoire-vc** [comment]
One thing you can do that might work better is to replace the pyworld line in requirements.txt to say "pyworld=0.3.2" rather than "pyworld>=0.3.2"

**Comment by longlivebigcat** [comment]
Thank you for the info. It worked for me. What I did was:
1. Run the colab till the error happened
2. From the colab running interface's folder GUI, modify the requirements.txt under the folder "Retrieval-based-Voice-Conversion-WebUI" , replace "pyworld>=0.3.2" with "pyworld==0.3.2"
3. Add this line to the "启动Web“ code block in Colab: 
!apt-get -y install build-essential python3-dev ffmpeg
!pip3 install --upgrade setuptools wheel
!pip3 install --upgrade pip
!sudo apt-get install build-essential
!pip install faiss-cpu
!pip install ffmpeg-python
!pip install pyproject.toml
!pip install fairseq gradio
!pip install -r "/content/Retrieval-based-Voice-Conversion-WebUI/requirements.txt"
4. Run the  "启动Web“ code block again

Then it worked

**Comment by tejasathakur** [comment]
getting the exact same issue, everything was fine till last night

**Comment by Hxydro12** [comment]
> I have been using the RVC WebUI all week, but today is the first time that I am having an issue installing the co-dependencies in the first cell which as a result cannot start the web. The following errors are what I get as seen in the screenshot and copied code below. Any help will be greatly appreciated, as the only thing that has changed is my physical location/wi-fi.
> 
> ![1Screenshot 2023-07-17 150337](https://user-images.githubusercontent.com/139819407/254079129-75894465-d0d2-48d9-861e-d4275be09226.png) ![2Screenshot 2023-07-17 150432](https://user-images.githubusercontent.com/139819407/254079132-6572b2f1-f1d2-4424-b7eb-26ce8aab960c.png)
> 
> Building wheels for collected packages: pyworld error: subprocess-exited-with-error
> 
> × Building wheel for pyworld (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. Building wheel for pyworld (pyproject.toml) ... error ERROR: Failed building wheel for pyworld Failed to build pyworld ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects

Getting same error

**Comment by Sahgee** [comment]
> Thank you for the info. It worked for me. What I did was:
> 
> 1. Run the colab till the error happened
> 2. From the colab running interface's folder GUI, modify the requirements.txt under the folder "Retrieval-based-Voice-Conversion-WebUI" , replace "pyworld>=0.3.2" with "pyworld==0.3.2"
> 3. Add this line to the "启动Web“ code block in Colab:
>    !apt-get -y install build-essential python3-dev ffmpeg
>    !pip3 install --upgrade setuptools wheel
>    !pip3 install --upgrade pip
>    !sudo apt-get install build-essential
>    !pip install faiss-cpu
>    !pip install ffmpeg-python
>    !pip install pyproject.toml
>    !pip install fairseq gradio
>    !pip install -r "/content/Retrieval-based-Voice-Conversion-WebUI/requirements.txt"
> 4. Run the "Start the Web" code block again
> 
> Then it worked

Thank you so much for responding with this detailed answer. I ran everything as you stated, but unfortunatley now get the following error message when starting the web, specifically "ModuleNotFoundError: No module named 'parselmouth". See below: 

/content/Retrieval-based-Voice-Conversion-WebUI
Use Language: en_US
2023-07-18 07:39:45.596651: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-18 07:39:46.857235: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-07-18 07:39:49 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 76, in <module>
    from vc_infer_pipeline import VC
  File "/content/Retrieval-based-Voice-Conversion-WebUI/vc_infer_pipeline.py", line 1, in <module>
    import numpy as np, parselmouth, torch, pdb
ModuleNotFoundError: No module named 'parselmouth'

**Comment by Sahgee** [comment]
Now getting a new error when starting web.

Below are the codes I used in install codependencies after modifying the requirements.txt under the folder "Retrieval-based-Voice-Conversion-WebUI" , replace "pyworld>=0.3.2" with "pyworld==0.3.2":

#@title 安装依赖
!apt-get -y install build-essential python3-dev ffmpeg
!pip3 install --upgrade setuptools wheel
!pip3 install --upgrade pip
!sudo apt-get install build-essential
!pip install faiss-cpu
!pip install ffmpeg-python
!pip install pyproject.toml
!pip install fairseq gradio
!pip install -r "/content/Retrieval-based-Voice-Conversion-WebUI/requirements.txt
!pip install pyworld==0.3.2
!pip install tensorboardX

This is the error I get at the Start Web cell. Please help.:

![3Screenshot 2023-07-18 015301](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/139819407/6d081a28-7d82-4ed3-953e-12ecd16e6806)

**Comment by Sahgee** [comment]
GOT IT TO WORK! Use the following the in the codependencies cell. Hope this helps anyone else. If it does not work again in the morning for whatever reason, I will post an updated comment. (what an emotional and mental rollercoaster @_@):

!apt-get -y install build-essential python3-dev ffmpeg
!pip3 install --upgrade setuptools wheel
!pip3 install --upgrade pip
!pip3 install faiss-cpu==1.7.3 fairseq gradio==3.14.0 ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.1

The change specifically came in the last line with the code:

!pip3 install faiss-cpu==1.7.3 fairseq gradio==3.14.0 ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.1

**Comment by atmos13** [comment]
@Sahgee Do you have any plans to modify colab?

**Comment by Hxydro12** [comment]
i made some changes and its working i was facing same issues on other RVC colab models

**Comment by Sahgee** [comment]
> i made some changes and its working i was facing same issues on other RVC colab models its fixed now thank god

What changes did you make?

**Comment by Sahgee** [comment]
Update: this morning the same code did not work and I am over it -______- any help will still be appreciated

**Comment by avimuh** [comment]
> Update: this morning the same code did not work and I am over it -______- any help will still be appreciated

Could get it to work by downgrading the Cython package to version 0.29.35

`!apt-get -y install build-essential python3-dev ffmpeg
!pip3 install --upgrade setuptools wheel
!pip3 install --upgrade pip
!pip install cython==0.29.35
!pip3 install faiss-cpu==1.7.3 fairseq gradio==3.14.0 ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.1`

**Comment by atmos13** [comment]
> Hi, I could get mine work by downgrading the Cython package to version 0.29.35
I tried to use it, but I didn’t work yet by same error ... any help please

**Comment by RVC-Boss** [comment]
Has been merged.

**Comment by screensguru** [comment]
> 
Thanks! it works for me.

**Comment by ThKnop** [comment]
Hi! There seems to be a similar issue in Colab. Is there a fix for this?
![Bildschirmfoto 2023-09-11 um 23 12 56](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/1767078/6255694d-af96-46d0-9b2f-6a301b21fd8d)

**Comment by tejasathakur** [comment]
> Hi! There seems to be a similar issue in Colab. Is there a fix for this? ![Bildschirmfoto 2023-09-11 um 23 12 56](https://user-images.githubusercontent.com/1767078/267149751-6255694d-af96-46d0-9b2f-6a301b21fd8d.png)

In the install dependencies cell, replace the 'pyworld' with 'pyworld==0.3.2'. That will work!

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/144054197/b32a8e0d-66a0-4939-85a3-e0e2c0b95bf4)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/144054197/3d1283fa-e091-4b8a-b3f8-0d1b753ef50f)

**Comment by ThKnop** [comment]
Thanks! it works for me.

**Comment by tejasathakur** [comment]
> Thanks! it works for me.
Glad that it worked for you!!

**Comment by PixelAvtar** [comment]
Same Error is occuring I am trying to install nes_py to automate super mario!! If anyone find any solution please let me know!! Its a very frustating error!!!

**Comment by utkarsh2299** [comment]
WORKED FOR ME USING:

sudo apt update
sudo apt install g++ OR sudo apt install build-essential
