### ISSUE TITLE
please, can you help me my GPU is Intel's Iris Xe Graphics what can I do?

### ISSUE THREAD

**Issue by noonADM** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#787]
please, can you help me my GPU is Intel's Iris Xe Graphics what can I do?

**Comment by RVC-Boss** [comment]
We're trying to support Intel card

**Comment by kaking4** [comment]
watiting for it work

**Comment by RVC-Boss** [comment]
Supported now.
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC0813AMD_Intel.7z

**Comment by TheWonderfulTartiflette** [comment]
Iris Xe Graphics seem to be supported, but what about Intel Arc GPUs? I downloaded RVC0813AMD_Intel, but when clicking on "One Click Training", it uses only the CPU, nothing more

**Comment by Disty0** [comment]
> Iris Xe Graphics seem to be supported, but what about Intel Arc GPUs? I downloaded RVC0813AMD_Intel, but when clicking on “One Click Training”, it uses only the CPU, nothing more. It takes extremely long to compute the One Click Training, it's been more than 2 hours now on my 13600K

You can use Intel ARC GPUs for training and infer on Linux (or via WSL on Windows):
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/1204

Installation steps:
https://www.technopat.net/sosyal/konu/installing-rvc-webui-with-intel-arc-gpus.2806060/

**Comment by ddpnpkuso** [comment]
Please help I am using intel iris xe graphics and I have confirmed that I can use the GPU for audio conversion in RVC but not for training and it uses the CPU. I want to hear my late wife's voice one more time.

**Comment by Disty0** [comment]
You can try compiling IPEX from the soruce for your iGPU:

https://github.com/intel/intel-extension-for-pytorch/issues/390#issuecomment-1642897738
