### ISSUE TITLE
because rvc-beta depends on torchcrepe (0.0.20), version solving failed.

### ISSUE THREAD

**Issue by jmfergeau** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#789]
Can't install dependencies.

```
$ poetry install
Creating virtualenv rvc-beta-wHl3gqcT-py3.11 in /home/max/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because rvc-beta depends on torchcrepe (0.0.20) which doesn't match any versions, version solving failed.

$ poetry lock
Updating dependencies
Resolving dependencies... (3.4s)

Because torchcrepe (0.0.20) depends on librosa (0.9.1)
 and rvc-beta depends on librosa (0.9.2), torchcrepe is forbidden.
So, because rvc-beta depends on torchcrepe (0.0.20), version solving failed.
```

Using Arch Linux with kernel 6.1.38

**Comment by HardikJain02** [comment]
Any luck?

**Comment by sumant326541** [comment]
same issue with MacBig sur 11.7.7

**Comment by sumant326541** [comment]
I have changed librosa = "0.9.2" to librosa = "0.9.1" in pyproject.toml then run command
poetry lock
and then 
poetry install 
it installed all dependencies

@jmfergeau @HardikJain02 @RVC-Boss

**Comment by HardikJain02** [comment]
I had a couple of errors, idk what's the solution for what error.

I used python version 3.9, and  run the command  `poetry env use [python.exe's path]` and then `poetry install`.

torchcrepe= 0.0.18 and librosa= 0 9.1

**Comment by jmfergeau** [comment]
I kinda fixed my problem by using google collab with this :p but i'll try this next time, just to check

**Comment by IndraTensei** [comment]
> I have changed librosa = "0.9.2" to librosa = "0.9.1" in pyproject.toml then run command poetry lock and then poetry install it installed all dependencies
> 
> @jmfergeau @HardikJain02 @RVC-Boss

Worked for me 👍

**Comment by NatoBoram** [comment]
Can confirm:

```sh
❯ poetry install
Creating virtualenv rvc-beta-eJGcu9WT-py3.10 in /home/nato/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because rvc-beta depends on torchcrepe (0.0.20) which doesn't match any versions, version solving failed.
```
