### ISSUE TITLE
/content/Retrieval-based-Voice-Conversion-WebUI Traceback (most recent call last): File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 7, in import faiss ModuleNotFoundError: No module named 'faiss'

### ISSUE THREAD

**Issue by Ali99997** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#791]
/content/Retrieval-based-Voice-Conversion-WebUI
Traceback (most recent call last):
File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 7, in
import faiss
ModuleNotFoundError: No module named 'faiss'

**Comment by Octasd** [comment]
!pip3 install faiss-cpu==1.7.2 fairseq gradio==3.14.0 ffmpeg ffmpeg-python praat-parselmouth pyworld==0.3.2

Working

**Comment by RVC-Boss** [comment]
↑that's right.
