### ISSUE TITLE
Vocals/Accompaniment Separation & Reverberation Removal - HP2 & HP3 Audio Spikes In Instrumentals

### ISSUE THREAD

**Issue by shalevc1098** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#792]
Is there any way to fix this? I can't get a clean audio because of this

**Comment by mocci24** [comment]
how about using demucs?

**Comment by shalevc1098** [comment]
> how about using demucs?

What is it?

**Comment by mocci24** [comment]
it's vocal separation

**Comment by shalevc1098** [comment]
> it's vocal separation

Tried, and I it worked. I found out that there is a "uvr5" software, downloaded it, tried in it the newest models and it worked. After that, I dragged the 2 models from the "uve5" software to the "models " folder, separated the vocals and instrumentals, but this time I got the spikes. Why is this happening?
