### ISSUE TITLE
ModuleNotFoundError: No module named 'faiss'

### ISSUE THREAD

**Issue by gjin10969** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#795]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/113190973/fdd886bd-d6ae-47d6-b74c-b15448782802)

/content/Retrieval-based-Voice-Conversion-WebUI
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 7, in <module>
    import faiss
ModuleNotFoundError: No module named 'faiss'

**Comment by RVC-Boss** [comment]
pip3 install faiss-cpu==1.7.2
Environmental Dependence: https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/requirements.txt

**Comment by Ali99997** [comment]
> cpu

how can install it??????? vedio pleas

**Comment by gjin10969** [comment]
after i install this
pip3 install faiss-cpu==1.7.2
Environmental Dependence: https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/requirements.txt


New error
/content/Retrieval-based-Voice-Conversion-WebUI
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 21, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'

**Comment by an-internet-user001** [comment]
Yes - i am running into the same issue

**Comment by RVC-Boss** [comment]
try 
apt install ffmpeg
or 
1-download ffmpeg(linux version) from https://github.com/BtbN/FFmpeg-Builds/releases
2-chmod the ffmpeg file to 777
3-modify "ffmpeg" to "path/of/ffmpeg" from https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/lib/audio.py#L16
