### ISSUE TITLE
Supported GPU

### ISSUE THREAD

**Issue by EXSYM** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#806]
Hello,

I have two questions, I got this message :
"No supported Nvidia GPU found, use CPU instead"

However, I have Nvidia RTX 4050 !! I don't know if 4000 series is not yet supported or there's something I've to done first

The second question is, What's the exact function we need "fairseq" for ? Does it "wave2vec" only, or we will use it during the training process ? Because I skipped installing it and disabled the calling function in infer-web file in line 26.

**Comment by hpx502766238** [comment]
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by EXSYM** [comment]
I tried it and also I tried the 117 version of torch with CUDA, I even installed the CUDA from nvidia developers. 

I think there's an issue with 4050 laptop version in drivers, I have just one last idea, I'll try the studio driver and re-install torch with CUDA118 again and will let you know. 4000 series drivers are not well optimized until now, So I think I need to give a try to the studio version with a clean installation after it.

I'll keep you updated.

**Comment by MySurmise** [comment]
I have the same problem with my GTX 1080.
Is that supported?

**Comment by Chriwro** [comment]
Same problem with a RTX 2080

**Comment by 2575156125** [comment]
运行
python
import torch
print(torch.__version__)
看看是不是安装了cpu版本

**Comment by Uahn** [comment]
same with using 3090 with venv, without venv he found all my gpus

**Comment by RVC-Boss** [comment]
× pip install torch ->in windows you will install a CPU version PyTorch.

**Comment by SmoothPlay** [comment]
Got this problem too

**Comment by userhonda** [comment]
Any updates on this issue? Doesn't seem like theres a solution
