### ISSUE TITLE
Ask: Voice Accent Conversion

### ISSUE THREAD

**Issue by imomin** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#807]
I am newbie to AI and RVC. Therefore, not sure if this a valid question but with RVC is it possible to change accent of the speaker (voice)?

**Comment by Federelis** [comment]
In my admittedly limited experience, if I want to have a trained voice speak without its original accent I skip applying the index file. It usually makes the voice sound as native as the voice track steering it. Might be way better ways to do it tho...

**Comment by imomin** [comment]
I mean, a user with non US English accent (Spanish, Indian, Chinese, etc.) and wants to replace their own voice and accent with a trained model. Would that be possible with RVC? One way is to use Whisper to convert speech to text and text to speech.  But thie cannot be implemented for realtime audio conversion.
That being said, is possible to take the original voice, run it through a "model" or speaker with US accent and output the audio in a different accent.

**Comment by Federelis** [comment]
My sense is the more datasets the voice has been trained on the more it follows it's speaker's accent. But I would assume if you're for example not a US english native speaker then that will still be picked up on.

**Comment by fumiama** [comment]
There are many aspects in the accent. RVC can change part of them (such as the detail speaking vowel /a/) but not all. As a result, it is hard to say that RVC can change from one accent to another, but only `similar to` the target.
