### ISSUE TITLE
No data found in dropdown ( Model, Inferencing voice etc ) Screenshot attached

### ISSUE THREAD

**Issue by sheikhsalman** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#808]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/19820316/46bb5fec-9158-419a-9063-e44d2069f481)

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/19820316/828031b0-bd25-4030-b44c-f22c8523c254)

**Comment by Mshriver2** [comment]
I am having the same issue when it comes to the inferencing voice drop down. Mine is blank even after training a model to 20+ epochs. Any ideas? I don't even see the mi-test.

**Comment by fumiama** [comment]
1. Check `weights` folder and find out whether there are the modelname.pt file you would like to load.
2. If not there, put it into that folder.
3. If find it, try to restart the program.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
it worked.Thanks大佬

**Comment by sheikhsalman** [comment]
@fumiama From where can I find or get this modelname.pt file
