### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by wyh0626** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#809]
建议。有很多优化的地方。一个AI的一些片段。会出现卡弹卡顿的部分。需要大量的后期修音。耗费大量的时间。有一个简单的方法。可以快速的解决这个问题。那就是。将这个人的AI换成其他人的AI。这样就变成了，合唱版本。下个版本可以更新一下。当AI出现卡顿的片段时。可以自动或手动选择。其他人的AI。然后生成一整首歌曲。希望你能听到。可以采纳。谢谢你。这也许是个目前最好的方法。很轻松就可以实现。整首歌曲的完整性。希望下个新版本。可以更新这个功能。
Suggestion. There are many areas for optimization. Some fragments of an AI. There will be stuck and stuck parts. A large amount of post tuning is required. Consuming a lot of time. There is a simple method. It can quickly solve this problem. That's it. Replace this person's AI with someone else's AI. This becomes the choir version. The next version can be updated. When AI shows a stuck fragment. It can be selected automatically or manually. Other people's AI. Then generate an entire song. I hope you can hear. Can be adopted. Thank you. This may be the best method currently available. It's easy to achieve. The completeness of the entire song. Hope for the next new version. This feature can be updated.

**Comment by RVC-Boss** [comment]
What are you talking about?
