### ISSUE TITLE
Guys, how do i solve this?

### ISSUE THREAD

**Issue by n4d5** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#810]
if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: **'NoneType' object has no attribute 'dtype'**

**Comment by Lipooooo** [comment]
same error

**Comment by fumiama** [comment]
The model hasn't been loaded properly.

**Comment by hanselke** [comment]
got the same problem on inferrence. How do we ensure the model is loaded? 

selected inferencing voice, input the audiofile path, and the auto detect index path dropdown. Then clicked convert and got that error.

**Comment by gigamesh** [comment]
+1 ...how do we load the model? I put them in the `/weights` directory but every one I try results in this error. 

<img width="413" alt="image" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/32403632/63975ffd-e29b-466e-9bb3-068804204eb8">
<img width="443" alt="image" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/32403632/73db67c5-f4cc-4905-80fb-792c7ad5cc51">
