### ISSUE TITLE
Is it expected that on the new beta training time is slower?

### ISSUE THREAD

**Issue by kalomaze** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#811]
Preprocessing and feature index training both changed somewhat significantly, but I am unsure if it is expected that training takes longer now.

**Comment by RVC-Boss** [comment]
48k config becomes slower for better target speaker similarity

**Comment by Tybost** [comment]
> 48k config becomes slower for better target speaker similarity

Training speed on local windows reminds me of speeds way back in April (for 40k). It's pretty bad right now.
June build = avg **45 seconds per epoch** on my 2070S
July build = **2 minutes per epoch**

**Comment by kalomaze** [comment]
The real issue seems to be fp32 vs fp16 not being set properly in config.py

**Comment by Hivemind11** [comment]
Same problem. mine is 6 ins per epoch but the total training time would be 40 hours for training 15 min sample for 400 epochs. 16 threads and 40 batch size on my 3080.

**Comment by RVC-Boss** [comment]
I will check the fp32/fp16 config

**Comment by RVC-Boss** [comment]
@kalomaze We apologize for the mistakes we made. 
baseline: The default setting is fp16, and the program will find the model of GPU that is not suitable for fp16 and change it to fp32.
new: @fumiama changed the configs/xxk.json files to default set this setting to fp32, forgot to check it. (His machine is mac and automatically fix the json file to fp32), and then commit it to the main branch.

I have changed the json files to baseline version, you can have a try! Looking forward to your reply!

**Comment by RVC-Boss** [comment]
@Tybost @Hivemind11  I have fixed the config json files to use fp16 default, you can have a try again.
