### ISSUE TITLE
cant install requirements because it cant find pyproject.toml

### ISSUE THREAD

**Issue by jrchubs** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#812]
i tried to do poetry install this is the error i got:
![Screenshot from 2023-07-20 17-49-12](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106204805/385eae9d-96dc-43fe-9ed8-d74706b8616e)
so then i tried pip install -r requirements.txt and got this error
![Screenshot from 2023-07-20 17-49-56](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/106204805/6261d8d5-3bbb-4d5f-a8a9-0592f7322aab)
any tips would be appreciated, i switched from windows to linux and i wanna make ai voices

**Comment by NatoBoram** [comment]
You have to run these commands *inside* the repo's folder

**Comment by RVC-Boss** [comment]
↑ That's right.
