### ISSUE TITLE
Really high CPU usage

### ISSUE THREAD

**Issue by Happyman03** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#813]
For context, my system: Ryzen 7 3700x, 32GB 3200mhz and a RTX 4090. Yes I am aware of a CPU bottleneck in some games

The problem lies in the usage of my CPU while running RVC, it's usage balances around 40% sometimes reaching 50%. This is an issue because if my CPU usage goes in the 90-100% usage range RVC becomes very unstable/laggy.

My settings:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/48656301/41785162-99b9-4471-8b04-92288f83150e)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/48656301/1190b6d0-0c24-4867-9ce6-ef040ca524d5)

**Comment by kalomaze** [comment]
Wrong software

**Comment by Naozumi520** [comment]
Isn't this [w-okada/voice-changer](https://github.com/w-okada/voice-changer)? Instead of posting here you should open a issue in there.

**Comment by Happyman03** [comment]
That is entirely

**Comment by Happyman03** [comment]
I entirely overlooked that, my bad!
