### ISSUE TITLE
no model(.pth) generated after training 

### ISSUE THREAD

**Issue by HardikJain02** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#816]
after training, index files are generated. But there's no .pth file here. 

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/69311953/920e7365-8bc5-4bab-b55f-026855c3c932)

And this is how my weights folder looks, no .pth file.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/69311953/dda258ef-e7d5-4917-8d36-1990ad2bbec6)

Can you look into this? @RVC-Boss

**Comment by AshajShams** [comment]
Me too having same problem
i need it fixed fast

**Comment by AshajShams** [comment]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/140228583/743e5450-3e91-4e1d-9995-1f81be449d94)

**Comment by AshajShams** [comment]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/140228583/53f92c4b-d6cd-4a5b-8d0c-14fbf87e47fe)

**Comment by NicoTitanPro** [comment]
Other user had the same issue and it apparently can be solved by lowering the batch size.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/678#issuecomment-1619379434

**Comment by HardikJain02** [comment]
I have tried that by setting batch size = 1, didn't work for me. And I don't have GPU, just inbuilt intel iris.

**Comment by tommyfinn** [comment]
> 
i do not have a GPU as well, batch is 1 and no pth file

**Comment by onasre** [comment]
same here 
all done but only index file on log folder nothing on weights
                Processor: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 CPUs), ~2.7GHz
                   Memory: 8192MB RAM
Intel(R) HD Graphics 620

**Comment by takeru1205** [comment]
I have RTX3070Ti. But I got no pth file.
I ran on Docker that replaced the base image into `pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel`
Are there any stable versions?

**Comment by gabriebuq** [comment]
Same here.

The "INDEX" files appear for me but the pht file does not appear. My buffer size is = 1

Any solution???

**Comment by Arkanoidvfx** [comment]
Same here, pth files do no creating

**Comment by Haxhom** [comment]
samee

**Comment by iamsyh** [comment]
same

**Comment by Helinabil** [comment]
Any found help to these yet ? Same problem here !

**Comment by parthdshah9** [comment]
Same issue.
@HardikJain02 @RVC-Boss 
Or anyone got the solution to get pth file?

**Comment by HardikJain02** [comment]
I used colab at that time, and it generated pth file. You will find working colab on Youtube

**Comment by pankajmyysports** [comment]
> I used colab at that time, and it generated pth file. You will find working colab on Youtube

can you share the colab working link?
