### ISSUE TITLE
Training process not starting

### ISSUE THREAD

**Issue by Mshriver2** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#817]
I click on "one click training", I see that my CPU usage goes up to ~70-80% for 1-2 mins. Then nothing happens after that point. Even waiting 15+ mins I am not seeing anything new in the console and task manager shows 0% on GPU and 1-3% on CPU. Any ideas what might be happening?

My log:

['extract_f0_print.py', 'C:\\Users\\maxwe\\Documents\\github_downloads\\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1', '6', 'harvest']
todo-f0-594
f0ing,now-0,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/0_0.wav
todo-f0-594
f0ing,now-0,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/0_1.wav
todo-f0-594
f0ing,now-0,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/0_10.wav
todo-f0-593
f0ing,now-0,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/0_11.wav
todo-f0-593
f0ing,now-0,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/0_12.wav
todo-f0-593
f0ing,now-0,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/0_13.wav
f0ing,now-118,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/1_11.wav
f0ing,now-118,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/1_14.wav
f0ing,now-118,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/1_13.wav
f0ing,now-118,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/1_12.wav
f0ing,now-118,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/1_0.wav
f0ing,now-118,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/1_10.wav
f0ing,now-236,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/31_40.wav
f0ing,now-236,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/31_42.wav
f0ing,now-236,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/31_43.wav
f0ing,now-236,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/31_41.wav
f0ing,now-236,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/31_39.wav
f0ing,now-236,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/31_4.wav
f0ing,now-354,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/43_66.wav
f0ing,now-354,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/43_67.wav
f0ing,now-354,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/43_69.wav
f0ing,now-354,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/43_8.wav
f0ing,now-354,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/43_65.wav
f0ing,now-354,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/43_64.wav
f0ing,now-472,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/55_77.wav
f0ing,now-472,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/55_75.wav
f0ing,now-472,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/55_78.wav
f0ing,now-472,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/55_76.wav
f0ing,now-472,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/55_74.wav
f0ing,now-472,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/55_73.wav
f0ing,now-590,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/9_45.wav
f0ing,now-590,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/9_47.wav
f0ing,now-590,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/9_46.wav
f0ing,now-590,all-593,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/9_48.wav
f0ing,now-590,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/9_44.wav
f0ing,now-590,all-594,-C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1/1_16k_wavs/9_43.wav
['extract_feature_print.py', 'cuda:0', '1', '0', '0', 'C:\\Users\\maxwe\\Documents\\github_downloads\\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1', 'v2']

C:\Users\maxwe\Documents\github_downloads\Retrieval-based-Voice-Conversion-WebUI/logs/juice_v1
load model(s) from hubert_base.pt
move model to cuda
all-feature-3561
now-3561,all-0,0_0.wav,(149, 768)
now-3561,all-356,14_32.wav,(149, 768)
now-3561,all-712,1_13.wav,(149, 768)
now-3561,all-1068,25_20.wav,(149, 768)
now-3561,all-1424,31_46.wav,(149, 768)
now-3561,all-1780,37_35.wav,(149, 768)
now-3561,all-2136,44_15.wav,(149, 768)
now-3561,all-2492,50_118.wav,(149, 768)
now-3561,all-2848,56_12.wav,(149, 768)
now-3561,all-3204,61_64.wav,(149, 768)
now-3561,all-3560,9_9.wav,(149, 768)
all-feature-done

**Comment by EXSYM** [comment]
I see no problem mentioned in the log, Just start training your model.

**Comment by Mshriver2** [comment]
That message is what happens after I click the "one-click training" button. So I do start the training but it seems to get stuck and not actually begin training.

**Comment by Mshriver2** [comment]
Awesome it seems I got the training to start by doing "start training" instead of "one-click training". So there still may be an issue in that part of the code, however it seems my model is now training.

**Comment by Tsar** [comment]
Updating gradio like described here https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2355 helped me.
