### ISSUE TITLE
Converged (lack of improvement in inertia) at step 1468/46312 (Gradio) 在第1468/46312步时收敛（惯性改善不足）（Gradio）

### ISSUE THREAD

**Issue by Eipckz** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#818]
My training completed at 1000 epochs, but a .index file was not created, so I wanted to just train the index independently, so I filled in all of the information to restart my training, and clicked on "train feature index" at the bottom of the training page, and I only get to about 1400-1500 steps out of 46813, and in the Command Prompt it will always say, at the end, "Converged (lack of improvement in inertia) at step 1XXX/46312", but replace XXX with 416 for example so it would be 1416/46312. Does anyone know how it possibly skipped creating a .index file if it usually always creates one? I have trained other models to completion and they have their own .index file...

我的训练在完成1000轮后完成，但没有创建.index文件，所以我想单独训练索引，因此我填写了所有信息以重新开始我的训练，并点击了训练页面底部的“训练特征索引”，但我只能完成大约1400-1500步，共46813步。在命令提示符中，最后总是显示“在第1XXX/46312步处收敛（惯性改善不足）”，其中XXX可以用416替换，例如1416/46312。有人知道它可能如何跳过创建.index文件，如果通常总是创建一个吗？我已经训练了其他模型到完成，并且它们有自己的.index文件...

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/49221576/6803c0ba-23fe-4a4b-8775-deada1f8802e)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/49221576/ef554002-dfbf-4ffb-9629-755ead349f8a)

**Comment by mikeuiop** [comment]
So in my experience with Windows, page files can run independently from the control panel without a hard drive to run it's system files even minus a hard disk, if for example you set Virtual Memory in a second partition for a larger sample-rate than size permits and are viewing your machine in Safe Mode to compensate for writing time or keeping resources in order and the idea was to access your data from a potentially corrupt drive. Public computer models that train AI in my understanding are heavily dependent on keeping resources (data) available to the operating system servers in broadband communication, such as with an ethernet connection, which may be, if you're trying to work a training model into a particular operating system that could not handle it at the time, either via smaller motherboard that use quasi-digital clock like magnetic resonance imaging but is relying on communication to handle the machine down to the operand, there a few things you could look into in the code being used, too, even as simple as a tick (') being used in the filename if you had been working with a number of voice models and you were keeping track. Those are just my thoughts. Look over your list for any typos.

**Comment by mikeuiop** [comment]
Now, in recycling your operating system to verify your hard disk is not corrupt, which Windows 10 is notorious for assigning as an operator and as a resource claim, what is happening is task manager from the toolbar is being re-written in parts as the program requires the communication to verify and likely assign it's own troubleshooting for the typos and editing assignments. Somewhere at the start I saw iOS is not supported. Reasons for that boil down to material data and copyright claims.

**Comment by RVC-Boss** [comment]
This log indicates that the training index was completed successfully. You can update to the latest `main` branch; I’ve made the console messages clearer.
