### ISSUE TITLE
torch.load missing keys 'config' and 'weight'

### ISSUE THREAD

**Issue by Ruddle** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#821]
When loading a model from the dropdown "Inferencing voice:", I have a missing key error on cpt["config"] and cpt["weight"] in infer-web.py

I believe some other open issues stem from that, for instance:

> 'NoneType' object missing 'dtype' attribute

or
> vc is not defined

I printed all keys of cpt just after `cpt = torch.load(person, map_location="cpu")` to investigate.

cpt keys : 
`
discriminators.0.convs.0.bias 
discriminators.0.convs.0.weight_g 
discriminators.0.convs.0.weight_v 
discriminators.0.convs.1.bias 
discriminators.0.convs.1.weight_g 
discriminators.0.convs.1.weight_v 
discriminators.0.convs.2.bias 
discriminators.0.convs.2.weight_g 
discriminators.0.convs.2.weight_v 
discriminators.0.convs.3.bias 
discriminators.0.convs.3.weight_g 
discriminators.0.convs.3.weight_v 
discriminators.0.convs.4.bias 
discriminators.0.convs.4.weight_g 
discriminators.0.convs.4.weight_v 
discriminators.0.convs.5.bias 
discriminators.0.convs.5.weight_g 
discriminators.0.convs.5.weight_v 
discriminators.0.conv_post.bias 
discriminators.0.conv_post.weight_g 
discriminators.0.conv_post.weight_v 
discriminators.1.convs.0.bias 
discriminators.1.convs.0.weight_g 
discriminators.1.convs.0.weight_v 
discriminators.1.convs.1.bias 
discriminators.1.convs.1.weight_g 
discriminators.1.convs.1.weight_v 
discriminators.1.convs.2.bias 
discriminators.1.convs.2.weight_g 
discriminators.1.convs.2.weight_v 
discriminators.1.convs.3.bias 
discriminators.1.convs.3.weight_g 
discriminators.1.convs.3.weight_v 
discriminators.1.convs.4.bias 
discriminators.1.convs.4.weight_g 
discriminators.1.convs.4.weight_v 
discriminators.1.conv_post.bias 
discriminators.1.conv_post.weight_g 
discriminators.1.conv_post.weight_v 
discriminators.2.convs.0.bias 
discriminators.2.convs.0.weight_g 
discriminators.2.convs.0.weight_v 
discriminators.2.convs.1.bias 
discriminators.2.convs.1.weight_g 
discriminators.2.convs.1.weight_v 
discriminators.2.convs.2.bias 
discriminators.2.convs.2.weight_g 
discriminators.2.convs.2.weight_v 
discriminators.2.convs.3.bias 
discriminators.2.convs.3.weight_g 
discriminators.2.convs.3.weight_v 
discriminators.2.convs.4.bias 
discriminators.2.convs.4.weight_g 
discriminators.2.convs.4.weight_v 
discriminators.2.conv_post.bias 
discriminators.2.conv_post.weight_g 
discriminators.2.conv_post.weight_v 
discriminators.3.convs.0.bias 
discriminators.3.convs.0.weight_g 
discriminators.3.convs.0.weight_v 
discriminators.3.convs.1.bias 
discriminators.3.convs.1.weight_g 
discriminators.3.convs.1.weight_v 
discriminators.3.convs.2.bias 
discriminators.3.convs.2.weight_g 
discriminators.3.convs.2.weight_v 
discriminators.3.convs.3.bias 
discriminators.3.convs.3.weight_g 
discriminators.3.convs.3.weight_v 
discriminators.3.convs.4.bias 
discriminators.3.convs.4.weight_g 
discriminators.3.convs.4.weight_v 
discriminators.3.conv_post.bias 
discriminators.3.conv_post.weight_g 
discriminators.3.conv_post.weight_v 
discriminators.4.convs.0.bias 
discriminators.4.convs.0.weight_g 
discriminators.4.convs.0.weight_v 
discriminators.4.convs.1.bias 
discriminators.4.convs.1.weight_g 
discriminators.4.convs.1.weight_v 
discriminators.4.convs.2.bias 
discriminators.4.convs.2.weight_g 
discriminators.4.convs.2.weight_v 
discriminators.4.convs.3.bias 
discriminators.4.convs.3.weight_g 
discriminators.4.convs.3.weight_v 
discriminators.4.convs.4.bias 
discriminators.4.convs.4.weight_g 
discriminators.4.convs.4.weight_v 
discriminators.4.conv_post.bias 
discriminators.4.conv_post.weight_g 
discriminators.4.conv_post.weight_v 
discriminators.5.convs.0.bias 
discriminators.5.convs.0.weight_g 
discriminators.5.convs.0.weight_v 
discriminators.5.convs.1.bias 
discriminators.5.convs.1.weight_g 
discriminators.5.convs.1.weight_v 
discriminators.5.convs.2.bias 
discriminators.5.convs.2.weight_g 
discriminators.5.convs.2.weight_v 
discriminators.5.convs.3.bias 
discriminators.5.convs.3.weight_g 
discriminators.5.convs.3.weight_v 
discriminators.5.convs.4.bias 
discriminators.5.convs.4.weight_g 
discriminators.5.convs.4.weight_v 
discriminators.5.conv_post.bias 
discriminators.5.conv_post.weight_g 
discriminators.5.conv_post.weight_v 
discriminators.6.convs.0.bias 
discriminators.6.convs.0.weight_g 
discriminators.6.convs.0.weight_v 
discriminators.6.convs.1.bias 
discriminators.6.convs.1.weight_g 
discriminators.6.convs.1.weight_v 
discriminators.6.convs.2.bias 
discriminators.6.convs.2.weight_g 
discriminators.6.convs.2.weight_v 
discriminators.6.convs.3.bias 
discriminators.6.convs.3.weight_g 
discriminators.6.convs.3.weight_v 
discriminators.6.convs.4.bias 
discriminators.6.convs.4.weight_g 
discriminators.6.convs.4.weight_v 
discriminators.6.conv_post.bias 
discriminators.6.conv_post.weight_g 
discriminators.6.conv_post.weight_v 
discriminators.7.convs.0.bias 
discriminators.7.convs.0.weight_g 
discriminators.7.convs.0.weight_v 
discriminators.7.convs.1.bias 
discriminators.7.convs.1.weight_g 
discriminators.7.convs.1.weight_v 
discriminators.7.convs.2.bias 
discriminators.7.convs.2.weight_g 
discriminators.7.convs.2.weight_v 
discriminators.7.convs.3.bias 
discriminators.7.convs.3.weight_g 
discriminators.7.convs.3.weight_v 
discriminators.7.convs.4.bias 
discriminators.7.convs.4.weight_g 
discriminators.7.convs.4.weight_v 
discriminators.7.conv_post.bias 
discriminators.7.conv_post.weight_g 
discriminators.7.conv_post.weight_v 
discriminators.8.convs.0.bias 
discriminators.8.convs.0.weight_g 
discriminators.8.convs.0.weight_v 
discriminators.8.convs.1.bias 
discriminators.8.convs.1.weight_g 
discriminators.8.convs.1.weight_v 
discriminators.8.convs.2.bias 
discriminators.8.convs.2.weight_g 
discriminators.8.convs.2.weight_v 
discriminators.8.convs.3.bias 
discriminators.8.convs.3.weight_g 
discriminators.8.convs.3.weight_v 
discriminators.8.convs.4.bias 
discriminators.8.convs.4.weight_g 
discriminators.8.convs.4.weight_v 
discriminators.8.conv_post.bias 
discriminators.8.conv_post.weight_g 
discriminators.8.conv_post.weight_v 
iteration 
learning_rate 
`

there are indeed no "config" or "weight".

I use models downloaded from https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main
that I then put individually in the "weights" folder, since they are not detected anywhere else.
Maybe the problem is here, but the wiki is not clear, and the pre-created folder named "pretrained" and "pretrained_v2" do not help, when you populate them, the dropdown of "Inferencing voice:" stays empty.
 
I tried with python 3.8 and 3.10, with `pip install -r requirements.txt` having no warning or errors

**Comment by kuugaoke05** [comment]
How to use python 3.8, and 3.10?
I want to try it

**Comment by RVC-Boss** [comment]
You need "ckpt processing"
and don't use Dxxx.pth
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/FAQ-(Frequently-Asked-Questions)#q4how-to-share-a-modelhow-to-use-others-models
