### ISSUE TITLE
Does This Tool Support AMD GPU ?

### ISSUE THREAD

**Issue by VenomXPyke** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#823]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/119789849/aa109b94-eab3-49c3-9453-1ff48cab1ca7)

**Comment by EXSYM** [comment]
No, As it appears in the infer file, The code search for this prefix in GPU name, Which are all of them an Nvidia cards.
```
for value in [
                "10",
                "16",
                "20",
                "30",
                "40",
                "A2",
                "A3",
                "A4",
                "P4",
                "A50",
                "500",
                "A60",
                "70",
                "80",
                "90",
                "M4",
                "T4",
                "TITAN",
            ]
```

**Comment by VenomXPyke** [comment]
> 

so for now its only Nvidia support ?

**Comment by EXSYM** [comment]
Yes, As I said before, The infer file just searching for Nvidia cards in the GPU name.
