### ISSUE TITLE
Is it possible with RVC to mimic the style of speech or Singing as well as the voice?  

### ISSUE THREAD

**Issue by TrickleDownClown** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#831]
Is there a way to do this?  Is there something else I should use?  I want to be able to mimic a person's speech style as well as the voice.  As far as I can tell the voice transfers perfectly but it still sounds like the original speech pattern.

**Comment by complexinteractive** [comment]
If you don't want the voice of the original clip, and you don't want the rhythm/intonation of the original clip, then you don't actually need the original clip at all. The easiest way to do it is re-record the original clip in the style of the destination voice and run THAT through RVC instead.

**Comment by TrickleDownClown** [comment]
> If you don't want the voice of the original clip, and you don't want the rhythm/intonation of the original clip, then you don't actually need the original clip at all. The easiest way to do it is re-record the original clip in the style of the destination voice and run THAT through RVC instead.

I am unsure what you mean.  I'll try to explain using vocals rather than voice only. If I wanted to replace the voice of a singer like Robert Plant with the voice of Phil Collins. It would sound like Phil singing like Robert rather than Phil singing (Voice and style) Led Zepplin. The voice can be perfect but the style that Phil sings is lost, and so it's not quite right to my ears.

Maybe it's not yet possible to do this or I am misunderstanding?

**Comment by sethtallen** [comment]
What complexinteractive is saying is that, no, this is not possible with RVC. What you can do is record a clip of yourself singing, in the voice and style of Phil, singing Led Zepplin and run it through RVC.

RVC is Speech to Speech synthesis software. It only changes the voice, not the emotion/inflections in a particular audio clip. You are asking for something far beyond the scope of RVC.
