### ISSUE TITLE
NameError: name `cpt` is not defined

### ISSUE THREAD

**Issue by NatoBoram** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#836]
```python
Traceback (most recent call last):
  File "/home/nato/Code/github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 187, in vc_single
    if_f0 = cpt.get("f0", 1)
NameError: name 'cpt' is not defined
```
And indeed, if we go to `infer-web.py:187`, we can see this code:

```python
def vc_single(
    sid,
    input_audio_path,
    f0_up_key,
    f0_file,
    f0_method,
    file_index,
    file_index2,
    # file_big_npy,
    index_rate,
    filter_radius,
    resample_sr,
    rms_mix_rate,
    protect,
):  # spk_item, input_audio0, vc_transform0,f0_file,f0method0
    global tgt_sr, net_g, vc, hubert_model, version
    if input_audio_path is None:
        return "You need to upload an audio", None
    f0_up_key = int(f0_up_key)
    try:
        audio = load_audio(input_audio_path, 16000)
        audio_max = np.abs(audio).max() / 0.95
        if audio_max > 1:
            audio /= audio_max
        times = [0, 0, 0]
        if not hubert_model:
            load_hubert()
        if_f0 = cpt.get("f0", 1)
```

And `cpt` is not defined.

Hover `cpt` and you get that message:

> (variable) cpt: Any | None

Hover `.get` and you get that message:

> "get" is not a known member of "None" Pylance([reportOptionalMemberAccess](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportOptionalMemberAccess))
> (function) get: Any

**Comment by PatrickSLU** [comment]
has this been resolved or does anyone know how to debug this? Thank you

**Comment by fumiama** [comment]
I tried to modify some code. You can try again to see what will happen this time. 😂 The code is really annoying.

**Comment by kim-arthur** [comment]
Hi there! Now it gives another error


```
Traceback (most recent call last):
File "/Users/arthur/projects/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 185, in vc_single
    if_f0 = cpt.get("f0", 1)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by fumiama** [comment]
> Hi there! Now it gives another error
> 
> ```
> Traceback (most recent call last):
> File "/Users/arthur/projects/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 185, in vc_single
>     if_f0 = cpt.get("f0", 1)
> AttributeError: 'NoneType' object has no attribute 'get'
> ```

Thanks for your report. It is possibly the same problem as original one.

**Comment by kim-arthur** [comment]
> ```python
> ```python
> Traceback (most recent call last):
>   File "/home/nato/Code/github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 187, in vc_single
>     if_f0 = cpt.get("f0", 1)
> NameError: name 'cpt' is not defined
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> And indeed, if we go to infer-web.py:187, we can see this code:
> ```python
> def vc_single(
>     sid,
>     input_audio_path,
>     f0_up_key,
>     f0_file,
>     f0_method,
>     file_index,
>     file_index2,
>     # file_big_npy,
>     index_rate,
>     filter_radius,
>     resample_sr,
>     rms_mix_rate,
>     protect,
> ):  # spk_item, input_audio0, vc_transform0,f0_file,f0method0
>     global tgt_sr, net_g, vc, hubert_model, version
>     if input_audio_path is None:
>         return "You need to upload an audio", None
>     f0_up_key = int(f0_up_key)
>     try:
>         audio = load_audio(input_audio_path, 16000)
>         audio_max = np.abs(audio).max() / 0.95
>         if audio_max > 1:
>             audio /= audio_max
>         times = [0, 0, 0]
>         if not hubert_model:
>             load_hubert()
>         if_f0 = cpt.get("f0", 1)
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> And cpt is not defined.
> Hover cpt and you get that message:
> 
> (variable) cpt: Any | None
> 
> Hover .get and you get that message:
> 
> "get" is not a known member of "None" Pylance(reportOptionalMemberAccess)
> (function) get: Any
> ```

Hi! Try to train model first and select it first, cpt problem will be solved, but there will probably be another)

**Comment by NatoBoram** [comment]
Model was trained first, but it didn't appear in the list and there's nothing in the "weights" folder. It seems like the software is just broken all over the place.

**Comment by GratefulTony** [comment]
> Model was trained first, but it didn't appear in the list and there's nothing in the "weights" folder. It seems like the software is just broken all over the place.
> 
> Not only that, but if this shouldn't be a problem, then a linter should be able to prove it.

I thought I was having the issue after model training because no errors came out of the training function, but I looked at the train script and in my case it was not hitting errors, but rather silently exiting after doing no training because I didn't have n_gpus > 0. I hacked the train script to allow gpu-less training and it appears to be progressing. Training is slow, but seemingly tractable on cpu: hopefully a model will appear in the list and the cpt error will go away. agree more explicit logging could be useful. might make a pr if I get it working.

**Comment by RVC-Boss** [comment]
Oh no, they don't get the point.

You meet this issue because you don't load model successfully.

You should load a pth file that is about 60MB in weights folder.

**Comment by Kareemfarid** [comment]
> > Model was trained first, but it didn't appear in the list and there's nothing in the "weights" folder. It seems like the software is just broken all over the place.
> > Not only that, but if this shouldn't be a problem, then a linter should be able to prove it.
> 
> I thought I was having the issue after model training because no errors came out of the training function, but I looked at the train script and in my case it was not hitting errors, but rather silently exiting after doing no training because I didn't have n_gpus > 0. I hacked the train script to allow gpu-less training and it appears to be progressing. Training is slow, but seemingly tractable on cpu: hopefully a model will appear in the list and the cpt error will go away. agree more explicit logging could be useful. might make a pr if I get it working.
> 
> Looking briefly at the cpt error, it seems it's using globals to access the cpt variable so understanding the workflow is more complicated. I might look more later if having a trained model doesn't fix it (:

I'm facing the same issue with nothing in the weights folder. how did you fix it?

**Comment by NatoBoram** [comment]
> I hacked the train script to allow gpu-less training and it appears to be progressing. Training is slow, but seemingly tractable on cpu: hopefully a model will appear in the list and the cpt error will go away. might make a pr if I get it working.

Can you share the code? I think every single user of this project would benefit from enabling CPU training in case there's no GPU.

**Comment by GratefulTony** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/889 <- hack to unblock cpu training. mostly untested besides my local test.

**Comment by fumiama** [comment]
> #889 <- hack to unblock cpu training. mostly untested besides my local test.

Merged.
