### ISSUE TITLE
Can't open go-web.bat, can't open file 'C:\\WINDOWS\\system32\\infer-web.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by EmptyHead21** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#841]
I have tried numerous things and whenever I run the bat file I get this error:

D:\Program Files\python.exe: can't open file 'C:\\WINDOWS\\system32\\infer-web.py': [Errno 2] No such file or directory

I can't figure this out, I'm not an expert or even remotely experienced in Python.

**Comment by fumiama** [comment]
You can just follow what README said. If any specific problem occurs, you can open another issue about it.

**Comment by EmptyHead21** [comment]
> You can just follow what README said. If any specific problem occurs, you can open another issue about it.

Okay, thanks. Sorry to bother with a basic question! I'm a noob I hope it was no trouble :)

**Comment by fumiama** [comment]
> Sorry to bother with a basic question! I'm a noob I hope it was no trouble :)

As long as the issue is clear to understand, we won't mind its content since everyone have a noob period.
