### ISSUE TITLE
i have no idea whats happing.

### ISSUE THREAD

**Issue by idontknowhowtocode123** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#848]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/140391045/db750ba4-35c8-4a74-828b-3fcc4d7ae4d3)
everytime i press a key its closes it

**Comment by fumiama** [comment]
Try https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases
