### ISSUE TITLE
After overwriting the infer-web file with the latest version, it does not work.

### ISSUE THREAD

**Issue by eqe1sa1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#857]
D:\RVC-beta-v2-0618>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Traceback (most recent call last):
  File "D:\RVC-beta-v2-0618\infer-web.py", line 21, in <module>
    from config import Config
ModuleNotFoundError: No module named 'config'

D:\RVC-beta-v2-0618>pause

It works when I replace the infer-web file of the old version, what should I do?

**Comment by RVC-Boss** [comment]
I have fixed it. Try to update it again.
