### ISSUE TITLE
Question: Can I add more sounds to the dataset ?

### ISSUE THREAD

**Issue by EXSYM** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#858]
Hello,

Can I add more sounds to the dataset after training about 200 epoch ?

**Comment by RVC-Boss** [comment]
step1: put all 35min to path2
step2: exp_name2+path2 -> process dataset and extract feature
step3: copy the latest G and D file of exp_name1 (your previous experiment) into exp_name2 folder
step4: click "train the model", and it will continue training from the beginning of 200epoch
