### ISSUE TITLE
training stopped mid way by pc turning off how to countinue?

### ISSUE THREAD

**Issue by Hardercement** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#859]
my pc turned off in the middle of training and i was on epoch 180 of 250, how can i make rvc train my model from 180?

**Comment by EXSYM** [comment]
Start training the model again and it will continue from the last saved ckpt.

**Comment by Hardercement** [comment]
> 

and how do i do that? sorry its my first time with stuff like this..

**Comment by ms903x1** [comment]
The program will continue training from the last checkpoint saved when the training was terminated. If the epochs saved at the checkpoint are not reached when the training is terminated, the training can only be started from scratch.

**Comment by RVC-Boss** [comment]
↑ They are right.
