### ISSUE TITLE
MISSING: SynthesizerTrnMs256NSFsid, SynthesizerTrnMs256NSFsid_nono, SynthesizerTrnMs768NSFsid, SynthesizerTrnMs768NSFsid_nono

### ISSUE THREAD

**Issue by aedeheathers1002** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#861]
CLI inference using infer_batch_rvc.py produces error where `SynthesizerTrnMs256NSFsid`, `SynthesizerTrnMs256NSFsid_nono`, `SynthesizerTrnMs768NSFsid`, `SynthesizerTrnMs768NSFsid_nono` are not found. They are imported as follows:
```
from lib.infer_pack.models import (
    SynthesizerTrnMs256NSFsid,
    SynthesizerTrnMs256NSFsid_nono,
    SynthesizerTrnMs768NSFsid,
    SynthesizerTrnMs768NSFsid_nono,
)
```
Where can we find an updated version of infer_pack? The `models.py` file where the Classes can be found are outdated in https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main/infer_pack.

**Comment by RVC-Boss** [comment]
I will update it.
