### ISSUE TITLE
`go-web.bat` not respecting my GPU choice

### ISSUE THREAD

**Issue by JapanYoshi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#862]
I'm trying to train my own dataset on a computer that has an NVIDIA GPU and an Intel integrated graphics chip. I've selected the NVIDIA GPU, but Task Manager says that the other GPU is used.

I've tried:

- used Windows' Graphics Settings to make the included Python executable use the NVIDIA GPU
- used NVIDIA GeForce settings to make the included Python executable use the NVIDIA GPU
- both to make Command Prompt do the same

None of them have worked.

**Comment by fumiama** [comment]
What is your GPU's exact model name?

**Comment by JapanYoshi** [comment]
My mistake; Task Manager numbers GPUs differently from the app (GPU0 is
called GPU1 in Task Manager), so I got confused. There’s no problem here.

**Comment by fumiama** [comment]
OK.
