### ISSUE TITLE
Repo is now too big, can't use google colab anymore

### ISSUE THREAD

**Issue by jmfergeau** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#865]
The repo is now bigger than Google Colab's available space, which makes us unable to use it with Google Colab.

Any workaround? (Like, a way to use only a specific version of the repo or anything)

**Comment by IndraTensei** [comment]
ig theres a fork called mangio rvc fork, try it in colab

**Comment by fumiama** [comment]
The size of RVC repo itself is only 1.3MB. If you meant the .pth s in logs folder, just delete some of them.
