### ISSUE TITLE
[Colab] unzip:  cannot find or open /content/drive/MyDrive/dataset/lulu20230327_32k.zip

### ISSUE THREAD

**Issue by asxckjasbhcxjkas** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#866]
Where can I find lulu20230327_32k.zip file?
unzip:  cannot find or open /content/drive/MyDrive/dataset/lulu20230327_32k.zip, /content/drive/MyDrive/dataset/lulu20230327_32k.zip.zip or /content/drive/MyDrive/dataset/lulu20230327_32k.zip.ZIP.

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/125092222/138bbc2b-2391-473a-9f14-84b997b011a3)

**Comment by RVC-Boss** [comment]
You should use your own dataset

**Comment by zzzh** [comment]
> You should use your own dataset

Sounds good, but what should be inside the zip file? 
How to create my own dataset?

**Comment by stokemctoke** [comment]
Don't know if this will be any good to you, but I am going to give it a go.

https://github.com/HarryAJMK418/RVC-SVC-Best-Dataset-Maker
