### ISSUE TITLE
model fusion sounds robotic\pitchy?

### ISSUE THREAD

**Issue by Yogevsho** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#867]
hey, I followed the instructions on combining 2 voice models, and no matter what 2 types of models im combining - the new model always comes out robotic and un-usable. 
i pointed the gui to right files (both .pth files of the models from the 'weight' folders), and theyre both are V1. 
am i doing something wrong here?
also, the merge doesn't produce a new 'added' file, so i tried (both of) the 'added' files of the original models that ive combined - maybe this is the problem? 

thank you in advance for your help!

**Comment by RVC-Boss** [comment]
The "if_f0"and sample_rate config should also be the same

**Comment by Yogevsho** [comment]
You mean the sample_rate config when im training the original model? 
and as for the if_f0 - do you mean the ‘whether the model have pitch guidance’ (Also in each model training part)?

thank you!

**Comment by Yogevsho** [comment]
> The "if_f0"and sample_rate config should also be the same

You mean the sample_rate config when im training the original model?
and as for the if_f0 - do you mean the ‘whether the model have pitch guidance’ (Also in each model training part)?

thank you!

**Comment by RVC-Boss** [comment]
> > The "if_f0"and sample_rate config should also be the same
> 
> You mean the sample_rate config when im training the original model? and as for the if_f0 - do you mean the ‘whether the model have pitch guidance’ (Also in each model training part)?
> 
> thank you!

yes

**Comment by Yogevsho** [comment]
> > > The "if_f0"and sample_rate config should also be the same
> > 
> > 
> > You mean the sample_rate config when im training the original model? and as for the if_f0 - do you mean the ‘whether the model have pitch guidance’ (Also in each model training part)?
> > thank you!
> 
> yes

Well u did everything you said and it still comes out robotic. 
Just for clearance - i chose the .pth files of the models from the weights folders (the small ones), and not those from the ‘logs’ folder. Is that ok? or that for the fusion i need both of the models big .pth files (‘G333…’ or ‘D333…’)?

**Comment by ms903x1** [comment]
The model fusion function only supports PTH under the weights folder. If the inference performance of the fused model is poor when all configurations are correct, it may be a problem with the two models to be fused themselves.
