### ISSUE TITLE
Question: Can I add new data halfway

### ISSUE THREAD

**Issue by tsukishima1321** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#871]
Will it help if I add new sounds to the dataset after already training the model for several epoch?

**Comment by Naozumi520** [comment]
Not sure if it's allowed in webui, but once you do, the model may be broken.

**Comment by RVC-Boss** [comment]
step1: put all 35min to path2
step2: exp_name2+path2 -> process dataset and extract feature
step3: copy the latest G and D file of exp_name1 (your previous experiment) into exp_name2 folder
step4: click "train the model", and it will continue training from the beginning of 200epoch
