### ISSUE TITLE
"IndexError" when further training existing model (V2 Colab)

### ISSUE THREAD

**Issue by Optic-the-Wolf** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#879]
When I put the D and G files taken directly from the logs into the training to further train my existing model (like **[this](https://files.catbox.moe/k6jhiz.png)**), I get a weird index out of range error. Help?

```
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 176, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "/content/Retrieval-based-Voice-Conversion-WebUI/lib/train/utils.py", line 207, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range
```

**[Here's the full error I got.](https://pastebin.com/WnbHkcgE)**

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/FAQ-(Frequently-Asked-Questions)#q15-how-to-continue-training-using-more-data
this may help you 

you don't need to modify the "pretrained" field
just copy the pretrained G D model to your exp_name path and train the model, it will try to continue training using the G D model you copied.
