### ISSUE TITLE
How to train on expressions?

### ISSUE THREAD

**Issue by adhikjoshi** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#880]
We want to add expressions into the generated audio and use prompt like

Hi, I'm adhik [Laughing] [sad] [crying] 

Something like this is available in Bark model, can we do it in RVC? If not, what's next steps to achieve this?

**Comment by sethtallen** [comment]
I don't think this is the target of this software. You're talking about adding things that only make sense in the context of text to speech synthesis. This is a speech to speech synthesis software package. If you want to infer noises like laughter or crying, then perform those actions in your target audio. I don't really understand how this would work, given the nature of how you convert audio using RBVC.

**Comment by fumiama** [comment]
The RVC just change the tone but not the emotion, which still depends on what the original voice is.
