### ISSUE TITLE
No sound after inference

### ISSUE THREAD

**Issue by OcarinaBravo** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#882]
Sorry, I'm a bit new. I'm having an issue with my model. I did 40 Sample rate, Version v2, Pitch Guidance True, 24 CPU Threads, 0 singer I.D A save Frequency of 20, 200 total epochs and a max gpu batch size of 20. When running inference I seem to have no sound at all. I've tried Harvest, Crepe, rpmvpe, nothing seems to change. My inference settings are largely unchanged. I use the auto detech index path and point to v2_index, have the path to the vocals with the filename.wav, everything else was left to default values except transpose which I set higher as I'm converting male to female in this instance.

Thanks!

**Comment by Bandita69** [comment]
Same issue, did you find a solution?
