### ISSUE TITLE
Original training specs

### ISSUE THREAD

**Issue by Rolun** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#884]
Hey,

Is there any info on how the original training was set up?
I'm looking for things such as the number of epochs trained, if it started from an existing model or from scratch, and hyperparameters.

Thanks in advance!

**Comment by RVC-Boss** [comment]
try VCTK with 100epoch

**Comment by Rolun** [comment]
@RVC-Boss I tried VCTK 100 epochs but got very poor sound quality (robotic) at some places, do you know what might cause it?

Here's an example:

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/19343330/af28abdb-e362-49cf-b96c-a1d91a2a1cb9


https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/19343330/66198d45-9b55-4d85-b9f9-42f4a3b5cd71

Many thanks in advance for any guidance!

**Comment by Coice** [comment]
@Rolun did you figure out scratch training? I'm having a similar issue.
