### ISSUE TITLE
Second inference makes a higher-pitched and slightly shorter sound without changing any parameters

### ISSUE THREAD

**Issue by porinky0424** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#885]
Hi,

When inferencing once, I can get the correct audio result. However, in the second inference or later, I get a quite higher-pitched and slightly shorter sound without changing any parameters. I can also get a correct audio result if I infer again after reloading the window.

My parameter settings are below:
- Transpose: 0
- Pitch extraction algorithm: crepe
- Filter radius: 3
- Search feature ratio: 0.5
- Resample the output audio in post-processing to the final sample rate: 48000
- Adjust the volume envelope scaling: 1
- Protect voiceless consonants and breath sounds to prevent artifacts such as tearing in electronic music: 0.33

Please note that when I leave parameters of "Resample the output audio in post-processing to the final sample rate," "Adjust the volume envelope scaling," and "Protect voiceless consonants and breath sounds to prevent artifacts such as tearing in electronic music" as default before the first inference, multiple inferences do not change a pitch and length of audio result at all.

Many thanks for considering my issue.

**Comment by RVC-Boss** [comment]
Fixed now.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/commit/deb756bf1b0bc5924865e646dc7925c68c9f5bc5
