### ISSUE TITLE
Ability to use GPU and APU

### ISSUE THREAD

**Issue by EXSYM** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#886]
Hello,

It will be much better if we can use both nvidia GPU and AMD APU or any integrated graphics like intel, Both at the same time as I think the current "use_gpus" is still looking for a nvidia GPU as it's not working with a nvidia GPU and AMD APU, It's only worked with nvidia and the APU usage is 0

So it will be great if we can use both of them to speed up the training process.

**Comment by sethtallen** [comment]
AMD ROCm support is only available for Linux machines, and I do not believe you can use CUDA and ROCm concurrently with Pytorch, although I may be wrong on that. That being said, according to this issue, AMD is not supported with this software.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/272

Also, ROCm is not supported on AMD APUs, at least in any official capacity right now. So even if RVC supported ROCm, you would not be able to utilize your APU as a result of AMD's hardware support.

**Comment by RVC-Boss** [comment]
We will support AMD card by using Pytorch DirectML.

**Comment by KawaiiSelbst** [comment]
> We will support AMD card by using Pytorch DirectML.

Judging by the experience of stable diffusion on direct-ml, the execution speed is likely to be much lower than on rocm...

**Comment by RVC-Boss** [comment]
Now AMD GPU is supported for inference.

**Comment by bommy-h** [comment]
> Now AMD GPU is supported for inference.

Hi, at the risk of sounding silly, how do you configure RVC for use with an AMD GPU ?

**Comment by Skynetaa** [comment]
Hi.. is it possible on AMD GPUs? I downloaded AMD version but it says no supported NVIDIA GPU found

**Comment by aliosmanzengin** [comment]
@Skynetaa did you fix the issue? I also get same log as  it says no supported NVIDIA GPU found with AMD 6700xt.
