### ISSUE TITLE
OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by NatoBoram** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#890]
### Steps

1. Open http://0.0.0.0:7865
2. Go to **Train**
3. Write a name in *Enter the experiment name*
4. Write a path in *Enter the path of the training folder*
5. Click on **One-click training**

### Logs

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/nato/.local/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 370, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
```

**Comment by Ado012** [comment]
> ### Steps
> 
>     1. Open http://0.0.0.0:7865
> 
>     2. Go to **Train**
> 
>     3. Write a name in _Enter the experiment name_
> 
>     4. Write a path in _Enter the path of the training folder_
> 
>     5. Click on **One-click training**
> 
> 
> ### Logs
> 
> ```python
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
>     obj = _ForkingPickler.dumps(obj)
>   File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
>     cls(buf, protocol).dump(obj)
>   File "/home/nato/.local/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 370, in reduce_storage
>     df = multiprocessing.reduction.DupFd(fd)
>   File "/usr/lib/python3.10/multiprocessing/reduction.py", line 198, in DupFd
>     return resource_sharer.DupFd(fd)
>   File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 53, in __init__
>     self._id = _resource_sharer.register(send, close)
>   File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 76, in register
>     self._start()
>   File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 126, in _start
>     self._listener = Listener(authkey=process.current_process().authkey)
>   File "/usr/lib/python3.10/multiprocessing/connection.py", line 448, in __init__
>     self._listener = SocketListener(address, family, backlog)
>   File "/usr/lib/python3.10/multiprocessing/connection.py", line 591, in __init__
>     self._socket.bind(address)
> OSError: AF_UNIX path too long
> ```

I'm having this issue too. I'm on linux. Did you figure it out?

**Comment by NatoBoram** [comment]
I think a workaround is to move `Retrieval-based-Voice-Conversion-WebUI` to somewhere with a shorter path, like `/opt/rbvc`. Ideally, the solution would be to have an actual Python programmer come in to improve the code quality.

**Comment by SmoothBrainApe** [comment]
October and this problem still existing....

**Comment by NatoBoram** [comment]
True. I just reinstalled my system while keeping my `$HOME` safe, but only after the fact, I realized that I lost all my models.

**Comment by AntonTimofeev** [comment]
Changing
```
-tmp = os.path.join(now_dir, "TEMP")
+tmp = os.path.normpath("/tmp/RVC")
```
in `infer-web.py` works for linux

**Comment by NatoBoram** [comment]
> works for linux

It's not hard to make it work for every OS. You just have to Google "[How to get temp folder path in Python](https://natoboram.github.io/lmgtfy/search/?q=How+to+get+temp+folder+path+in+Python&btnI=I%27m+Feeling+Lucky)" and you'll find [this](https://stackoverflow.com/a/847866/5083247) as the top result.

Another problem is that this program has some absolutely horrifying lines such as this one:

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/0de65053247fb616fa696e4c40d32411174b6310/infer-web.py#L47

**Comment by NatoBoram** [comment]
Rude
