### ISSUE TITLE
Failed to press Process Data.

### ISSUE THREAD

**Issue by Tokayaka1807** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#895]
runtime\python.exe trainset_preprocess_pipeline_print.py D:\Voice Changer\RVC-beta-v2-0528\voice 40000 16 D:\Voice Changer\RVC-beta-v2-0528/logs/myself False
Traceback (most recent call last):
  File "D:\Voice Changer\RVC-beta-v2-0528\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: 'Changer\\RVC-beta-v2-0528\\voice'

**Comment by cepLI** [comment]
**Enter the path of the training folder:**
`D:\Voice Changer\RVC-beta-v2-0528\voice`

**Comment by RVC-Boss** [comment]
0528version: space is not allowed to be in the full path
