### ISSUE TITLE
[Question] Dataset of singing vocals

### ISSUE THREAD

**Issue by Rolun** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#904]
Hey,

Is anyone here aware of some good datasets with clean singing voices?
Looking to train on more data but have a hard time finding such datasets.

Thanks in advance!

**Comment by RVC-Boss** [comment]
kiritan:
https://zunko.jp/kiridev/login.php

Here are some open source singing voice dataset. But some needs e-mail contact.
https://github.com/PlayVoice/so-vits-svc-5.0#data-set
