### ISSUE TITLE
Error! The system cannot find the path specified

### ISSUE THREAD

**Issue by hijab232** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#905]
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/37248973/0e71e028-0da6-44be-8063-90a569e0a8ec)

How could I fix that?

**Comment by ms903x1** [comment]
You downloaded a compressed package that only contains code. If you want to use the bat command to start webui, you need to download the complete package.

Full package link：
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC-beta.7z

**Comment by EXSYM** [comment]
I think you run the file as administrator, Try NOT to run the file as administrator, run it normally.

**Comment by RVC-Boss** [comment]
↑ is right.
