### ISSUE TITLE
是否可以增加一个清理显存的方法？

### ISSUE THREAD

**Issue by 2575156125** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#910]
因为在模型训练之前，我用了模型推理和用伴奏人声分离处理了数据，模型没有卸载
总结：
1.模型推理后的模型卸载（已经有了）
2.伴奏人声分离模型卸载（目前还没有，模型会一直在显存）
最后，希望你们可以做的更好，期待你们的消息！

**Comment by RVC-Boss** [comment]
好主意

**Comment by RVC-Boss** [comment]
检查后发现已经2支持了显存清理，只是清理得不彻底，目前没有什么更好的方式
