### ISSUE TITLE
关于本模型中vits的作用

### ISSUE THREAD

**Issue by ywh-my** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#912]
（1）请问vits模型在该项目中是当做一个输入为hubert特征，输出为波形的声码器吗？参考论文《Voice Conversion With Just Nearest Neighbors》。 若是，这个声码器训练的时候需要使用论文提到的 prematched vocoder training?
（2）第二个问题。 vits模型输入是文本序列，输出是波形序列，如果问题（1）的回答肯定，那么是否需要去掉MAS（单调对齐）。而是单纯地保留一个 深度特征先验编码器。

**Comment by Swimming1997** [comment]
我看代码里是没有随机时长预测器了

**Comment by RVC-Boss** [comment]
1-没做knnvc里的预处理
2-去了
