### ISSUE TITLE
Output error for training?

### ISSUE THREAD

**Issue by JafarAlkbr** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#913]
Step 1: Processing data
C:\Python310\python.exe trainset_preprocess_pipeline_print.py C:\TCHT\Retrieval-based-Voice-Conversion-WebUI\opt 40000 6 C:\TCHT\Retrieval-based-Voice-Conversion-WebUI/logs/mi-test False

**Comment by ms903x1** [comment]
A complete error log is required, as there is too little information to locate the problem.

**Comment by RVC-Boss** [comment]
I don't see the error.
