### ISSUE TITLE
Bad result  train with a voice

### ISSUE THREAD

**Issue by Fairplayn** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#916]
I've trained many popular voices perfectly, but for some reason and for this voice only it doesn't do a good job.
https://whyp.it/tracks/113084/01?token=DVdVc (audio)
I have 20 minutes dataset with this high quality audio.

**Comment by ms903x1** [comment]
If your dataset consists entirely of this serious and formal broadcasting tone, then in order for the trained model to achieve good inference results, the input source should also mimic this broadcasting tone as closely as possible.

**Comment by Fairplayn** [comment]
well even if i use the same voice, it's not that good 
I want this voice: https://www.whyp.it/tracks/113084/01?token=DVdVc
but the result is this(bad): https://www.whyp.it/tracks/113106/none?token=Lz00f

And for example i tried another voice like elon musk (works perfectly)
elon musk voice: https://www.whyp.it/tracks/113107/elon?token=n6Q7I
