### ISSUE TITLE
do we still use total_fea.npy?

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#917]
I see from the bili2 video

You put index in 特征检索库文件路径?
and
npy in 自动检测index路径?

But in the real code 自动检测index路径 only detect trained .index not .npy?
Is the .npy feature function deleted and not used?Like totally useful to improve results or we had some code limitations?

**Comment by ms903x1** [comment]
"total_fea.npy" has been deprecated. Although the "total_fea.npy" option may still exist in previous versions of the integration package, it is actually no longer functional.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
i see huge thanks.closing this then
