### ISSUE TITLE
更多说话人的基础模型更新

### ISSUE THREAD

**Issue by Ranzige** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#919]
你好，您的工作非常出色，让我受益匪浅，我想咨询一下，现在我想训练更多说话人的基础模型来替代VCTK的基础模型，请问目前的项目支持吗

**Comment by ms903x1** [comment]
有计划支持多说话人训练，但目前优先级不高。
There are plans to support multi-speaker training, but currently, it is not a high priority.

**Comment by RVC-Boss** [comment]
基础模型就是多说话人训练的
支持多说话人训练不过你要自己写多说话人的filelist.txt，以及把infer-web.py中自动写filelist.txt的语句注释掉。
