### ISSUE TITLE
got tons of pth from one training

### ISSUE THREAD

**Issue by zeevfoox** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#922]
hello, im not sure if thats a problem or not- i did a 200 epoch training, and when i try to use it in the model inference- I get alot of epoch to choose from. i tryed couple (8, 50 ,200) and theres no change in the quality. now im worried it didnt worked properly and i could achived better quality...
in the end of the training i got an error:
Converged (lack of improvement in inertia) at step 460
but in the training log it finishes with:
2023-08-01 13:03:43,350	shppoookkkkk	INFO	Saving model and optimizer state at epoch 200 to ./logs\shppoookkkkk\G_2333333.pth
2023-08-01 13:03:43,835	shppoookkkkk	INFO	Saving model and optimizer state at epoch 200 to ./logs\shppoookkkkk\D_2333333.pth
2023-08-01 13:03:44,866	shppoookkkkk	INFO	saving ckpt shppoookkkkk_e200:Success.
2023-08-01 13:03:44,866	shppoookkkkk	INFO	====> Epoch: 200 [2023-08-01 13:03:44] | (0:04:29.482871)
2023-08-01 13:03:44,866	shppoookkkkk	INFO	Training is done. The program is closed.
2023-08-01 13:03:44,944	shppoookkkkk	INFO	saving final ckpt:Success.

any ideas what this is about? what file should i choose and why theres so many without any notable difference between them?
![33333](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/102409612/4dd4b770-07b8-4b6e-91ef-34b75c4a2e6b)

**Comment by ms903x1** [comment]
It is evident that you have enabled the 'Save final small model to the weights folder at each save checkpoint' option in the training tab and set the save frequency too small. This will not affect the training performance, but a very small save frequency can slow down the training process, since saving weights takes time. Additionally, a very small save frequency can lead to the consumption of a significant amount of disk space.

**Comment by zeevfoox** [comment]
thanks for your answer.
So in conclusion- what is the pth i should use here? the one with e200 in it's name, or the one called shpoookkkk.pth (without epoch number)? What is the final one?
Or should I use the "auto detect indext path" instead?

**Comment by ms903x1** [comment]
In general, directly using the pth without the epoch number works, this pth is the last pth exported after the end of training, if the inference results of this pth have obvious defects, you can try whether the previous pth improves it.
