### ISSUE TITLE
What is the solution to this problem

### ISSUE THREAD

**Issue by hackman1973** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#923]
runtime\python.exe trainset_preprocess_pipeline_print.py C:\Users\ABOTRIKA 2022\Desktop\My Sound 40000 8 C:\Users\ABOTRIKA 2022\Desktop\Voice Clone\RVC-beta0717/logs/mi-test False
Traceback (most recent call last):
  File "C:\Users\ABOTRIKA 2022\Desktop\Voice Clone\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: '2022\\Desktop\\My'

**Comment by ms903x1** [comment]
The error is caused by spaces in the file path, file paths are not allowed to have spaces and special characters other than "-" and "_".

**Comment by RVC-Boss** [comment]
Now RVC supports paths containing space now. You can try updating RVC codes from github.
