### ISSUE TITLE
runtime\python.exe trainset_preprocess_pipeline_print.py C:\Users\ABOTRIKA 2022\Desktop\My Sound 40000 8 C:\Users\ABOTRIKA 2022\Desktop\Voice Clone\RVC-beta0717/logs/mi-test False Traceback (most recent call last):   File "C:\Users\ABOTRIKA 2022\Desktop\Voice Clone\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 8, in <module>     sr = int(sys.argv[2]) ValueError: invalid literal for int() with base 10: '2022\\Desktop\\My'

### ISSUE THREAD

**Issue by hackman1973** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#924]
runtime\python.exe trainset_preprocess_pipeline_print.py C:\Users\ABOTRIKA 2022\Desktop\My Sound 40000 8 C:\Users\ABOTRIKA 2022\Desktop\Voice Clone\RVC-beta0717/logs/mi-test False
Traceback (most recent call last):
  File "C:\Users\ABOTRIKA 2022\Desktop\Voice Clone\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 8, in <module>
    sr = int(sys.argv[2])
ValueError: invalid literal for int() with base 10: '2022\\Desktop\\My'

**Comment by ms903x1** [comment]
The error is caused by spaces in the file path, file paths are not allowed to have spaces and special characters other than "-" and "_".

**Comment by hackman1973** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 16.00 GiB total capacity; 13.60 GiB already allocated; 0 bytes free; 15.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ms903x1** [comment]
Reduce batch_size.
