### ISSUE TITLE
No module named 'lib.infer_pack'

### ISSUE THREAD

**Issue by nauticlabadge3** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#928]
Every time i run go-web i get the error
Traceback (most recent call last):
  File "C:\Users\infer-web.py", line 28, in <module>
    from lib.infer_pack.models import (
ModuleNotFoundError: No module named 'lib.infer_pack'

**Comment by ms903x1** [comment]
You need to update the entire code repository as there have been some changes in the file structure recently.

**Comment by sr44l3i** [comment]
> You need to update the entire code repository as there have been some changes in the file structure recently.

still not working

**Comment by mopoIo** [comment]
Did you manage to solve this? I'm getting the exact same error

**Comment by Comethri** [comment]
i got the same error now.

Traceback (most recent call last):
  File "E:\RVC\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 28, in <module>
    from lib.infer_pack.models import (
ModuleNotFoundError: No module named 'lib.infer_pack'

**Comment by PK2-Stimpy** [comment]
I have the same problem, running on Linux.

**Comment by computersrmyfriends** [comment]
same error

**Comment by ZeaMays14142** [comment]
similar error, no module named 'infer.lib'

i reported this in a new issue

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2083
