### ISSUE TITLE
error when process data

### ISSUE THREAD

**Issue by Felzow47** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#929]
`runtime\python.exe trainset_preprocess_pipeline_print.py opt\vocal.wav 40000 16 C:\RVC Webui/logs/mi-test False
Traceback (most recent call last):
  File "C:\RVC Webui\trainset_preprocess_pipeline_print.py", line 20, in <module>
    f = open("%s/preprocess.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\RVC/preprocess.log'`

thx in advice for the help

**Comment by RVC-Boss** [comment]
The error is caused by spaces in the file path, file paths are not allowed to have spaces or special characters other than "-" and "_".

**Comment by RVC-Boss** [comment]
Now RVC supports paths containing space now. You can try updating RVC codes from github.
