### ISSUE TITLE
Preparation of tutorials in English

### ISSUE THREAD

**Issue by nadare881** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#93]
I would like to create a tutorial in /docs in markdown format. In the tutorial, I would like to write:

- How to tune faiss for developers
- Explanation of learning and inference parameters for beginners

First, I will write the tuning method of the former faiss and create a PR by ~4/19.

**Comment by fumiama** [comment]
That helps a lot. Thank you very much!

**Comment by Katsuyuki-Karasawa** [comment]
What do you plan to use to create the manual?
I think mkdocs-material or Docusaurus. Personally, I think mkdocs is better because you only have to add one file, so it's less messy in the repository.
@nadare881
