### ISSUE TITLE
process data error

### ISSUE THREAD

**Issue by jojo10538** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#931]
when i click process data nothing fills the output informationd and cmd come up with the error "ValueError: invalid literal for int() with base 10: 'Changer'"

**Comment by RVC-Boss** [comment]
The error is caused by spaces in the file path, file paths are not allowed to have spaces or special characters other than "-" and "_".

**Comment by RVC-Boss** [comment]
Now RVC supports paths containing space now. You can try updating RVC codes from github.
