### ISSUE TITLE
Question about HuBERT model

### ISSUE THREAD

**Issue by asr-pub** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#933]
Is the HuBERT model comes from `https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt` ?

**Comment by RVC-Boss** [comment]
no

**Comment by asr-pub** [comment]
> no

Can u point the place where it comes from?

**Comment by RVC-Boss** [comment]
https://github.com/auspicious3000/contentvec

**Comment by Keith-Hon** [comment]
> https://github.com/auspicious3000/contentvec

did you convert into onnx? did you check the accuracy drop?

**Comment by asr-pub** [comment]
> https://github.com/auspicious3000/contentvec

Thank u a lot.
