### ISSUE TITLE
"The system cannot find the path specified"

### ISSUE THREAD

**Issue by pichelsteiner** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#935]
Attempting to run one-click training, I receive the error "The system cannot find the path specified: `C:\\rvc-webui\\Retrieval-based-Voice-Conversion-WebUI/logs/ksk/0_gt_wavs`, 'ksk' being the experiment name. I'm not sure why it attempts to navigate to the root folder with dual backslashes, or further directories with forward slashes.

**Comment by RVC-Boss** [comment]
There may be some other issues before this issue. Such as "space in your dataset path" causing there is no file in 0_gt_wavs dir.

**Comment by LilMayoo** [comment]
> There may be some other issues before this issue. Such as "space in your dataset path" causing there is no file in 0_gt_wavs dir.

And how do I change the path? Do I have to reinstall everything?

**Comment by RVC-Boss** [comment]
delete the " "in the file path
