### ISSUE TITLE
No .index file added after training

### ISSUE THREAD

**Issue by owenborillo82** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#938]
As my problem today, my finished model didn't add an .index file. I'm training my Flame Princess Model for almost half an hour in 200 epochs, but my index file is missing. I tried to lower my total_epoch and batch size but still doesn't work, even I pressed the "Train Feature Index" for several times to add it desperately. I have no problems on my first (Princess Bubblegum) model because I obtained the index file for that model automatically after training.

Please give me some several alternative ways to fix the issue as possible because I worked HARD overnight for this model. Thanks!

**Comment by 2033723741** [comment]
Are u sure your code is update to latest?

**Comment by owenborillo82** [comment]
I don't know, since I'm a beginner user of RVC. I don't even know how to find and update their codes & components either. I'm using RVC v2 Colab Edition on my old Android 4.4 tablet.

**Comment by owenborillo82** [comment]
@ms903x1 I hope your advice works. Thanks!
