### ISSUE TITLE
训练后模型推理正常，但实时变声是底模的声音

### ISSUE THREAD

**Issue by 2033723741** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#939]
成功训练了模型（男性声音），使用模型推理生产的音频播放正常。但将模型加入到实时变声的model里，变声的时候能发声，但不是模型声音，听起来像底模的声音。请问可能是哪里的问题？

**Comment by ms903x1** [comment]
You need to adjust the pitch parameter to match the value set in the web UI for inference.

**Comment by 2033723741** [comment]
> You need to adjust the pitch parameter to match the value set in the web UI for inference.

It seems that all models have the same problem, and real-time RVC output is the same sound.  I tried to download the latest version package,  and retrained the model, it has the same issue.


调整音调会有声音变化，但也不是训练的声音。

**Comment by 2033723741** [comment]
大佬，今天尝试下载了其他版本的实时变声器，也是基于RVC的。把RVC训练的模型导入后是可以正常实时变音的，所以怀疑本库当前版本的实时变音器是不是有问题？ @RVC-Boss

**Comment by ms903x1** [comment]
测试了，没有发现这个问题，也没有其他用户反映这个问题。

**Comment by 2033723741** [comment]
> 

今天用另外一台电脑重新下载了RVC-beta0717，还是用以前训练的男声模型，用老版的gui终于正常了，新版的gui就是不起作用。两个版本的参数设置一样。

**Comment by ms903x1** [comment]
哦，这是v2版本gui的bug，无法切换模型，如果你加了官方交流群的话，可以在群文件里找到更新修复包，解压覆盖就能解决了
