### ISSUE TITLE
dl服务器环境cuda版本不支持4090

### ISSUE THREAD

**Issue by Chaoriticle** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#940]

**Comment by ms903x1** [comment]
需要选择cuda版本支持11.7以上的机器，并选择正确的镜像.

**Comment by RVC-Boss** [comment]
https://www.codewithgpu.com/i/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/RVC_WebUI
v4 4090已支持最新版
