### ISSUE TITLE
[功能建议]一些我认为可以加入的功能

### ISSUE THREAD

**Issue by TLMEMO** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#949]
1. 对于不同体量的数据集，使用固定的epoch来训练导致的步数差距过大。对于小的数据集我需要练更多epoch来拟合，而对于大量的数据集，我只需要比较少的epoch即可。所以说建议加入一个训练指定步数的选项，而不是只有训练固定epoch能选。
2. 加入批量训练的功能，比如说我有大量角色需要训练，而等待一个角色训练完再手动填写参数继续训练实在是太折磨人了，特别是对于有几十或是上百个角色要训练时。所以说我认为批量训练的功能是很重要的，在训练完成一个模型时能够自动训练下一个模型。可以考虑遍历一个文件夹下的子文件夹，而每个子文件夹包含一个单独项目的数据集，将文件夹的名字作为实验名。

另外有一个BUG：
在训练选项卡中训练完后如果要再次训练需要刷新页面，直接改实验名和数据集路径会报错并且无效。

**Comment by ms903x1** [comment]
1，在有预训练模型的情况下，以epoch为单位训练是更好的选择，
2，或许你更需要多说话人训练功能，实际上是支持的，只是还没支持多说话人的预处理。

**Comment by TLMEMO** [comment]
> 1，在有预训练模型的情况下，以epoch为单位训练是更好的选择， 2，或许你更需要多说话人训练功能，实际上是支持的，只是还没支持多说话人的预处理。

这样的话使用梯度累加，来加高batch size是不是更好呢？

**Comment by RVC-Boss** [comment]
1、
（1）你为什么觉得用iteration来评价训练完成度是合理的，因为大家都在这么用吗？
（2）你只懂理论，不懂产品。
训练小数据集的人往往数据质量都不好，所以依赖底模去抬高模型的质量，反而应该是较低的训练完成度，训练太满了音质被训练集拉下来了；
训练大量数据集的人往往是自己录的数据，数据集质量高，所以可以释放满血的训练计划，有更多的训练完成度。

2、批量训练有在计划支持，不过更可能是多个单说话人模型的批处理的逻辑。一个大数据集文件夹，里头多个不同说话人子文件夹，每个子文件夹里面识别所有可识别的音频文件。

**Comment by RVC-Boss** [comment]
1（1）有预训练模型的情况下，微调训练集大概率是数量质量不如pretrain数据集的，等于音频重建和基本音色功能的完成度已经是满血了，剩下的就是去适配微调训练集，微调训练集越大越难就越吃训练时长。
我不知道用itertation衡量训练完成度的习惯是从哪里来的，但我可以叙述一下我做超分实验的经历。
DF2K是DIV2K训练集的3倍数量。实际性能指标   DIV2K 200e<DF2K训练DIV2K 200e等量时间<DF2K 200e。你可以发现你用iteration来衡量训练进度根本发挥不了DF2K的真实实力的。

**Comment by TLMEMO** [comment]
> 
呃，其实我只是觉得如果数据量大的话用更高的batch size训练会更好，的确我是认同应该按epoch来训练的，可以当我没说，如果有梯度累加就更好了。只是在实际微调的时候数据量太大，少练点epoch效果感觉也不差多少，但有时候epoch调太大导致总训练时长太长了，现在也没有终止键，所以说才想用步数来。因为我在训练过程中用的数据集都是48K无底噪的，的确没有考虑到一些问题。

**Comment by TLMEMO** [comment]
> 1（1）有预训练模型的情况下，微调训练集大概率是数量质量不如pretrain数据集的，等于音频重建和基本音色功能的完成度已经是满血了，剩下的就是去适配微调训练集，微调训练集越大越难就越吃训练时长。 我不知道用itertation衡量训练完成度的习惯是从哪里来的，但我可以叙述一下我做超分实验的经历。 DF2K是DIV2K训练集的3倍数量。实际性能指标 DIV2K 200e<DF2K训练DIV2K 200e等量时间<DF2K 200e。你可以发现你用iteration来衡量训练进度根本发挥不了DF2K的真实实力的。

另外我再反馈一个问题，不开新的issues了。实时变声V2的模型切换是不起作用的，换模型实际用的模型也是kiki.pth。而V1没有这个问题。

**Comment by ms903x1** [comment]
那个是v2版本gui的bug，你加了官方群的话，可以在群里找到更新修复包，更新一下就好了。

**Comment by TLMEMO** [comment]
> 那个是v2版本gui的bug，你加了官方群的话，可以在群里找到更新修复包，更新一下就好了。

不用QQ......这样的话我还是等github上更新吧
