### ISSUE TITLE
Question: Can I resume an aborted/interrupted model training session?

### ISSUE THREAD

**Issue by VertofChest** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#953]
I was training a voice for personal usage when my PC blue-screened; Driver_IRQ_not_less_or_equal error. I figured it was because of overheating or something.

Now I was generating a voice for 230 epochs, but it only got to 120. Can I resume where it left off? If so, how?

**Comment by ms903x1** [comment]
Once the training progress reaches the designated checkpoint for saving an epoch, you can interrupt the training and resume from the last saved checkpoint. However, if the training is interrupted due to a computer crash, the last saved checkpoint may be corrupted. In such cases, it is recommended to continue training from the checkpoint preceding the last saved one. To do this, simply delete the last saved checkpoint files (D_xxx.pth and G_xxx.pth) located in the experiment's folder.

**Comment by VertofChest** [comment]
> Once the training progress reaches the designated checkpoint for saving an epoch, you can interrupt the training and resume from the last saved checkpoint. However, if the training is interrupted due to a computer crash, the last saved checkpoint may be corrupted. In such cases, it is recommended to continue training from the checkpoint preceding the last saved one. To do this, simply delete the last saved checkpoint files (D_xxx.pth and G_xxx.pth) located in the experiment's folder.

Thank you for the response in haste. I will do this and report back on anything that happens!

**Comment by ms903x1** [comment]
To continue training, you need to ensure consistency in the experiment name, version, and sampling rate. Once you have confirmed these details, you can click on the "Train Model" button to resume training. Starting from epoch 1 is not a normal scenario for continuing training.

**Comment by VertofChest** [comment]
Appreciate it, everyone.

So yes, as long as the **D_xxx.pth** and **G_xxx.pth** files did not become corrupted, you can resume a cancelled/interrupted model training session!

Thank you, and take care!

**Comment by MiranyStory** [comment]
> Once the training progress reaches the designated checkpoint for saving an epoch, you can interrupt the training and resume from the last saved checkpoint. However, if the training is interrupted due to a computer crash, the last saved checkpoint may be corrupted. In such cases, it is recommended to continue training from the checkpoint preceding the last saved one. To do this, simply delete the last saved checkpoint files (D_xxx.pth and G_xxx.pth) located in the experiment's folder.

I trained one model and it created the D_xxx.pth and G_xxx.pth, but for the second one it didn't. What do I do? Is there any minimal number of epochs you need for a checkpoint to be created?
