### ISSUE TITLE
please change this audio file path textbox into browse file button instead

### ISSUE THREAD

**Issue by sukualam** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#955]
i dont know why file path has to use typing/copy manually to textbox , i find it hard to use. is it better to use browse file button instead? or drag n drop?

i using it on macos, and it annoying when i has to copy my audio path manually
![Jepretan Layar 2023-08-07 pukul 10 35 41](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/11465849/9c776634-85b6-47c0-8f3d-f9ec75abada1)

**Comment by RVC-Boss** [comment]
Ok. This feature now has been implemented. You can update the code to the latest `main` branch, where this issue has already been resolved.
