### ISSUE TITLE
The volume of some of the output audio is reduced.

### ISSUE THREAD

**Issue by skeleton66** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#956]
The volume of some of the output audio is reduced.If the index file is applied, it will be somewhat larger, but if it is not applied, it may not appear at all. What should I do?
Original voice
https://d.kuku.lu/5n3s62jfj
Output Voice
https://d.kuku.lu/w48uaj6f8
Output Voice(Index applied)
https://d.kuku.lu/g46mfszsg

**Comment by RVC-Boss** [comment]
use this 
"Adjust the volume envelope scaling. Closer to 0, the more it mimicks the volume of the original vocals. Can help mask noise and make volume sound more natural when set relatively low. Closer to 1 will be more of a consistently loud volume"
change this to 0 may help you to control the volume same as the input.

**Comment by skeleton66** [comment]
Thank you
