### ISSUE TITLE
推理带有高音歌声的问题

### ISSUE THREAD

**Issue by PKevin123** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#957]
我训练的模型 
训练集质量高 无底躁 音频时长73min
训练时目标取样率48k 有带音高指导 版本v2
训练了200epoch

推理的音高提取演算法是用rmvpe
推理正常说话的内容没问题
推理歌声时正常音域时也没问题
唯独高音歌声唱不上去
具体情况在audio_sample.zip里面(注意音量)
[audio_sample.zip](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/files/12274576/audio_sample.zip)

由于我的训练集都是正常说话的语调
并没有唱歌时会出现的那种高音
这可能是问题所在吗?
恳求各位大佬帮忙解惑

**Comment by ms903x1** [comment]
数据集里没有高音的话，推理高音歌曲就会哑掉。

**Comment by PKevin123** [comment]
> 数据集里没有高音的话，推理高音歌曲就会哑掉。
好的 我明白了
谢谢大佬

**Comment by RVC-Boss** [comment]
嗯，训练集内需要带高音数据。

**Comment by liziru** [comment]
> 嗯，训练集内需要带高音数据。

@RVC-Boss  但是往往数据集内音高数据有限，尤其是10min数据，那该如何解决？通过做数据增强pitch_shift有效吗（我尝试了，音色会变）
