### ISSUE TITLE
Using the pth model to text to speech?

### ISSUE THREAD

**Issue by fugaprascolinas** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#958]
Is it possible to use the trained pth model in the GUI for Text to Speech generation, instead of voice conversion?

What type of model RVC v2 is?

**Comment by ms903x1** [comment]
The RVC project stands for Singing Voice Conversion. If you're looking for assistance related to that, you should probably reach out to a Text-to-Speech (TTS) project

**Comment by RVC-Boss** [comment]
TTS not supported.
