### ISSUE TITLE
how do i clear the cache ?

### ISSUE THREAD

**Issue by Aivoice1** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#959]
![Screenshot (305)](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/126923861/9610462e-bf5b-4f69-91b6-a979940a24ca)

please be a bit detailed as i'm new to this and programming. thanks in advance.

**Comment by ms903x1** [comment]
This error is not related to the cache. It is due to a large batch_size that exceeds the GPU memory capacity. To resolve this, you can reduce the batch_size.

**Comment by RVC-Boss** [comment]
↑ is right.

**Comment by Aivoice1** [comment]
> This error is not related to the cache. It is due to a large batch_size that exceeds the GPU memory capacity. To resolve this, you can reduce the batch_size.

thANKS
