### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by ran-app** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#96]
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by ran-app** [comment]
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by liujing04** [comment]
What pytorch version did you install?

**Comment by ran-app** [comment]
> 

2.0.0下面，使用的是MacPro M2

**Comment by autumnmotor** [comment]
https://github.com/liujing04/Retrieval-based-Voice-Conversion-WebUI/issues/67#issuecomment-1510027220
