### ISSUE TITLE
Stuck at "size mismatch for dec.conv_post.weight: copying a param with shape torch. Not sure if anything's working.

### ISSUE THREAD

**Issue by MastermindR** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#967]
size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 256]) from checkpoint, the shape in current model is torch.Size([192, 768]).
    size mismatch for dec.noise_convs.0.weight: copying a param with shape torch.Size([256, 1, 96]) from checkpoint, the shape in current model is torch.Size([256, 1, 80]).
    size mismatch for dec.noise_convs.1.weight: copying a param with shape torch.Size([128, 1, 16]) from checkpoint, the shape in current model is torch.Size([128, 1, 8]).
    size mismatch for dec.noise_convs.2.weight: copying a param with shape torch.Size([64, 1, 8]) from checkpoint, the shape in current model is torch.Size([64, 1, 4]).
    size mismatch for dec.noise_convs.3.weight: copying a param with shape torch.Size([32, 1, 4]) from checkpoint, the shape in current model is torch.Size([32, 1, 1]).
    size mismatch for dec.ups.0.weight_v: copying a param with shape torch.Size([512, 256, 16]) from checkpoint, the shape in current model is torch.Size([512, 256, 24]).
    size mismatch for dec.ups.1.weight_v: copying a param with shape torch.Size([256, 128, 16]) from checkpoint, the shape in current model is torch.Size([256, 128, 20]).
    size mismatch for dec.conv_post.weight: copying a param with shape torch.Size([1, 16, 7]) from checkpoint, the shape in current model is torch.Size([1, 32, 7]).

I'm using a Mangio RVC fork to run RVC on Mac, and I'm stalled at this point. I have no idea if I'm supposed to wait for something else to load or if I'm stuck. I don't know if it's supposed to take a long time because I don't know how to check if a process is running. I see questions are answered sparingly on here so I don't know if I'll get a response but yeah

**Comment by RVC-Boss** [comment]
This issue means you want to train a v2 model but use a v1 model as pretrained model.

**Comment by AVAW** [comment]
I have similar problem
`
size mismatch for model_g.dec.conv_pre.weight: copying a param with shape torch.Size([512, 192, 7]) from checkpoint, the shape in current model is torch.Size([256, 192, 7]).
`

How can i specify which version to generate? I can not find anything about versioning in docs. Or where i find pretrained model v2?
