### ISSUE TITLE
RMVPE model missing

### ISSUE THREAD

**Issue by jremb** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#972]
When trying to train with rmvpe I get the following error: FileNotFoundError: [Errno 2] No such file or directory: 'rmvpe.pt'

When selecting rmvpe in inference I get the following error: AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by ylzz1997** [comment]
You need to download the RMVPE model weight file:
https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/rmvpe.pt

**Comment by jremb** [comment]
Thanks. It's not mentioned here, which is how I missed it I guess. https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/README.en.md
