### ISSUE TITLE
Connection errored out

### ISSUE THREAD

**Issue by RuCybernetic** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#976]
how to solve this problem? I can't find the answer
![tLB6ALacmpM](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/47589158/6fcbcd34-1194-4706-8bca-461b234d676c)

**Comment by RuCybernetic** [comment]
Antivirus is bad

**Comment by kbanana10** [comment]
i have the same problem did you fixed it

**Comment by laoli2046** [comment]
Clean the web broswer's cookes do work.
