### ISSUE TITLE
'Process data' function in 'Train' can not work. Help me. Any Idea ?

### ISSUE THREAD

**Issue by WuanHoang** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#977]
After i clicked "process data" nothing happen. 
When i check log this show up.

D:\VoiceConverter\Retrieval-based-Voice-Conversion-WebUI-main>py infer-web.py --pycmd runtime\python.exe --port 7897
Found GPU NVIDIA GeForce RTX 3070 Ti
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
runtime\python.exe trainset_preprocess_pipeline_print.py "D:\VoiceConverter\Retrieval-based-Voice-Conversion-WebUI-main\voice\me" 40000 24 "D:\VoiceConverter\Retrieval-based-Voice-Conversion-WebUI-main/logs/wuan" False
The system cannot find the path specified.

Tried rename folder and audio files. But nothing happens !

Any idea ?

**Comment by ho1george** [comment]
I'm having the same issue. I think Windows is not recognizing the "runtime\python.exe". How do we get it to be able to invoke the correct python executable?

**Comment by ho1george** [comment]
If you already have a previous python installed or running a virtual environment you can try to run this line instead: "python infer-web.py --pycmd python --port 7897" it worked for me.

**Comment by TheMysticSaint** [comment]
I'm also unable to "Process data". I've tried different file formats, and moving the training folder right to the main drive to avoid spaces as I read that that is an issue.

I'm not super computer-savvy with python, code, or anything else that doesn't just work, so I'm out of ideas unless someone can help me. 

Running Windows 10, AMD FX(tm)-8350 Eight-Core Processor. 4.00 GHz, RAM	16.0 GB, Storage: 932 GB SSD , 447 GB SSD, Graphics Card: Radeon RX 570 Series (8 GB), System Type: 64-bit operating system, x64-based processor

This message shows in the prompt: 
runtime\python.exe trainset_preprocess_pipeline_print.py C:\rob 40000 6 C:\Program Files\RVC-beta0717/logs/Rob False
Traceback (most recent call last):
  File "C:\Program Files\RVC-beta0717\trainset_preprocess_pipeline_print.py", line 20, in <module>
    f = open("%s/preprocess.log" % exp_dir, "a+")
PermissionError: [Errno 13] Permission denied: 'C:\\Program/preprocess.log'
