### ISSUE TITLE
After converting audio twice in a row, the second output has a much deeper pitch?

### ISSUE THREAD

**Issue by moolzebub** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#984]
_I have NO CLUE how to approach explaining this issue, but it's consistently happening._
I do the regular steps towards converting audio and it goes without a hitch the first time! Then I convert the same audio file cause I changed some settings, but the result is much **deeper** and noticeably **slower** than the previous.
I found a way to temporarily stop it from doing this: just unloading the voice. Okay, fine, I can deal with unloading it everytime... but when it comes to batch conversion it's annoying!

[The first audio generated is fine.](https://drive.google.com/file/d/1O26BTg-so0AFx7wqokQq8xXBenHkAFc1/view?usp=drive_link)
[Then the next generation, no different settings, no unloading.](https://drive.google.com/file/d/1NgR762r11pR7ic7qdrWF9LtGnEc1HFpD/view?usp=drive_link)

**Comment by ben-mkiv** [comment]
also happens in the opposite direction with female voices the pitch increases.

maybe the pitch algorithm result doesn't get purged correctly?!

**Comment by JarodMica** [comment]
The issue occurs when resampling the audio.  If you leave it at 0, this does not occur, though, it's definitely a bug.  It's been in RVC since I've been using it back for a few months now, though, I don't notice much of a difference between audio at 48k vs 0 so I just leave it there.

**Comment by RVC-Boss** [comment]
Fixed now.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/commit/deb756bf1b0bc5924865e646dc7925c68c9f5bc5
