### ISSUE TITLE
Unable to get past 1 epoch on Mac M1 

### ISSUE THREAD

**Issue by MastermindR** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#995]
I'm running RVC on a mac locally and am attempting to train a dataset with over 500 samples that is up to 800 MB. I'm running a training session under these settings: 

Mangio-Crepe Hop length: 20. I know that this is probably one of the causes as to why it's taking so long to generate, but it's a gamble I took to try and make the model higher quality

Save frequency: 1 epoch

total training epochs: 300. I set it to around 1000 before so I could generate a huge model while I worked in the background

Batch size per GPU: 2. Originally, it was 16, because I presumed with around 16 samples per iteration, it would generate a higher quality model. I thought that that was the reason why I wasn't going anywhere past 1 epoch because of the large size so I kept it to 2 batch sizes.

Number of CPU processes used for pitch extraction and data processing: 7. I'm not sure if I'm supposed to change it or if the number is too high, since that is the default. I have 10 core processes so I don't know if 7 is too much. 

<img width="617" alt="Screenshot 2023-08-13 at 3 52 06 AM" src="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/140288517/1e995992-ca99-461e-9638-3e4312697f56">

The first problem I have is going past this point. The torch reducer buckets take too long to download or get to so I was wondering if my dataset was too large.

My second problem is watching the GB my dataset is generating go up rapidly. I'm up to 11 GB in the Mangio folder and I panic at how much storage I'm going to have left, or if RVC is supposed to generate this high of an output. The logs folder is mostly comprised of events out logs because I have to keep shutting it down. Last I checked, I'm not sure if it's doing anything at all and it was going through the 0_gt_wavs folder really slowly and it looked like it was converting files in there. 

Should I uninstall everything and start all over? I'm also afraid I overwrote the files way too many times because I had to go back and try and adjust the Batch sizes and training Epochs.

I have this same problem on Google Drive's training colab as well to see if it runs faster with a GPU processing since Mac doesn't have any, and  the model sits in data purgatory loading everything. It really has to be because of the size of the data I have...

It's mostly getting past the Reducer buckets. It takes forever to load and I don't know what to do. I'm also unsure of where all the data it's generating is going to, or where the data is downloading towards because of how much stuff is getting loaded into my computer.

Sorry that I'm not a programmer, but any help is nice :,,,,,)

**Comment by smfreeze** [comment]
I'm no expert, but you kinda need a GPU to train an RVC model (or really any ai model!).
In terms of storage usage, you can just delete all logs once you have trained your model, all you need are the path and index files of the model.
