### ISSUE TITLE
gpu not detected

### ISSUE THREAD

**Issue by savandt** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#997]
I have a RTX 3070 ti and keep getting this error
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/142150098/23a4032a-c74c-4207-89c1-22ecb059cb3a)

please can someone help me, I have tried downloading pytorch version and I am not sure but I think I should have the correct one

**Comment by tommiionfire** [comment]
Make sure your pytorch and cuda version are compatible. 

I'm running this version: 12.1

https://developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda_12.1.1_531.14_windows.exe

pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

**Comment by savandt** [comment]
I had that version installed it, when i used the command this happened:
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/142150098/454df1fa-ab93-463a-aa0c-679201087d16)
