### ISSUE TITLE
 WARNING | xformers | Triton is not available, some optimizations will not be enabled. This is just a warning: No module named 'triton'

### ISSUE THREAD

**Issue by FarshadGrayson** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#999]
i get this warning after installing the new update ! " WARNING | xformers | Triton is not available, some optimizations will not be enabled. This is just a warning: No module named 'triton' . "
i have a Nvidia RTX 3070 Ti GPU. tried installing triton using 'pip install triton' but i get errors . what should i do ?

**Comment by RVC-Boss** [comment]
It doesn't matter.

**Comment by PatrickAi01** [comment]
hello @FarshadGrayson have you found a resolution for this? 
I couldnt run this on my windows laptop as well since when i click on the go-web bat file it giving me that same error you have mentioned

**Comment by ofocn** [comment]
搞定了按照这个链接操作就可以了
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1182
